(about . "my-lisp-constitution.lisp — the executable proof of docs/language-core-axioms.md's project principles and axioms (G1-G8 generative, S1-S3 safety). Each fixture is one of the observable claims from tests/fixtures/conformance.lisp, tagged with the tier (1 CORE SEMANTICS, 2 LANGUAGE CONTRACT, 3 ECOSYSTEM CONFORMANCE) and, where one applies, the axiom(s) it is evidence for. Symbolic-reasoning fixtures (tier 3, unify/reason) carry no axiom tag on purpose — they are evidence for project principle 3, not the G/S axiom list.")
(status . "draft — not yet ratified; will become read-only once ratified")
(generated . "This file is GENERATED — do not hand-edit it. It is a projection over tests/fixtures/conformance.lisp (facts and tags in one record) plus this script's own principle/axiom text. Edit tests/fixtures/conformance.lisp or scripts/build-constitution.lisp, then run: cargo run -p sens-cli -- scripts/build-constitution.lisp > my-lisp-constitution.lisp . Written as sens data, not JSON: readable directly via (read-all (read-file \"my-lisp-constitution.lisp\")), no foreign parser needed — the same reason conformance.lisp itself moved off JSON.")
(self-contained . "principles and axioms below are the canonical one-line statements from docs/language-core-axioms.md, kept here so this file can be read and understood on its own; docs/language-core-axioms.md remains the single source of the full prose rationale, examples, and open questions — not duplicated here, to avoid two sources of truth for the same wording drifting apart")
(role-field . "Each fixture may carry a \"role\" of \"constitutive\" — meaning it directly invokes one of McCarthy's seven original primitives (quote, atom, eq, car, cdr, cons, cond), including their documented error paths. A constitutive fixture doesn't just provide evidence that an axiom holds; it's one of the acts that makes the axiom true in the first place — remove the primitive and the axiom becomes false, not just unproven. Every other fixture (role omitted, i.e. \"derived\") demonstrates a consequence built on top of the constitutive primitives — removing it could in principle still leave the axiom provable some other way.")
(principles-document . "docs/language-core-axioms.md")
(tier-map . "docs/conformance-tier-map.md")
(principle 1 "Write about possibilities, not limitations." "Писати про можливості, не про обмеження.")
(principle 2 "Be Lisp in the full sense of the word — homoiconicity and a minimal, closed core that grows the rest of the language from inside itself, not the surface syntax of any one historical dialect." "Бути Lisp-ом у повному розумінні цього слова — гомоіконність і мінімальне, замкнене ядро, що вирощує решту мови зсередини себе, не поверхневий синтаксис якогось одного історичного діалекту.")
(principle 3 "Build the reasoning machine — McCarthy's documented 1958 Advice Taker goal, extended by the author's own hybrid neural/symbolic vision (private/lisp-to-knowledge.md)." "Реалізувати розумну машину — задокументована ціль МакКарті 1958 року (Advice Taker), продовжена власним гібридним нейро-символьним баченням автора (private/lisp-to-knowledge.md).")
(principle 4 "Cross-platform-ness, or more simply: universality — the falsifiability test for G6/G7; sens commits to real, physically different substrates (Rust, fpga-lisp), not just one implementation asserting conformance." "Кросплатформеність, або простіше — універсальність — тест на фальсифіковність для G6/G7; sens зобов'язується перед реально різними фізичними субстратами (Rust, fpga-lisp), не лише однією реалізацією, що заявляє конформність.")
(principle 5 "Maximum awareness of today's technology, applied to symbolic AI — classical symbolic AI is not a museum piece; modern tooling and modern LLMs (as the fuzzy natural-language interface, not a competitor to the precise symbolic core) are part of building it." "Максимальна обізнаність у сьогоднішніх технологіях, застосована до символьного ШІ — класичний символьний AI не музейний експонат; сучасні інструменти й сучасні LLM (як нечіткий інтерфейс природної мови, не конкурент точному символьному ядру) — частина його побудови.")
(axiom G1 generative "A value's meaning can be fully defined by observable behavior." "Значення value може бути повністю визначене спостережуваною поведінкою.")
(axiom G2 generative "Every value can be built from just two things: atoms and pairs." "Кожне значення можна побудувати лише з двох речей: атомів і пар.")
(axiom G3 generative "Program structure can be inspected, transformed, and built like any other value." "Структуру програми можна оглядати, трансформувати й будувати, як і будь-яке інше значення.")
(axiom G4 generative "A minimal core can grow an entire language inside itself." "Мінімальне ядро може вирощувати всю мову всередині себе.")
(axiom G5 generative "Anything expressible within the language can live above the implementation boundary." "Усе, що виразне мовою, може жити над межею реалізації.")
(axiom G6 generative "Conformance can be defined purely by observable behavior." "Конформність можна визначити суто спостережуваною поведінкою.")
(axiom G7 generative "The same expression can mean the same thing everywhere." "Той самий вираз може означати те саме всюди.")
(axiom G8 generative "The absence of any element and the absence of truth can be the same value." "Відсутність будь-якого елемента й відсутність істини можуть бути тим самим значенням.")
(axiom S1 safety "Never silently turn an exact value into an approximation." "Ніколи мовчки не перетворювати точне значення на наближення.")
(axiom S2 safety "Never fail silently — every failure is a named, observable outcome." "Ніколи не провалюватись мовчки — кожен провал є названим, спостережуваним результатом.")
(axiom S3 safety "Never let a resource limit silently redefine an operation's meaning." "Ніколи не дозволяти обмеженню ресурсу мовчки переозначити сенс операції.")
(tier 1 "CORE SEMANTICS — every conforming implementation must have this")
(tier 2 "LANGUAGE CONTRACT — every conforming implementation must have this")
(tier 3 "ECOSYSTEM CONFORMANCE — an implementation can be sens without this loaded yet; tests a library, not the language itself")
(fixture (expr . "(quote radio)") (expected . "radio") (tier . 1) (axioms G3) (role . "constitutive") (compiler-corpus . t) (wsm-native (status . pending)) (meta-eval . t))
(fixture (expr . "(00000010 (quote radio))") (expected . "(1)") (tier . 1) (axioms G2) (role . "constitutive") (compiler-corpus . t) (wsm-native (status . pending)) (meta-eval . t))
(fixture (expr . "(00000010 (quote ()))") (expected . "()") (tier . 1) (axioms G2) (role . "constitutive") (meta-eval . t))
(fixture (expr . "(00000010 (quote (radio antenna)))") (expected . "(0)") (tier . 1) (axioms G2) (role . "constitutive") (meta-eval . t))
(fixture (expr . "(00000011 (quote radio) (quote radio))") (expected . "(1)") (tier . 1) (axioms G1) (role . "constitutive") (compiler-corpus . t) (wsm-native (status . pending)) (meta-eval . t))
(fixture (expr . "(00000011 (quote radio) (quote antenna))") (expected . "(0)") (tier . 1) (axioms G1) (role . "constitutive") (meta-eval . t))
(fixture (expr . "(car (quote (radio antenna)))") (expected . "radio") (tier . 1) (axioms G2) (role . "constitutive") (compiler-corpus . t) (wsm-native (status . pending)) (meta-eval . t))
(fixture (expr . "(cdr (quote (radio antenna)))") (expected . "(antenna)") (tier . 1) (axioms G2) (role . "constitutive") (compiler-corpus . t) (wsm-native (status . pending)) (meta-eval . t))
(fixture (expr . "(cons (quote radio) (quote (antenna)))") (expected . "(radio antenna)") (tier . 1) (axioms G2) (role . "constitutive") (compiler-corpus . t) (wsm-native (status . pending)) (meta-eval . t))
(fixture (expr . "(за-умовою (() (як-є wrong)) ((тотожне? (як-є x) (як-є x)) (як-є right)))") (expected . "right") (tier . 3) (axioms) (role . "historical-compatibility") (compatibility . historical-truthiness) (note . "Historical surface/migration truthiness only. Contract 11.8 exact D3:110 does not admit structural () as PredicateBit control.") (meta-eval . t))
(fixture (expr . "(/ 5 6 8 7)") (expected . "5/336") (tier . 2) (axioms S1) (compiler-corpus . t) (meta-eval-gap . t) (wsm-native (status . pending)))
(fixture (expr . "(+ (/ 1 3) (/ 1 3))") (expected . "2/3") (tier . 2) (axioms S1))
(fixture (expr . "(- 1 (/ 1 3))") (expected . "2/3") (tier . 2) (axioms S1))
(fixture (expr . "(* (/ 2 3) (/ 9 4))") (expected . "3/2") (tier . 2) (axioms S1))
(fixture (expr . "(- (/ 1 3))") (expected . "-1/3") (tier . 2) (axioms S1))
(fixture (expr . "(+ (/ 1 2) 0.25)") (expected . "3/4") (tier . 2) (axioms S1))
(fixture (expr . "(/ 1 2.0)") (expected . "1/2") (tier . 2) (axioms S1))
(fixture (expr . "(/ 1.0 2)") (expected . "1/2") (tier . 2) (axioms S1))
(fixture (expr . "(/ 1.0 2.0)") (expected . "1/2") (tier . 2) (axioms S1))
(fixture (expr . "(+ 0.1 0.2)") (expected . "3/10") (tier . 2) (axioms S1))
(fixture (expr . "(- 0.5 0.6)") (expected . "-1/10") (tier . 2) (axioms S1))
(fixture (expr . "(/ 0.5 0.6)") (expected . "5/6") (tier . 2) (axioms S1))
(fixture (expr . "12345678901234567890.12345678901234567890") (expected . "123456789012345678901234567890123456789/10000000000000000000") (tier . 2) (axioms S1))
(fixture (expr . "1e100") (expected . "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000") (tier . 2) (axioms S1))
(fixture (expr . "1e-100") (expected . "1/10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000") (tier . 2) (axioms S1))
(fixture (expr . ".e3") (error . "UnknownSymbol") (tier . 2) (axioms S2))
(fixture (expr . "1e") (error . "UnknownSymbol") (tier . 2) (axioms S2))
(fixture (expr . "1e+") (error . "UnknownSymbol") (tier . 2) (axioms S2))
(fixture (expr . "1e-") (error . "UnknownSymbol") (tier . 2) (axioms S2))
(fixture (expr . "1.2.3") (error . "UnknownSymbol") (tier . 2) (axioms S2))
(fixture (expr . "1e100001") (error . "NumericOverflow") (tier . 2) (axioms S3))
(fixture (expr . "1e-100001") (error . "NumericOverflow") (tier . 2) (axioms S3))
(fixture (expr . "(def 1e100001 5)") (error . "NumericOverflow") (tier . 2) (axioms S3))
(fixture (expr . "1ee3") (error . "UnknownSymbol") (tier . 2) (axioms S2))
(fixture (expr . "--0.5") (error . "UnknownSymbol") (tier . 2) (axioms S2))
(fixture (expr . "((lambda (f) (f 3 4)) +)") (expected . "7") (tier . 2) (since-contract 2 1) (requires first-class-builtins builtin-add) (axioms S2) (note . "bare + passed as an ordinary value and called -- proves first-classness without pinning #<builtin +>'s print format as contract"))
(fixture (expr . "((lambda (f) (f 10 4)) -)") (expected . "6") (tier . 2) (since-contract 2 1) (requires first-class-builtins builtin-subtract) (axioms S2) (note . "same reframing for -"))
(fixture (expr . ".5") (expected . "1/2") (tier . 2) (axioms S1))
(fixture (expr . "-.5") (expected . "-1/2") (tier . 2) (axioms S1))
(fixture (expr . "5.") (expected . "5") (tier . 2) (axioms S1))
(fixture (expr . "000.500") (expected . "1/2") (tier . 2) (axioms S1))
(fixture (expr . "1e3") (expected . "1000") (tier . 2) (axioms S1))
(fixture (expr . "1e-3") (expected . "1/1000") (tier . 2) (axioms S1))
(fixture (expr . "1.25e2") (expected . "125") (tier . 2) (axioms S1))
(fixture (expr . "-0.0") (expected . "0") (tier . 2) (axioms S1))
(fixture (expr . "0.0") (expected . "0") (tier . 2) (axioms S1))
(fixture (expr . "(/ 1 0.0)") (error . "DivisionByZero") (tier . 2) (since-contract 3 0) (axioms S2))
(fixture (expr . "(00000011 3 3)") (expected . "(1)") (tier . 1) (axioms G1) (role . "constitutive") (meta-eval . t))
(fixture (expr . "(00000011 3 4)") (expected . "(0)") (tier . 1) (axioms G1) (role . "constitutive") (meta-eval . t))
(fixture (expr . "(00000011 \"radio\" \"radio\")") (expected . "(1)") (tier . 1) (axioms G1) (role . "constitutive") (requires strings) (meta-eval . t))
(fixture (expr . "(00000011 \"\\r\" \"r\")") (expected . "(0)") (tier . 1) (axioms G1) (role . "constitutive") (requires strings) (note . "\\r must be the real carriage-return byte (0x0D), not the letter r — found broken in a real fpga-lisp bug, fixed 2026-08-10") (meta-eval . t))
(fixture (expr . "(cond (() (quote first)) (() (quote second)) (t (quote third)))") (expected . "third") (tier . 3) (axioms) (role . "historical-compatibility") (compatibility . historical-truthiness) (note . "Historical surface/migration truthiness only. Structural () is not a current exact PredicateBit answer.") (meta-eval . t))
(fixture (expr . "(second (quote (radio antenna signal)))") (expected . "antenna") (tier . 3) (axioms G5))
(fixture (expr . "(third (quote (radio antenna signal)))") (expected . "signal") (tier . 3) (axioms G5))
(fixture (expr . "(not (quote ()))") (expected . "t") (tier . 3) (axioms G5))
(fixture (expr . "(not (quote radio))") (expected . "()") (tier . 3) (axioms G5))
(fixture (expr . "(and)") (expected . "t") (tier . 3) (axioms G5 G8) (note . "vacuous and -- neutral element, added 2026-08-27 after grep confirmed and/or were absent from both core.my and Rust builtins entirely; chess-lisp-zero had to bootstrap its own copy"))
(fixture (expr . "(or)") (expected . "()") (tier . 3) (axioms G5 G8) (note . "vacuous or -- neutral element"))
(fixture (expr . "(symbol? (gensym \"temp-\"))") (expected . "t") (tier . 3) (axioms G5) (note . "gensym, added 2026-08-27 (see docs/macro-hygiene-2026-08-27.md) -- returns a real symbol, built entirely from existing primitives (mono-ns/write-to-string/string-append/string->symbol), no new Rust code"))
(fixture (expr . "(00000011 (gensym \"temp-\") (gensym \"temp-\"))") (expected . "(0)") (tier . 3) (axioms G5) (note . "two calls with the same prefix are never eq -- the actual property that matters for a fresh-name generator, not just a type check"))
(fixture (expr . "(string-prefix? \"temp-\" (symbol->string (gensym \"temp-\")))") (expected . "t") (tier . 3) (axioms G5) (note . "the caller's prefix is genuinely preserved in the generated name, not discarded"))
(fixture (expr . "(and t t t)") (expected . "t") (tier . 3) (axioms G5))
(fixture (expr . "(and t (quote ()) t)") (expected . "()") (tier . 3) (axioms G5))
(fixture (expr . "(and t 42)") (expected . "42") (tier . 3) (axioms G5) (note . "and/or return the actual value of the deciding form, not just t/() -- matches Common Lisp/Scheme, not a plain boolean-only and/or"))
(fixture (expr . "(or (quote ()) (quote ()) t)") (expected . "t") (tier . 3) (axioms G5))
(fixture (expr . "(or (quote ()) (quote ()) (quote ()))") (expected . "()") (tier . 3) (axioms G5))
(fixture (expr . "(or (quote ()) 7)") (expected . "7") (tier . 3) (axioms G5))
(fixture (expr . "(and (quote ()) (undefined-symbol))") (expected . "()") (tier . 3) (axioms G5) (note . "proves real short-circuit, not eager evaluation: undefined-symbol would raise UnknownSymbol if and ever evaluated it"))
(fixture (expr . "(or t (undefined-symbol))") (expected . "t") (tier . 3) (axioms G5) (note . "same short-circuit proof for or"))
(fixture (expr . "(length (quote (radio antenna signal)))") (expected . "3") (tier . 3) (axioms G5))
(fixture (expr . "(length (quote ()))") (expected . "0") (tier . 3) (axioms G5))
(fixture (expr . "(reverse (quote (radio antenna signal)))") (expected . "(signal antenna radio)") (tier . 3) (axioms G5))
(fixture (expr . "(append (quote (radio)) (quote (antenna signal)))") (expected . "(radio antenna signal)") (tier . 3) (axioms G5))
(fixture (expr . "(map (lambda (x) (+ x 1)) (quote (1 2 3)))") (expected . "(2 3 4)") (tier . 3) (axioms G5))
(fixture (expr . "(filter (lambda (x) (00000011 x 2)) (quote (1 2 3 2)))") (expected . "(2 2)") (tier . 3) (axioms G5))
(fixture (expr . "(reduce (lambda (acc x) (+ acc x)) 0 (quote (1 2 3 4)))") (expected . "10") (tier . 3) (axioms G5))
(fixture (expr . "(< 1 2 3)") (expected . "t") (tier . 2) (axioms) (meta-eval . t))
(fixture (expr . "(< 1 3 2)") (expected . "()") (tier . 2) (axioms) (meta-eval . t))
(fixture (expr . "(> 3 2 1)") (expected . "t") (tier . 2) (axioms) (meta-eval . t))
(fixture (expr . "(= 1 1 1)") (expected . "t") (tier . 2) (axioms) (meta-eval . t))
(fixture (expr . "(= 1/2 0.5)") (expected . "t") (tier . 2) (axioms G1 S1) (meta-eval . t))
(fixture (expr . "(<= 1 1 2)") (expected . "t") (tier . 2) (axioms))
(fixture (expr . "(>= 2 2 1)") (expected . "t") (tier . 2) (axioms))
(fixture (expr . "(print 42)") (expected . "42") (tier . 2) (axioms))
(fixture (expr . "(read \"(+ 1 2)\")") (expected . "(+ 1 2)") (tier . 2) (axioms G3))
(fixture (expr . "(eval (read \"(+ 1 2)\"))") (expected . "3") (tier . 2) (axioms G3))
(fixture (expr . "(car 5)") (error . "Type") (tier . 1) (axioms S2) (role . "constitutive"))
(fixture (expr . "(car (quote ()))") (error . "Type") (tier . 1) (axioms S2) (role . "constitutive"))
(fixture (expr . "(00000011 (quote (1)) (quote (2)))") (error . "Type") (tier . 1) (axioms S2) (role . "constitutive"))
(fixture (expr . "(undefined-symbol)") (error . "UnknownSymbol") (tier . 1) (axioms S2) (note . "symbol lookup is core semantics (tier 1 explicitly lists \"symbols\"); not actually borderline with tier 2"))
(fixture (expr . "(lambda (x))") (error . "Arity") (tier . 2) (axioms S2))
(fixture (expr . "(quote a b)") (error . "Arity") (tier . 1) (axioms S2) (role . "constitutive"))
(fixture (expr . "(cons 1)") (error . "Arity") (tier . 1) (axioms S2) (role . "constitutive"))
(fixture (expr . "(/ 1 0)") (error . "DivisionByZero") (tier . 2) (since-contract 3 0) (axioms S2))
(fixture (expr . "(let ((x 1) (y 2)) (+ x y))") (expected . "3") (tier . 3) (axioms G5))
(fixture (expr . "(let* ((x 1) (y (+ x 1))) y)") (expected . "2") (tier . 3) (axioms G5))
(fixture (expr . "(equal? (quote (1 (2 3) 4)) (quote (1 (2 3) 4)))") (expected . "(1)") (tier . 3) (axioms G5))
(fixture (expr . "(equal? (quote (1 2)) (quote (1 2 3)))") (expected . "(0)") (tier . 3) (axioms G5))
(fixture (expr . "(00000011 (lambda (x) x) (lambda (x) x))") (expected . "(0)") (tier . 2) (axioms G1) (role . "constitutive") (compiler-corpus . t) (meta-eval-gap . t) (wsm-native (status . pending)))
(fixture (expr . "(unify (quote a) (quote a) (quote ()))") (expected . "()") (tier . 3) (axioms))
(fixture (expr . "(unify (quote (var x)) (quote a) (quote ()))") (expected . "((x . a))") (tier . 3) (axioms))
(fixture (expr . "(unify (quote (var x)) (quote (var x)) (quote ()))") (expected . "()") (tier . 3) (axioms))
(fixture (expr . "(unify (quote (1 (var x) 3)) (quote (1 2 3)) (quote ()))") (expected . "((x . 2))") (tier . 3) (axioms))
(fixture (expr . "(unify (quote (1 (var x) 3)) (quote (1 2 4)) (quote ()))") (expected . "fail") (tier . 3) (axioms))
(fixture (expr . "(let ((rules (quote (((parent alice bob)))))) (reason (quote (parent alice bob)) rules))") (expected . "((() (proved (parent alice bob) (parent alice bob) ())))") (tier . 3) (axioms))
(fixture (expr . "(let ((rules (quote (((parent alice bob)))))) (reason (list (quote parent) (logic-var (quote x)) (quote bob)) rules))") (expected . "((((x . alice)) (proved (parent (var x) bob) (parent alice bob) ())))") (tier . 3) (axioms))
(fixture (expr . "(let ((rules (quote (((bird (var x)) (animal (var x)) (not (penguin (var x)))) ((animal tweety)) ((animal pingu)) ((penguin pingu)))))) (reason (list (quote bird) (logic-var (quote x))) rules))") (expected . "(((((x . 0) . tweety) (x var (x . 0))) (proved (bird (var x)) (bird (var (x . 0))) ((proved (animal (var (x . 0))) (animal tweety) ()) (proved-not (penguin (var (x . 0))))))))") (tier . 3) (axioms))
(fixture (expr . "(equal? (quote (p . 0)) (cons (quote p) 0))") (expected . "(1)") (tier . 1) (axioms G2))
(fixture (expr . "(car (quote (a b . c)))") (expected . "a") (tier . 1) (axioms G2) (role . "constitutive") (meta-eval . t))
(fixture (expr . "(cdr (cdr (quote (a b . c))))") (expected . "c") (tier . 1) (axioms G2) (role . "constitutive") (meta-eval . t))
(fixture (expr . "(unify (quote (var x)) (quote (f (var x))) (quote ()))") (expected . "fail") (tier . 3) (axioms) (note . "occurs-check, principle 3 evidence — prevents building an infinite structure, not a G/S axiom"))
(fixture (expr . "(defmacro foo)") (error . "Arity") (tier . 2) (axioms S2) (note . "defmacro validates arity like any other special form") (compiler-corpus . t) (wsm-native (status . pending)))
(fixture (expr . "(defmacro 5 (x) x)") (error . "InvalidForm") (tier . 2) (axioms S2) (note . "defmacro validates its name is a symbol, not just its arity"))
(fixture (expr . "(def count-down (lambda (n) (за-умовою ((тотожне? n 0) (як-є done)) ((тотожне? n n) (count-down (- n 1)))))) (count-down 100000)") (expected . "done") (tier . 2) (axioms S3) (note . "100,000-deep self-tail-call under current exact D3 control: EQ(n,0) selects the base case with D1:1; EQ(n,n) is the explicit admitted numeric fallback guard; no bare-T truthiness") (compiler-corpus . t) (meta-eval-gap . t) (wsm-native (status . pending)))
(fixture (expr . "(map (lambda (x) (+ x 1)) (quote ()))") (expected . "()") (tier . 3) (axioms G5) (note . "empty-list edge case, previously untested — map"))
(fixture (expr . "(filter (lambda (x) (00000011 x 2)) (quote ()))") (expected . "()") (tier . 3) (axioms G5) (note . "empty-list edge case, previously untested — filter"))
(fixture (expr . "(reduce (lambda (acc x) (+ acc x)) 0 (quote ()))") (expected . "0") (tier . 3) (axioms G5) (note . "empty-list edge case, previously untested — reduce returns its initial accumulator unchanged"))
(fixture (expr . "((lambda (a b . rest) rest) 1 2 3 4 5)") (expected . "(3 4 5)") (tier . 1) (axioms G2) (role . "constitutive") (note . "dotted lambda-list: variadic parameter binding, added 2026-08-09 to let list move out of Rust") (compiler-corpus . t) (wsm-native (status . pending)))
(fixture (expr . "((lambda args args) 1 2 3)") (expected . "(1 2 3)") (tier . 1) (axioms G2) (role . "constitutive") (note . "bare-symbol lambda-list: zero fixed params, every argument bound as one list") (compiler-corpus . t) (wsm-native (status . pending)) (meta-eval . t))
(fixture (expr . "((lambda (a b . rest) a) 1)") (error . "Arity") (tier . 1) (axioms S2) (role . "constitutive") (note . "variadic lambda still enforces its fixed parameters") (compiler-corpus . t) (wsm-native (status . pending)))
(fixture (expr . "(list 1 2 3)") (expected . "(1 2 3)") (tier . 3) (axioms G5) (note . "list moved from a Rust special form to lib/core.my (lambda args args) once variadic parameters existed to express it"))
(fixture (expr . "(let ((local-second (lambda (x) (quote shadowed)))) (local-second (quote (1 2 3))))") (expected . "shadowed") (tier . 2) (axioms G4) (note . "ordinary lexical function-valued bindings remain locally callable when their name is genuinely local and not an admitted SENS surface") (compiler-corpus . t) (meta-eval-gap . t) (wsm-native (status . pending)))
(fixture (expr . "(let ((car (lambda (x) (quote shadowed)))) (car (quote (1 2))))") (error . "InvalidForm") (tier . 1) (since-contract 6 0) (requires immutable-canon) (axioms G4 S2) (role . "constitutive") (note . "Contract 6.0: Canon 0+7 spellings are reserved and unshadowable. let lowers through a lambda binder, so attempting to bind car is rejected as InvalidForm. Ordinary non-Canon builtins remain first-class and shadowable.") (compiler-corpus . t) (wsm-native (status . pending)))
(fixture (expr . "(reverse (quote ()))") (expected . "()") (tier . 3) (axioms G5) (note . "empty-list edge case, previously untested"))
(fixture (expr . "(append (quote ()) (quote (a b)))") (expected . "(a b)") (tier . 3) (axioms G5) (note . "empty-list edge case, previously untested — empty first argument"))
(fixture (expr . "(append (quote (a b)) (quote ()))") (expected . "(a b)") (tier . 3) (axioms G5) (note . "empty-list edge case, previously untested — empty second argument"))
(fixture (expr . "(symbol? (quote radio))") (expected . "t") (tier . 3) (axioms G5) (note . "symbol? is now lib/core.my: derived from atom, write-to-string, string->symbol, and eq rather than Rust type dispatch"))
(fixture (expr . "(string? \"radio\")") (expected . "t") (tier . 2) (axioms))
(fixture (expr . "(symbol->string (quote radio))") (expected . "\"radio\"") (tier . 2) (axioms))
(fixture (expr . "(string->symbol \"radio\")") (expected . "radio") (tier . 2) (axioms))
(fixture (expr . "(string-first \"radio\")") (expected . "\"r\"") (tier . 2) (axioms))
(fixture (expr . "(string-rest \"radio\")") (expected . "\"adio\"") (tier . 2) (axioms))
(fixture (expr . "(string-slice \"привіт\" 1 3)") (expected . "\"ри\"") (tier . 2) (axioms) (note . "character-indexed Unicode slice; indices are scalar values, not UTF-8 bytes"))
(fixture (expr . "(string-slice \"abc\" 0 0)") (expected . "\"\"") (tier . 2) (axioms))
(fixture (expr . "(string-slice \"abc\" 2 9)") (expected . "\"c\"") (tier . 2) (axioms) (note . "end index clamps to the string length"))
(fixture (expr . "(string-slice \"abc\" 4 9)") (expected . "\"\"") (tier . 2) (axioms) (note . "start beyond the string length yields the empty string"))
(fixture (expr . "(read-all \"1 2 3\")") (expected . "(1 2 3)") (tier . 2) (axioms G3) (note . "the multi-form counterpart to read — previously tested only in Rust unit tests"))
(fixture (expr . "(princ \"raw\")") (expected . "\"raw\"") (tier . 2) (axioms) (note . "princ composes and returns its argument exactly like print — the raw/unquoted transcript output itself is regression-tested in crates/my-lisp/tests/mccarthy.rs since this fixture harness only checks the return value, not the print transcript"))
(fixture (expr . "(< 5)") (expected . "t") (tier . 2) (axioms) (note . "a single argument is vacuously ordered, previously untested here"))
(fixture (expr . "(defmacro my-list items (cons (quote quote) (cons items (quote ())))) (my-list 1 2 3)") (expected . "(1 2 3)") (tier . 1) (axioms G4) (role . "constitutive") (note . "variadic defmacro success path — the error paths were already covered, the success path wasn't") (compiler-corpus . t) (meta-eval-gap . t) (wsm-native (status . pending)))
(fixture (expr . "(understand (quote (earth is a planet)))") (expected . "((planet earth))") (tier . 3) (axioms) (note . "lib/understand.my — the controlled-natural-language bridge, previously tested only in Rust unit tests, not the implementation-independent contract"))
(fixture (expr . "(understand (quote (earth orbits sun)))") (expected . "((orbits earth sun))") (tier . 3) (axioms) (note . "subject-verb-object relation shape"))
(fixture (expr . "(understand (quote (all planet have mass)))") (expected . "((has (var w) mass) (planet (var w)))") (tier . 3) (axioms) (note . "universal-rule shape"))
(fixture (expr . "(narrate-fact (car (understand (quote (earth is a planet)))))") (expected . "(earth is a planet)") (tier . 3) (axioms) (note . "lib/narrate.my — the structure-to-text half of the bridge, previously tested only in Rust unit tests"))
(fixture (expr . "(equal? (quote (mars is a planet)) (narrate-fact (car (understand (quote (mars is a planet))))))") (expected . "(1)") (tier . 3) (axioms) (note . "understand and narrate-fact are direct inverses for the is-a shape"))
(fixture (expr . "(understand-query (quote (is socrates mortal)))") (expected . "(mortal socrates)") (tier . 3) (axioms) (note . "lib/understand.my query form — a question shape -> a reason goal, the goal-shaped complement of understand"))
(fixture (expr . "(understand-query (quote (does socrates drink hemlock)))") (expected . "(drink socrates hemlock)") (tier . 3) (axioms) (note . "does-question shape -> a relation goal"))
(fixture (expr . "(cond (0 (quote truthy)) (t (quote falsy)))") (expected . "truthy") (tier . 3) (axioms) (role . "historical-compatibility") (compatibility . historical-truthiness) (note . "Historical surface/migration truthiness only. Number 0 is not current D1:0 PredicateBit and cannot control exact D3:110.") (meta-eval . t))
(fixture (expr . "(00000011 3 3.0)") (expected . "(1)") (tier . 1) (axioms S1) (note . "decimal literals are exact by default (S1): 3.0 is the exact integer 3, so eq reports the same atom identity relation.") (meta-eval . t))
(fixture (expr . "(00000011 3 3)") (expected . "(1)") (tier . 1) (axioms S1) (note . "same exactness, same magnitude") (meta-eval . t))
(fixture (expr . "(00000011 3.0 3.0)") (expected . "(1)") (tier . 1) (axioms S1) (note . "same exact value both sides") (meta-eval . t))
(fixture (expr . "(= 3 3.0)") (expected . "t") (tier . 1) (axioms S1) (note . "= compares magnitude only, deliberately diverging from eq — 3 and 3.0 are the same mathematical quantity even though they are different values"))
(fixture (expr . "(print 3)") (expected . "3") (tier . 2) (axioms S1) (note . "exact integer prints without a decimal point"))
(fixture (expr . "(print 3.0)") (expected . "3") (tier . 2) (axioms S1) (note . "decimal literals are exact by default (S1): 3.0 is the exact integer 3, so print renders it as \"3\""))
(fixture (expr . "(print 3.00)") (expected . "3") (tier . 2) (axioms S1) (note . "3.0/3.00/3.000 are the same exact integer 3 regardless of trailing zeros in the literal"))
(fixture (expr . "(+ 2.0 1.0)") (expected . "3") (tier . 2) (axioms S1) (note . "exact + exact -> exact under decimal-exact-by-default (S1): 2.0 + 1.0 is the exact integer 3"))
(fixture (expr . "(+ 2.0 1)") (expected . "3") (tier . 2) (axioms S1) (note . "decimal literals are exact by default (S1): 2.0 is the exact integer 2, so 2.0 + 1 = 3"))
(fixture (expr . "(+ 2 1)") (expected . "3") (tier . 2) (axioms S1) (note . "exact + exact -> exact, stays a precise integer"))
(fixture (expr . "(string-append \"hello, \" \"world\")") (expected . "\"hello, world\"") (tier . 2) (axioms) (note . "PLAN.md item 14 — genuinely needs a Rust primitive, unlike string-length/string-contains? below: no existing primitive combines two strings into a new one"))
(fixture (expr . "(string<? \"a\" \"b\")") (expected . "t") (tier . 2) (axioms) (note . "PLAN.md item 15 — the one Rust primitive the persistent-map design needed; ordering, not just equality, can't be derived from string-first/string-rest/eq alone"))
(fixture (expr . "(string<? \"b\" \"a\")") (expected . "()") (tier . 2) (axioms))
(fixture (expr . "(map-get \"a\" (map-insert \"a\" 1 map-empty))") (expected . "(1)") (tier . 3) (axioms G5) (note . "PLAN.md item 15 — lib/persistent-map.my, an AVL-balanced persistent tree built on cons/car/cdr alone, no mutation; map-get's \"maybe\" shape (() absent, (value) present) avoids confusing a stored () with not-found"))
(fixture (expr . "(map-get \"z\" (map-insert \"a\" 1 map-empty))") (expected . "()") (tier . 3) (axioms G5))
(fixture (expr . "(string-length \"\")") (expected . "0") (tier . 3) (axioms G5) (note . "PLAN.md item 14/20 — lib/core.my, expressible via string-first/string-rest/eq alone, no new Rust primitive needed"))
(fixture (expr . "(string-length \"hello\")") (expected . "5") (tier . 3) (axioms G5))
(fixture (expr . "(string-prefix? \"hell\" \"hello\")") (expected . "t") (tier . 3) (axioms G5))
(fixture (expr . "(string-prefix? \"world\" \"hello\")") (expected . "()") (tier . 3) (axioms G5))
(fixture (expr . "(string-contains? \"ell\" \"hello\")") (expected . "t") (tier . 3) (axioms G5))
(fixture (expr . "(string-contains? \"xyz\" \"hello\")") (expected . "()") (tier . 3) (axioms G5))
(fixture (expr . "(tcp-connect 42 8099)") (error . "Type") (tier . 2) (axioms) (note . "PLAN.md item 21 — a real listen/accept/connect round trip needs a live network peer, which conformance.my's single-session fixture runner can't provide; only the type-check error path is a pure expression testable this way. See crates/my-lisp/tests/tcp.rs for the live client/server round-trip, run on separate threads with separate Sessions."))
(fixture (expr . "(tcp-write \"not a connection\" \"x\")") (error . "Type") (tier . 2) (axioms))
(fixture (expr . "(process-run 42 (quote ()))") (error . "Type") (tier . 2) (axioms S2) (note . "process-run is unrestricted in the trusted native Lisp-machine profile, but still rejects a non-string program name with a named Type error. The fixture cannot accidentally launch a host process."))
(fixture (expr . "(write-file-bytes 42 (quote (1 2 3)))") (error . "Type") (tier . 2) (axioms) (note . "PLAN.md item 22 — a real write-file-bytes/read-file-bytes round trip is a filesystem side effect, which conformance.my's pure-expression fixture runner can't provide; only the type-check error path is testable this way. See crates/my-lisp/tests/mccarthy.rs's write_file_bytes_then_read_file_bytes_round_trips_non_utf8_bytes for the real round trip, including bytes (255, 254) that aren't valid standalone UTF-8 — the exact case write-file (String-based) can't represent."))
(fixture (expr . "(write-file-bytes \"path-does-not-matter.bin\" (quote (1 256 3)))") (error . "Type") (tier . 2) (axioms) (note . "PLAN.md item 22 — each byte-list element must be an integer 0-255"))
(fixture (expr . "(quotient 17 5)") (expected . "3") (tier . 3) (axioms G5) (note . "surfaced from the fpga-lisp session's assembler.my — lib/core.my, expressible via -, <, and cond alone, no new Rust primitive needed. Scope: non-negative a, positive b only"))
(fixture (expr . "(mod 17 5)") (expected . "2") (tier . 3) (axioms G5))
(fixture (expr . "(mod 100 10)") (expected . "0") (tier . 3) (axioms G5))
(fixture (expr . "(quotient 9999999999999 10)") (expected . "999999999999") (tier . 3) (axioms G5) (note . "regression fixture: the original repeated-subtraction quotient had recursion depth equal to the quotient's VALUE, not its digit count, and overflowed the Rust host's stack on exactly this input while implementing number->string. Fixed 2026-08-10 via a doubling algorithm, O(log(a/b)) depth"))
(fixture (expr . "(number->string 9999999999999)") (expected . "\"9999999999999\"") (tier . 3) (axioms G5) (note . "surfaced from the fpga-lisp session's assembler.my, which had its own version limited to ~10 digits by a fixed DECIMAL-POWERS table; this one has no digit-count ceiling of its own"))
(fixture (expr . "(number->string 0)") (expected . "\"0\"") (tier . 3) (axioms G5))
(fixture (expr . "(quotient 5 0)") (error . "DivisionByZero") (tier . 3) (since-contract 3 0) (axioms G5 S2) (note . "regression fixture: (quotient a 0) used to hang forever; contract 3.0 names the routed primitive / failure DivisionByZero"))
(fixture (expr . "(mod 5 0)") (error . "DivisionByZero") (tier . 3) (since-contract 3 0) (axioms G5 S2))
(fixture (expr . "(json-parse \"{\")") (error . "Parse") (tier . 2) (since-contract 3 0) (axioms S2) (note . "contract 3.0 classifies malformed decoder input as Parse, not InvalidForm"))
(fixture (expr . "(fourth (quote (w x y z)))") (expected . "z") (tier . 3) (axioms G5) (note . "surfaced from the fpga-lisp session's assembler.my — same single-parameter primitive-chain pattern as second/third, one step deeper"))
(fixture (expr . "(nth 2 (quote (a b c)))") (expected . "c") (tier . 3) (axioms G5))
(fixture (expr . "(member? (quote b) (quote (a b c)))") (expected . "t") (tier . 3) (axioms G5))
(fixture (expr . "(member? (quote q) (quote (a b c)))") (expected . "()") (tier . 3) (axioms G5))
(fixture (expr . "(assoc (quote b) (quote ((a . 1) (b . 2) (c . 3))))") (expected . "(b . 2)") (tier . 3) (axioms G5) (note . "generalizes the (symbol . value) alist-lookup shape lib/meta-eval.my's env-lookup already hand-rolls for its own specific case"))
(fixture (expr . "(assoc (quote q) (quote ((a . 1) (b . 2))))") (expected . "()") (tier . 3) (axioms G5))
(fixture (expr . "(cddr (quote (a b c d)))") (expected . "(c d)") (tier . 3) (axioms G5) (note . "found duplicated locally in lib/understand.my before being moved to core.my, 2026-08-10"))
(fixture (expr . "(00000011 cadddr fourth)") (expected . "(1)") (tier . 3) (axioms G5) (note . "cadddr is a literal alias for fourth, same closure object -- lib/reason.my had its own character-for-character-identical local cadddr before this dedup"))
(fixture (expr . "(fifth (quote (v w x y z)))") (expected . "z") (tier . 3) (axioms G5) (note . "found duplicated in two places at once: lib/narrate.my's own local fifth (identical), and lib/persistent-map.my's node-right (same operation, no name)"))
(fixture (expr . "(+ 123456789012345678901234567890 1)") (expected . "123456789012345678901234567891") (tier . 2) (axioms S1) (note . "bare integer literals use arbitrary precision beyond f64's exact 2^53 range; exact syntax never silently rounds"))
(fixture (expr . "(write-to-string (quote radio))") (expected . "\"radio\"") (tier . 2) (axioms G6 S1) (note . "canonical serialization: readable symbol"))
(fixture (expr . "(equal? (read (write-to-string (quote radio))) (quote radio))") (expected . "(1)") (tier . 2) (axioms G6 S1) (note . "canonical serialization round-trip: symbol"))
(fixture (expr . "(write-to-string \"line\\n\\t\\\"\\\\\")") (expected . "\"\\\"line\\\\n\\\\t\\\\\\\"\\\\\\\\\\\"\"") (tier . 2) (axioms G6 S1) (note . "canonical serialization: string escapes"))
(fixture (expr . "(equal? (read (write-to-string \"line\\n\\t\\\"\\\\\")) \"line\\n\\t\\\"\\\\\")") (expected . "(1)") (tier . 2) (axioms G6 S1) (note . "canonical serialization round-trip: escaped string"))
(fixture (expr . "(write-to-string (quote (alpha beta gamma)))") (expected . "\"(alpha beta gamma)\"") (tier . 2) (axioms G6 S1) (note . "canonical serialization: proper list"))
(fixture (expr . "(equal? (read (write-to-string (quote (alpha beta gamma)))) (quote (alpha beta gamma)))") (expected . "(1)") (tier . 2) (axioms G6 S1) (note . "canonical serialization round-trip: proper list"))
(fixture (expr . "(write-to-string (quote (alpha beta . gamma)))") (expected . "\"(alpha beta . gamma)\"") (tier . 2) (axioms G6 S1) (note . "canonical serialization: dotted list"))
(fixture (expr . "(equal? (read (write-to-string (quote (alpha beta . gamma)))) (quote (alpha beta . gamma)))") (expected . "(1)") (tier . 2) (axioms G6 S1) (note . "canonical serialization round-trip: dotted list"))
(fixture (expr . "(list (write-to-string 42) (write-to-string 10/20))") (expected . "(\"#q2:101010/1\" \"#q2:1/10\")") (tier . 2) (axioms G6 S1) (note . "canonical machine wire: tagged binary exact integer and reduced rational; human presentation remains decimal/rational"))
(fixture (expr . "(list (equal? (read (write-to-string 42)) 42) (equal? (read (write-to-string 10/20)) 1/2))") (expected . "((1) (1))") (tier . 2) (axioms G6 S1) (note . "canonical serialization round-trip: exact numbers"))
(fixture (expr . "(list (write-to-string 3.00) (write-to-string 1.25))") (expected . "(\"#q2:11/1\" \"#q2:101/100\")") (tier . 2) (axioms G6 S1) (note . "canonical machine wire is binary and exact; source spelling 3.00/1.25 does not leak into the wire"))
(fixture (expr . "(list (equal? (read (write-to-string 3.00)) 3.0) (equal? (read (write-to-string 1.25)) 1.25))") (expected . "((1) (1))") (tier . 2) (axioms G6 S1) (note . "canonical serialization round-trip: exact numbers, decimal literals are exact by default"))
(fixture (expr . "(cond (0 (quote zero-is-truthy)) (t (quote wrong)))") (expected . "zero-is-truthy") (tier . 3) (axioms) (role . "historical-compatibility") (compatibility . historical-truthiness) (note . "Historical duplicate of the surface/migration Number-0 truthiness witness; not current Contract 11.8 control authority.") (meta-eval . t))
(fixture (expr . "(-> 10 (+ 2) (* 3))") (expected . "36") (tier . 3) (axioms G5) (note . "thread-first macro (->) unwraps forms recursively"))
(fixture (expr . "(->> 10 (+ 2) (* 3))") (expected . "36") (tier . 3) (axioms G5) (note . "thread-last macro (->>) unwraps forms recursively, placing subject last"))
(fixture (expr . "(-> 5 (- 2))") (expected . "3") (tier . 3) (axioms G5))
(fixture (expr . "(->> 5 (- 2))") (expected . "-3") (tier . 3) (axioms G5))
(fixture (expr . "(-> 5)") (expected . "5") (tier . 3) (axioms G5))
(fixture (expr . "(->> 5)") (expected . "5") (tier . 3) (axioms G5))
(fixture (expr . "(number->string 1/3)") (expected . "\"#q2:1/11\"") (tier . 3) (axioms G5 S1) (note . "number->string delegates to canonical machine wire; human rational presentation is a separate projection"))
(fixture (expr . "(number->string 10/20)") (expected . "\"#q2:1/10\"") (tier . 3) (axioms G5 S1) (note . "reduced exact value in the same tagged binary wire as write-to-string"))
(fixture (expr . "(number->string -10/4)") (expected . "\"#q2:-101/10\"") (tier . 3) (axioms G5 S1) (note . "negative reduced exact value in canonical binary wire"))
(fixture (expr . "#i32(1 -2 3)") (expected . "#i32(1 -2 3)") (tier . 2) (since-contract 2 2) (requires typed-numeric-buffers) (axioms G6 G7 S1))
(fixture (expr . "(i32-buffer 1 -2 3)") (expected . "#i32(1 -2 3)") (tier . 2) (since-contract 2 2) (requires typed-numeric-buffers) (axioms G6 G7 S1))
(fixture (expr . "(f32-buffer 1 1/10 -2.5)") (expected . "#f32(1.0 0.1 -2.5)") (tier . 2) (since-contract 2 2) (requires typed-numeric-buffers) (axioms G6 G7 S1) (note . "f32 conversion is explicit and returns inexact elements"))
(fixture (expr . "(list (numeric-buffer-type #i32()) (numeric-buffer-length #f32(1.0 2.0)) (numeric-buffer-ref #i32(-7) 0))") (expected . "(i32 2 -7)") (tier . 2) (since-contract 2 2) (requires typed-numeric-buffers) (axioms G6 G7 S1))
(fixture (expr . "(00000011 (read (write-to-string #f32(1.0 0.1 -2.5))) #f32(1.0 0.1 -2.5))") (expected . "(1)") (tier . 2) (since-contract 2 2) (requires typed-numeric-buffers) (axioms G6 G7 S1))
(fixture (expr . "(i32-buffer 2147483648)") (error . "NumericOverflow") (tier . 2) (since-contract 2 2) (requires typed-numeric-buffers) (axioms S2 S3))
(fixture (expr . "(i32-buffer 1/2)") (error . "Type") (tier . 2) (since-contract 2 2) (requires typed-numeric-buffers) (axioms S1 S2))
(fixture (expr . "(numeric-buffer-map (lambda (x) (+ x 1)) #i32(1 2 3))") (expected . "#i32(2 3 4)") (tier . 2) (since-contract 2 3) (requires typed-numeric-buffers numeric-buffer-map) (axioms G6 G7 S1))
(fixture (expr . "(numeric-buffer-map (lambda (x) (+ x 0.5)) #f32(1.0 2.0))") (expected . "#f32(1.5 2.5)") (tier . 2) (since-contract 2 3) (requires typed-numeric-buffers numeric-buffer-map) (axioms G6 G7 S1))
(fixture (expr . "(numeric-buffer-map (lambda (x) (+ x 1)) #i32(2147483647))") (error . "NumericOverflow") (tier . 2) (since-contract 2 3) (requires typed-numeric-buffers numeric-buffer-map) (axioms S2 S3))
(fixture (expr . "(abs -5)") (expected . "5") (tier . 3) (axioms G5))
(fixture (expr . "(abs 5.5)") (expected . "11/2") (tier . 3) (axioms G5 S1))
(fixture (expr . "(abs (/ -3 4))") (expected . "3/4") (tier . 3) (axioms G5 S1))
(fixture (expr . "(abs 0)") (expected . "0") (tier . 3) (axioms G5))
(fixture (expr . "(min 3 1 2)") (expected . "1") (tier . 3) (axioms G5))
(fixture (expr . "(max 3 1 2)") (expected . "3") (tier . 3) (axioms G5))
(fixture (expr . "(min 5)") (expected . "5") (tier . 3) (axioms G5) (note . "single argument is vacuously the minimum"))
(fixture (expr . "(min)") (error . "Arity") (tier . 3) (axioms G5 S2) (note . "required first parameter (dotted lambda-list) gives the Arity error structurally, not a hand-written check"))
(fixture (expr . "(max)") (error . "Arity") (tier . 3) (axioms G5 S2))
(fixture (expr . "(min-list (quote (5 2 8 1)))") (expected . "1") (tier . 3) (axioms G5))
(fixture (expr . "(max-list (quote (5 2 8 1)))") (expected . "8") (tier . 3) (axioms G5))
(fixture (expr . "(min-list (quote ()))") (expected . "()") (tier . 3) (axioms G5 G8) (note . "empty list argument is Nil, distinct from min/max's own zero-argument Arity error above"))
(fixture (expr . "(max-list (quote ()))") (expected . "()") (tier . 3) (axioms G5 G8))
(fixture (expr . "(cond ((quote radio) antenna (quote wrong)))") (error . "UnsatisfiedConditional") (tier . 1) (since-contract 8 0) (axioms G8 S2) (role . "historical-compatibility") (compatibility . historical-cond-contract-8-0) (note . "Historical Contract 8.0 three-part COND / UnsatisfiedConditional expectation. Current Contract 11.8 uses exact D1 PredicateBit control and the admitted two-field clause form; this row is retained for provenance only."))
()
