; Machine-readable summary of docs/PROPOSAL-TYPED-NUMERIC-BUFFERS.md.
; Machine-readable summary of the ratified language contract 2.2 boundary.

((kind . typed-numeric-buffer-proposal)
 (version . (0 1))
 (status . ratified-implemented)
 (current-language-contract . (2 2))
 (value-semantics . immutable)
 (element-types . ((i32 . ((domain . exact-integer)
                           (minimum . -2147483648)
                           (maximum . 2147483647)
                           (overflow . NumericOverflow)))
                   (f32 . ((domain . explicit-inexact-ieee754-binary32)
                           (rounding . nearest-ties-to-even)
                           (non-finite . unsupported)
                           (overflow . NumericOverflow)))))
 (canonical-reader-forms . ("#i32(...)" "#f32(...)"))
 (gpu-admission . ((purity-proof . required)
                   (contiguous-storage-proof . required)
                   (numeric-representation-proof . required)
                   (unknown-facts . reject)
                   (fallback . cpu)))
 (invariants . ((implicit-exact-to-f32 . forbidden)
                (mutation . forbidden)
                (backend-selection-changes-result . forbidden)
                (vendor-api-in-source-semantics . forbidden)))
 (implementation . crates/my-lisp)
 (authority . "language-contract.lisp 2.2 and tests/fixtures/conformance.lisp"))
