; #114/#115 authority inventory projection.
; Lisp reads this as data; CI/host code may transport paths but must not own
; the allow/deny rule. Keep tests/authority-inventory.tsv as the tabular audit
; projection for reviewers.

(authority "crates/my-lisp/tests/witness_authority.rs" observer)
(authority "crates/my-lisp/tests/probabilistic_decision_jev_like.rs" observer)
(authority "crates/my-lisp/tests/member_named_vs_sid_cost_1278.rs" observer)
(authority "crates/my-lisp/tests/backend_not_on_sid_gap.rs" observer)
(authority "crates/my-lisp/tests/guard.rs" observer)
(authority "crates/my-lisp/tests/structural_observation_contract.rs" observer)
(authority "crates/my-lisp/tests/exact_q_binary_contract.rs" observer)
(authority "crates/my-lisp/tests/mathematical_result_taxonomy.rs" observer)
(authority "crates/my-lisp/tests/canon_laws_v2_contract.rs" observer)
(authority "crates/my-lisp/tests/reason_honesty_contract.rs" observer)
(authority "crates/my-lisp/tests/unification_outcome_contract.rs" observer)
(authority "crates/my-lisp/tests/knowledge_clause_kind_contract.rs" observer)
(authority "crates/my-lisp/tests/authority_guard_contract.rs" observer)
(authority "crates/my-lisp/tests/content_store_authority.rs" observer)
(authority "crates/my-lisp/tests/decimal_comma_authority.rs" observer)
(authority "crates/my-lisp/tests/epistemic_authority.rs" observer)
(authority "crates/my-lisp/tests/mccarthy.rs" semantic-authority)
(authority "crates/my-lisp/tests/ukrainian_api_docs.rs" semantic-authority)
(authority "crates/my-lisp/tests/rivnopravnist_mov.rs" observer)
(authority "tests/fixtures/authority-guard/forbidden-semantic.rs" semantic-authority)
(authority "tests/fixtures/authority-guard/allowed-mechanism.rs" mechanism)
(authority "crates/my-lisp/tests/skylake_inventory_contract.rs" observer)
(authority "crates/xtask/tests/xed_import_cli.rs" observer)
(authority "crates/xtask/tests/external_oracle_cli.rs" observer)
(authority "crates/my-lisp/tests/machine_noninterference_contract.rs" observer)
(authority "crates/my-lisp/tests/x86_64_lisp_encoder.rs" mechanism)
(authority "crates/xtask/tests/encoder_coverage_cli.rs" observer)
(authority "crates/my-lisp/tests/machine_admission_adversarial.rs" mechanism)
(authority "crates/my-lisp/tests/machine_atoms.rs" mechanism)
(authority "crates/my-lisp/tests/machine_typed_operands.rs" mechanism)
(authority "crates/my-lisp/tests/machine_block_roundtrip.rs" mechanism)
(authority "crates/my-lisp/tests/support/x86_64_block_decoder.rs" mechanism)
(authority "crates/my-lisp/tests/machine_lowering_boundary.rs" observer)
(authority "crates/my-lisp-host/tests/native_lisp_bytes.rs" mechanism)
(authority "crates/my-lisp-host/tests/windows_native_exec_abi.rs" mechanism)
(authority "crates/my-lisp-host/tests/native_guest_abi.rs" mechanism)
(authority "crates/my-lisp/tests/machine_minimal_profile.rs" observer)
(authority "crates/my-lisp-host/tests/native_cond_profile.rs" mechanism)
(authority "crates/xtask/tests/license_policy.rs" observer)
(authority "crates/my-lisp/tests/full_uk_surface.rs" observer)

(authority "crates/my-lisp/tests/i5_6400_machine_profile.rs" observer)
(authority "crates/my-lisp/tests/semantic_ref_fail_closed.rs" mechanism)
(authority "crates/my-lisp/tests/uk_docs_surface_model.rs" observer)
(authority "crates/my-lisp/tests/uk_surface_equivalence.rs" observer)
(authority "crates/my-lisp/tests/uk_surface_inventory.rs" observer)
(authority "crates/my-lisp/tests/macro_derivation.rs" mechanism)
(authority "crates/my-lisp/tests/meta_eval_advice_taker.rs" observer)
(authority "crates/my-lisp/tests/yantra.rs" observer)
(authority "crates/wsm-common-lisp-kernel/tests/c_abi_semantic_witness.rs" mechanism)
(authority "crates/wsm-prolog-kernel/tests/c_abi_semantic_witness.rs" mechanism)
(authority "crates/wsm-clips-kernel/tests/c_abi_semantic_witness.rs" mechanism)
(authority "crates/wsm-kernel-host/tests/language_simplify_island_orchestration.rs" observer)
(authority "crates/wsm-native-result-types/tests/four_real_kernels.rs" observer)
(authority "crates/wsm-datalog-kernel/tests/c_abi_semantic_witness.rs" mechanism)
(authority "crates/my-lisp/tests/utf8.rs" observer)
(authority "crates/my-lisp-cli/tests/semantic_oracle_preservation.rs" observer)
(authority "crates/my-lisp-cli/tests/legacy_coordination_rejected.rs" observer)
(authority "crates/my-lisp-cli/tests/islands_cli.rs" mechanism)
(authority "tests/fixtures/semantic-coordinate-law-axis-v1.lisp" semantic-witness)
(authority "crates/sens/tests/semantic_coordinate_law_axis.rs" observer)
(authority "crates/my-lisp/tests/machine_capability_axis.rs" observer)
(authority "crates/my-lisp/tests/semantic_coordinate_join.rs" observer)
(authority "crates/my-lisp/tests/error_kind_vocabulary_is_closed.rs" observer)

(authority "crates/my-lisp/tests/semantic_coordinate_matrix_845.rs" observer)
(authority "tests/fixtures/semantic-coordinate-matrix-845.lisp" semantic-witness)
(authority "crates/wsm-native-result-types/tests/kernel_availability.rs" observer)
(authority "crates/wsm-native-result-types/tests/kernel_lifecycle.rs" mechanism)
(authority "crates/wsm-native-result-types/tests/observation_capabilities.rs" observer)

(authority "lib/bridge/prolog-to-datalog.lisp" semantic-witness)
(authority "tests/fixtures/prolog-datalog-bridge-witness.lisp" semantic-witness)
(authority "crates/wsm-native-result-types/tests/prolog_datalog_bridge.rs" observer)

(authority "crates/wsm-native-result-types/tests/observation_provenance.rs" observer)
(authority "crates/my-lisp-cli/tests/islands_release_asset.rs" mechanism)
(authority "crates/my-lisp/tests/clock.rs" observer)
(authority "crates/my-lisp/tests/timezone_ownership.rs" observer)
(authority "crates/my-lisp/tests/semantic_coordinate_join_2.rs" observer)
(authority "crates/my-lisp/tests/life_1_scheduler.rs" observer)

(authority "crates/my-lisp/tests/semantic_registry_lisp.rs" observer)
(authority "crates/my-lisp/tests/runtime_peer_operators.rs" observer)
(authority "crates/my-lisp/tests/canon_authority_inventory.rs" observer)
(authority "crates/my-lisp/tests/semantic_authority_guard_1049.rs" observer)
(authority "crates/my-lisp/tests/program_surface_translation.rs" observer)
(authority "contracts/datalog-math-capability-1001.lisp" semantic-witness)
(authority "crates/wsm-datalog-kernel/tests/arithmetic_execution_1001.rs" observer)

(authority "crates/my-lisp/tests/uk_surface.rs" observer)
(authority "crates/my-lisp/tests/world.rs" observer)
(authority "crates/my-lisp/tests/sens_foundation.rs" observer)
(authority "crates/my-lisp-cli/tests/cli.rs" observer)
(authority "crates/sens/tests/sens_smoke.rs" observer)
(authority "crates/my-lisp/tests/canon_adversarial.rs" observer)
(authority "crates/my-lisp/tests/semantic_form_identity.rs" observer)
(authority "crates/my-lisp/tests/ukr_acceptance.rs" observer)

(authority "crates/my-lisp/tests/core_profile_runtime_1272.rs" observer)
(authority "crates/my-lisp/tests/sens_host_registration_admission_1406.rs" observer)
(authority "crates/my-lisp/tests/core3_profile_runtime_1414.rs" observer)
(authority "crates/sens/tests/machine_asm_differential.rs" mechanism)
(authority "crates/sens/tests/machine_semantic_effect_lowering.rs" observer)
