#!r6rs
(import (rnrs))

;; Source-only R6RS reference computation, not the SENS interpreter.
(define (bits str)
  (map (lambda (c)
         (cond ((char=? c #\0) 0)
               ((char=? c #\1) 1)
               (else (assertion-violation 'bits "non-binary digit"))))
       (string->list str)))
(define (tap mask order j)
  (mod (div mask (expt 2 (- order j 1))) 2))
(define (fits? sequence order mask)
  (let ((n (length sequence)))
    (let loop-t ((t order))
      (if (= t n)
          #t
          (let loop-j ((j 0) (value 0))
            (if (= j order)
                (and (= value (list-ref sequence t))
                     (loop-t (+ t 1)))
                (loop-j (+ j 1)
                        (mod (+ value
                                (* (tap mask order j)
                                   (list-ref sequence (- t j 1))))
                             2))))))))
(define (taps mask order)
  (let loop ((j 0) (out '()))
    (if (= j order)
        (reverse out)
        (loop (+ j 1) (cons (tap mask order j) out)))))
(define (reference seq)
  (let order-loop ((L 0))
    (if (> L (length seq))
        (assertion-violation 'reference "no finite recurrence")
        (let mask-loop ((mask 0))
          (cond ((>= mask (expt 2 L)) (order-loop (+ L 1)))
                ((fits? seq L mask) (cons L (taps mask L)))
                (else (mask-loop (+ mask 1))))))))
(define (check input expected)
  (let ((actual (reference (bits input))))
    (unless (equal? actual expected)
      (assertion-violation 'gf2-recurrence "oracle mismatch"
                           input expected actual))))
(check "" '(0))
(check "0" '(0))
(check "1" '(1 0))
(check "00000" '(0))
(check "11111" '(1 1))
(check "010101" '(2 0 1))
(check "101001" '(3 1 0 1))
(check "11010110010001111010" '(4 1 0 0 1))
;; Test all finite samples up to eight bits: conformance and observed fit.
(define (word mask n)
  (let loop ((j 0) (out '()))
    (if (= j n) (reverse out)
        (loop (+ j 1)
              (cons (tap mask n j) out)))))
(define inspected 0)
(do ((n 0 (+ n 1))) ((> n 8))
  (do ((mask 0 (+ mask 1))) ((= mask (expt 2 n)))
    (let* ((s (word mask n))
           (out (reference s))
           (degree (car out))
           (coeff (cdr out))
           (packed (fold-left (lambda (a x) (+ (* 2 a) x)) 0 coeff)))
      (unless (and (= degree (length coeff))
                   (fits? s degree packed))
        (assertion-violation 'gf2-recurrence "invalid inferred recurrence"))
      (set! inspected (+ inspected 1)))))
(display "R6RS GF2 RECURRENCE PASS: ")
(display inspected)
(display " exhaustive observed finite words, exact minimality via enumeration, 0 coordinates")
(newline)
