#!r6rs
(import (rnrs))
;; Actual Chez Scheme R6RS independent donor computation, not SENS execution.
(define checks 0)
(define (must label truth)
  (if truth (set! checks (+ checks 1))
      (assertion-violation 'binary-lyndon label)))

(define (valid-bits? s)
  (and (string? s)
       (let loop ((i 0))
         (or (= i (string-length s))
             (and (or (char=? (string-ref s i) #\0)
                      (char=? (string-ref s i) #\1))
                  (loop (+ i 1)))))))

(define (lyndon? s)
  (and (> (string-length s) 0)
       (let loop ((i 1))
         (or (= i (string-length s))
             (and (string<? s (substring s i (string-length s)))
                  (loop (+ i 1)))))))

(define (nonincreasing? factors)
  (or (null? factors) (null? (cdr factors))
      (and (string>=? (car factors) (cadr factors))
           (nonincreasing? (cdr factors)))))

(define (factorize s)
  (if (not (valid-bits? s))
      (assertion-violation 'factorize "finite D1 word required")
      (let ((n (string-length s)))
        (let outer ((i 0) (acc '()))
          (if (= i n)
              (reverse acc)
              (let scan ((j (+ i 1)) (k i))
                (if (and (< j n)
                         (char<=? (string-ref s k) (string-ref s j)))
                    (scan (+ j 1)
                          (if (char<? (string-ref s k) (string-ref s j))
                              i (+ k 1)))
                    (let ((size (- j k)))
                      (let emit ((pos i) (acc acc))
                        (if (> pos k)
                            (outer pos acc)
                            (emit (+ pos size)
                                  (cons (substring s pos (+ pos size)) acc))))))))))))

(define (check word expected)
  (let ((factors (factorize word)))
    (must "fixture exact" (equal? factors expected))
    (must "reconstruction" (string=? (apply string-append factors) word))
    (must "lyndon pieces" (for-all lyndon? factors))
    (must "nonincreasing order" (nonincreasing? factors))))

(check "" '())
(check "0" '("0"))
(check "1111" '("1" "1" "1" "1"))
(check "01010" '("01" "01" "0"))
(check "010010010001000" '("01" "001" "001" "0001" "0" "0" "0"))
(check "001001" '("001" "001"))
(check "101" '("1" "01"))

(define (binary-words n)
  (if (= n 0) '("")
      (let ((shorter (binary-words (- n 1))))
        (append (map (lambda (w) (string-append "0" w)) shorter)
                (map (lambda (w) (string-append "1" w)) shorter)))))

(do ((n 0 (+ n 1))) ((> n 10))
  (for-each (lambda (w)
              (let ((pieces (factorize w)))
                (must "exhaustive reconstruct"
                      (string=? w (apply string-append pieces)))
                (must "exhaustive Lyndon"
                      (for-all lyndon? pieces))
                (must "exhaustive order"
                      (nonincreasing? pieces))))
            (binary-words n)))

(define (rejected? thunk)
  (guard (e [(assertion-violation? e) #t] [else #f])
    (thunk) #f))
(must "reject non-binary digit" (rejected? (lambda () (factorize "012"))))
(must "reject non-binary alphabet" (rejected? (lambda () (factorize "ab"))))
(must "reject non-word" (rejected? (lambda () (factorize 5))))

(display "D10-BINARY-LYNDON Chez R6RS oracle PASS checks=")
(display checks)
(newline)
