#!r6rs
(import (rnrs))
;; Independent R6RS mathematical donor, not SENS runtime.
(define (bits? w)
  (and (string? w)
       (let loop ((i 0))
         (or (= i (string-length w))
             (and (or (char=? (string-ref w i) #\0)
                      (char=? (string-ref w i) #\1))
                  (loop (+ i 1)))))))
(define (window w pos n)
  (let ((out (make-string n #\0)) (len (string-length w)))
    (do ((j 0 (+ j 1))) ((= j n) out)
      (string-set! out j (string-ref w (mod (+ pos j) len)))))
)
(define (distinct? words)
  (let loop ((left words) (seen '()))
    (if (null? left) #t
        (and (not (member (car left) seen))
             (loop (cdr left) (cons (car left) seen))))))
(define (debruijn? w n)
  (cond
    ((not (and (integer? n) (exact? n) (> n 0)))
     (assertion-violation 'debruijn "positive exact order required"))
    ((not (bits? w))
     (assertion-violation 'debruijn "D1-bit word required"))
    ((not (= (string-length w) (expt 2 n))) #f)
    (else
      (let loop ((i 0) (seen '()))
        (if (= i (string-length w))
            #t
            (let ((next (window w i n)))
              (and (not (member next seen))
                   (loop (+ i 1) (cons next seen))))))))
)
(define observations 0)
(define (must label ok)
  (if ok (set! observations (+ 1 observations))
      (assertion-violation 'debruijn label)))
(define (witness w n expected)
  (must "fixture" (eq? (debruijn? w n) expected)))
(witness "01" 1 #t)
(witness "10" 1 #t)
(witness "0011" 2 #t)
(witness "00010111" 3 #t)
(witness "00101110" 3 #t)
(witness "10001011" 3 #t)
(witness "00010110" 3 #f)
(witness "00000000" 3 #f)
(witness "000101110" 3 #f)
(witness "" 1 #f)
(witness "0101" 2 #f)
(witness "0010" 2 #f)
(define (numeric-word value width)
  (let ((w (make-string width #\0)))
    (let loop ((pos (- width 1)) (v value))
      (if (< pos 0) w
          (begin
            (string-set! w pos (if (odd? v) #\1 #\0))
            (loop (- pos 1) (div v 2)))))))
(define (rotate w i)
  (string-append (substring w i (string-length w)) (substring w 0 i)))
(for-each
  (lambda (x)
    (let* ((w (car x)) (n (cdr x)) (len (string-length w)))
      (do ((i 0 (+ i 1))) ((= i len))
        (must "rotation invariance" (debruijn? (rotate w i) n)))))
  '(("01" . 1) ("0011" . 2) ("00010111" . 3)))
(do ((n 1 (+ n 1))) ((> n 3))
  (let* ((len (expt 2 n)) (limit (expt 2 len)))
    (do ((v 0 (+ v 1))) ((= v limit))
      (let* ((w (numeric-word v len))
             (windows (let loop ((i 0) (out '()))
                        (if (= i len) out
                            (loop (+ i 1) (cons (window w i n) out))))))
        (must "independent cyclic windows"
              (eq? (distinct? windows) (debruijn? w n)))))))
(define (rejects? thunk)
  (guard (e [(assertion-violation? e) #t] [else #f])
    (thunk) #f))
(must "n=0 rejected" (rejects? (lambda () (debruijn? "0011" 0))))
(must "float order rejected" (rejects? (lambda () (debruijn? "0011" 2.0))))
(must "non-D1 bit rejected" (rejects? (lambda () (debruijn? "0021" 2))))
(display "D10 DE-BRUIJN R6RS DONOR PASS checks=")
(display observations)
(newline)
