#!r6rs
(import (rnrs))
(define (word n k rho)
  (if (and (exact? n) (integer? n) (> n 0)
           (exact? k) (integer? k) (<= 0 k n)
           (exact? rho) (rational? rho) (<= 0 rho) (< rho 1))
      (let loop ((i 0) (out '()))
        (if (= i n) (reverse out)
            (loop (+ i 1)
                  (cons (- (floor (+ (/ (* (+ i 1) k) n) rho))
                           (floor (+ (/ (* i k) n) rho))) out))))
      (assertion-violation 'word "invalid arguments")))
(define (sum-bits xs)
  (if (null? xs) 0 (+ (car xs) (sum-bits (cdr xs)))))
(define (must condition)
  (if (not condition) (assertion-violation 'oracle "math law violated")))
(define count 0)
(define (run n k rho expected)
  (let ((actual (word n k rho)))
    (must (equal? actual expected))
    (must (= (length actual) n))
    (must (= (sum-bits actual) k))
    (set! count (+ count 1))))
(run 8 3 0 '(0 0 1 0 0 1 0 1))
(run 8 3 1/2 '(0 1 0 1 0 0 1 0))
(run 8 5 0 '(0 1 0 1 1 0 1 1))
(run 5 2 1/3 '(0 1 0 0 1))
(run 12 4 0 '(0 0 1 0 0 1 0 0 1 0 0 1))
(do ((n 1 (+ n 1))) ((> n 24))
  (do ((k 0 (+ k 1))) ((> k n))
    (for-each
      (lambda (rho)
        (let ((bits (word n k rho)))
          (must (= (length bits) n))
          (must (= (sum-bits bits) k))
          (set! count (+ count 1))))
      '(0 1/7 1/2 5/7))))
(display "R6RS MECHANICAL WORD ORACLE PASS cases=")
(display count)
(newline)
