#!r6rs
(import (rnrs))

;; Незалежна реалізація точної семантики над рядками бітів у Chez Scheme.
;; Це еталон донора, не виконання двійкової SENS.
(define (valid-bits? w)
  (and (string? w)
       (let loop ((i 0))
         (or (= i (string-length w))
             (and (or (char=? (string-ref w i) #\0)
                      (char=? (string-ref w i) #\1))
                  (loop (+ i 1)))))))
(define (times prefix k)
  (let loop ((i k) (out ""))
    (if (= i 0) out (loop (- i 1) (string-append out prefix)))))
(define (root w)
  (if (not (valid-bits? w))
      (assertion-violation 'root "D1 bits only")
      (let ((n (string-length w)))
        (if (= n 0) ""
            (let loop ((p 1))
              (cond
                ((> p n) (assertion-violation 'root "unreachable"))
                ((and (= (mod n p) 0)
                      (string=? w (times (substring w 0 p) (div n p))))
                 (substring w 0 p))
                (else (loop (+ p 1))))))))
(define seen 0)
(define (must label truth)
  (if truth (set! seen (+ seen 1))
      (assertion-violation 'root label)))
(define (check w expected)
  (let ((u (root w)))
    (must "exact expected root" (string=? u expected))
    (must "idempotence" (string=? (root u) u))
    (if (= (string-length w) 0)
        (must "empty has empty root" (= (string-length u) 0))
        (must "exact repetition" (string=? w (times u (div (string-length w)
                                                          (string-length u))))))))
(check "" "")
(check "01010101" "01")
(check "01010" "01010")
(check "101101101" "101")
(check "000000" "0")
(check "001001" "001")
(check "00100" "00100")
(check "11111111" "1")
(must "partial overlap not primitive root" (not (string=? (root "01010") "01")))
(define (enumerate-binary n)
  (if (= n 0) (list "")
      (let ((old (enumerate-binary (- n 1))))
        (append (map (lambda (s) (string-append "0" s)) old)
                (map (lambda (s) (string-append "1" s)) old)))))
(do ((n 0 (+ n 1))) ((> n 12))
  (for-each
   (lambda (w)
     (let ((u (root w)))
       (must "short word returns primitive repetition"
             (or (= (string-length w) 0)
                 (string=? (times u (div (string-length w)
                                         (string-length u))) w)))
       (must "root itself primitive" (string=? (root u) u))))
   (enumerate-binary n)))
(display "R6RS PRIMITIVE BINARY WORD ROOT PASS checks=")
(display seen)
(newline)
