#!r6rs
(import (rnrs))

;; Chez Scheme R6RS independent historical donor oracle, NOT SENS execution.
;; Regex data: zero | eps | (bit 0/1) | (or r s) | (cat r s) | (star r).
(define (zero? r) (eq? r 'zero))
(define (eps? r) (eq? r 'eps))
(define (mk-or a b)
  (cond ((zero? a) b) ((zero? b) a) ((equal? a b) a)
        (else (list 'or a b))))
(define (mk-cat a b)
  (cond ((or (zero? a) (zero? b)) 'zero)
        ((eps? a) b) ((eps? b) a)
        (else (list 'cat a b))))
(define (nullable? r)
  (cond ((zero? r) #f) ((eps? r) #t)
        ((eq? (car r) 'bit) #f)
        ((eq? (car r) 'or)
         (or (nullable? (cadr r)) (nullable? (caddr r))))
        ((eq? (car r) 'cat)
         (and (nullable? (cadr r)) (nullable? (caddr r))))
        ((eq? (car r) 'star) #t)
        (else (assertion-violation 'nullable "invalid AST" r))))
(define (derive r a)
  (cond
    ((or (zero? r) (eps? r)) 'zero)
    ((eq? (car r) 'bit) (if (= (cadr r) a) 'eps 'zero))
    ((eq? (car r) 'or)
     (mk-or (derive (cadr r) a) (derive (caddr r) a)))
    ((eq? (car r) 'cat)
     (mk-or (mk-cat (derive (cadr r) a) (caddr r))
            (if (nullable? (cadr r))
                (derive (caddr r) a) 'zero)))
    ((eq? (car r) 'star)
     (mk-cat (derive (cadr r) a) r))
    (else (assertion-violation 'derive "invalid AST" r))))
(define (matches-direct r word)
  ;; This is direct word splitting; it never invokes derive or nullable.
  (cond
    ((zero? r) #f)
    ((eps? r) (string=? word ""))
    ((eq? (car r) 'bit)
     (and (= (string-length word) 1)
          (char=? (string-ref word 0)
                  (if (= (cadr r) 0) #\0 #\1))))
    ((eq? (car r) 'or)
     (or (matches-direct (cadr r) word)
         (matches-direct (caddr r) word)))
    ((eq? (car r) 'cat)
     (let ((n (string-length word)))
       (let loop ((i 0))
         (and (<= i n)
              (or (and (matches-direct (cadr r) (substring word 0 i))
                       (matches-direct (caddr r) (substring word i n)))
                  (loop (+ i 1)))))))
    ((eq? (car r) 'star)
     (let ((n (string-length word)))
       (if (= n 0) #t
           (let loop ((i 1))
             (and (<= i n)
                  (or (and (matches-direct (cadr r) (substring word 0 i))
                           (matches-direct r (substring word i n)))
                      (loop (+ i 1))))))))
    (else (assertion-violation 'matches-direct "invalid AST" r))))
(define (enumerate-bits n)
  (if (= n 0) (list "")
      (let ((prev (enumerate-bits (- n 1))))
        (append (map (lambda (w) (string-append "0" w)) prev)
                (map (lambda (w) (string-append "1" w)) prev)))))
(define checks 0)
(define (must label truth)
  (if truth
      (set! checks (+ checks 1))
      (assertion-violation 'brzozowski-1964 label)))
(define bit0 '(bit 0))
(define bit1 '(bit 1))
(define rx01 (list 'cat bit0 bit1))
(define rx0-star-1 (list 'cat (list 'star bit0) bit1))
(define samples
  (list 'zero 'eps bit0 bit1
        (list 'or bit0 bit1)
        rx01 rx0-star-1
        (list 'star bit0)
        (list 'star bit1)
        (list 'star (list 'or bit0 bit1))
        (list 'cat (list 'or 'eps bit0) bit1)
        (list 'star rx01)))
(define (check-r r a)
  (let ((residual (derive r a))
        (prefix (if (= a 0) "0" "1")))
    (do ((n 0 (+ n 1))) ((> n 5))
      (for-each
       (lambda (suffix)
         (must "D_a(L) exactly suffixes for a·suffix"
               (eq? (matches-direct residual suffix)
                    (matches-direct r (string-append prefix suffix)))))
       (enumerate-bits n)))))
(for-each
 (lambda (regex)
   (check-r regex 0)
   (check-r regex 1))
 samples)
(must "nullable left concatenation matters"
      (nullable? (derive rx0-star-1 1)))
(must "literal 0 derivative leaves epsilon"
      (nullable? (derive bit0 0)))
(must "literal 1 derivative rejects 0"
      (not (nullable? (derive bit1 0))))
(must "empty language never accepts"
      (not (nullable? (derive 'zero 0))))
(display "D10 BRZOZOWSKI 1964 CHEZ R6RS ORACLE PASS checks=")
(display checks)
(newline)
