//! #1675: canonical completion gate for the active authored Lisp library.
//!
//! This test intentionally delegates "is this executable surface safely
//! convertible?" to the real `sens-to-sens` tool.  The older repository
//! inventories are conservative lexical ratchets and may still count names in
//! quote/data/shadowing positions.  Migration completion must not be faked by
//! rewriting those positions.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repo root")
}

fn tool() -> Command {
    Command::new(env!("CARGO_BIN_EXE_sens-to-sens"))
}

fn is_explicit_non_implementation(rel: &str) -> bool {
    rel.starts_with("lib/generated/")
        || rel.starts_with("lib/surface/")
        || rel == "lib/machine/encoding/coverage.lisp"
}

/// The *only* machine catalogue excluded from executable source migration.
/// Verify the actual generated record grammar, not a filename/marker alone:
/// otherwise one appended executable form would silently escape the gate.
fn is_generated_iclass_catalogue(rel: &str, source: &str) -> bool {
    if rel != "lib/machine/encoding/admitted-iclass-index.lisp" {
        return false;
    }

    let mut lines = source.lines().map(str::trim).filter(|line| !line.is_empty());
    if lines.next()
        != Some("; GENERATED by scripts/generate-encoder-coverage-input.py -- do not hand-edit.")
        || lines.next()
            != Some("; Compact #175 evidence projection: no status, opcode, semantic ID, or policy.")
        || lines.next() != Some("(x86-admitted-iclass-index/2")
    {
        return false;
    }

    let count = match lines.next()
        .and_then(|line| line.strip_prefix("(pair-count #b"))
        .and_then(|bits| bits.strip_suffix(')'))
    {
        Some(bits) if !bits.is_empty() && bits.bytes().all(|ch| ch == b'0' || ch == b'1') =>
            usize::from_str_radix(bits, 2).ok(),
        _ => None,
    };
    let Some(expected) = count else { return false };
    if expected == 0 {
        return false;
    }

    let mut observed = 0_usize;
    for line in &mut lines {
        if line == ")" {
            return observed == expected && lines.next().is_none();
        }
        let Some(rest) = line
            .strip_prefix("(00101110 ")
            .and_then(|line| line.strip_suffix(')'))
        else {
            return false;
        };
        let Some((feature, quoted)) = rest.split_once(" \"") else {
            return false;
        };
        let Some(iclass) = quoted.strip_suffix('"') else {
            return false;
        };
        if feature.is_empty() || iclass.is_empty() ||
            !feature.bytes().all(|b| b.is_ascii_uppercase() || b.is_ascii_digit() ||
                                  b"-+._".contains(&b)) ||
            !iclass.bytes().all(|b| b.is_ascii_uppercase() || b.is_ascii_digit() ||
                                 b"_".contains(&b))
        {
            return false;
        }
        observed += 1;
        if observed > expected {
            return false;
        }
    }
    false // Missing close delimiter.
}

fn is_explicit_non_implementation_file(rel: &str, path: &Path) -> bool {
    if is_explicit_non_implementation(rel) {
        return true;
    }
    if rel == "lib/machine/encoding/admitted-iclass-index.lisp" {
        return fs::read_to_string(path)
            .is_ok_and(|source| is_generated_iclass_catalogue(rel, &source));
    }
    false
}

fn is_language_definition_file(rel: &str) -> bool {
    let Some(name) = rel.strip_prefix("lib/") else {
        return false;
    };
    name.starts_with("core") && name.ends_with(".lisp") && !name.contains('/')
}

fn active_lisp_files() -> Vec<(String, PathBuf)> {
    fn walk(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
        for entry in fs::read_dir(dir).expect("read active lib directory") {
            let entry = entry.expect("read active lib entry");
            let path = entry.path();
            if path.is_dir() {
                walk(root, &path, out);
                continue;
            }
            if path.extension().and_then(|ext| ext.to_str()) != Some("lisp") {
                continue;
            }
            let rel = path
                .strip_prefix(root)
                .expect("active lib path under repo")
                .to_string_lossy()
                .replace('\\', "/");
            if !is_explicit_non_implementation_file(&rel, &path) {
                out.push((rel, path));
            }
        }
    }

    let root = repo_root();
    let mut files = Vec::new();
    walk(&root, &root.join("lib"), &mut files);
    files.sort_by(|left, right| left.0.cmp(&right.0));
    files
}

fn run_check(files: &[PathBuf], language: bool) -> Output {
    let mut command = tool();
    command.current_dir(repo_root()).arg("--check");
    if language {
        command.arg("--language");
    }
    for file in files {
        command.arg(file);
    }
    command.output().expect("run canonical sens-to-sens check")
}

fn assert_clean(label: &str, files: &[(String, PathBuf)], language: bool) {
    assert!(!files.is_empty(), "{label}: no files selected");

    let paths: Vec<PathBuf> = files.iter().map(|(_, path)| path.clone()).collect();
    let output = run_check(&paths, language);
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);

    assert!(
        output.status.success(),
        "{label}: canonical sens-to-sens found remaining parser-convertible heads \
         or could not analyze the active library.\nstatus={}\nstdout:\n{}\nstderr:\n{}",
        output.status,
        stdout,
        stderr
    );

    for (rel, _) in files {
        let marker = format!("{rel}: convertible=0");
        assert!(
            stdout.contains(&marker),
            "{label}: missing zero-conversion witness for {rel}\nstdout:\n{stdout}"
        );
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
struct ConversionCounts {
    convertible: usize,
    named_calls: usize,
    blocked_host: usize,
}

fn parse_conversion_rows(stdout: &str, root: &Path) -> BTreeMap<String, ConversionCounts> {
    let mut rows = BTreeMap::new();
    for line in stdout.lines().filter(|line| !line.trim().is_empty()) {
        let (filename, metrics) = line
            .rsplit_once(": convertible=")
            .unwrap_or_else(|| panic!("malformed sens-to-sens --check row: {line}"));
        let relative = Path::new(filename)
            .strip_prefix(root)
            .unwrap_or_else(|_| panic!("check returned a path outside repository: {filename}"))
            .to_string_lossy()
            .replace('\\', "/");
        let mut fields = metrics.split_whitespace();
        let convertible = fields.next()
            .unwrap_or_else(|| panic!("missing convertible count: {line}"))
            .parse::<usize>()
            .unwrap_or_else(|_| panic!("invalid convertible count: {line}"));
        let named_calls = fields.next()
            .and_then(|value| value.strip_prefix("named-calls="))
            .unwrap_or_else(|| panic!("missing named-calls count: {line}"))
            .parse::<usize>()
            .unwrap_or_else(|_| panic!("invalid named-calls count: {line}"));
        let blocked_host = fields.next()
            .and_then(|value| value.strip_prefix("blocked-host="))
            .unwrap_or_else(|| panic!("missing blocked-host count: {line}"))
            .parse::<usize>()
            .unwrap_or_else(|_| panic!("invalid blocked-host count: {line}"));
        assert!(fields.next().is_none(), "unexpected check fields: {line}");
        let previous = rows.insert(relative.clone(), ConversionCounts {
            convertible,
            named_calls,
            blocked_host,
        });
        assert!(previous.is_none(), "duplicate sens-to-sens row for {relative}");
    }
    rows
}

fn committed_blob_sha(root: &Path, relative: &str) -> String {
    let spec = format!("HEAD:{relative}");
    let output = Command::new("git")
        .current_dir(root)
        .args(["rev-parse", "--verify", &spec])
        .output()
        .expect("read committed source blob SHA");
    assert!(
        output.status.success(),
        "baseline path must be a tracked file at HEAD: {relative}; stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout)
        .expect("git SHA is UTF-8")
        .trim()
        .to_owned()
}

/// Ratchet only the known parser-rewrite debt in canonical Ukrainian source.
/// This is deliberately NOT a migration-completion test: physical T5, view,
/// digests and independent semantic oracle admission remain separate gates.
fn assert_matches_pinned_conversion_baseline(files: &[(String, PathBuf)]) {
    assert!(!files.is_empty(), "ordinary active lib: no files selected");
    let root = repo_root();
    let paths: Vec<PathBuf> = files.iter().map(|(_, path)| path.clone()).collect();
    let output = run_check(&paths, false);
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.is_empty(),
        "sens-to-sens --check emitted diagnostics; do not absorb analysis errors into the baseline:\nstderr={stderr}\nstdout={stdout}"
    );

    let actual = parse_conversion_rows(&stdout, &root);
    assert_eq!(
        actual.len(),
        files.len(),
        "every selected active source must have exactly one check row; stdout={stdout}"
    );
    for (relative, _) in files {
        assert!(
            actual.contains_key(relative),
            "missing conversion report for {relative}; stdout={stdout}"
        );
    }

    let baseline_path = root.join("knowledge/active-authored-lib-conversion-baseline-v1.json");
    let raw = fs::read_to_string(&baseline_path)
        .unwrap_or_else(|error| panic!("read {}: {error}", baseline_path.display()));
    let manifest: serde_json::Value =
        serde_json::from_str(&raw).expect("valid conversion-baseline JSON");
    assert_eq!(manifest["schema"], "active-authored-lib-conversion-baseline/v1");
    assert_eq!(manifest["status"], "PARTIAL-BLOCKED-NOT-ADMISSION");
    assert_eq!(manifest["migration_credit"], 0);
    assert_eq!(manifest["physical_admission_effect"], "NONE");

    let known = manifest["known_blockers"]
        .as_array()
        .expect("known_blockers is an array");
    let mut baseline = BTreeMap::<String, ConversionCounts>::new();
    for row in known {
        let relative = row["path"].as_str().expect("blocker path is a string");
        let expected_blob = row["git_blob_sha"]
            .as_str()
            .expect("blocker Git blob SHA is pinned");
        assert!(
            files.iter().any(|(path, _)| path == relative),
            "baseline path is not in the active ordinary lib set: {relative}"
        );
        assert_eq!(
            committed_blob_sha(&root, relative),
            expected_blob,
            "source changed at {relative}; update its blocker baseline in a reviewed change"
        );
        let expected = ConversionCounts {
            convertible: row["convertible"].as_u64().expect("convertible count") as usize,
            named_calls: row["named_calls"].as_u64().expect("named_calls count") as usize,
            blocked_host: row["blocked_host"].as_u64().expect("blocked_host count") as usize,
        };
        assert!(
            baseline.insert(relative.to_owned(), expected).is_none(),
            "duplicate blocker path in pinned baseline: {relative}"
        );
    }

    let zero = ConversionCounts::default();
    for (relative, observed) in &actual {
        match baseline.get(relative) {
            Some(expected) => assert_eq!(
                observed, expected,
                "known blocker changed at {relative}; revise the source-pinned baseline explicitly"
            ),
            None => assert_eq!(
                observed, &zero,
                "NEW parser-convertible active source: {relative}; do not widen the baseline without source/semantic review"
            ),
        }
    }
    for relative in baseline.keys() {
        assert!(
            actual.contains_key(relative),
            "pinned blocker disappeared from active census without a baseline update: {relative}"
        );
    }

    // The tool exits 1 when it found rewrite candidates, 0 when it found none;
    // exit 2 or any other result indicates an analysis/tool failure.
    let has_candidates = actual.values().any(|row| row.convertible > 0);
    let expected_exit = if has_candidates { 1 } else { 0 };
    assert_eq!(
        output.status.code(),
        Some(expected_exit),
        "unexpected sens-to-sens --check status; stdout={stdout}\nstderr={stderr}"
    );
}

#[test]
fn active_authored_lib_conversion_candidates_match_pinned_baseline() {
    let files = active_lisp_files();
    let (language, ordinary): (Vec<_>, Vec<_>) = files
        .into_iter()
        .partition(|(rel, _)| is_language_definition_file(rel));

    // Table-owned core functions retain the strict zero-conversion check.
    // This lane is for ordinary library source only.
    assert_clean("language-definition lib", &language, true);

    // Canonical Ukrainian source may have known mechanical rewrite candidates.
    // Pin those blockers; reject every new path/count until explicitly reviewed.
    assert_matches_pinned_conversion_baseline(&ordinary);
}

#[test]
fn generated_iclass_snapshot_is_data_only_when_full_record_contract_holds() {
    let rel = "lib/machine/encoding/admitted-iclass-index.lisp";
    let source_path = repo_root().join(rel);
    let source = fs::read_to_string(&source_path).expect("current generated owner catalogue");
    assert!(is_generated_iclass_catalogue(rel, &source));
    assert!(is_explicit_non_implementation_file(rel, &source_path));

    // A similar file, executable code, forged owner header or new root form
    // must remain in the active-language scan, NOT inherit an exemption.
    assert!(!is_generated_iclass_catalogue("lib/machine/dispatch/native-first.lisp", &source));
    assert!(!is_generated_iclass_catalogue(rel, &source.replace(
        "; GENERATED by scripts/generate-encoder-coverage-input.py",
        "; rewritten by hand",
    )));
    assert!(!is_generated_iclass_catalogue(rel, &source.replace(
        "(pair-count #b10010011000)",
        "(pair-count #b10010011001)",
    )));
    assert!(!is_generated_iclass_catalogue(rel, &source.replacen(
        "(00101110 X86-BASE \"AAA\")",
        "(00001001 X86-BASE \"AAA\")",
        1,
    )));
    assert!(!is_generated_iclass_catalogue(
        rel,
        &format!("{source}\n(00001001 malicious (00001000 () ()))\n"),
    ));
    assert!(!is_generated_iclass_catalogue(
        rel,
        source.trim_end().strip_suffix(')').expect("catalogue close"),
    ));
}

#[test]
fn active_compiler_and_native_first_are_never_catalogue_data() {
    for rel in ["lib/compiler-nucleus.lisp", "lib/machine/dispatch/native-first.lisp"] {
        let path = repo_root().join(rel);
        let source = fs::read_to_string(&path).expect("active authored code");
        assert!(!is_explicit_non_implementation_file(rel, &path));
        assert!(!is_generated_iclass_catalogue(rel, &source));
    }
}

#[test]
fn actual_active_lib_collection_excludes_only_validated_generated_catalogue() {
    let selected: Vec<String> = active_lisp_files()
        .into_iter().map(|(relative, _)| relative).collect();
    assert!(!selected.contains(
        &"lib/machine/encoding/admitted-iclass-index.lisp".to_owned()
    ));
    assert!(selected.contains(&"lib/compiler-nucleus.lisp".to_owned()));
    assert!(selected.contains(&"lib/machine/dispatch/native-first.lisp".to_owned()));
    assert!(selected.contains(&"lib/machine/layout/pair-x86-64.lisp".to_owned()));
}

#[test]
fn completion_gate_exclusions_are_narrow_and_explicit() {
    assert!(is_explicit_non_implementation(
        "lib/machine/encoding/coverage.lisp"
    ));
    assert!(is_explicit_non_implementation(
        "lib/surface/uk-acceptance.lisp"
    ));
    assert!(is_explicit_non_implementation(
        "lib/generated/function-table.lisp"
    ));

    assert!(!is_explicit_non_implementation("lib/meta-eval.lisp"));
    assert!(!is_explicit_non_implementation(
        "lib/machine/dispatch/native-first-coverage.lisp"
    ));
    assert!(!is_explicit_non_implementation("lib/core4.lisp"));
}