//! #1675: canonical completion gate for the active authored Lisp library.
//!
//! This test intentionally delegates "is this executable surface safely
//! convertible?" to the real `sens-to-sens` tool.  The older repository
//! inventories are conservative lexical ratchets and may still count names in
//! quote/data/shadowing positions.  Migration completion must not be faked by
//! rewriting those positions.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repo root")
}

fn tool() -> Command {
    Command::new(env!("CARGO_BIN_EXE_sens-to-sens"))
}

fn is_explicit_non_implementation(rel: &str) -> bool {
    rel.starts_with("lib/generated/")
        || rel.starts_with("lib/surface/")
        || rel == "lib/machine/encoding/coverage.lisp"
}

/// The *only* machine catalogue excluded from executable source migration.
/// Verify the actual generated record grammar, not a filename/marker alone:
/// otherwise one appended executable form would silently escape the gate.
fn is_generated_iclass_catalogue(rel: &str, source: &str) -> bool {
    if rel != "lib/machine/encoding/admitted-iclass-index.lisp" {
        return false;
    }

    let mut lines = source.lines().map(str::trim).filter(|line| !line.is_empty());
    if lines.next()
        != Some("; GENERATED by scripts/generate-encoder-coverage-input.py -- do not hand-edit.")
        || lines.next()
            != Some("; Compact #175 evidence projection: no status, opcode, semantic ID, or policy.")
        || lines.next() != Some("(x86-admitted-iclass-index/2")
    {
        return false;
    }

    let count = match lines.next()
        .and_then(|line| line.strip_prefix("(pair-count #b"))
        .and_then(|bits| bits.strip_suffix(')'))
    {
        Some(bits) if !bits.is_empty() && bits.bytes().all(|ch| ch == b'0' || ch == b'1') =>
            usize::from_str_radix(bits, 2).ok(),
        _ => None,
    };
    let Some(expected) = count else { return false };
    if expected == 0 {
        return false;
    }

    let mut observed = 0_usize;
    for line in &mut lines {
        if line == ")" {
            return observed == expected && lines.next().is_none();
        }
        let Some(rest) = line
            .strip_prefix("(00101110 ")
            .and_then(|line| line.strip_suffix(')'))
        else {
            return false;
        };
        let Some((feature, quoted)) = rest.split_once(" \"") else {
            return false;
        };
        let Some(iclass) = quoted.strip_suffix('"') else {
            return false;
        };
        if feature.is_empty() || iclass.is_empty() ||
            !feature.bytes().all(|b| b.is_ascii_uppercase() || b.is_ascii_digit() ||
                                  b"-+._".contains(&b)) ||
            !iclass.bytes().all(|b| b.is_ascii_uppercase() || b.is_ascii_digit() ||
                                 b"_".contains(&b))
        {
            return false;
        }
        observed += 1;
        if observed > expected {
            return false;
        }
    }
    false // Missing close delimiter.
}

fn is_explicit_non_implementation_file(rel: &str, path: &Path) -> bool {
    if is_explicit_non_implementation(rel) {
        return true;
    }
    if rel == "lib/machine/encoding/admitted-iclass-index.lisp" {
        return fs::read_to_string(path)
            .is_ok_and(|source| is_generated_iclass_catalogue(rel, &source));
    }
    false
}

fn is_language_definition_file(rel: &str) -> bool {
    let Some(name) = rel.strip_prefix("lib/") else {
        return false;
    };
    name.starts_with("core") && name.ends_with(".lisp") && !name.contains('/')
}

fn active_lisp_files() -> Vec<(String, PathBuf)> {
    fn walk(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
        for entry in fs::read_dir(dir).expect("read active lib directory") {
            let entry = entry.expect("read active lib entry");
            let path = entry.path();
            if path.is_dir() {
                walk(root, &path, out);
                continue;
            }
            if path.extension().and_then(|ext| ext.to_str()) != Some("lisp") {
                continue;
            }
            let rel = path
                .strip_prefix(root)
                .expect("active lib path under repo")
                .to_string_lossy()
                .replace('\\', "/");
            if !is_explicit_non_implementation_file(&rel, &path) {
                out.push((rel, path));
            }
        }
    }

    let root = repo_root();
    let mut files = Vec::new();
    walk(&root, &root.join("lib"), &mut files);
    files.sort_by(|left, right| left.0.cmp(&right.0));
    files
}

fn run_check(files: &[PathBuf], language: bool) -> Output {
    let mut command = tool();
    command.current_dir(repo_root()).arg("--check");
    if language {
        command.arg("--language");
    }
    for file in files {
        command.arg(file);
    }
    command.output().expect("run canonical sens-to-sens check")
}

fn parse_report_count(line: &str, key: &str, rel: &str) -> usize {
    line.split_whitespace()
        .find_map(|field| field.strip_prefix(&format!("{key}=")))
        .and_then(|number| number.parse::<usize>().ok())
        .unwrap_or_else(|| panic!("{rel}: malformed {key} counter in report: {line}"))
}

fn report_line<'a>(stdout: &'a str, rel: &str) -> &'a str {
    let marker = format!("{rel}: convertible=");
    stdout
        .lines()
        .find(|line| line.contains(&marker))
        .unwrap_or_else(|| panic!("missing sens-to-sens report for {rel}\nstdout:\n{stdout}"))
}

fn domain_identity_count(expression: &sens::Expr) -> usize {
    match &expression.kind {
        sens::ExprKind::DomainIdentity(_) => 1,
        sens::ExprKind::List(items) => items.iter().map(domain_identity_count).sum(),
        sens::ExprKind::Pair(head, tail) => {
            domain_identity_count(head) + domain_identity_count(tail)
        }
        _ => 0,
    }
}

fn domain_identities(expressions: &[sens::Expr]) -> usize {
    expressions.iter().map(domain_identity_count).sum()
}

/// The language's own first-definition files use a distinct code-slot rule:
/// no surface spelling may remain rewriteable in --language mode.
fn assert_language_definitions_are_exact(
    label: &str,
    files: &[(String, PathBuf)],
) {
    assert!(!files.is_empty(), "{label}: no files selected");
    let paths: Vec<PathBuf> = files.iter().map(|(_, path)| path.clone()).collect();
    let output = run_check(&paths, true);
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        output.status.success(),
        "{label}: language-definition check failed\nstatus={}\nstdout:\n{}\nstderr:\n{}",
        output.status,
        stdout,
        stderr
    );

    for (rel, _) in files {
        let line = report_line(&stdout, rel);
        assert_eq!(
            parse_report_count(line, "convertible", rel),
            0,
            "{label}: language-defined first code-slot functions must already use exact identities: {line}"
        );
        assert_eq!(
            parse_report_count(line, "blocked-host", rel),
            0,
            "{label}: host-capability blockers remain in language-definition file: {line}"
        );
    }
}

/// For ordinary authored .lisp, a non-zero sens-to-sens conversion count is
/// not proof of invalid source: Ukrainian .lisp is the canonical human
/// projection. Use the actual current mixed reader as the authority instead.
/// The diagnostic tool must still parse/analyze every file (exit 2 is a real
/// failure), and each file with candidate heads must demonstrate that the
/// role-aware projection creates exact domain identities without writing the
/// source or pretending this is physical-T5 admission.
fn assert_ordinary_sources_have_mixed_projection(
    label: &str,
    files: &[(String, PathBuf)],
) {
    assert!(!files.is_empty(), "{label}: no files selected");
    let paths: Vec<PathBuf> = files.iter().map(|(_, path)| path.clone()).collect();
    let output = run_check(&paths, false);
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        matches!(output.status.code(), Some(0) | Some(1)),
        "{label}: sens-to-sens could not analyze the active library (only 0/1 are expected; 2 means parse/analyze failure)\nstatus={}\nstdout:\n{}\nstderr:\n{}",
        output.status,
        stdout,
        stderr
    );

    let mut total_convertible = 0usize;
    for (rel, path) in files {
        let line = report_line(&stdout, rel);
        let convertible = parse_report_count(line, "convertible", rel);
        let blocked_host = parse_report_count(line, "blocked-host", rel);
        total_convertible += convertible;
        assert_eq!(
            blocked_host, 0,
            "{label}: explicit host-capability migration blockers remain for {rel}: {line}"
        );

        if convertible == 0 {
            continue;
        }

        let source = fs::read_to_string(path).unwrap_or_else(|error| {
            panic!("{rel}: cannot read source for role-aware projection: {error}")
        });
        let ordinary = sens::parse(&source).unwrap_or_else(|error| {
            panic!("{rel}: ordinary reader rejected canonical source: {error:?}")
        });
        let projected = sens::parse_mixed_exact_domain(&source).unwrap_or_else(|error| {
            panic!("{rel}: mixed exact-domain reader rejected canonical source: {error:?}")
        });
        assert_eq!(
            ordinary.len(),
            projected.len(),
            "{rel}: role-aware projection changed top-level form count"
        );
        let before = domain_identities(&ordinary);
        let after = domain_identities(&projected);
        assert!(
            after >= before,
            "{rel}: role-aware projection lost exact domain identities ({before} -> {after})"
        );
        assert!(
            after > before,
            "{rel}: sens-to-sens reports {convertible} surface candidates, but the current mixed reader produced no additional exact domain identity. This is a real projection/lowering mismatch, not a reason to rewrite canonical Ukrainian source."
        );
    }

    // Exit 1 is expected when --check finds surface projections. It is not
    // expected to become a migration-completion failure so long as the
    // role-aware reader admits the corresponding exact-domain projection.
    if total_convertible > 0 {
        assert_eq!(
            output.status.code(),
            Some(1),
            "{label}: converter report and --check exit code disagree"
        );
    }
}

#[test]
fn generated_iclass_snapshot_is_data_only_when_full_record_contract_holds() {
    let rel = "lib/machine/encoding/admitted-iclass-index.lisp";
    let source_path = repo_root().join(rel);
    let source = fs::read_to_string(&source_path).expect("current generated owner catalogue");
    assert!(is_generated_iclass_catalogue(rel, &source));
    assert!(is_explicit_non_implementation_file(rel, &source_path));

    // A similar file, executable code, forged owner header or new root form
    // must remain in the active-language scan, NOT inherit an exemption.
    assert!(!is_generated_iclass_catalogue("lib/machine/dispatch/native-first.lisp", &source));
    assert!(!is_generated_iclass_catalogue(rel, &source.replace(
        "; GENERATED by scripts/generate-encoder-coverage-input.py",
        "; rewritten by hand",
    )));
    assert!(!is_generated_iclass_catalogue(rel, &source.replace(
        "(pair-count #b10010011000)",
        "(pair-count #b10010011001)",
    )));
    assert!(!is_generated_iclass_catalogue(rel, &source.replacen(
        "(00101110 X86-BASE \"AAA\")",
        "(00001001 X86-BASE \"AAA\")",
        1,
    )));
    assert!(!is_generated_iclass_catalogue(
        rel,
        &format!("{source}\n(00001001 malicious (00001000 () ()))\n"),
    ));
    assert!(!is_generated_iclass_catalogue(
        rel,
        source.trim_end().strip_suffix(')').expect("catalogue close"),
    ));
}

#[test]
fn active_compiler_and_native_first_are_never_catalogue_data() {
    for rel in ["lib/compiler-nucleus.lisp", "lib/machine/dispatch/native-first.lisp"] {
        let path = repo_root().join(rel);
        let source = fs::read_to_string(&path).expect("active authored code");
        assert!(!is_explicit_non_implementation_file(rel, &path));
        assert!(!is_generated_iclass_catalogue(rel, &source));
    }
}

#[test]
fn actual_active_lib_collection_excludes_only_validated_generated_catalogue() {
    let selected: Vec<String> = active_lisp_files()
        .into_iter().map(|(relative, _)| relative).collect();
    assert!(!selected.contains(
        &"lib/machine/encoding/admitted-iclass-index.lisp".to_owned()
    ));
    assert!(selected.contains(&"lib/compiler-nucleus.lisp".to_owned()));
    assert!(selected.contains(&"lib/machine/dispatch/native-first.lisp".to_owned()));
    assert!(selected.contains(&"lib/machine/layout/pair-x86-64.lisp".to_owned()));
}

#[test]
fn completion_gate_exclusions_are_narrow_and_explicit() {
    assert!(is_explicit_non_implementation(
        "lib/machine/encoding/coverage.lisp"
    ));
    assert!(is_explicit_non_implementation(
        "lib/surface/uk-acceptance.lisp"
    ));
    assert!(is_explicit_non_implementation(
        "lib/generated/function-table.lisp"
    ));

    assert!(!is_explicit_non_implementation("lib/meta-eval.lisp"));
    assert!(!is_explicit_non_implementation(
        "lib/machine/dispatch/native-first-coverage.lisp"
    ));
    assert!(!is_explicit_non_implementation("lib/core4.lisp"));
}