; Canonical human-readable domain table.
; D6: exact-width 6-bit keys only.
; The binary key width is the domain address.
; Columns: ук → укр → san → en → LISP → sym
; Predicate marker rule: ук/укр/en end in ?, Sanskrit does not.
; Empty/missing: ()

(domain-table/1
  (000000 (ук довжина) (укр довжина) (san pramāṇa) (en length) (LISP LENGTH) (sym ()))
  (000001 (ук довжина-до) (укр довжина-до) (san pramāṇa-saṅkalana) (en length-onto) (LISP LENGTH-ONTO) (sym ()))
  (000010 (ук найменше-у-списку) (укр найменше-у-списку) (san śreṇī-alpatara) (en min-list) (LISP MIN-LIST) (sym ()))
  (000011 (ук найбільше-у-списку) (укр найбільше-у-списку) (san śreṇī-brhattara) (en max-list) (LISP MAX-LIST) (sym ()))
  (000100 (ук елемент-списку-за-індексом) (укр елемент-списку-за-індексом) (san kramāṅka) (en nth) (LISP NTH) (sym ()))
  (000101 (ук відобразити-залишки) (укр відобразити-залишки) (san śeṣa-āvartana) (en maplist) (LISP MAPLIST) (sym ()))
  (000110 (ук розгорнути-макрос-1) (укр розгорнути-макрос-1) (san vistāra-rūpa-prasāra-eka) (en macroexpand-1) (LISP MACROEXPAND-1) (sym ()))
  (000111 (ук розгорнути-макрос) (укр розгорнути-макрос) (san vistāra-rūpa-prasāra) (en macroexpand) (LISP MACROEXPAND) (sym ()))
  (001000 (ук нехай) (укр нехай) (san sthānika-bandha) (en let) (LISP LET) (sym ()))
  (001001 (ук нехай*) (укр нехай-послідовно) (san krama-sthānika-bandha) (en let*) (LISP LET*) (sym ()))
  (001010 (ук підставити-пари) (укр підставити-пари) (san yugma-ādeśa) (en sublis) (LISP SUBLIS) (sym ()))
  (001011 (ук скласти-функції) (укр скласти-функції) (san phalana-saṃyojana) (en compose) (LISP COMPOSE) (sym ()))
  (001100 (ук знайти-за-значенням) (укр знайти-за-значенням) (san mūlya-saṃbandha-anveṣaṇa) (en rassoc) (LISP RASSOC) (sym ()))
  (001101 (ук додати-асоціацію) (укр додати-асоціацію) (san saṃbandha-niveśana) (en acons) (LISP ACONS) (sym ()))
  (001110 (ук додати-1) (укр додати-1) (san eka-yoga) (en add1) (LISP ADD1) (sym ()))
  (001111 (ук відняти-1) (укр відняти-1) (san eka-viyoga) (en sub1) (LISP SUB1) (sym ()))
  (010000 (ук парне?) (укр парне?) (san sama-saṅkhyā) (en evenp?) (LISP EVENP) (sym ()))
  (010001 (ук непарне?) (укр непарне?) (san viṣama-saṅkhyā) (en oddp?) (LISP ODDP) (sym ()))
  (010010 (ук змінити-знак) (укр змінити-знак) (san cihna-viparyaya) (en neg) (LISP NEG) (sym ()))
  (010011 (ук модуль) (укр модуль) (san rūpa) (en abs) (LISP ABS) (sym ()))
  (010100 (ук остача) (укр остача) (san avasiṣṭa) (en remainder) (LISP REMAINDER) (sym ()))
  (010101 (ук найбільший-спільний-дільник) (укр найбільший-спільний-дільник) (san mahattama-samāpavartaka) (en gcd) (LISP GCD) (sym ()))
  (010110 (ук обернене) (укр обернене) (san vyutkrama) (en recip) (LISP RECIP) (sym ()))
  (010111 (ук піднести-до-степеня) (укр піднести-до-степеня) (san ghāta) (en expt) (LISP EXPT) (sym ()))
  (011000 (ук решта-від-першого-від-першого-від-першого) (укр решта-від-першого-від-першого-від-першого) (san śeṣa-ādi-ādi-ādi) (en cdaaar) (LISP CDAAAR) (sym ()))
  (011001 (ук решта-від-першого-від-першого-від-решти) (укр решта-від-першого-від-першого-від-решти) (san śeṣa-ādi-ādi-śeṣa) (en cdaadr) (LISP CDAADR) (sym ()))
  (011010 (ук решта-від-першого-від-решти-від-першого) (укр решта-від-першого-від-решти-від-першого) (san śeṣa-ādi-śeṣa-ādi) (en cdadar) (LISP CDADAR) (sym ()))
  (011011 (ук решта-від-першого-від-решти-від-решти) (укр решта-від-першого-від-решти-від-решти) (san śeṣa-ādi-śeṣa-śeṣa) (en cdaddr) (LISP CDADDR) (sym ()))
  (011100 (ук решта-від-решти-від-першого-від-першого) (укр решта-від-решти-від-першого-від-першого) (san śeṣa-śeṣa-ādi-ādi) (en cddaar) (LISP CDDAAR) (sym ()))
  (011101 (ук решта-від-решти-від-першого-від-решти) (укр решта-від-решти-від-першого-від-решти) (san śeṣa-śeṣa-ādi-śeṣa) (en cddadr) (LISP CDDADR) (sym ()))
  (011110 (ук решта-від-решти-від-решти-від-першого) (укр решта-від-решти-від-решти-від-першого) (san śeṣa-śeṣa-śeṣa-ādi) (en cdddar) (LISP CDDDAR) (sym ()))
  (011111 (ук решта-від-решти-від-решти-від-решти) (укр решта-від-решти-від-решти-від-решти) (san śeṣa-śeṣa-śeṣa-śeṣa) (en cddddr) (LISP CDDDDR) (sym ()))
  (100000 (ук перше-від-першого-від-першого-від-першого) (укр перше-від-першого-від-першого-від-першого) (san ādi-ādi-ādi-ādi) (en caaaar) (LISP CAAAAR) (sym ()))
  (100001 (ук перше-від-першого-від-першого-від-решти) (укр перше-від-першого-від-першого-від-решти) (san ādi-ādi-ādi-śeṣa) (en caaadr) (LISP CAAADR) (sym ()))
  (100010 (ук перше-від-першого-від-решти-від-першого) (укр перше-від-першого-від-решти-від-першого) (san ādi-ādi-śeṣa-ādi) (en caadar) (LISP CAADAR) (sym ()))
  (100011 (ук перше-від-першого-від-решти-від-решти) (укр перше-від-першого-від-решти-від-решти) (san ādi-ādi-śeṣa-śeṣa) (en caaddr) (LISP CAADDR) (sym ()))
  (100100 (ук перше-від-решти-від-першого-від-першого) (укр перше-від-решти-від-першого-від-першого) (san ādi-śeṣa-ādi-ādi) (en cadaar) (LISP CADAAR) (sym ()))
  (100101 (ук перше-від-решти-від-першого-від-решти) (укр перше-від-решти-від-першого-від-решти) (san ādi-śeṣa-ādi-śeṣa) (en cadadr) (LISP CADADR) (sym ()))
  (100110 (ук перше-від-решти-від-решти-від-першого) (укр перше-від-решти-від-решти-від-першого) (san ādi-śeṣa-śeṣa-ādi) (en caddar) (LISP CADDAR) (sym ()))
  (100111 (ук перше-від-решти-від-решти-від-решти) (укр перше-після-трьох-решт) (san ādi-śeṣa-śeṣa-śeṣa) (en cadddr) (LISP CADDDR) (sym ()))
  (101000 (ук відобразити) (укр відобразити) (san āvartana) (en map) (LISP MAP) (sym ()))
  (101001 (ук відсіяти) (укр відсіяти) (san kalpana) (en filter) (LISP FILTER) (sym ()))
  (101010 (ук відобразити-до) (укр відобразити-до) (san āvartana-saṅkalana) (en map-onto) (LISP MAP-ONTO) (sym ()))
  (101011 (ук відсіяти-до) (укр відсіяти-до) (san kalpana-saṅkalana) (en filter-onto) (LISP FILTER-ONTO) (sym ()))
  (101100 (ук частково-застосувати) (укр частково-застосувати) (san pūrva-bandha) (en curry) (LISP CURRY) (sym ()))
  (101101 (ук поміняти-аргументи) (укр поміняти-аргументи) (san krama-viparyaya) (en flip) (LISP FLIP) (sym ()))
  (101110 (ук згорнути) (укр згорнути) (san saṅgraha) (en reduce) (LISP REDUCE) (sym ()))
  (101111 (ук накопичувати) (укр накопичувати) (san krama-saṅgraha) (en scan) (LISP SCAN) (sym ()))
  (110000 (ук взяти) (укр взяти) (san grahaṇa) (en take) (LISP TAKE) (sym ()))
  (110001 (ук відкинути) (укр відкинути) (san tyāga) (en drop) (LISP DROP) (sym ()))
  (110010 (ук робити) (укр робити) (san kriyā-punarāvṛtti) (en do) (LISP DO) (sym ()))
  (110011 (ук поки) (укр поки) (san yāvat-punarāvṛtti) (en while) (LISP WHILE) (sym ()))
  (110100 (ук не-більше?) (укр не-більше?) (san na-adhika) (en leq?) (LISP LEQ) (sym ()))
  (110101 (ук найменше) (укр найменше) (san alpatara) (en min) (LISP MIN) (sym ()))
  (110110 (ук не-менше?) (укр не-менше?) (san na-hīna) (en geq?) (LISP GEQ) (sym ()))
  (110111 (ук найбільше) (укр найбільше) (san brhattara) (en max) (LISP MAX) (sym ()))
  (111000 (ук спарувати-послідовності) (укр спарувати-послідовності) (san yugma-saṃyojana) (en zip) (LISP ZIP) (sym ()))
  (111001 (ук розпарувати-пари) (укр розпарувати-пари) (san yugma-vibhajana) (en unzip) (LISP UNZIP) (sym ()))
  (111010 (ук перетин) (укр перетин) (san mithaścheda) (en intersection) (LISP INTERSECTION) (sym ()))
  (111011 (ук об'єднання) (укр об'єднання) (san samūha-saṃyoga) (en union) (LISP UNION) (sym ()))
  (111100 (ук будь-яке?) (укр будь-яке?) (san kaścit) (en any?) (LISP ANY) (sym ()))
  (111101 (ук усі?) (укр усі?) (san sarva) (en all?) (LISP ALL) (sym ()))
  (111110 (ук ціле?) (укр ціле?) (san pūrṇāṅka) (en integerp?) (LISP INTEGERP) (sym ()))
  (111111 (ук раціональне?) (укр раціональне?) (san parimeya-saṅkhyā) (en rationalp?) (LISP RATIONALP) (sym ()))
)
