;;;; Research-only exact donor oracle — Dung grounded argumentation (1995).
;;;; (role research-only)
;;;; (semantic-authority-change none)
;;;; This checks the characteristic-function least fixed point in REAL SBCL,
;;;; independently of Python's synchronous IN/OUT wave propagation.

(defpackage :d10-dung-oracle (:use :cl))
(in-package :d10-dung-oracle)
(defvar *checks* 0)
(defvar *graph-cases* 0)
(defun check (label actual expected)
  (unless (equal actual expected)
    (error "~A: expected ~S; actual ~S" label expected actual))
  (incf *checks*))
(defun is-exact-node-list (nodes)
  (and (listp nodes)
       (every (lambda (node) (and (symbolp node) node)) nodes)
       (= (length nodes) (length (remove-duplicates nodes :test #'eq)))))
(defun valid-graph? (nodes edges)
  (and (is-exact-node-list nodes)
       (listp edges)
       (every (lambda (edge)
                (and (listp edge)
                     (= (length edge) 2)
                     (member (first edge) nodes :test #'eq)
                     (member (second edge) nodes :test #'eq)))
              edges)
       (= (length edges)
          (length (remove-duplicates edges :test #'equal)))))
(defun attacks? (a b edges)
  (member (list a b) edges :test #'equal))
(defun defended? (argument accepted nodes edges)
  (every (lambda (attacker)
           (or (not (attacks? attacker argument edges))
               (some (lambda (defender)
                       (attacks? defender attacker edges))
                     accepted)))
         nodes))
(defun characteristic (accepted nodes edges)
  (remove-if-not (lambda (node)
                   (defended? node accepted nodes edges))
                 nodes))
(defun grounded (nodes edges)
  (unless (valid-graph? nodes edges)
    (error "finite attack framework: duplicate/invalid identity or edge"))
  (let ((accepted nil))
    (loop for step from 0 to (1+ (length nodes)) do
      (let ((next (characteristic accepted nodes edges)))
        (when (equal next accepted)
          (return))
        (when (= step (1+ (length nodes)))
          (error "failed to reach finite characteristic fixed point"))
        (setf accepted next)))
    (let ((rejected (remove-if-not
                     (lambda (node)
                       (some (lambda (a) (attacks? a node edges))
                             accepted))
                     nodes)))
      (list :in accepted
            :out rejected
            :undec (remove-if
                    (lambda (node)
                      (or (member node accepted :test #'eq)
                          (member node rejected :test #'eq)))
                    nodes)))))
(defun rejected-input? (nodes edges)
  (handler-case (progn (grounded nodes edges) nil)
    (error () t)))
(defun all-mask-edges (nodes code)
  (let ((counter -1))
    (loop for attacker in nodes nconc
      (loop for target in nodes
            for bit = (incf counter)
            when (logbitp bit code) collect (list attacker target)))))
(defun check-invariants (answer nodes edges)
  (let* ((i (getf answer :in))
         (o (getf answer :out))
         (u (getf answer :undec)))
    (unless (and (= (length (append i o u)) (length nodes))
                 (null (intersection i o))
                 (null (intersection i u))
                 (null (intersection o u))
                 (equal i (characteristic i nodes edges))
                 (every (lambda (v)
                          (some (lambda (a) (attacks? a v edges)) i))
                        o)
                 (every (lambda (v) (not (member v o))) u))
      (error "grounded partition or fixed-point invariant failed"))))
(defun suite ()
  (dolist (row
           '(((a) () (:in (a) :out () :undec ()))
             ((a b) ((a b)) (:in (a) :out (b) :undec ()))
             ((a b c) ((a b) (b c)) (:in (a c) :out (b) :undec ()))
             ((a b) ((a b) (b a)) (:in () :out () :undec (a b)))
             ((a) ((a a)) (:in () :out () :undec (a)))
             ((a b c) ((a b) (b c) (c a))
              (:in () :out () :undec (a b c)))
             ((a b c d) ((a b) (b c) (c a) (d a))
              (:in (b d) :out (a c) :undec ()))
             ((x a b) ((a b) (b a))
              (:in (x) :out () :undec (a b)))
             (() () (:in () :out () :undec ()))))
    (check "Dung primary grounded semantic witness"
           (grounded (first row) (second row)) (third row)))
  (check "reject duplicate arguments"
         (rejected-input? '(a a) nil) t)
  (check "reject unknown attack endpoint"
         (rejected-input? '(a) '((b a))) t)
  (check "reject duplicate attack"
         (rejected-input? '(a b) '((a b) (a b))) t)
  (check "reject atom instead of graph"
         (rejected-input? 'a '((a a))) t)
  (check "self attack cannot force IN"
         (grounded '(a) '((a a)))
         '(:in () :out () :undec (a)))
  (loop for n from 0 to 3 do
    (let ((nodes (subseq '(a b c) 0 n)))
      (loop for code from 0 below (ash 1 (* n n)) do
        (let* ((edges (all-mask-edges nodes code))
               (label (grounded nodes edges)))
          (check-invariants label nodes edges)
          (incf *graph-cases*)))))
  (unless (= *graph-cases* 531)
    (error "expected 531 finite directed graphs, got ~D" *graph-cases*))
  (format t "D10 DUNG independent real SBCL oracle PASS ~D named checks and ~D complete finite graphs~%"
          *checks* *graph-cases*)
  (finish-output))
(handler-case (suite)
  (error (reason)
    (format *error-output* "D10 DUNG independent SBCL oracle FAIL: ~A~%" reason)
    (sb-ext:exit :code 1)))
