;;;; Independent real SBCL mathematical model — D10 donor research only.
;;;; (role research-only)
;;;; (semantic-authority-change none)
;;;; Sources: NIST SP811 §8.5 and BIPM kelvin.
;;;; These are NOT executable .sens words or an original SENS interpreter oracle.
(defpackage :d10-affine-measure (:use :cl))
(in-package :d10-affine-measure)
(defvar *tests* 0)
(defun is (name actual expected)
  (unless (equal actual expected)
    (error "~a: expected ~s, got ~s" name expected actual))
  (incf *tests*))
(defun refuses? (thunk)
  (handler-case (progn (funcall thunk) nil) (error () t)))
(defstruct (unit (:constructor raw-unit (dims factor origin)))
  dims factor origin)
(defun make-exact-unit (dims factor origin)
  (unless (and (listp dims) (= (length dims) 7)
               (every #'rationalp dims)
               (rationalp factor) (> factor 0)
               (rationalp origin))
    (error "Invalid exact 7-dimension unit"))
  (raw-unit dims factor origin))
(defun convert-value (x kind from to)
  (unless (and (rationalp x) (member kind '(:point :delta)))
    (error "Exact rational POINT or DELTA required"))
  (unless (and (unit-p from) (unit-p to)
               (equal (unit-dims from) (unit-dims to)))
    (error "Dimension mismatch"))
  ;; Use separately-derived relative affine coefficients, rather than
  ;; the Python model's two-step physical base-coordinate intermediary.
  (let* ((relative-factor (/ (unit-factor from) (unit-factor to)))
         (relative-origin (if (eq kind :point)
                              (/ (- (unit-origin from) (unit-origin to))
                                 (unit-factor to)) 0)))
    (list (+ (* relative-factor x) relative-origin) kind)))
(defparameter *temp* '(0 0 0 0 1 0 0))
(defparameter *length* '(1 0 0 0 0 0 0))
(defparameter *k* (make-exact-unit *temp* 1 0))
(defparameter *c* (make-exact-unit *temp* 1 5463/20)) ; 273.15 K
(defparameter *f* (make-exact-unit *temp* 5/9 45967/180))
(defparameter *metre* (make-exact-unit *length* 1 0))
(defun run ()
  (is "Celsius point to Kelvin" (convert-value 0 :point *c* *k*)
      '(5463/20 :point))
  (is "Celsius delta to Kelvin" (convert-value 5 :delta *c* *k*)
      '(5 :delta))
  (is "Fahrenheit point to Kelvin" (convert-value 32 :point *f* *k*)
      '(5463/20 :point))
  (is "Fahrenheit delta to Kelvin" (convert-value 9 :delta *f* *k*)
      '(5 :delta))
  (is "Kelvin back to Celsius" (convert-value 5463/20 :point *k* *c*)
      '(0 :point))
  (is "Boiling in F" (convert-value 100 :point *c* *f*)
      '(212 :point))
  (is "difference 100 C equals 180 F" (convert-value 100 :delta *c* *f*)
      '(180 :delta))
  (is "0 C is not 0 K" (equal (convert-value 0 :point *c* *k*)
                              '(0 :point)) nil)
  (is "absolute roundtrip" (convert-value
                            (first (convert-value -75/13 :point *f* *k*))
                            :point *k* *f*)
      '(-75/13 :point))
  (is "delta roundtrip" (convert-value
                         (first (convert-value 17/19 :delta *f* *c*))
                         :delta *c* *f*)
      '(17/19 :delta))
  (is "offset cancels for deltas" (convert-value 7 :delta *c* *k*)
      '(7 :delta))
  (is "mismatched dimensions rejected"
      (refuses? (lambda () (convert-value 1 :point *c* *metre*))) t)
  (is "inexact floating values rejected"
      (refuses? (lambda () (convert-value 0.5 :point *c* *k*))) t)
  (is "zero factor rejected"
      (refuses? (lambda () (make-exact-unit *temp* 0 0))) t)
  (is "bad dimension cardinality rejected"
      (refuses? (lambda () (make-exact-unit '(1 0) 1 0))) t)
  (is "bad kind rejected"
      (refuses? (lambda () (convert-value 1 :unknown *c* *k*))) t)
  (is "non-exact origin rejected"
      (refuses? (lambda () (make-exact-unit *temp* 1 0.1))) t)
  (let* ((source (make-exact-unit *temp* 4/5 11/13))
         (middle (make-exact-unit *temp* 7/9 -3/8))
         (target (make-exact-unit *temp* 5/11 2/3)))
    (dolist (kind '(:point :delta))
      (let* ((x -333/7)
             (y (first (convert-value x kind source middle)))
             (via (convert-value y kind middle target))
             (direct (convert-value x kind source target)))
        (is "multi-unit composition" via direct))))
  (format t "D10 AFFINE-QUANTITY real SBCL donor oracle PASS ~D checks~%" *tests*)
  (finish-output))
(handler-case (run)
  (error (err)
    (format *error-output* "D10 AFFINE-QUANTITY SBCL FAIL ~A~%" err)
    (sb-ext:exit :code 1)))
