; Machine-readable lifecycle inventory for GitHub Actions.
; Parent: #384
; This is institutional metadata, not semantic authority.
;
; Fields:
; path purpose triggers lane semantic-or-mechanism direct-commands
; repo-tools upstream-authority expected-cost cancellation lifecycle removal-condition

(workflow-inventory
  (workflow
    (path ".github/workflows/ci.yml")
    (purpose "default PR/main verification and changed-surface gates")
    (triggers (push-main pull-request workflow-dispatch))
    (lane fast-pr)
    (semantic-or-mechanism mixed)
    (direct-commands ("rust one-way valve" "authority guards" "generated projection checks" "focused cargo tests" "clippy"))
    (repo-tools ("scripts/test-ci-semantic-path-classifier.sh" "scripts/test-rust-one-way-valve.sh" "scripts/rust-one-way-valve.sh" "scripts/test-current-semantic-slice.sh" "scripts/public_api_inventory.py"))
    (upstream-authority ("Lisp-owned semantic witnesses" "mechanism/build tests"))
    (expected-cost medium)
    (cancellation cancel-in-progress)
    (lifecycle active)
    (removal-condition explicit-review))

  (workflow
    (path ".github/workflows/full-nightly.yml")
    (purpose "full workspace, platform and generated-authority verification")
    (triggers (schedule workflow-dispatch))
    (lane nightly)
    (semantic-or-mechanism mixed)
    (direct-commands ("cargo test --workspace" "cargo build --workspace" "cargo xtask verify" "WASM browser tests"))
    (repo-tools ("scripts/generate-meta-semantic-registry.lisp" "scripts/generate-rust-semantic-registry.lisp" "scripts/public_api_inventory.py" "scripts/перевірити-український-профіль.lisp"))
    (upstream-authority ("current repository contracts and generated projections"))
    (expected-cost high)
    (cancellation preserve-running)
    (lifecycle active)
    (removal-condition explicit-review))

  (workflow
    (path ".github/workflows/deep-meta-nightly.yml")
    (purpose "expensive ignored meta-eval and reasoning scale witnesses")
    (triggers (schedule workflow-dispatch))
    (lane nightly)
    (semantic-or-mechanism semantic-gate)
    (direct-commands ("meta_eval_advice_taker" "reason_scale" "reason_advice_scale"))
    (repo-tools ())
    (upstream-authority ("Lisp-owned current semantic witnesses"))
    (expected-cost high)
    (cancellation preserve-running)
    (lifecycle active)
    (removal-condition explicit-review))

  (workflow
    (path ".github/workflows/release-preflight.yml")
    (purpose "exact workspace test and clippy preflight for release-affecting changes")
    (triggers (pull-request workflow-dispatch))
    (lane release)
    (semantic-or-mechanism mixed)
    (direct-commands ("cargo test --workspace" "cargo clippy --workspace --all-targets -- -D warnings"))
    (repo-tools ())
    (upstream-authority ("release gate #968"))
    (expected-cost high)
    (cancellation unspecified)
    (lifecycle active)
    (removal-condition explicit-review))

  (workflow
    (path ".github/workflows/release.yml")
    (purpose "build and publish tagged release assets and release witnesses")
    (triggers (push-release-tag-or-branch))
    (lane release)
    (semantic-or-mechanism mechanism-build)
    (direct-commands ("release-focused tests" "cross-target CLI builds" "Windows MSI" "WASM build" "GitHub release upload"))
    (repo-tools ())
    (upstream-authority ("release contract and islands manifest"))
    (expected-cost high)
    (cancellation unspecified)
    (lifecycle active)
    (removal-condition explicit-review))

  (workflow
    (path ".github/workflows/sync-language-contract.yml")
    (purpose "reusable consumer workflow that synchronizes vendored language contract")
    (triggers (workflow-call))
    (lane other)
    (semantic-or-mechanism docs-policy)
    (direct-commands ("checkout" "compare/copy pinned language contract"))
    (repo-tools ())
    (upstream-authority ("language-contract.lisp"))
    (expected-cost low)
    (cancellation unspecified)
    (lifecycle active)
    (removal-condition "consumer contract distribution mechanism replaced"))

  (workflow
    (path ".github/workflows/verify-language-contract.yml")
    (purpose "reusable read-only verification of a consumer pinned language contract")
    (triggers (workflow-call))
    (lane other)
    (semantic-or-mechanism docs-policy)
    (direct-commands ("checkout" "verify pinned language contract"))
    (repo-tools ())
    (upstream-authority ("language-contract.lisp"))
    (expected-cost low)
    (cancellation unspecified)
    (lifecycle active)
    (removal-condition "consumer contract verification mechanism replaced"))

  (workflow
    (path ".github/workflows/surface-drift-check.yml")
    (purpose "detect surface, trilingual and semantic-registry projection drift")
    (triggers (push pull-request))
    (lane fast-pr)
    (semantic-or-mechanism semantic-gate)
    (direct-commands ("surface coverage check" "trilingual surface check" "semantic registry check"))
    (repo-tools ("scripts/check_surface_coverage.py" "scripts/check_trilingual_surface.py" "scripts/check_semantic_registry.py"))
    (upstream-authority ("lib/surface" "canonical semantic registry"))
    (expected-cost low)
    (cancellation unspecified)
    (lifecycle transitional)
    (removal-condition "#76 Python migration and equivalent Lisp-owned checks complete"))

  (workflow
    (path ".github/workflows/kernel-host-test.yml")
    (purpose "wsm kernel-host package tests and clippy")
    (triggers (pull-request workflow-dispatch))
    (lane fast-pr)
    (semantic-or-mechanism mechanism-build)
    (direct-commands ("cargo test -p wsm-kernel-host" "cargo clippy -p wsm-kernel-host"))
    (repo-tools ())
    (upstream-authority ("kernel-host implementation/tests"))
    (expected-cost low)
    (cancellation unspecified)
    (lifecycle active)
    (removal-condition explicit-review))

  (workflow
    (path ".github/workflows/four-kernel-c-abi-test.yml")
    (purpose "four-kernel C ABI package tests, clippy and ABI witness")
    (triggers (pull-request workflow-dispatch))
    (lane fast-pr)
    (semantic-or-mechanism mechanism-build)
    (direct-commands ("cargo test -p wsm-kernel-c-abi" "cargo clippy -p wsm-kernel-c-abi"))
    (repo-tools ())
    (upstream-authority ("four-kernel mechanical boundary #725"))
    (expected-cost low)
    (cancellation unspecified)
    (lifecycle active)
    (removal-condition explicit-review))

  (workflow
    (path ".github/workflows/clips-kernel-test.yml")
    (purpose "CLIPS kernel native and no-default-features witnesses")
    (triggers (pull-request push workflow-dispatch))
    (lane fast-pr)
    (semantic-or-mechanism mechanism-build)
    (direct-commands ("CLIPS unit tests" "native CLIPS check" "C ABI semantic witness" "clippy"))
    (repo-tools ())
    (upstream-authority ("CLIPS producer-native execution"))
    (expected-cost medium)
    (cancellation unspecified)
    (lifecycle active)
    (removal-condition explicit-review))

  (workflow
    (path ".github/workflows/common-lisp-kernel-test.yml")
    (purpose "Common Lisp kernel real-runtime tests and clippy")
    (triggers (pull-request workflow-dispatch))
    (lane fast-pr)
    (semantic-or-mechanism mechanism-build)
    (direct-commands ("Common Lisp runtime setup" "cargo test -p wsm-common-lisp-kernel" "clippy"))
    (repo-tools ())
    (upstream-authority ("Common Lisp producer-native execution"))
    (expected-cost medium)
    (cancellation unspecified)
    (lifecycle active)
    (removal-condition explicit-review))

  (workflow
    (path ".github/workflows/datalog-kernel-test.yml")
    (purpose "Datalog kernel tests and clippy")
    (triggers (pull-request workflow-dispatch))
    (lane fast-pr)
    (semantic-or-mechanism mechanism-build)
    (direct-commands ("cargo test -p wsm-datalog-kernel" "clippy"))
    (repo-tools ())
    (upstream-authority ("Datalog producer-native execution"))
    (expected-cost low)
    (cancellation unspecified)
    (lifecycle active)
    (removal-condition explicit-review))

  (workflow
    (path ".github/workflows/prolog-kernel-test.yml")
    (purpose "Prolog kernel real-runtime tests and clippy")
    (triggers (pull-request workflow-dispatch))
    (lane fast-pr)
    (semantic-or-mechanism mechanism-build)
    (direct-commands ("Prolog runtime setup" "cargo test -p wsm-prolog-kernel" "clippy"))
    (repo-tools ())
    (upstream-authority ("Prolog producer-native execution"))
    (expected-cost medium)
    (cancellation unspecified)
    (lifecycle active)
    (removal-condition explicit-review))

  (workflow
    (path ".github/workflows/native-result-types-test.yml")
    (purpose "preserve producer-native result domains across four real kernels")
    (triggers (pull-request push workflow-dispatch))
    (lane fast-pr)
    (semantic-or-mechanism mixed)
    (direct-commands ("native result library tests" "four_real_kernels" "prolog_datalog_bridge" "clippy"))
    (repo-tools ())
    (upstream-authority ("producer-native result-domain contracts"))
    (expected-cost medium)
    (cancellation unspecified)
    (lifecycle active)
    (removal-condition explicit-review))

  (workflow
    (path ".github/workflows/wasm-browser-test.yml")
    (purpose "WASM browser execution tests in Chrome and Firefox")
    (triggers (pull-request workflow-dispatch))
    (lane fast-pr)
    (semantic-or-mechanism mechanism-build)
    (direct-commands ("wasm-pack Chrome test" "wasm-pack Firefox test"))
    (repo-tools ())
    (upstream-authority ("WASM implementation/tests"))
    (expected-cost medium)
    (cancellation unspecified)
    (lifecycle active)
    (removal-condition explicit-review))

  (workflow
    (path ".github/workflows/host-abi.yml")
    (purpose "native host guest-ABI and CPU vertical regression")
    (triggers (pull-request push workflow-dispatch))
    (lane fast-pr)
    (semantic-or-mechanism mechanism-build)
    (direct-commands ("native_guest_abi" "native_lisp_bytes/native_cond_profile" "host clippy"))
    (repo-tools ())
    (upstream-authority ("host ABI tests"))
    (expected-cost low)
    (cancellation unspecified)
    (lifecycle active)
    (removal-condition explicit-review))

  (workflow
    (path ".github/workflows/embed-staticlib.yml")
    (purpose "canonical embed static library tests and packaging witnesses")
    (triggers (pull-request push workflow-dispatch))
    (lane fast-pr)
    (semantic-or-mechanism mechanism-build)
    (direct-commands ("release embed tests" "staticlib build/link witnesses"))
    (repo-tools ())
    (upstream-authority ("my-lisp-embed ABI/tests"))
    (expected-cost medium)
    (cancellation unspecified)
    (lifecycle active)
    (removal-condition explicit-review))

  (workflow
    (path ".github/workflows/life-1.yml")
    (purpose "focused LIFE-1 real execution spine witness")
    (triggers (pull-request push workflow-dispatch))
    (lane fast-pr)
    (semantic-or-mechanism mixed)
    (direct-commands ("LIFE-1 contract/runtime focused witnesses"))
    (repo-tools ())
    (upstream-authority ("contracts/life-1-contract.lisp"))
    (expected-cost medium)
    (cancellation unspecified)
    (lifecycle active)
    (removal-condition explicit-review))

  (workflow
    (path ".github/workflows/834-semantic-coordinate-targeted.yml")
    (purpose "targeted semantic-coordinate law-axis witness for #834")
    (triggers (pull-request))
    (lane migration)
    (semantic-or-mechanism semantic-gate)
    (direct-commands ("semantic_coordinate_law_axis test"))
    (repo-tools ())
    (upstream-authority ("#834 semantic-coordinate law-axis fixture"))
    (expected-cost low)
    (cancellation unspecified)
    (lifecycle migration-only)
    (removal-condition "#834 follow-up lifecycle review"))

  (workflow
    (path ".github/workflows/857-semantic-coordinate-join.yml")
    (purpose "targeted semantic-coordinate join witnesses for #857")
    (triggers (pull-request))
    (lane migration)
    (semantic-or-mechanism semantic-gate)
    (direct-commands ("semantic-coordinate join focused tests"))
    (repo-tools ())
    (upstream-authority ("#857 join witnesses"))
    (expected-cost low)
    (cancellation unspecified)
    (lifecycle migration-only)
    (removal-condition "#857 follow-up lifecycle review"))

  (workflow
    (path ".github/workflows/956-semreg-targeted.yml")
    (purpose "targeted Lisp semantic-registry API witness for #956")
    (triggers (pull-request))
    (lane migration)
    (semantic-or-mechanism semantic-gate)
    (direct-commands ("semantic_registry_lisp test"))
    (repo-tools ())
    (upstream-authority ("lib/surface/semantic-registry-api.lisp"))
    (expected-cost low)
    (cancellation unspecified)
    (lifecycle migration-only)
    (removal-condition "#956 migration lifecycle review"))

  (workflow
    (path ".github/workflows/authority-guard-self-test.yml")
    (purpose "adversarial self-test of authority guard behavior")
    (triggers (pull-request push workflow-dispatch))
    (lane fast-pr)
    (semantic-or-mechanism docs-policy)
    (direct-commands ("build CLI" "authority negative witnesses" "life_1_scheduler"))
    (repo-tools ())
    (upstream-authority ("authority inventory/guard contracts"))
    (expected-cost low)
    (cancellation unspecified)
    (lifecycle active)
    (removal-condition explicit-review))

  (workflow
    (path ".github/workflows/bilingual-docs-check.yml")
    (purpose "bilingual documentation policy check")
    (triggers (push pull-request))
    (lane fast-pr)
    (semantic-or-mechanism docs-policy)
    (direct-commands ("bilingual documentation checks"))
    (repo-tools ("scripts/check-bilingual-docs"))
    (upstream-authority ("documentation policy"))
    (expected-cost low)
    (cancellation unspecified)
    (lifecycle active)
    (removal-condition explicit-review))

  (workflow
    (path ".github/workflows/c5-swarm-removal-gate.yml")
    (purpose "guard removal of legacy swarm coordination surfaces")
    (triggers (push pull-request))
    (lane migration)
    (semantic-or-mechanism docs-policy)
    (direct-commands ("swarm_deprecation" "swarm_live_caller_inventory" "legacy_coordination_rejected" "semantic_oracle_preservation"))
    (repo-tools ())
    (upstream-authority ("C5 swarm retirement contract/tests"))
    (expected-cost low)
    (cancellation unspecified)
    (lifecycle migration-only)
    (removal-condition "swarm retirement complete and guard no longer needed"))

  (workflow
    (path ".github/workflows/issue-74-real-readfile-benchmark.yml")
    (purpose "targeted real read-file performance benchmark for issue #74")
    (triggers (pull-request))
    (lane migration)
    (semantic-or-mechanism mechanism-build)
    (direct-commands ("semantic-registry read benchmark"))
    (repo-tools ("scripts/benchmark-semantic-registry-read.lisp"))
    (upstream-authority ("#74 performance evidence"))
    (expected-cost high)
    (cancellation unspecified)
    (lifecycle migration-only)
    (removal-condition "#74 benchmark migration/performance decision complete"))
)
