; #1060 CANON-AUTHORITY-INVENTORY-1
; #1347 policy note (2026-09-24): this 2026-09-20 inventory is historical audit data.
; Any row classifying Rust/host local semantics as forbidden duplicate authority
; does NOT impose a current prohibition. Rust/backend local semantics may grow
; freely. Only a reverse edge that makes host implementation semantics the
; source of Lisp language authority is forbidden by the asymmetric firewall.
;
; Data-only audit. This file is NOT a semantic contract and cannot mint a SID,
; define a Lisp law, or admit an execution mechanism.
;
; Historical inventory, updated by #2939 for the domain cutover.
; Canonical identity authority is no longer one flat SID/function table.
; Contract 11 owns D3/D4, while the ratified D5/D6 owner maps own those
; exact-width residents. The old surface registry may donate spellings and
; compatibility bytes only; it cannot assign domain identity.

(schema canon-authority-inventory/1)
(as-of "2026-09-20")
(parent-issue 997)
(issue 1060)
(authority-root "language-contract.lisp + knowledge/d5-historical-full-map.json + knowledge/d6-historical-full-map.json")
(scope "domain-qualified identity authority plus compatibility surface/transport projections")

; authority PATH MAPPING CLASS PROVENANCE CONSUMERS RETIREMENT NOTE
(authority (path "language-contract.lisp") (mapping "D3/D4 exact-domain law and coordinates") (class domain-semantic-authority) (provenance "#2490; #2155; #2158; #2162; Contract 11") (consumers "CoreDomainIdentity; domain surface projection; evaluator routing") (retirement ()) (note "Current D3/D4 identity authority; no universal Function8 space."))
(authority (path "knowledge/d5-historical-full-map.json") (mapping "Core.D5 coordinate->role/behavior/provenance") (class domain-owner-map-authority) (provenance "owner directive 2026-10-03; #2762") (consumers "domain surface projection; D5 admission gates") (retirement ()) (note "Owns D5 identity/residency; runtime admission remains separately gated."))
(authority (path "knowledge/d6-historical-full-map.json") (mapping "Core.D6 coordinate->role/behavior/provenance") (class domain-owner-map-authority) (provenance "owner directive 2026-10-03; #2762") (consumers "domain surface projection; D6 admission gates") (retirement ()) (note "Owns D6 identity/residency; runtime admission remains separately gated."))
(authority (path "lib/surface/semantic-registry.lisp") (mapping "historical byte row->human surface aliases") (class compatibility-surface-projection) (provenance "historical flat-Sens8 registry") (consumers "legacy semantic_registry_generated.rs; compatibility exports; domain-surface alias donor") (retirement 2939) (note "Donates spellings only. Historical byte positions MUST NOT determine CoreDomainIdentity."))
(authority (path "crates/sens/src/domain_surface_registry_generated.rs") (mapping "domain coordinate->canonical/alias surfaces") (class generated-domain-projection) (provenance "Contract 11 D3/D4 + D5/D6 owner maps; old registry aliases only") (consumers "crates/sens/src/semantic_registry.rs") (retirement ()) (note "Canonical runtime surface projection; generated without using legacy byte positions as identity."))
(authority (path "lib/canon.lisp") (mapping "canon-law-name->semantic expectation") (class forbidden-duplicate-semantic-authority) (provenance "language-contract.lisp; historical Canon laws") (consumers "canon witnesses; conformance tests") (retirement 1046) (note "Keep executable laws, but key/validate them downstream of the one function-table SID row instead of leaving a parallel law authority."))
(authority (path "lib/generated/function-table.lisp") (mapping "sid->generated display/function-table projection") (class generated-mechanical-projection) (provenance "lib/surface/semantic-registry.lisp via scripts/generate-function-table.lisp") (consumers "docs/tooling") (retirement 1004) (note "Projection only; #1004 retires it as an input API."))
(authority (path "scripts/generate-function-table.lisp") (mapping "registry->generated function-table projection") (class generated-mechanical-projection) (provenance "lib/surface/semantic-registry.lisp") (consumers "lib/generated/function-table.lisp; docs/generated/function-table.md") (retirement ()) (note "Generator mechanics only; must not add meaning absent from source rows."))

(authority (path "crates/sens/src/semantic_registry_generated.rs") (mapping "legacy byte<->surface compatibility rows") (class generated-compatibility-projection) (provenance "lib/surface/semantic-registry.lisp via scripts/generate-rust-semantic-registry.lisp") (consumers "legacy exports/adapters in crates/sens/src/semantic_registry.rs") (retirement 2939) (note "Historical 256-row compatibility projection only; never canonical domain identity."))
(authority (path "crates/sens/src/semantic_registry.rs") (mapping "surface->CoreDomainIdentity plus explicit legacy projection") (class domain-routing-projection) (provenance "domain_surface_registry_generated.rs; legacy semantic_registry_generated.rs only for compatibility") (consumers "lowering; evaluator routing; tooling; compatibility exports") (retirement ()) (note "Canonical lookup is domain-first; historical bytes are isolated to legacy APIs."))
(authority (path "scripts/generate-rust-semantic-registry.lisp") (mapping "registry->Rust surface projection") (class generated-mechanical-projection) (provenance "lib/surface/semantic-registry.lisp") (consumers "crates/sens/src/semantic_registry_generated.rs") (retirement ()) (note "Projection generator only."))

(authority (path "crates/sens/src/eval/canon.rs") (mapping "sid->CanonicalIdentity/kind->Rust evaluator meaning") (class forbidden-duplicate-semantic-authority) (provenance "hand-maintained Rust CANON constants/table plus semantic_registry lookup") (consumers "eval/mod.rs; lib.rs") (retirement 1046) (note "Primary split-authority hotspot: hard-coded SID constants, CanonicalKind, identity map and invoke_semantic_ref reconstruct language meaning outside the function-table row."))
(authority (path "lib/surface/function-signatures.lisp") (mapping "sid->kind/form/arity/signature/documentation") (class function-table-metadata) (provenance "language-owned companion of semantic-registry.lisp, keyed only by Sens8") (consumers "scripts/generate-rust-function-signatures.lisp; scripts/generate-rust-evaluator-dispatch.lisp") (retirement ()) (note "Replaces lib/evaluator-dispatch.lisp and the hand-maintained Rust tooling table in language_items.rs; holds no names — surfaces come only from the registry."))
(authority (path "scripts/generate-rust-evaluator-dispatch.lisp") (mapping "function-signatures form->Rust mechanism projection") (class generated-mechanical-projection) (provenance "lib/surface/function-signatures.lisp") (consumers "crates/sens/src/eval/necessary_forms_generated.rs") (retirement 1046) (note "Generator is mechanical, but its current source is split authority; provenance must move to Canon/function-table."))
(authority (path "crates/sens/src/eval/necessary_forms_generated.rs") (mapping "sid->NecessaryFormMechanism generated table") (class generated-mechanical-projection) (provenance "lib/surface/function-signatures.lisp via scripts/generate-rust-evaluator-dispatch.lisp") (consumers "crates/sens/src/eval/necessary_forms.rs") (retirement 1046) (note "Generated, but from a temporary split source; not a permanent whitelist."))
(authority (path "crates/sens/src/eval/necessary_forms.rs") (mapping "sid->NecessaryFormIdentity->evaluator mechanism") (class executor-local-mechanism-detail) (provenance "necessary_forms_generated.rs plus semantic_registry surface resolution") (consumers "eval/mod.rs; lib.rs") (retirement 1047) (note "Rust may own execution mechanics only after semantic meaning is fixed; selector seam #1047 should make this post-semantics."))
(authority (path "crates/sens/src/language_items.rs") (mapping "generated signature rows->LanguageItem per registry surface") (class executor-local-mechanism-detail) (provenance "crates/sens/src/function_signatures_generated.rs; semantic_registry surfaces") (consumers "tooling/language discovery") (retirement ()) (note "#1494: no hand-maintained SID or name table remains; metadata comes from lib/surface/function-signatures.lisp."))
(authority (path "crates/sens-cli/src/bin/cml-export.rs") (mapping "exported code list->surfaces/role/callable CML export") (class generated-mechanical-projection) (provenance "semantic_registry_export: surfaces from semantic-registry.lisp, role from function-signatures.lisp via function_role") (consumers "mylisp-cml-export.lisp; CML") (retirement ()) (note "Holds only the export scope (which codes CML needs); role/callable are no longer hand-authored in Rust."))
(authority (path "mylisp-cml-export.lisp") (mapping "sid->surfaces/role/callable exported projection") (class generated-mechanical-projection) (provenance "crates/sens-cli/src/bin/cml-export.rs") (consumers "CML") (retirement 1046) (note "Artifact is deterministic but role/callable derived from lib/surface/function-signatures.lisp (2026-09-26)."))

(authority (path "lib/machine/lowering/semantic-x86-64.lisp") (mapping "sid->x86 realization profile") (class executor-local-mechanism-detail) (provenance "existing semantic identities plus Lisp-owned machine ISA/encoding") (consumers "native-first dispatch; machine witnesses") (retirement 1047) (note "Correct category is realization only; #1047/#1061 must attach mechanism admission/provenance downstream of the same Canon row."))
(authority (path "lib/machine/dispatch/native-first.lisp") (mapping "surface/form-shape->native mechanism selection") (class forbidden-duplicate-semantic-authority) (provenance "hand-matched English car/cons forms plus x86 lowerings") (consumers "native-first execution witnesses") (retirement 1047) (note "Selector currently recognizes literal surface names instead of consuming an already-resolved SID/admitted mechanism set."))
(authority (path "crates/sens-host/src/native_exec.rs") (mapping "admitted machine forms/bytes->physical execution") (class executor-local-mechanism-detail) (provenance "lib/machine admission/lowering ABI") (consumers "native machine witnesses") (retirement ()) (note "Semantics-blind host mechanism; no SID->meaning assignment found."))

(authority (path "crates/wsm-kernel-c-abi/src/lib.rs") (mapping "opaque sid+payload<->kernel ABI transport") (class executor-local-mechanism-detail) (provenance "WsmKernelRequest semantic_id is opaque u8") (consumers "four kernel adapters") (retirement ()) (note "Transport identity only; kernel enum selects runtime kind, not Lisp meaning."))
(authority (path "crates/wsm-kernel-host/src/lib.rs") (mapping "kernel-id->lifecycle/router mechanism") (class executor-local-mechanism-detail) (provenance "mechanical KernelDriver/KernelRouter lifecycle") (consumers "island orchestration") (retirement ()) (note "No SID->meaning map found; availability/lifecycle routing is mechanical."))
(authority (path "crates/wsm-common-lisp-kernel/src/lib.rs") (mapping "opaque sid+native Common Lisp form->native result") (class executor-local-mechanism-detail) (provenance "request carries SemanticId without interpreting it") (consumers "C ABI; native-result observation") (retirement 1048) (note "#1048 should generate native forms from Lisp-owned SID/law; kernel itself remains mechanical."))
(authority (path "crates/wsm-prolog-kernel/src/lib.rs") (mapping "opaque sid+Prolog query->native result") (class executor-local-mechanism-detail) (provenance "request carries SemanticId without assigning Lisp meaning") (consumers "C ABI; native-result observation") (retirement 1048) (note "#1048 should generate query payload downstream of Canon; Prolog semantics remain local to Prolog."))
(authority (path "crates/wsm-clips-kernel/src/lib.rs") (mapping "opaque sid+CLIPS payload->native result") (class executor-local-mechanism-detail) (provenance "C ABI carries semantic_id; CLIPS runtime owns rule mechanics") (consumers "C ABI; native-result observation") (retirement 1048) (note "#1048 should supply generated payload; adapter must not gain operator->SID authority."))
(authority (path "crates/wsm-datalog-kernel/src/lib.rs") (mapping "opaque sid+relational program->fixpoint result") (class executor-local-mechanism-detail) (provenance "Datalog engine owns relation/fixpoint mechanics; SID stored as observation provenance") (consumers "C ABI; native-result observation") (retirement 1048) (note "#1048 should supply generated lowering; Datalog relation names must not mint Lisp meaning."))
(authority (path "crates/wsm-native-result-types/src/lib.rs") (mapping "producer+optional sid->observation provenance") (class executor-local-mechanism-detail) (provenance "native results are preserved side-by-side") (consumers "four-kernel observation/coordination tests") (retirement ()) (note "Observation metadata only; producer slot and SID do not define operation meaning."))

(authority (path "crates/wsm-common-lisp-kernel/tests/sbcl_semantic_witness.rs") (mapping "hard-coded SID constants->CAR/CONS/CDR test intent") (class compatibility-historical-fixture) (provenance "test-local constants/comments") (consumers "Common Lisp kernel witness only") (retirement 1048) (note "Test evidence may name historical SIDs, but production lowering must come from Canon/function-table; replace with generated witness input when #1048 lands."))
(authority (path "knowledge/semantic-ownership.lisp") (mapping "behavior/SID->claimed owner") (class compatibility-historical-fixture) (provenance "audit data as-of 2026-09-17") (consumers "ownership tooling/docs") (retirement 1062) (note "Explicitly data, not contract, but currently claims canon.rs owns Canon meaning; must be synchronized after #1046."))
(authority (path "contracts/semantic-ownership-audit-733.lisp") (mapping "component->semantic authority category") (class compatibility-historical-fixture) (provenance "earlier ownership audit") (consumers "audit/research tooling") (retirement 1062) (note "Labels lib/surface/function-signatures.lisp (formerly evaluator-dispatch.lisp) as the language-owned evaluator operation classification; preserve as evidence, never as live dispatch source."))
(authority (path "CURRENT.md") (mapping "authority-order->claimed semantic owner") (class forbidden-duplicate-semantic-authority) (provenance "active human guidance") (consumers "agents/contributors") (retirement 1062) (note "Still names canon.rs/necessary_forms.rs in authority order; active guidance contradicts #997 and can recreate split authority even without code changes."))

; Audit conclusion updated by #2939:
; - canonical identity is distributed by explicit domain authority (Contract 11 D3/D4 + D5/D6 owner maps);
; - lib/surface/semantic-registry.lisp is no longer an identity root and survives only as a spelling/compatibility projection;
; - the most important active duplicate-meaning table is canon.rs (cml-export.rs roles
;   derived from the function table since 2026-09-26)
;   (evaluator-dispatch and language_items.rs retired 2026-09-26 into
;   lib/surface/function-signatures.lisp; unused compiler IR ir.rs deleted);
; - machine lowering is a legitimate mechanism layer but must gain verifiable
;   provenance/admission from the same Canon row (#1047/#1061);
; - the four kernel adapters are presently mechanical transports/executors;
; - active/stale policy artifacts are explicitly listed so they cannot silently
;   re-legitimize a second authority.
