; #1060 CANON-AUTHORITY-INVENTORY-1
; Data-only audit. This file is NOT a semantic contract and cannot mint a SID,
; define a Lisp law, or admit an execution mechanism.
;
; One row records one place that can currently assign, project, transport,
; document, or realize SID-related meaning/mechanism information.
; The only row allowed to claim canon-function-table-authority is the existing
; Lisp-owned semantic registry. Everything else must be either a projection,
; executor-local mechanism detail, historical/compatibility evidence, or an
; explicitly tracked duplicate authority with a retirement path.

(schema canon-authority-inventory/1)
(as-of "2026-09-20")
(parent-issue 997)
(issue 1060)
(authority-root "lib/surface/semantic-registry.lisp")
(scope "active SID/meaning/mechanism mappings plus risk-bearing generated/tooling projections")

; authority PATH MAPPING CLASS PROVENANCE CONSUMERS RETIREMENT NOTE
(authority (path "lib/surface/semantic-registry.lisp") (mapping "surface<->sid identity root") (class canon-function-table-authority) (provenance "self; language-contract.lisp") (consumers "semantic_registry_generated.rs; function-table/meta projections; downstream repos") (retirement ()) (note "Sole existing numeric identity root; #1046 converges meaning/domain/law/mechanisms onto this row model without creating another registry."))
(authority (path "lib/canon.lisp") (mapping "canon-law-name->semantic expectation") (class forbidden-duplicate-semantic-authority) (provenance "language-contract.lisp; historical Canon laws") (consumers "canon witnesses; conformance tests") (retirement 1046) (note "Keep executable laws, but key/validate them downstream of the one function-table SID row instead of leaving a parallel law authority."))
(authority (path "lib/generated/function-table.lisp") (mapping "sid->generated display/function-table projection") (class generated-mechanical-projection) (provenance "lib/surface/semantic-registry.lisp via scripts/generate-function-table.lisp") (consumers "docs/tooling") (retirement 1004) (note "Projection only; #1004 retires it as an input API."))
(authority (path "scripts/generate-function-table.lisp") (mapping "registry->generated function-table projection") (class generated-mechanical-projection) (provenance "lib/surface/semantic-registry.lisp") (consumers "lib/generated/function-table.lisp; docs/generated/function-table.md") (retirement ()) (note "Generator mechanics only; must not add meaning absent from source rows."))

(authority (path "crates/sens/src/semantic_registry_generated.rs") (mapping "sid<->surface generated runtime rows") (class generated-mechanical-projection) (provenance "lib/surface/semantic-registry.lisp via scripts/generate-rust-semantic-registry.lisp") (consumers "crates/sens/src/semantic_registry.rs") (retirement ()) (note "Generated runtime projection; no semantic role/domain fields."))
(authority (path "crates/sens/src/semantic_registry.rs") (mapping "surface<->sid runtime lookup") (class generated-mechanical-projection) (provenance "crates/sens/src/semantic_registry_generated.rs") (consumers "evaluator; IR; tooling; public semantic_registry_export") (retirement ()) (note "Mechanical lookup over generated rows; it must remain unable to assign operation meaning."))
(authority (path "scripts/generate-rust-semantic-registry.lisp") (mapping "registry->Rust surface projection") (class generated-mechanical-projection) (provenance "lib/surface/semantic-registry.lisp") (consumers "crates/sens/src/semantic_registry_generated.rs") (retirement ()) (note "Projection generator only."))

(authority (path "crates/sens/src/eval/canon.rs") (mapping "sid->CanonicalIdentity/kind->Rust evaluator meaning") (class forbidden-duplicate-semantic-authority) (provenance "hand-maintained Rust CANON constants/table plus semantic_registry lookup") (consumers "eval/mod.rs; ir.rs; lib.rs") (retirement 1046) (note "Primary split-authority hotspot: hard-coded SID constants, CanonicalKind, identity map and invoke_semantic_ref reconstruct language meaning outside the function-table row."))
(authority (path "lib/evaluator-dispatch.lisp") (mapping "sid->lambda/define operation class") (class forbidden-duplicate-semantic-authority) (provenance "independent Lisp companion table") (consumers "scripts/generate-rust-evaluator-dispatch.lisp") (retirement 1046) (note "#1046 explicitly forbids keeping evaluator-dispatch.lisp as independent authority; useful mechanism metadata must converge onto/validate against the Canon function-table row."))
(authority (path "scripts/generate-rust-evaluator-dispatch.lisp") (mapping "evaluator-dispatch->Rust mechanism projection") (class generated-mechanical-projection) (provenance "lib/evaluator-dispatch.lisp") (consumers "crates/sens/src/eval/necessary_forms_generated.rs") (retirement 1046) (note "Generator is mechanical, but its current source is split authority; provenance must move to Canon/function-table."))
(authority (path "crates/sens/src/eval/necessary_forms_generated.rs") (mapping "sid->NecessaryFormMechanism generated table") (class generated-mechanical-projection) (provenance "lib/evaluator-dispatch.lisp via scripts/generate-rust-evaluator-dispatch.lisp") (consumers "crates/sens/src/eval/necessary_forms.rs") (retirement 1046) (note "Generated, but from a temporary split source; not a permanent whitelist."))
(authority (path "crates/sens/src/eval/necessary_forms.rs") (mapping "sid->NecessaryFormIdentity->evaluator mechanism") (class executor-local-mechanism-detail) (provenance "necessary_forms_generated.rs plus semantic_registry surface resolution") (consumers "eval/mod.rs; ir.rs; lib.rs") (retirement 1047) (note "Rust may own execution mechanics only after semantic meaning is fixed; selector seam #1047 should make this post-semantics."))
(authority (path "crates/sens/src/ir.rs") (mapping "sid->KnownSyntaxId/IR role") (class forbidden-duplicate-semantic-authority) (provenance "hand-maintained match semantic_id plus DEFMACRO_SEMANTIC_ID constant") (consumers "compiler IR tests/future backend") (retirement 1046) (note "Hard-coded 1/7/8/9/10 syntax classification independently reconstructs role/meaning."))
(authority (path "crates/sens/src/language_items.rs") (mapping "sid->signature/documentation/kind/arity") (class forbidden-duplicate-semantic-authority) (provenance "hand-maintained SEMANTIC_TOOLING table") (consumers "tooling/language discovery") (retirement 1046) (note "Arity/kind/signature are semantic/domain metadata and must not remain a second Rust SID table."))
(authority (path "crates/sens-cli/src/bin/cml-export.rs") (mapping "sid->role/callable CML export metadata") (class forbidden-duplicate-semantic-authority) (provenance "hand-maintained EXPORTED_FORMS Rust table plus registry surfaces") (consumers "mylisp-cml-export.lisp; CML") (retirement 1046) (note "Generated output is not sufficient provenance: role/callable are authored in Rust and are absent from the current registry row."))
(authority (path "mylisp-cml-export.lisp") (mapping "sid->surfaces/role/callable exported projection") (class generated-mechanical-projection) (provenance "crates/sens-cli/src/bin/cml-export.rs") (consumers "CML") (retirement 1046) (note "Artifact is deterministic but currently inherits hand-authored role/callable metadata from its producer; regenerate from Canon authority after #1046."))

(authority (path "lib/machine/lowering/semantic-x86-64.lisp") (mapping "sid->x86 realization profile") (class executor-local-mechanism-detail) (provenance "existing semantic identities plus Lisp-owned machine ISA/encoding") (consumers "native-first dispatch; machine witnesses") (retirement 1047) (note "Correct category is realization only; #1047/#1061 must attach mechanism admission/provenance downstream of the same Canon row."))
(authority (path "lib/machine/dispatch/native-first.lisp") (mapping "surface/form-shape->native mechanism selection") (class forbidden-duplicate-semantic-authority) (provenance "hand-matched English car/cons forms plus x86 lowerings") (consumers "native-first execution witnesses") (retirement 1047) (note "Selector currently recognizes literal surface names instead of consuming an already-resolved SID/admitted mechanism set."))
(authority (path "crates/sens-host/src/native_exec.rs") (mapping "admitted machine forms/bytes->physical execution") (class executor-local-mechanism-detail) (provenance "lib/machine admission/lowering ABI") (consumers "native machine witnesses") (retirement ()) (note "Semantics-blind host mechanism; no SID->meaning assignment found."))

(authority (path "crates/wsm-kernel-c-abi/src/lib.rs") (mapping "opaque sid+payload<->kernel ABI transport") (class executor-local-mechanism-detail) (provenance "WsmKernelRequest semantic_id is opaque u8") (consumers "four kernel adapters") (retirement ()) (note "Transport identity only; kernel enum selects runtime kind, not Lisp meaning."))
(authority (path "crates/wsm-kernel-host/src/lib.rs") (mapping "kernel-id->lifecycle/router mechanism") (class executor-local-mechanism-detail) (provenance "mechanical KernelDriver/KernelRouter lifecycle") (consumers "island orchestration") (retirement ()) (note "No SID->meaning map found; availability/lifecycle routing is mechanical."))
(authority (path "crates/wsm-common-lisp-kernel/src/lib.rs") (mapping "opaque sid+native Common Lisp form->native result") (class executor-local-mechanism-detail) (provenance "request carries SemanticId without interpreting it") (consumers "C ABI; native-result observation") (retirement 1048) (note "#1048 should generate native forms from Lisp-owned SID/law; kernel itself remains mechanical."))
(authority (path "crates/wsm-prolog-kernel/src/lib.rs") (mapping "opaque sid+Prolog query->native result") (class executor-local-mechanism-detail) (provenance "request carries SemanticId without assigning Lisp meaning") (consumers "C ABI; native-result observation") (retirement 1048) (note "#1048 should generate query payload downstream of Canon; Prolog semantics remain local to Prolog."))
(authority (path "crates/wsm-clips-kernel/src/lib.rs") (mapping "opaque sid+CLIPS payload->native result") (class executor-local-mechanism-detail) (provenance "C ABI carries semantic_id; CLIPS runtime owns rule mechanics") (consumers "C ABI; native-result observation") (retirement 1048) (note "#1048 should supply generated payload; adapter must not gain operator->SID authority."))
(authority (path "crates/wsm-datalog-kernel/src/lib.rs") (mapping "opaque sid+relational program->fixpoint result") (class executor-local-mechanism-detail) (provenance "Datalog engine owns relation/fixpoint mechanics; SID stored as observation provenance") (consumers "C ABI; native-result observation") (retirement 1048) (note "#1048 should supply generated lowering; Datalog relation names must not mint Lisp meaning."))
(authority (path "crates/wsm-native-result-types/src/lib.rs") (mapping "producer+optional sid->observation provenance") (class executor-local-mechanism-detail) (provenance "native results are preserved side-by-side") (consumers "four-kernel observation/coordination tests") (retirement ()) (note "Observation metadata only; producer slot and SID do not define operation meaning."))

(authority (path "crates/wsm-common-lisp-kernel/tests/sbcl_semantic_witness.rs") (mapping "hard-coded SID constants->CAR/CONS/CDR test intent") (class compatibility-historical-fixture) (provenance "test-local constants/comments") (consumers "Common Lisp kernel witness only") (retirement 1048) (note "Test evidence may name historical SIDs, but production lowering must come from Canon/function-table; replace with generated witness input when #1048 lands."))
(authority (path "knowledge/semantic-ownership.lisp") (mapping "behavior/SID->claimed owner") (class compatibility-historical-fixture) (provenance "audit data as-of 2026-09-17") (consumers "ownership tooling/docs") (retirement 1062) (note "Explicitly data, not contract, but currently claims canon.rs owns Canon meaning; must be synchronized after #1046."))
(authority (path "contracts/semantic-ownership-audit-733.lisp") (mapping "component->semantic authority category") (class compatibility-historical-fixture) (provenance "earlier ownership audit") (consumers "audit/research tooling") (retirement 1062) (note "Currently labels evaluator-dispatch.lisp semantic authority; preserve as evidence or update status, never as live dispatch source."))
(authority (path "CURRENT.md") (mapping "authority-order->claimed semantic owner") (class forbidden-duplicate-semantic-authority) (provenance "active human guidance") (consumers "agents/contributors") (retirement 1062) (note "Still names canon.rs/necessary_forms.rs in authority order; active guidance contradicts #997 and can recreate split authority even without code changes."))

; Audit conclusion (2026-09-20):
; - one identity root exists: lib/surface/semantic-registry.lisp;
; - the most important active duplicate-meaning tables are canon.rs, evaluator-dispatch,
;   ir.rs, language_items.rs and cml-export.rs;
; - machine lowering is a legitimate mechanism layer but must gain verifiable
;   provenance/admission from the same Canon row (#1047/#1061);
; - the four kernel adapters are presently mechanical transports/executors;
; - active/stale policy artifacts are explicitly listed so they cannot silently
;   re-legitimize a second authority.
