; #604 migration-only witness. This is not coverage authority.
; It freezes the last 32-row Rust partial projection and proves that every
; legacy partial pair survives inside the derived Lisp-owned 122-pair projection.

(encoder-coverage-legacy-parity/1
  (legacy-pair-count #b100000)
  (successor-pair-count #b1111010)
  (legacy X86-BASE "ADD")
  (legacy X86-BASE "AND")
  (legacy X86-BASE "CMP")
  (legacy X86-BASE "DEC")
  (legacy X86-BASE "INC")
  (legacy X86-BASE "JB")
  (legacy X86-BASE "JBE")
  (legacy X86-BASE "JL")
  (legacy X86-BASE "JLE")
  (legacy X86-BASE "JMP")
  (legacy X86-BASE "JNB")
  (legacy X86-BASE "JNBE")
  (legacy X86-BASE "JNL")
  (legacy X86-BASE "JNLE")
  (legacy X86-BASE "JNO")
  (legacy X86-BASE "JNP")
  (legacy X86-BASE "JNS")
  (legacy X86-BASE "JNZ")
  (legacy X86-BASE "JO")
  (legacy X86-BASE "JP")
  (legacy X86-BASE "JS")
  (legacy X86-BASE "JZ")
  (legacy X86-BASE "MOV")
  (legacy X86-BASE "NEG")
  (legacy X86-BASE "NOT")
  (legacy X86-BASE "OR")
  (legacy X86-BASE "POP")
  (legacy X86-BASE "PUSH")
  (legacy X86-BASE "RET_NEAR")
  (legacy X86-BASE "SUB")
  (legacy X86-BASE "TEST")
  (legacy X86-BASE "XOR")
)
