; function-table-sculpt-audit.lisp — live SID implementation audit (#1118)
; Audit data, NOT semantic authority. Identity authority remains lib/surface/semantic-registry.lisp.
; Historical #734 is superseded where current executable implementation disagrees.
; remove backend implementation != demote primitive status != reclaim/delete SID.

(function-table-sculpt-audit/1
  (issue 1118)
  (as-of "2026-09-21")
  (registry "lib/surface/semantic-registry.lisp")
  (registry-count 170)
  (rows
    (row
      (sid 00000000)
      (name "empty-list")
      (definition-locus "crates/my-lisp/src/eval/canon.rs")
      (class ground-value)
      (backend-required-now? no)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "runtime value representation")
      (sid-reclaim-candidate? no)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "#419;crates/my-lisp/src/eval/canon.rs")
      (notes "Ground identity, not a callable primitive."))
    (row
      (sid 00000001)
      (name "quote")
      (definition-locus "crates/my-lisp/src/eval/canon.rs")
      (class evaluation-control-anchor)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "evaluator control/evaluation-order mechanism")
      (sid-reclaim-candidate? no)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "#419;crates/my-lisp/src/eval/canon.rs")
      (notes "Controls evaluation; ordinary eager-function replacement is not equivalent. Strict reduction remains evidence-governed."))
    (row
      (sid 00000010)
      (name "atom")
      (definition-locus "crates/my-lisp/src/eval/canon.rs")
      (class backend-core-candidate)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "total structural atom observation")
      (sid-reclaim-candidate? no)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "#419;crates/my-lisp/src/eval/canon.rs")
      (notes "Current backend anchor only; #419 governs irreducibility claims. Backend presence alone is not proof."))
    (row
      (sid 00000011)
      (name "eq")
      (definition-locus "crates/my-lisp/src/eval/canon.rs")
      (class backend-core-candidate)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "runtime identity observation")
      (sid-reclaim-candidate? no)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "#419;crates/my-lisp/src/eval/canon.rs")
      (notes "Current backend anchor only; #419 governs irreducibility claims. Backend presence alone is not proof."))
    (row
      (sid 00000100)
      (name "cons")
      (definition-locus "crates/my-lisp/src/eval/canon.rs")
      (class backend-core-candidate)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "pair construction")
      (sid-reclaim-candidate? no)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "#419;crates/my-lisp/src/eval/canon.rs")
      (notes "Current backend anchor only; #419 governs irreducibility claims. Backend presence alone is not proof."))
    (row
      (sid 00000101)
      (name "car")
      (definition-locus "crates/my-lisp/src/eval/canon.rs")
      (class backend-core-candidate)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "pair projection")
      (sid-reclaim-candidate? no)
      (irreducibility-proved? basis-relative)
      (confidence high)
      (evidence "#419;crates/my-lisp/src/eval/canon.rs")
      (notes "Current backend anchor only; #419 governs irreducibility claims. Backend presence alone is not proof."))
    (row
      (sid 00000110)
      (name "cdr")
      (definition-locus "crates/my-lisp/src/eval/canon.rs")
      (class backend-core-candidate)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "pair projection")
      (sid-reclaim-candidate? no)
      (irreducibility-proved? basis-relative)
      (confidence high)
      (evidence "#419;crates/my-lisp/src/eval/canon.rs")
      (notes "Current backend anchor only; #419 governs irreducibility claims. Backend presence alone is not proof."))
    (row
      (sid 00000111)
      (name "cond")
      (definition-locus "crates/my-lisp/src/eval/canon.rs")
      (class evaluation-control-anchor)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "evaluator control/evaluation-order mechanism")
      (sid-reclaim-candidate? no)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "#419;crates/my-lisp/src/eval/canon.rs")
      (notes "Controls evaluation; ordinary eager-function replacement is not equivalent. Strict reduction remains evidence-governed."))
    (row
      (sid 00001000)
      (name "lambda")
      (definition-locus "crates/my-lisp/src/eval/necessary_forms.rs;crates/my-lisp/src/eval/mod.rs")
      (class evaluation-control-anchor)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "evaluator control/evaluation-order mechanism")
      (sid-reclaim-candidate? no)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/necessary_forms.rs;crates/my-lisp/src/eval/mod.rs")
      (notes "Needs focused evidence before primitive or reclaim claim."))
    (row
      (sid 00001001)
      (name "define")
      (definition-locus "crates/my-lisp/src/eval/necessary_forms.rs;crates/my-lisp/src/eval/mod.rs")
      (class evaluation-control-anchor)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "evaluator control/evaluation-order mechanism")
      (sid-reclaim-candidate? no)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/necessary_forms.rs;crates/my-lisp/src/eval/mod.rs")
      (notes "Needs focused evidence before primitive or reclaim claim."))
    (row
      (sid 00001010)
      (name "defmacro")
      (definition-locus "lib/macro.lisp;crates/my-lisp/src/eval/macro_substrate.rs")
      (class evaluation-control-anchor)
      (backend-required-now? yes)
      (pure-lisp-definition-now? partial)
      (macro-expansion-now? no)
      (lower-mechanism "macro-expansion substrate plus Lisp-owned macro semantics")
      (sid-reclaim-candidate? no)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "knowledge/semantic-ownership.lisp;lib/macro.lisp;crates/my-lisp/src/eval/macro_substrate.rs")
      (notes "Public semantics are Lisp-owned over a narrow macro substrate; not mere textual alias."))
    (row
      (sid 00001011)
      (name "def")
      (definition-locus "crates/my-lisp/src/eval/necessary_forms.rs;crates/my-lisp/src/eval/mod.rs")
      (class compatibility-only)
      (backend-required-now? no)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? compatibility-route)
      (lower-mechanism "define")
      (sid-reclaim-candidate? yes)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "knowledge/meta-eval-evidence.lisp;crates/my-lisp/src/eval/necessary_forms.rs")
      (notes "Compatibility form for define; strongest immediate reclaim candidate after compatibility impact check."))
    (row
      (sid 00001100)
      (name "+")
      (definition-locus "crates/my-lisp/src/eval/canon.rs;crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "numeric representation/arithmetic/comparison mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/canon.rs;crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend arithmetic/comparison mechanism today; permanence is not inferred from implementation."))
    (row
      (sid 00001101)
      (name "-")
      (definition-locus "crates/my-lisp/src/eval/canon.rs;crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "numeric representation/arithmetic/comparison mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/canon.rs;crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend arithmetic/comparison mechanism today; permanence is not inferred from implementation."))
    (row
      (sid 00001110)
      (name "*")
      (definition-locus "crates/my-lisp/src/eval/canon.rs;crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "numeric representation/arithmetic/comparison mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/canon.rs;crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend arithmetic/comparison mechanism today; permanence is not inferred from implementation."))
    (row
      (sid 00001111)
      (name "/")
      (definition-locus "crates/my-lisp/src/eval/canon.rs;crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "numeric representation/arithmetic/comparison mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/canon.rs;crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend arithmetic/comparison mechanism today; permanence is not inferred from implementation."))
    (row
      (sid 00010000)
      (name "abs")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "existing arithmetic/comparison/control/list primitives")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00010001)
      (name "min")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "existing arithmetic/comparison/control/list primitives")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00010010)
      (name "max")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "existing arithmetic/comparison/control/list primitives")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00010011)
      (name "mod")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "existing arithmetic/comparison/control/list primitives")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00010100)
      (name "quotient")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "existing arithmetic/comparison/control/list primitives")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00010101)
      (name "sqrt")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "existing arithmetic/comparison/control/list primitives")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00010110)
      (name "isqrt")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "existing arithmetic/comparison/control/list primitives")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00010111)
      (name "min-list")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "existing arithmetic/comparison/control/list primitives")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00011000)
      (name "max-list")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "existing arithmetic/comparison/control/list primitives")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00011001)
      (name "largest-chunk")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "existing arithmetic/comparison/control/list primitives")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00011010)
      (name "<")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "numeric representation/arithmetic/comparison mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend arithmetic/comparison mechanism today; permanence is not inferred from implementation."))
    (row
      (sid 00011011)
      (name ">")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "numeric representation/arithmetic/comparison mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend arithmetic/comparison mechanism today; permanence is not inferred from implementation."))
    (row
      (sid 00011100)
      (name "=")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "numeric representation/arithmetic/comparison mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend arithmetic/comparison mechanism today; permanence is not inferred from implementation."))
    (row
      (sid 00011101)
      (name "<=")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "existing arithmetic/comparison/control/list primitives")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00011110)
      (name ">=")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "existing arithmetic/comparison/control/list primitives")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00011111)
      (name "nondecreasing-from?")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "existing arithmetic/comparison/control/list primitives")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00100000)
      (name "nonincreasing-from?")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "existing arithmetic/comparison/control/list primitives")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00100001)
      (name "not")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "existing arithmetic/comparison/control/list primitives")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00100010)
      (name "equal?")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "existing arithmetic/comparison/control/list primitives")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00100011)
      (name "symbol?")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "existing arithmetic/comparison/control/list primitives")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00100100)
      (name "string?")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "string/symbol/buffer representation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 00100101)
      (name "string<?")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "string/symbol/buffer representation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 00100110)
      (name "numeric-buffer?")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "string/symbol/buffer representation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 00100111)
      (name "list")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "cons/car/cdr/cond/lambda and recursion")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00101000)
      (name "length")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "cons/car/cdr/cond/lambda and recursion")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00101001)
      (name "append")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "cons/car/cdr/cond/lambda and recursion")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00101010)
      (name "reverse")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "cons/car/cdr/cond/lambda and recursion")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00101011)
      (name "nth")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "cons/car/cdr/cond/lambda and recursion")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00101100)
      (name "member?")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "cons/car/cdr/cond/lambda and recursion")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00101101)
      (name "assoc")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "cons/car/cdr/cond/lambda and recursion")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00101110)
      (name "pair")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "cons/car/cdr/cond/lambda and recursion")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00101111)
      (name "second")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "cons/car/cdr/cond/lambda and recursion")
      (sid-reclaim-candidate? yes)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00110000)
      (name "third")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "cons/car/cdr/cond/lambda and recursion")
      (sid-reclaim-candidate? yes)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00110001)
      (name "fourth")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "cons/car/cdr/cond/lambda and recursion")
      (sid-reclaim-candidate? yes)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00110010)
      (name "fifth")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "cons/car/cdr/cond/lambda and recursion")
      (sid-reclaim-candidate? yes)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00110011)
      (name "caar")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "cons/car/cdr/cond/lambda and recursion")
      (sid-reclaim-candidate? yes)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00110100)
      (name "cadr")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "cons/car/cdr/cond/lambda and recursion")
      (sid-reclaim-candidate? yes)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00110101)
      (name "cddr")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "cons/car/cdr/cond/lambda and recursion")
      (sid-reclaim-candidate? yes)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00110110)
      (name "cadddr")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "cons/car/cdr/cond/lambda and recursion")
      (sid-reclaim-candidate? yes)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00110111)
      (name "map")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "cons/car/cdr/cond/lambda and recursion")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00111000)
      (name "filter")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "cons/car/cdr/cond/lambda and recursion")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00111001)
      (name "reduce")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "cons/car/cdr/cond/lambda and recursion")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00111010)
      (name "string-append")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "string/symbol/buffer representation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 00111011)
      (name "string-length")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "string primitive mechanisms plus recursion")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00111100)
      (name "string-empty?")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "string primitive mechanisms plus recursion")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00111101)
      (name "string-prefix?")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "string primitive mechanisms plus recursion")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00111110)
      (name "string-contains?")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "string primitive mechanisms plus recursion")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 00111111)
      (name "string-first")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "string/symbol/buffer representation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01000000)
      (name "string-rest")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "string/symbol/buffer representation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01000001)
      (name "string-slice")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "string/symbol/buffer representation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01000010)
      (name "symbol->string")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "string/symbol/buffer representation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01000011)
      (name "string->symbol")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "string/symbol/buffer representation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01000100)
      (name "codepoint->string")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "string/symbol/buffer representation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01000101)
      (name "string->codepoint")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "string/symbol/buffer representation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01000110)
      (name "number->string")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "writer/list/arithmetic helpers")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 01000111)
      (name "digit->string")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "writer/list/arithmetic helpers")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 01001000)
      (name "print")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "reader/writer/evaluator/environment effect or reflection mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01001001)
      (name "princ")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "reader/writer/evaluator/environment effect or reflection mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01001010)
      (name "read")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "reader/writer/evaluator/environment effect or reflection mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01001011)
      (name "read-all")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "reader/writer/evaluator/environment effect or reflection mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01001100)
      (name "write-to-string")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "reader/writer/evaluator/environment effect or reflection mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01001101)
      (name "eval")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "reader/writer/evaluator/environment effect or reflection mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01001110)
      (name "env")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "reader/writer/evaluator/environment effect or reflection mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01001111)
      (name "vector")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "vector/numeric-buffer representation and mutation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01010000)
      (name "make-vector")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "vector/numeric-buffer representation and mutation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01010001)
      (name "vector-length")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "vector/numeric-buffer representation and mutation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01010010)
      (name "vector-ref")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "vector/numeric-buffer representation and mutation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01010011)
      (name "vector-set!")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "vector/numeric-buffer representation and mutation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01010100)
      (name "i32-buffer")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "vector/numeric-buffer representation and mutation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01010101)
      (name "f32-buffer")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "vector/numeric-buffer representation and mutation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01010110)
      (name "numeric-buffer-type")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "vector/numeric-buffer representation and mutation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01010111)
      (name "numeric-buffer-length")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "vector/numeric-buffer representation and mutation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01011000)
      (name "numeric-buffer-ref")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "vector/numeric-buffer representation and mutation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01011001)
      (name "numeric-buffer-map")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "vector/numeric-buffer representation and mutation mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Direct backend mechanism today; replace only after a lower honest mechanism plus parity witness exists."))
    (row
      (sid 01011010)
      (name "mono-ns")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class host-observation-anchor)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "clock/network/environment observation supplied by host")
      (sid-reclaim-candidate? no)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "knowledge/semantic-ownership.lisp;crates/my-lisp/src/eval/builtins.rs")
      (notes "Physical observation cannot be manufactured by syntax sugar; interpretation above it should stay Lisp-owned."))
    (row
      (sid 01011011)
      (name "unix-time-now")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class host-observation-anchor)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "clock/network/environment observation supplied by host")
      (sid-reclaim-candidate? no)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "knowledge/semantic-ownership.lisp;crates/my-lisp/src/eval/builtins.rs")
      (notes "Physical observation cannot be manufactured by syntax sugar; interpretation above it should stay Lisp-owned."))
    (row
      (sid 01011100)
      (name "ntp-query-raw")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class host-observation-anchor)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "clock/network/environment observation supplied by host")
      (sid-reclaim-candidate? no)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "knowledge/semantic-ownership.lisp;crates/my-lisp/src/eval/builtins.rs")
      (notes "Physical observation cannot be manufactured by syntax sugar; interpretation above it should stay Lisp-owned."))
    (row
      (sid 01011101)
      (name "timezone-declarations-raw")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class host-observation-anchor)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "clock/network/environment observation supplied by host")
      (sid-reclaim-candidate? no)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "knowledge/semantic-ownership.lisp;crates/my-lisp/src/eval/builtins.rs")
      (notes "Physical observation cannot be manufactured by syntax sugar; interpretation above it should stay Lisp-owned."))
    (row
      (sid 01011110)
      (name "utc-now")
      (definition-locus "lib/time.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "raw clock/timezone observations plus pure Lisp policy")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/time.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 01011111)
      (name "utc-from-unix")
      (definition-locus "lib/time.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "raw clock/timezone observations plus pure Lisp policy")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/time.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 01100000)
      (name "unix-time-observation->utc")
      (definition-locus "lib/time.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "raw clock/timezone observations plus pure Lisp policy")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/time.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 01100001)
      (name "milliseconds-from-nanoseconds")
      (definition-locus "lib/time.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "raw clock/timezone observations plus pure Lisp policy")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/time.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 01100010)
      (name "mono-ms")
      (definition-locus "lib/time.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "raw clock/timezone observations plus pure Lisp policy")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/time.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 01100011)
      (name "timezone-name")
      (definition-locus "lib/time.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "raw clock/timezone observations plus pure Lisp policy")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/time.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 01100100)
      (name "timezone-detect")
      (definition-locus "lib/time.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "raw clock/timezone observations plus pure Lisp policy")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/time.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 01100101)
      (name "timezone-offset-seconds")
      (definition-locus "lib/time.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "raw clock/timezone observations plus pure Lisp policy")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/time.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 01100110)
      (name "deadline-reached?")
      (definition-locus "lib/time.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "raw clock/timezone observations plus pure Lisp policy")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/time.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 01100111)
      (name "deadline-reached-at?")
      (definition-locus "lib/time.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "raw clock/timezone observations plus pure Lisp policy")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/time.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 01101000)
      (name "elapsed-ns")
      (definition-locus "lib/time.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "raw clock/timezone observations plus pure Lisp policy")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/time.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 01101001)
      (name "deadline-from")
      (definition-locus "lib/time.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "raw clock/timezone observations plus pure Lisp policy")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/time.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 01101010)
      (name "deadline-after-ns")
      (definition-locus "lib/time.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "raw clock/timezone observations plus pure Lisp policy")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/time.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 01101011)
      (name "internet-time-sync")
      (definition-locus "lib/time.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "raw clock/timezone observations plus pure Lisp policy")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/time.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 01101100)
      (name "map-empty")
      (definition-locus "lib/persistent-map.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp persistent data-structure algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/persistent-map.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 01101101)
      (name "map-get")
      (definition-locus "lib/persistent-map.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp persistent data-structure algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/persistent-map.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 01101110)
      (name "map-insert")
      (definition-locus "lib/persistent-map.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp persistent data-structure algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/persistent-map.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 01101111)
      (name "map-contains?")
      (definition-locus "lib/persistent-map.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp persistent data-structure algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/persistent-map.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 01110000)
      (name "map->list")
      (definition-locus "lib/persistent-map.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp persistent data-structure algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/persistent-map.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 01110001)
      (name "vec-empty")
      (definition-locus "lib/persistent-vector.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp persistent data-structure algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/persistent-vector.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 01110010)
      (name "vec-conj")
      (definition-locus "lib/persistent-vector.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp persistent data-structure algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/persistent-vector.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 01110011)
      (name "vec-count")
      (definition-locus "lib/persistent-vector.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp persistent data-structure algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/persistent-vector.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 01110100)
      (name "vec-nth")
      (definition-locus "lib/persistent-vector.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp persistent data-structure algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/persistent-vector.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 01110101)
      (name "vec->list")
      (definition-locus "lib/persistent-vector.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp persistent data-structure algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/persistent-vector.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 01110110)
      (name "vec-from-list")
      (definition-locus "lib/persistent-vector.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp persistent data-structure algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/persistent-vector.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 01110111)
      (name "is-fact?")
      (definition-locus "lib/knowledge.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp knowledge/reasoning algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/knowledge.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 01111000)
      (name "describe")
      (definition-locus "lib/knowledge.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp knowledge/reasoning algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/knowledge.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 01111001)
      (name "collect-facts-about")
      (definition-locus "lib/knowledge.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp knowledge/reasoning algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/knowledge.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 01111010)
      (name "contains-atom?")
      (definition-locus "lib/knowledge.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp knowledge/reasoning algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/knowledge.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 01111011)
      (name "forward-in")
      (definition-locus "lib/knowledge.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp knowledge/reasoning algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/knowledge.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 01111100)
      (name "reason-in")
      (definition-locus "lib/knowledge.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp knowledge/reasoning algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/knowledge.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 01111101)
      (name "check-conflict")
      (definition-locus "lib/knowledge.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp knowledge/reasoning algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/knowledge.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 01111110)
      (name "module-known?")
      (definition-locus "lib/knowledge.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp knowledge/reasoning algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/knowledge.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 01111111)
      (name "module-clauses-now")
      (definition-locus "lib/knowledge.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp knowledge/reasoning algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/knowledge.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10000000)
      (name "prove-goal")
      (definition-locus "lib/reason.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp knowledge/reasoning algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/reason.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10000001)
      (name "prove-goals")
      (definition-locus "lib/reason.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp knowledge/reasoning algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/reason.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10000010)
      (name "explain-proof")
      (definition-locus "lib/reason.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp knowledge/reasoning algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/reason.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10000011)
      (name "source-of")
      (definition-locus "lib/reason.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp knowledge/reasoning algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/reason.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10000100)
      (name "provenance")
      (definition-locus "lib/reason.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp knowledge/reasoning algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/reason.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10000101)
      (name "reason")
      (definition-locus "lib/reason.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp knowledge/reasoning algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/reason.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10000110)
      (name "reason-explain")
      (definition-locus "lib/reason.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp knowledge/reasoning algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/reason.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10000111)
      (name "unify")
      (definition-locus "lib/unify.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp unification algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/unify.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10001000)
      (name "logic-var")
      (definition-locus "lib/unify.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp unification algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/unify.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10001001)
      (name "var?")
      (definition-locus "lib/unify.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp unification algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/unify.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10001010)
      (name "apply-subst")
      (definition-locus "lib/unify.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp unification algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/unify.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10001011)
      (name "walk")
      (definition-locus "lib/unify.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp unification algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/unify.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10001100)
      (name "occurs-check")
      (definition-locus "lib/unify.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp unification algorithms")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/unify.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10001101)
      (name "claim?")
      (definition-locus "lib/epistemic.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp epistemic data/operations")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/epistemic.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10001110)
      (name "claim-statement")
      (definition-locus "lib/epistemic.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp epistemic data/operations")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/epistemic.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10001111)
      (name "claim-review")
      (definition-locus "lib/epistemic.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp epistemic data/operations")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/epistemic.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10010000)
      (name "evidence?")
      (definition-locus "lib/epistemic.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp epistemic data/operations")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/epistemic.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10010001)
      (name "evidence-method")
      (definition-locus "lib/epistemic.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp epistemic data/operations")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/epistemic.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10010010)
      (name "evidence-outcome")
      (definition-locus "lib/epistemic.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp epistemic data/operations")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/epistemic.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10010011)
      (name "observation?")
      (definition-locus "lib/epistemic.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp epistemic data/operations")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/epistemic.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10010100)
      (name "observation-statement")
      (definition-locus "lib/epistemic.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp epistemic data/operations")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/epistemic.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10010101)
      (name "intent?")
      (definition-locus "lib/epistemic.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp epistemic data/operations")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/epistemic.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10010110)
      (name "intent-goal")
      (definition-locus "lib/epistemic.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp epistemic data/operations")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/epistemic.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10010111)
      (name "supporting-evidence")
      (definition-locus "lib/epistemic.lisp")
      (class library-identity)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "pure Lisp epistemic data/operations")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/epistemic.lisp")
      (notes "Library semantic identity with Lisp implementation; SID retention is API-budget policy, not backend necessity."))
    (row
      (sid 10011000)
      (name "identity")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "lambda identity")
      (sid-reclaim-candidate? yes)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 10011001)
      (name "gensym")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "mono-ns plus string/symbol construction")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
    (row
      (sid 10011010)
      (name "and")
      (definition-locus "lib/core.lisp")
      (class syntax-sugar)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? yes)
      (lower-mechanism "cond")
      (sid-reclaim-candidate? yes)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Current macro expansion provides behavior from lower identities; strong primitive/SID necessity review candidate."))
    (row
      (sid 10011011)
      (name "or")
      (definition-locus "lib/core.lisp")
      (class syntax-sugar)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? yes)
      (lower-mechanism "cond")
      (sid-reclaim-candidate? yes)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Current macro expansion provides behavior from lower identities; strong primitive/SID necessity review candidate."))
    (row
      (sid 10011100)
      (name "let")
      (definition-locus "lib/core.lisp")
      (class syntax-sugar)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? yes)
      (lower-mechanism "lambda/define")
      (sid-reclaim-candidate? yes)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Current macro expansion provides behavior from lower identities; strong primitive/SID necessity review candidate."))
    (row
      (sid 10011101)
      (name "let*")
      (definition-locus "lib/core.lisp")
      (class syntax-sugar)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? yes)
      (lower-mechanism "lambda/define")
      (sid-reclaim-candidate? yes)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Current macro expansion provides behavior from lower identities; strong primitive/SID necessity review candidate."))
    (row
      (sid 10011110)
      (name "->")
      (definition-locus "lib/core.lisp")
      (class syntax-sugar)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? yes)
      (lower-mechanism "macro expansion plus ordinary application")
      (sid-reclaim-candidate? yes)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Current macro expansion provides behavior from lower identities; strong primitive/SID necessity review candidate."))
    (row
      (sid 10011111)
      (name "->>")
      (definition-locus "lib/core.lisp")
      (class syntax-sugar)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? yes)
      (lower-mechanism "macro expansion plus ordinary application")
      (sid-reclaim-candidate? yes)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Current macro expansion provides behavior from lower identities; strong primitive/SID necessity review candidate."))
    (row
      (sid 10100000)
      (name "json-parse")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "JSON decoding mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Backend JSON parser today. Derivability must be re-audited because current language now has codepoint/string bridges."))
    (row
      (sid 10100001)
      (name "sha256-hex")
      (definition-locus "crates/my-lisp/src/eval/builtins.rs")
      (class backend-value-mechanism)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "SHA-256 digest mechanism")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "crates/my-lisp/src/eval/builtins.rs")
      (notes "Digest computation is backend-provided today; no claim of eternal primitiveness."))
    (row
      (sid 10100010)
      (name "process-run")
      (definition-locus "lib/process.lisp;crates/my-lisp-host/src/process_raw.rs")
      (class host-wrapper-lisp-owned)
      (backend-required-now? yes)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "process-run-raw")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "knowledge/semantic-ownership.lisp;lib/process.lisp;crates/my-lisp-host/src/process_raw.rs")
      (notes "Public meaning is Lisp-owned; only the raw physical capability is host-owned."))
    (row
      (sid 10100011)
      (name "tcp-read")
      (definition-locus "lib/tcp.lisp;crates/my-lisp-host/src/lib.rs")
      (class host-wrapper-lisp-owned)
      (backend-required-now? yes)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "tcp-read-raw")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "knowledge/semantic-ownership.lisp;lib/tcp.lisp;crates/my-lisp-host/src/lib.rs")
      (notes "Public meaning is Lisp-owned; only the raw physical capability is host-owned."))
    (row
      (sid 10100100)
      (name "tcp-write")
      (definition-locus "lib/tcp.lisp;crates/my-lisp-host/src/lib.rs")
      (class host-wrapper-lisp-owned)
      (backend-required-now? yes)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "tcp-write-raw")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "knowledge/semantic-ownership.lisp;lib/tcp.lisp;crates/my-lisp-host/src/lib.rs")
      (notes "Public meaning is Lisp-owned; only the raw physical capability is host-owned."))
    (row
      (sid 10100101)
      (name "tcp-listen")
      (definition-locus "lib/tcp.lisp;crates/my-lisp-host/src/lib.rs")
      (class host-wrapper-lisp-owned)
      (backend-required-now? yes)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "tcp-listen-raw")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "knowledge/semantic-ownership.lisp;lib/tcp.lisp;crates/my-lisp-host/src/lib.rs")
      (notes "Public meaning is Lisp-owned; only the raw physical capability is host-owned."))
    (row
      (sid 10100110)
      (name "read-file")
      (definition-locus "lib/fs.lisp;crates/my-lisp-host/src/lib.rs")
      (class host-wrapper-lisp-owned)
      (backend-required-now? yes)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "read-file-bytes/raw filesystem capability")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "knowledge/semantic-ownership.lisp;lib/fs.lisp;crates/my-lisp-host/src/lib.rs")
      (notes "Public meaning is Lisp-owned; only the raw physical capability is host-owned."))
    (row
      (sid 10100111)
      (name "write-file")
      (definition-locus "lib/fs.lisp;crates/my-lisp-host/src/lib.rs")
      (class host-wrapper-lisp-owned)
      (backend-required-now? yes)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "write-file-bytes/raw filesystem capability")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "knowledge/semantic-ownership.lisp;lib/fs.lisp;crates/my-lisp-host/src/lib.rs")
      (notes "Public meaning is Lisp-owned; only the raw physical capability is host-owned."))
    (row
      (sid 10101000)
      (name "invoke")
      (definition-locus "crates/wsm-kernel-host/src/lib.rs;crates/wsm-native-result-types/tests/four_real_kernels.rs")
      (class backend-core-candidate)
      (backend-required-now? yes)
      (pure-lisp-definition-now? no)
      (macro-expansion-now? no)
      (lower-mechanism "shared kernel-host/C-ABI invocation mechanism")
      (sid-reclaim-candidate? no)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "#747;docs/architecture/PRIMITIVE-ADMISSION-AUDIT-747.md;crates/wsm-native-result-types/tests/four_real_kernels.rs")
      (notes "Cross-kernel invocation identity has a four-real-kernel witness; payload/result semantics remain kernel-private."))
    (row
      (sid 10101001)
      (name "binary")
      (definition-locus "lib/core.lisp")
      (class lisp-derived-function)
      (backend-required-now? no)
      (pure-lisp-definition-now? yes)
      (macro-expansion-now? no)
      (lower-mechanism "my-lisp numeric/bit construction")
      (sid-reclaim-candidate? unknown)
      (irreducibility-proved? no)
      (confidence high)
      (evidence "lib/core.lisp")
      (notes "Already executable as Lisp definition; cannot be called primitive merely because it owns a SID."))
  ))
