; semantic-lineage-core-v1.lisp — bounded first lineage inventory for #1113.
; This is audit data, not a semantic authority table. It records provenance,
; current law status, and known uncertainty so implementation artifacts cannot
; silently masquerade as language design.
;
; Authority remains the canonical function table / registry:
;   lib/surface/semantic-registry.lisp
;
; Classification vocabulary follows #1113:
;   mccarthy-inspired | my-lisp-native | deliberate-departure
;   compatibility-only | substrate-projection | historical-only | unresolved
;
; Every row is intentionally evidence-linked. "unresolved" means the project
; must not treat the current implementation shape as final language law.

(semantic-lineage/1
  (issue 1113)
  (as-of "2026-09-23")
  (authority "lib/surface/semantic-registry.lisp")
  (status "bounded-first-mandatory-core-row-set")
  (rows

    (row
      (concept s-expression)
      (identity ())
      (surface "S-expression")
      (lineage mccarthy-inspired)
      (historical-reference "McCarthy Lisp S-expression model")
      (my-lisp-rationale "Portable symbolic data substrate retained as the language's basic expression/data representation.")
      (observable-law "Programs and quoted data are representable as Lisp-readable symbolic structure.")
      (current-witness "crates/my-lisp/src/parser.rs;tests/fixtures/conformance.lisp")
      (deliberate-differences "my-lisp adds exact SID8 function identities and richer explicit result domains downstream.")
      (substrate-assumptions none)
      (portability-risk low)
      (owner-issue 1113)
      (status current))

    (row
      (concept atom/pair-model)
      (identity 00000010)
      (surface atom)
      (lineage mccarthy-inspired)
      (historical-reference "McCarthy atom/structure distinction")
      (my-lisp-rationale "Retains an explicit structural distinction while current predicate/classifier representation is being re-separated under #218.")
      (observable-law "Atomic values and pair-shaped values are distinguishable by a language-owned observation.")
      (current-witness "tests/fixtures/semantic/atom-1bit-v1.lisp;tests/fixtures/semantic/eq-1bit-v1.lisp")
      (deliberate-differences "Current #218 treats predicate questions and richer structural classifiers as distinct concepts; final predicate answer representation is not yet frozen.")
      (substrate-assumptions none)
      (portability-risk medium)
      (owner-issue 218)
      (status current-with-open-representation-review))

    (row
      (concept quote)
      (identity 00000001)
      (surface quote)
      (lineage mccarthy-inspired)
      (historical-reference "McCarthy quote")
      (my-lisp-rationale "Preserves the evaluation boundary between code and literal symbolic data.")
      (observable-law "Quoted structure is returned as data without ordinary evaluation.")
      (current-witness "crates/my-lisp/tests/mccarthy.rs;tests/fixtures/conformance.lisp")
      (deliberate-differences "None currently ratified beyond SID8 transport representation.")
      (substrate-assumptions "reader/evaluator implementation")
      (portability-risk low)
      (owner-issue 1113)
      (status current))

    (row
      (concept cons)
      (identity 00000100)
      (surface cons)
      (lineage mccarthy-inspired)
      (historical-reference "McCarthy cons")
      (my-lisp-rationale "Pair construction remains a basic portable data operation.")
      (observable-law "Construct a pair from two values.")
      (current-witness "crates/my-lisp/tests/mccarthy.rs;tests/fixtures/conformance.lisp")
      (deliberate-differences "Exact bare SID8 is the function identity after resolution.")
      (substrate-assumptions none)
      (portability-risk low)
      (owner-issue 1113)
      (status current))

    (row
      (concept car)
      (identity 00000101)
      (surface car)
      (lineage mccarthy-inspired)
      (historical-reference "McCarthy car")
      (my-lisp-rationale "Pair projection remains a basic portable data operation.")
      (observable-law "Project the first component of a valid pair.")
      (current-witness "crates/my-lisp/tests/mccarthy.rs;tests/fixtures/conformance.lisp")
      (deliberate-differences "Errors and explicit failure observations are my-lisp boundary policy.")
      (substrate-assumptions none)
      (portability-risk low)
      (owner-issue 1113)
      (status current))

    (row
      (concept cdr)
      (identity 00000110)
      (surface cdr)
      (lineage mccarthy-inspired)
      (historical-reference "McCarthy cdr")
      (my-lisp-rationale "Pair-tail projection remains a basic portable data operation.")
      (observable-law "Project the second component/tail of a valid pair.")
      (current-witness "crates/my-lisp/tests/mccarthy.rs;tests/fixtures/conformance.lisp")
      (deliberate-differences "Dotted-pair reader support is an implementation-independent language witness.")
      (substrate-assumptions none)
      (portability-risk low)
      (owner-issue 1113)
      (status current))

    (row
      (concept cond)
      (identity 00000111)
      (surface cond)
      (lineage deliberate-departure)
      (historical-reference "McCarthy conditional control")
      (my-lisp-rationale "Core4 canonical control uses explicit result equality and separates structural/richer-domain dispatch from generic value truthiness.")
      (observable-law "Canonical Core4 conditional dispatch consumes explicitly matched query/result pairs; historical two-part behavior is profile-scoped compatibility.")
      (current-witness "tests/fixtures/semantic/cond-2part-v1.lisp;contracts/canon-laws-v2-contract.lisp")
      (deliberate-differences "Generic arbitrary-value truth coercion is not the canonical control authority.")
      (substrate-assumptions "profile-specific evaluator mechanics may execute the law")
      (portability-risk medium)
      (owner-issue 217)
      (status current-with-legacy-profile))

    (row
      (concept lambda/application/recursion)
      (identity 00001000)
      (surface lambda)
      (lineage mccarthy-inspired)
      (historical-reference "McCarthy lambda/application model")
      (my-lisp-rationale "Lexical closure, application order, and recursion are portable evaluator laws independent of Rust.")
      (observable-law "Lambda captures environment, binds arguments, evaluates body, and supports recursive definitions within admitted limits.")
      (current-witness "crates/my-lisp/tests/macro_derivation.rs;crates/my-lisp/tests/stack_safety.rs;tests/fixtures/conformance.lisp")
      (deliberate-differences "Resource limits and structured errors are explicit my-lisp policy.")
      (substrate-assumptions "evaluator or equivalent execution mechanism")
      (portability-risk low)
      (owner-issue 1113)
      (status current))

    (row
      (concept define)
      (identity 00001001)
      (surface define)
      (lineage my-lisp-native)
      (historical-reference "Lisp-family top-level binding precedent")
      (my-lisp-rationale "Current Canon resolves definitions through the language's own function identity and binding model.")
      (observable-law "A definition installs a name/function binding in the current program environment.")
      (current-witness "tests/fixtures/process-load-witness.lisp;crates/my-lisp/tests/meta_eval_advice_taker.rs")
      (deliberate-differences "Bare SID8 source notation is part of current my-lisp transport identity, not a second name-based authority.")
      (substrate-assumptions "environment storage")
      (portability-risk medium)
      (owner-issue 1113)
      (status current))

    (row
      (concept empty-list)
      (identity 00000000)
      (surface "()")
      (lineage mccarthy-inspired)
      (historical-reference "Lisp empty list / NIL structural value")
      (my-lisp-rationale "Retained as Canon-0 ground value; it is not globally predeclared as FALSE.")
      (observable-law "Represents the canonical empty list and Canon-0/no-produced-knowledge where explicitly defined by a law.")
      (current-witness "crates/my-lisp/tests/mccarthy.rs;tests/fixtures/conformance.lisp")
      (deliberate-differences "Current #220 explicitly forbids using () as an undocumented universal false value.")
      (substrate-assumptions none)
      (portability-risk low)
      (owner-issue 220)
      (status current))

    (row
      (concept sid-function-identity-space)
      (identity "00000000..11111111")
      (surface "bare 8-bit SID")
      (lineage my-lisp-native)
      (historical-reference "None; this is a my-lisp identity encoding experiment.")
      (my-lisp-rationale "One exact 8-bit function-identity space lets independent substrates carry the same operation identity without copying host semantic tables.")
      (observable-law "After function resolution, semantic function identity is exactly one bare Sid8 token; quoted/string/decimal/host-name aliases are not equivalent identities.")
      (current-witness "tests/fixtures/bare-sid-literal-v1.lisp;tests/fixtures/semantic-registry-self-hosted-witness.lisp")
      (deliberate-differences "Identity encoding is deliberately separate from machine numeric convenience.")
      (substrate-assumptions "substates may pack the byte differently but must preserve identity")
      (portability-risk medium)
      (owner-issue 1167)
      (status current))

    (row
      (concept canon-function-table-authority)
      (identity ())
      (surface "function-table / Canon")
      (lineage my-lisp-native)
      (historical-reference "Architecture synthesized for my-lisp")
      (my-lisp-rationale "Semantic identity, meaning, law, and admitted mechanism metadata belong to one language-owned table rather than any executor.")
      (observable-law "Surface namespace names resolve to one SID and downstream mechanisms cannot mint language meaning.")
      (current-witness "lib/surface/semantic-registry.lisp;tests/fixtures/semantic-registry-self-hosted-witness.lisp;contracts/semantic-ownership-audit-733.lisp")
      (deliberate-differences "Generated tables are projections and evidence artifacts, not semantic authority.")
      (substrate-assumptions "none for semantic authority; executors are downstream mechanisms")
      (portability-risk medium)
      (owner-issue 997)
      (status current))

    (row
      (concept binary-function)
      (identity "registry-row-for-binary")
      (surface binary)
      (lineage my-lisp-native)
      (historical-reference "None; exact binary function is project-native.")
      (my-lisp-rationale "The language owns binary/SID8 formation and manipulation as Lisp data rather than deriving semantic identity from a host integer.")
      (observable-law "Binary/SID8 operations preserve width, leading zeroes, and exact identity category.")
      (current-witness "tests/fixtures/bare-sid-literal-v1.lisp;tests/fixtures/u8-native-witness.lisp")
      (deliberate-differences "Machine u8 packing is substrate representation only.")
      (substrate-assumptions "host may pack bits as u8 internally")
      (portability-risk medium)
      (owner-issue 1110)
      (status current-with-active-followups))

    (row
      (concept error-observation)
      (identity "error-vocabulary-identities")
      (surface "named error/result observations")
      (lineage my-lisp-native)
      (historical-reference "Error categories are project-defined observable behavior.")
      (my-lisp-rationale "Error meaning is expressed as language data/categories; Rust ErrorKind names are implementation mechanisms unless explicitly ratified.")
      (observable-law "Invalid operations produce stable named observations without importing host enum identity.")
      (current-witness "tests/fixtures/error-observation-v1.lisp;crates/my-lisp/tests/error_kind_vocabulary_is_closed.rs")
      (deliberate-differences "Host error taxonomy may differ internally while the language observation stays stable.")
      (substrate-assumptions "host-specific failure transport")
      (portability-risk medium)
      (owner-issue 1104)
      (status current-with-lineage-review))

    (row
      (concept predicate-answer-representation)
      (identity "cross-cutting")
      (surface "? predicates")
      (lineage unresolved)
      (historical-reference "Lisp-family predicate conventions")
      (my-lisp-rationale "ATOM and EQ now use the shared exact one-bit predicate law; richer classifiers remain separate observations.")
      (observable-law "Current core predicates are witnessed by Lisp-owned exact-bit contracts rather than host truth carriers.")
      (current-witness "contracts/structural-observation-contract.lisp;issue-218")
      (deliberate-differences "Classifier records remain separate from the one-bit predicate answer domain.")
      (substrate-assumptions none)
      (portability-risk high)
      (owner-issue 218)
      (status current))

    (row
      (concept mathematical-decisions)
      (identity "comparison/exact-q domain")
      (surface "<, >, =, <=, >=")
      (lineage my-lisp-native)
      (historical-reference "Arithmetic comparison is inherited in broad concept but result representation is project-defined.")
      (my-lisp-rationale "Mathematical YES/NO belongs to the exact numeric domain and is separate from structural predicates and reasoning statuses.")
      (observable-law "Numerical comparison follows the explicit mathematical result contract and is not generic value truth.")
      (current-witness "contracts/exact-q-binary-contract.lisp;tests/fixtures/conformance.lisp")
      (deliberate-differences "Exact-Q representation and control consumption are explicitly separated from generic truthiness.")
      (substrate-assumptions "arbitrary-precision numeric mechanism")
      (portability-risk medium)
      (owner-issue 216)
      (status current))

    (row
      (concept richer-reasoning-results)
      (identity "reasoning-result-domain")
      (surface "proved/unknown/partial/... where admitted")
      (lineage my-lisp-native)
      (historical-reference "Prior multi-valued logic work is historical/experimental.")
      (my-lisp-rationale "Reasoning evidence, multiplicity, provenance, and optional logic projection are separate from basic predicate truth.")
      (observable-law "No-evidence remains distinguishable from explicit negative evidence; richer statuses require their own named contracts.")
      (current-witness "lib/reason.lisp;lib/result-status.lisp;contracts/island-compat-contract.lisp")
      (deliberate-differences "Historical pyramidal logic is optional rather than universal foundation.")
      (substrate-assumptions "Prolog/Datalog/CLIPS/Common Lisp may provide native observations")
      (portability-risk high)
      (owner-issue 219)
      (status current-with-optional-logic))

    (row
      (concept mechanism-selection/island-dispatch)
      (identity "post-semantics mechanism layer")
      (surface "invoke / mechanism selector")
      (lineage my-lisp-native)
      (historical-reference "Architecture synthesized for my-lisp's multi-kernel model.")
      (my-lisp-rationale "Lisp decides admitted mechanisms and lowering after semantic resolution; executors only execute opaque requests.")
      (observable-law "Replacing an island/mechanism does not change unrelated Lisp meaning or SID identity.")
      (current-witness "contracts/semantic-coordinate-matrix-845.lisp;tests/fixtures/mechanism-selector-1047-witness.lisp;tests/fixtures/island-lowering-1048-witness.lisp")
      (deliberate-differences "Island-native syntax, truth, multiplicity, and rule systems remain substrate-local.")
      (substrate-assumptions "Rust/C/CPU/Common Lisp/Prolog/CLIPS/Datalog execution mechanisms")
      (portability-risk high)
      (owner-issue 997)
      (status current-with-open-verticals))

  ))
