;; Silent-fallback inventory (#2134).
;; Baseline for scripts/check-silent-fallback-classes.py: a known site passes,
;; a NEW unnamed site fails. Regenerate with --emit-inventory.
;; Classes: total-serializer-fallback | implicit-default-flag |
;;          fail-fast-hides-suites | silent-regeneration.
(silent-fallback-inventory
  (site (class "fail-fast-hides-suites") (file ".github/workflows/ci.yml") (key "fail-fast-hides-suites|.github/workflows/ci.yml|cargo test --workspace") (line "278"))
  (site (class "fail-fast-hides-suites") (file ".github/workflows/full-nightly.yml") (key "fail-fast-hides-suites|.github/workflows/full-nightly.yml|run: cargo test --workspace") (line "34"))
  (site (class "implicit-default-flag") (file "crates/sens/src/environment.rs") (key "implicit-default-flag|crates/sens/src/environment.rs|pub fn is_tcp_connect_allowed(&self, host: &str, port: u16) -> bool {") (line "174"))
  (site (class "implicit-default-flag") (file "crates/sens/src/environment.rs") (key "implicit-default-flag|crates/sens/src/environment.rs|pub fn is_tcp_listen_allowed(&self, address: &str, port: u16) -> bool {") (line "183"))
  (site (class "implicit-default-flag") (file "crates/sens/tests/semantic_authority.rs") (key "implicit-default-flag|crates/sens/tests/semantic_authority.rs|fn alist_flag(entries: &[Expr], key: &str) -> bool {") (line "103"))
  (site (class "implicit-default-flag") (file "crates/sens/tests/witness_authority.rs") (key "implicit-default-flag|crates/sens/tests/witness_authority.rs|fn alist_flag(entries: &[Expr], key: &str) -> bool {") (line "58"))
  (site (class "silent-regeneration") (file "lib/generated/meta-semantic-registry.lisp") (key "silent-regeneration|lib/generated/meta-semantic-registry.lisp|((00000010 entry) () (00000001 ()))") (line "681"))
  (site (class "silent-regeneration") (file "lib/generated/meta-semantic-registry.lisp") (key "silent-regeneration|lib/generated/meta-semantic-registry.lisp|((00000010 entry) (0) (00101111 entry))") (line "682"))
  (site (class "silent-regeneration") (file "scripts/generate-function-table.lisp") (key "silent-regeneration|scripts/generate-function-table.lisp|((00000010 sections) () (00000001 ()))") (line "52"))
  (site (class "silent-regeneration") (file "scripts/generate-function-table.lisp") (key "silent-regeneration|scripts/generate-function-table.lisp|((00000010 sections) (1) (00000001 ()))") (line "53"))
  (site (class "silent-regeneration") (file "scripts/generate-function-table.lisp") (key "silent-regeneration|scripts/generate-function-table.lisp|((00000010 rows) () (00000001 ()))") (line "63"))
  (site (class "silent-regeneration") (file "scripts/generate-function-table.lisp") (key "silent-regeneration|scripts/generate-function-table.lisp|((00000010 rows) (1) (00000001 ()))") (line "64"))
  (site (class "silent-regeneration") (file "scripts/generate-function-table.lisp") (key "silent-regeneration|scripts/generate-function-table.lisp|((00000010 row) () \"()\")") (line "72"))
  (site (class "silent-regeneration") (file "scripts/generate-function-table.lisp") (key "silent-regeneration|scripts/generate-function-table.lisp|((00000010 row) (1) \"()\")") (line "73"))
  (site (class "silent-regeneration") (file "scripts/generate-function-table.lisp") (key "silent-regeneration|scripts/generate-function-table.lisp|((00000010 rows) () (00000001 ()))") (line "89"))
  (site (class "silent-regeneration") (file "scripts/generate-function-table.lisp") (key "silent-regeneration|scripts/generate-function-table.lisp|((00000010 rows) (1) (00000001 ()))") (line "90"))
  (site (class "silent-regeneration") (file "scripts/generate-function-table.lisp") (key "silent-regeneration|scripts/generate-function-table.lisp|((00000010 row) () \"()\")") (line "98"))
  (site (class "silent-regeneration") (file "scripts/generate-function-table.lisp") (key "silent-regeneration|scripts/generate-function-table.lisp|((00000010 row) (1) \"()\")") (line "99"))
  (site (class "silent-regeneration") (file "scripts/generate-function-table.lisp") (key "silent-regeneration|scripts/generate-function-table.lisp|((00000010 surfaces) () (00000001 ()))") (line "138"))
  (site (class "silent-regeneration") (file "scripts/generate-function-table.lisp") (key "silent-regeneration|scripts/generate-function-table.lisp|((00000010 surfaces) (1) (00000001 ()))") (line "139"))
  (site (class "silent-regeneration") (file "scripts/generate-function-table.lisp") (key "silent-regeneration|scripts/generate-function-table.lisp|((00000010 surface-entry) () (00000001 ()))") (line "146"))
  (site (class "silent-regeneration") (file "scripts/generate-function-table.lisp") (key "silent-regeneration|scripts/generate-function-table.lisp|((00000010 surface-entry) (1) (00000001 ()))") (line "147"))
  (site (class "silent-regeneration") (file "scripts/generate-functions-md.lisp") (key "silent-regeneration|scripts/generate-functions-md.lisp|((00000010 forms) () (00000001 ()))") (line "34"))
  (site (class "silent-regeneration") (file "scripts/generate-functions-md.lisp") (key "silent-regeneration|scripts/generate-functions-md.lisp|((00000010 items) (0) (00001100 1 (count-items (00000110 items))))") (line "49"))
  (site (class "silent-regeneration") (file "scripts/generate-functions-md.lisp") (key "silent-regeneration|scripts/generate-functions-md.lisp|((00000010 (00000110 names)) () (str+ \"`\" (00000101 names) \"`\"))") (line "84"))
  (site (class "silent-regeneration") (file "scripts/generate-functions-md.lisp") (key "silent-regeneration|scripts/generate-functions-md.lisp|((00000010 files) (0) (replace-all (replace-section doc (00000101 files)) (00000110 files)))") (line "131"))
  (site (class "silent-regeneration") (file "scripts/generate-functions-md.lisp") (key "silent-regeneration|scripts/generate-functions-md.lisp|((00100010 current generated) (1) (01001000 \"docs/FUNCTIONS.md sections are current\"))") (line "146"))
  (site (class "silent-regeneration") (file "scripts/generate-meta-semantic-registry.lisp") (key "silent-regeneration|scripts/generate-meta-semantic-registry.lisp|((00000010 surface) () ())") (line "24"))
  (site (class "silent-regeneration") (file "scripts/generate-meta-semantic-registry.lisp") (key "silent-regeneration|scripts/generate-meta-semantic-registry.lisp|((00000010 surface) (1) ())") (line "25"))
  (site (class "silent-regeneration") (file "scripts/generate-meta-semantic-registry.lisp") (key "silent-regeneration|scripts/generate-meta-semantic-registry.lisp|((00000010 entry) () (00000001 ()))") (line "104"))
  (site (class "silent-regeneration") (file "scripts/generate-meta-semantic-registry.lisp") (key "silent-regeneration|scripts/generate-meta-semantic-registry.lisp|((00000010 entry) (0) (00101111 entry))") (line "105"))
  (site (class "silent-regeneration") (file "scripts/generate-rust-function-signatures.lisp") (key "silent-regeneration|scripts/generate-rust-function-signatures.lisp|((00000010 (00101101 key (00000110 row))) () (00000001 ()))") (line "52"))
  (site (class "silent-regeneration") (file "scripts/generate-rust-profile-mechanism-routes.lisp") (key "silent-regeneration|scripts/generate-rust-profile-mechanism-routes.lisp|((00000010 sections) () (00000001 ()))") (line "24"))
  (site (class "silent-regeneration") (file "scripts/generate-uk-surface-audit.lisp") (key "silent-regeneration|scripts/generate-uk-surface-audit.lisp|((00000010 rows) () (00000001 ()))") (line "71"))
  (site (class "silent-regeneration") (file "scripts/generate-uk-surface-audit.lisp") (key "silent-regeneration|scripts/generate-uk-surface-audit.lisp|((00000010 sections) () (00000001 ()))") (line "83"))
  (site (class "silent-regeneration") (file "scripts/generate-uk-surface-audit.lisp") (key "silent-regeneration|scripts/generate-uk-surface-audit.lisp|((00000010 sections) (1) (00000001 ()))") (line "84"))
  (site (class "silent-regeneration") (file "scripts/generate-uk-surface-audit.lisp") (key "silent-regeneration|scripts/generate-uk-surface-audit.lisp|((00000010 candidate-section) () (00000001 ()))") (line "92"))
  (site (class "silent-regeneration") (file "scripts/generate-uk-surface-audit.lisp") (key "silent-regeneration|scripts/generate-uk-surface-audit.lisp|((00000010 candidate-section) (1) (00000001 ()))") (line "93"))
  (site (class "silent-regeneration") (file "scripts/generate-uk-surface-audit.lisp") (key "silent-regeneration|scripts/generate-uk-surface-audit.lisp|((00000010 rows) () (00000001 ()))") (line "99"))
  (site (class "silent-regeneration") (file "scripts/generate-uk-surface-audit.lisp") (key "silent-regeneration|scripts/generate-uk-surface-audit.lisp|((00000010 rows) (1) (00000001 ()))") (line "100"))
  (site (class "silent-regeneration") (file "scripts/generate-uk-surface-audit.lisp") (key "silent-regeneration|scripts/generate-uk-surface-audit.lisp|((00000010 candidate) () (00000001 needs-research))") (line "129"))
  (site (class "silent-regeneration") (file "scripts/generate-uk-surface-audit.lisp") (key "silent-regeneration|scripts/generate-uk-surface-audit.lisp|((00000010 candidate) (1) (00000001 needs-research))") (line "130"))
  (site (class "silent-regeneration") (file "scripts/generate-uk-surface-audit.lisp") (key "silent-regeneration|scripts/generate-uk-surface-audit.lisp|((00000010 candidate) () (00000001 —))") (line "136"))
  (site (class "silent-regeneration") (file "scripts/generate-uk-surface-audit.lisp") (key "silent-regeneration|scripts/generate-uk-surface-audit.lisp|((00000010 candidate) (1) (00000001 —))") (line "137"))
  (site (class "silent-regeneration") (file "scripts/generate-uk-surface-audit.lisp") (key "silent-regeneration|scripts/generate-uk-surface-audit.lisp|((00000010 candidate) () (00000001 no-staging-evidence))") (line "142"))
  (site (class "silent-regeneration") (file "scripts/generate-uk-surface-audit.lisp") (key "silent-regeneration|scripts/generate-uk-surface-audit.lisp|((00000010 candidate) (1) (00000001 no-staging-evidence))") (line "143"))
  (site (class "silent-regeneration") (file "scripts/generate-uk-surface-audit.lisp") (key "silent-regeneration|scripts/generate-uk-surface-audit.lisp|((00000010 candidate) () (00000001 needs-research))") (line "153"))
  (site (class "silent-regeneration") (file "scripts/generate-uk-surface-audit.lisp") (key "silent-regeneration|scripts/generate-uk-surface-audit.lisp|((00000010 candidate) (1) (00000001 needs-research))") (line "154"))
  (site (class "silent-regeneration") (file "scripts/generate-uk-surface-audit.lisp") (key "silent-regeneration|scripts/generate-uk-surface-audit.lisp|((00000010 candidate) () (00000001 missing))") (line "162"))
  (site (class "total-serializer-fallback") (file "crates/sens/src/value.rs") (key "total-serializer-fallback|crates/sens/src/value.rs|_ => render(value, true),") (line "852"))
)
