(core1-generation-manifest/1
  ((generation . s0)
   (role . typed-sid8-historical-physical-seed)
   (repository . juv4uk/mccarthy-eval)
   (commit . "79f2f38f2a8da22a5bbcb39312da5f726ab2471f")
   (source-path . "mccarthy-kernel.s")
   (source-sha256 . "edeba0c40d32a828b1a468db211c923347d93911d9ffff6279c7324cf08d092d")
   (binary-sha256 . "c34c972720c16511f436d93b28b0014f0daf142e4ac35c266ba9c7e6ea97561a")
   (semantic-authority . no)
   (status . witnessed))

  ((generation . s1)
   (role . lisp-owned-bootstrap)
   (repository . juv4uk/my-lisp)
   (path . "lib/core1.lisp")
   (source-sha256 . "647e6de1b15d22a66bd4c47e2e8869962824c36ec043864866e40b3fc5f3e3b1")
   (executed-by . s0)
   (mechanism . historical-function-funarg-plus-zero-copy-lisp-owned-dispatch)
   (witnesses .
     ((historical-function-funarg . "HISTORICAL-FUNARG")
      (core1-lambda-representation . "T")
      (closure-capture . "(A . B)")
      (self-recursive-definition . "C")
      (unsupported-modern-identity .
        ((sid . 01001111)
         (surface . VECTOR)
         (observation . "(C1-ERROR UNBOUND VECTOR)")))))
   (status . witnessed))

  ((generation . s2)
   (role . lisp-authored-compiler-source)
   (repository . juv4uk/wsm-my-lisp)
   (commit . "a6bd9747196f2d676ab6883cbb4b84c7fcfc6947")
   (path . "lib/compiler.lisp")
   (source-sha256 . "b401cd09a0040c64668aa98369cad4932c06767343de5214a0eae2dae3ce6cce")
   (executed-by . s1-on-s0)
   (witnesses .
     ((atom-lowering . "(var FOO)")
      (primitive-lowering . "(prim cons ((quote A) (quote B)))")))
   (status . witnessed))

  ((identity . s3-s5-claim-boundary)
   (s2-product . cml-shaped-ir-data)
   (compiled-emitter-elf-alone-proves-self-hosting . no)
   (source-input-boundary . required-for-standalone-compiler-claim)
   (result-output-boundary . required)
   (result-transport-semantics . forbidden)
   (external-backend-provenance . required-if-present)
   (fixed-point-scope-before-backend-self-hosting . lisp-authored-emitter-frontend)
   (fully-self-contained-compiler-claim . deferred-until-evidence))

  ((generation . s3)
   (role . compiled-emitter-artifact)
   (owner . wsm-my-lisp-issue-39)
   (compiler-mechanism-owner . cml-issue-190)
   (artifact-sha256 . pending)
   (status . pending))

  ((generation . s4)
   (role . self-compiled-emitter-artifact)
   (owner . wsm-my-lisp-issue-39)
   (artifact-sha256 . pending)
   (status . pending))

  ((generation . s5)
   (role . emitter-fixed-point-comparison)
   (comparison . same-compiler-source)
   (accepted-equivalence . byte-identical-or-explicit-normalized-equivalence)
   (status . pending))

  ((lineage-invariants . core1)
   (semantic-authority . my-lisp)
   (seed-may-add-semantics-for-bootstrap . forbidden)
   (unwitnessed-generation-may-be-called-self-hosted . forbidden)
   (generation-provenance . required)
   (artifact-hashes . required)))
