(core1-generation-manifest/1
  ((generation . s0)
   (role . typed-sid8-historical-physical-seed)
   (repository . juv4uk/mccarthy-eval)
   (commit . "6031f92652066825a245c806c0773e9e524257bd")
   (source-path . "mccarthy-kernel.s")
   (source-sha256 . "20bdd714a4072cd45ce782bb0b4597a1ff3e96b35624ff86188fb7bb3f455cdd")
   (build-system . guix-time-machine)
   (guix-channel-commit . "5375f33fd48ffc3b39ecc1c5993e299258a043d8")
   (build-package . "gcc-toolchain")
   (build-command . "gcc -no-pie -O0 -s -o mccarthy-kernel mccarthy-kernel.s")
   (artifact-scope . x86_64-linux-pinned-guix-closure)
   (binary-sha256 . "3283cec94edb4211f2aaa4fee5d52c4f9b6add72b1d1db36c142788bf548cfa0")
   (semantic-authority . no)
   (status . witnessed))

  ((generation . s1)
   (role . lisp-owned-bootstrap)
   (repository . juv4uk/sens)
   (path . "lib/core1.lisp")
   (source-sha256 . "fa858aed41abd51957ebdc696eb332d799bb750faf7bb7074c18286c573254a4")
   (executed-by . s0)
   (mechanism . historical-function-funarg-plus-zero-copy-lisp-owned-dispatch)
   (witnesses .
     ((historical-function-funarg . "HISTORICAL-FUNARG")
      (core1-lambda-representation . "T")
      (closure-capture . "(A . B)")
      (self-recursive-definition . "C")
      (self-source-load . "(00000100 Y T)")
      (unsupported-modern-identity .
        ((sid . 01001111)
         (surface . VECTOR)
         (observation . "(C1-ERROR UNBOUND VECTOR)")))))
   (status . witnessed))

  ((generation . s2)
   (role . lisp-authored-compiler-source)
   (repository . juv4uk/wsm-my-lisp)
   (commit . "a6bd9747196f2d676ab6883cbb4b84c7fcfc6947")
   (path . "lib/compiler.lisp")
   (source-sha256 . "b401cd09a0040c64668aa98369cad4932c06767343de5214a0eae2dae3ce6cce")
   (executed-by . s1-on-s0)
   (witnesses .
     ((atom-lowering . "(var FOO)")
      (primitive-lowering . "(prim cons ((quote A) (quote B)))")))
   (status . witnessed))

  ((identity . s3-s5-claim-boundary)
   (s2-product . cml-shaped-ir-data)
   (compiled-emitter-elf-alone-proves-self-hosting . no)
   (source-input-boundary . required-for-standalone-compiler-claim)
   (result-output-boundary . required)
   (result-transport-semantics . forbidden)
   (external-backend-provenance . required-if-present)
   (fixed-point-scope-before-backend-self-hosting . lisp-authored-emitter-frontend)
   (fully-self-contained-compiler-claim . deferred-until-evidence))

  ((generation . s3)
   (role . compiled-emitter-artifact)
   (owner . wsm-my-lisp-issue-39)
   (compiler-mechanism-owner . cml-issue-190)
   (artifact-sha256 . pending)
   (status . pending))

  ((generation . s4)
   (role . self-compiled-emitter-artifact)
   (owner . wsm-my-lisp-issue-39)
   (artifact-sha256 . pending)
   (status . pending))

  ((generation . s5)
   (role . emitter-fixed-point-comparison)
   (comparison . same-compiler-source)
   (accepted-equivalence . byte-identical-or-explicit-normalized-equivalence)
   (status . pending))

  ((lineage-invariants . core1)
   (semantic-authority . my-lisp)
   (seed-may-add-semantics-for-bootstrap . forbidden)
   (unwitnessed-generation-may-be-called-self-hosted . forbidden)
   (generation-provenance . required)
   (artifact-hashes . required)))
