(core1-s2-compiler-admission/2
  (supersedes . core1-s2-compiler-admission/1)

  ((source . compiler-seed)
   (repository . juv4uk/wsm-my-lisp)
   (repository-head . "22a626f5c3cb4dbcbf6e4903278b384744a45a0b")
   (path . "lib/compiler.lisp")
   (blob . "89e5653876cf6dc31242ce0b91bdfbb7cdd36a75")
   (semantic-authority . no)
   (projection-invariant . two-part-historical-cond)
   (withdrawn-projection . cond-match))

  ((runtime-required . core1)
   (special-forms . (quote lambda cond define))
   (primitive-operations . (atom eq cons car cdr list not))
   (mechanisms . (recursion lexical-closure top-level-definition-frame))
   (arithmetic . not-required)
   (strings . not-required)
   (io . not-required)
   (mutation . not-required))

  ((cond-projection . two-part-historical)
   (source-clause-arity . 2)
   (source-clause . (test body))
   (emitted-ir . "(cond ((test) (body)))")
   (owner-decision . "sens#1703")
   (withdrawn . cond-match)
   (withdrawn-reason . three-part-test-expected-body-projection-is-canonical-only)
   (evidence . "CI probe form-cond"))

  ((data-only-symbols . compiler-source)
   (symbols . (+ - cons car cdr eq atom))
   (rule . quoted-data-does-not-admit-host-primitive))

  ((surface-projection . bounded)
   (mechanism . lazy-core1-dispatch)
   (source-surface . current-wsm-compiler)
   (target-surface . core1-s0-historical)
   (mapping-authority . "contracts/core1-historical-sid-map.lisp")
   (identity-source . semantic-registry-sid)
   (surface-spelling-derived-from-sid . yes)
   (historical-control-projection . ((t T)))
   (quoted-payload . preserve-verbatim)
   (user-identifiers . preserve-verbatim)
   (global-text-uppercasing . forbidden)
   (whole-ast-copy . forbidden)
   (allocation . zero-copy)
   (scope . pinned-compiler-source-only))

  ((identity-projection . sid-exact)
   (emitted-ir-primitive . "00000100")
   (surface-spelling-is-derived-only . yes)
   (rationale . "identity-source is semantic-registry-sid; surface spelling is a derived view, not IR identity")
   (evidence . "CI probe form-cons; sid-name-identity and sid-direct-identity both resolve 00000100"))

  ((acceptance . s2-loader)
   (core1-loads-pinned-compiler-source . required)
   (compiler-form-executes . required)
   (expected-input . "(cons (quote A) (quote B))")
   (expected-ir . "(prim 00000100 ((quote A) (quote B)))")
   (core1-expansion-on-failure . require-concrete-witness)))