(core1-s2-compiler-admission/1
  ((source . compiler-seed)
   (repository . juv4uk/wsm-my-lisp)
   (repository-head . "a6bd9747196f2d676ab6883cbb4b84c7fcfc6947")
   (path . "lib/compiler.lisp")
   (blob . "d708d22f03e0095211399e83474a5e6df11e614d")
   (semantic-authority . no))

  ((runtime-required . core1)
   (special-forms . (quote lambda cond define))
   (primitive-operations . (atom? eq cons car cdr list not))
   (mechanisms . (recursion lexical-closure top-level-definition-frame))
   (arithmetic . not-required)
   (strings . not-required)
   (io . not-required)
   (mutation . not-required))

  ((data-only-symbols . compiler-source)
   (symbols . (+ - cons car cdr eq atom))
   (rule . quoted-data-does-not-admit-host-primitive))

  ((surface-projection . bounded)
   (mechanism . lazy-core1-dispatch)
   (source-surface . current-wsm-compiler)
   (target-surface . core1-s0-historical)
   (mapping-authority . "contracts/core1-historical-sid-map.lisp")
   (identity-source . semantic-registry-sid)
   (surface-spelling-derived-from-sid . yes)
   (historical-control-projection . ((t T)))
   (quoted-payload . preserve-verbatim)
   (user-identifiers . preserve-verbatim)
   (global-text-uppercasing . forbidden)
   (whole-ast-copy . forbidden)
   (allocation . zero-copy)
   (scope . pinned-compiler-source-only))

  ((acceptance . s2-loader)
   (core1-loads-pinned-compiler-source . required)
   (compiler-form-executes . required)
   (expected-input . "(cons (quote A) (quote B))")
   (expected-ir . "(prim cons ((quote A) (quote B)))")
   (core1-expansion-on-failure . require-concrete-witness)))