(core1-generation-manifest/1
  ((generation . s0)
   (role . historical-physical-seed)
   (repository . juv4uk/mccarthy-eval)
   (commit . "1c6acdb9dac890b2a0535ec0453bd83dfdda7248")
   (source-path . "mccarthy-kernel.s")
   (source-sha256 . "5e7190ba486e64c240a3f1cd74e31a8f39f7d5d28aa0df22dc73ee78dc743617")
   (binary-sha256 . "28d3ee3e1af1fac69f03bb678d35d0878e852efdee8af2766a37c63153e6fb07")
   (semantic-authority . no)
   (status . witnessed))

  ((generation . s1)
   (role . lisp-owned-bootstrap)
   (repository . juv4uk/my-lisp)
   (path . "lib/core1.lisp")
   (source-sha256 . "e56cbbeb4f3aaededf14a8af6ce164ccc219cd3b535fcaf575329f0f5c8c3b34")
   (executed-by . s0)
   (mechanism . zero-copy-lisp-owned-dispatch)
   (witnesses .
     ((closure-capture . "(A . B)")
      (self-recursive-definition . "C")
      (unsupported-modern-identity .
        ((sid . 01001111)
         (surface . VECTOR)
         (observation . "(C1-ERROR UNBOUND VECTOR)")))))
   (status . witnessed))

  ((generation . s2)
   (role . lisp-authored-compiler-source)
   (repository . juv4uk/wsm-my-lisp)
   (commit . "a6bd9747196f2d676ab6883cbb4b84c7fcfc6947")
   (path . "lib/compiler.lisp")
   (source-sha256 . "b401cd09a0040c64668aa98369cad4932c06767343de5214a0eae2dae3ce6cce")
   (executed-by . s1-on-s0)
   (witnesses .
     ((atom-lowering . "(var FOO)")
      (primitive-lowering . "(prim cons ((quote A) (quote B)))")))
   (status . witnessed))

  ((identity . s3-s5-claim-boundary)
   (s2-product . cml-shaped-ir-data)
   (compiled-emitter-elf-alone-proves-self-hosting . no)
   (source-input-boundary . required-for-standalone-compiler-claim)
   (result-output-boundary . required)
   (result-transport-semantics . forbidden)
   (external-backend-provenance . required-if-present)
   (fixed-point-scope-before-backend-self-hosting . lisp-authored-emitter-frontend)
   (fully-self-contained-compiler-claim . deferred-until-evidence))

  ((generation . s3)
   (role . compiled-emitter-artifact)
   (owner . wsm-my-lisp-issue-39)
   (compiler-mechanism-owner . cml-issue-190)
   (artifact-sha256 . pending)
   (status . pending))

  ((generation . s4)
   (role . self-compiled-emitter-artifact)
   (owner . wsm-my-lisp-issue-39)
   (artifact-sha256 . pending)
   (status . pending))

  ((generation . s5)
   (role . emitter-fixed-point-comparison)
   (comparison . same-compiler-source)
   (accepted-equivalence . byte-identical-or-explicit-normalized-equivalence)
   (status . pending))

  ((lineage-invariants . core1)
   (semantic-authority . my-lisp)
   (seed-may-add-semantics-for-bootstrap . forbidden)
   (unwitnessed-generation-may-be-called-self-hosted . forbidden)
   (generation-provenance . required)
   (artifact-hashes . required)))
