((schema . deep-structural-relation/1)
 (operation . equal?)
 (question-domain . structure)
 (result-form . structural-relation)
 (result-values . ((1)
                   (0)))
 (laws .
   ((identity-is-not-structure . t)
    (universal-truth-forbidden . t)
    (canon-zero-may-be-compared-as-structure . t)
    (generic-value-to-bool-forbidden . t)))
 (cases .
   (((left . ())
     (right . ())
     (result . (1)))
    ((left . radio)
     (right . radio)
     (result . (1)))
    ((left . radio)
     (right . antenna)
     (result . (0)))
    ((left . (radio antenna))
     (right . (radio antenna))
     (result . (1)))
    ((left . (radio antenna))
     (right . (radio signal))
     (result . (0)))
    ((left . (radio))
     (right . radio)
     (result . (0))))))
