; primitive-budget-audit-734.lisp — 197 Experimental IDs Budget Audit (#734)
;
; Parent: #730, #726
; Hard budget constraint: <= 256 identities (00000000..11111111)
; Accounted baseline: 197 identities (0..196), leaving 59 unused slots.
;
(primitive-budget-audit/1
  ((sid . 00000000) (name . "empty-list") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Canon 0 ground object"))
  ((sid . 00000001) (name . "quote") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "McCarthy 7 constitutive primitive"))
  ((sid . 00000010) (name . "atom") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "McCarthy 7 constitutive primitive"))
  ((sid . 00000011) (name . "eq") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "McCarthy 7 constitutive primitive"))
  ((sid . 00000100) (name . "cons") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "McCarthy 7 constitutive primitive"))
  ((sid . 00000101) (name . "car") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "McCarthy 7 constitutive primitive"))
  ((sid . 00000110) (name . "cdr") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "McCarthy 7 constitutive primitive"))
  ((sid . 00000111) (name . "cond") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "McCarthy 7 constitutive primitive"))
  ((sid . 00001000) (name . "lambda") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core evaluator binding form"))
  ((sid . 00001001) (name . "define") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core evaluator binding form"))
  ((sid . 00001010) (name . "defmacro") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core evaluator binding form"))
  ((sid . 00001011) (name . "def") (category . surface-only) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Alias for define"))
  ((sid . 00001100) (name . "додати") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Exact arithmetic core operation"))
  ((sid . 00001101) (name . "відняти") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Exact arithmetic core operation"))
  ((sid . 00001110) (name . "помножити") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Exact arithmetic core operation"))
  ((sid . 00001111) (name . "поділити") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Exact arithmetic core operation"))
  ((sid . 00010000) (name . "abs") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Derivable via cond and unary minus"))
  ((sid . 00010001) (name . "min") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Derivable via comparison and cond"))
  ((sid . 00010010) (name . "max") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Derivable via comparison and cond"))
  ((sid . 00010011) (name . "mod") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Integer division / remainder primitive"))
  ((sid . 00010100) (name . "quotient") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Integer division / remainder primitive"))
  ((sid . 00010101) (name . "sqrt") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Substrate numeric calculation hook"))
  ((sid . 00010110) (name . "isqrt") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Integer square root algorithm"))
  ((sid . 00010111) (name . "min-list") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: derivable via reduce"))
  ((sid . 00011000) (name . "max-list") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: derivable via reduce"))
  ((sid . 00011001) (name . "largest-chunk") (category . compatibility-only) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Historical buffer calculation helper"))
  ((sid . 00011010) (name . "менше?") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core mathematical comparison order/equality"))
  ((sid . 00011011) (name . "більше?") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: derivable from < and ="))
  ((sid . 00011100) (name . "рівне?") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core mathematical comparison order/equality"))
  ((sid . 00011101) (name . "не-більше?") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: derivable from < and ="))
  ((sid . 00011110) (name . "не-менше?") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: derivable from < and ="))
  ((sid . 00011111) (name . "nondecreasing-from?") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Sequence property checker over pairwise comparison"))
  ((sid . 00100000) (name . "nonincreasing-from?") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Sequence property checker over pairwise comparison"))
  ((sid . 00100001) (name . "not") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: derivable via cond"))
  ((sid . 00100010) (name . "equal?") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: structural recursive equality over eq"))
  ((sid . 00100011) (name . "symbol?") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core structural predicate and string ordering"))
  ((sid . 00100100) (name . "string?") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core structural predicate and string ordering"))
  ((sid . 00100101) (name . "string<?") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core structural predicate and string ordering"))
  ((sid . 00100110) (name . "numeric-buffer?") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host buffer type inspection"))
  ((sid . 00100111) (name . "list") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: variadic lambda (lambda args args)"))
  ((sid . "00101000") (name . "length") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Standard list operations derived in pure Lisp"))
  ((sid . "00101001") (name . "append") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Standard list operations derived in pure Lisp"))
  ((sid . "00101010") (name . "reverse") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Standard list operations derived in pure Lisp"))
  ((sid . "00101011") (name . "nth") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Standard list operations derived in pure Lisp"))
  ((sid . "00101100") (name . "member?") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Standard list operations derived in pure Lisp"))
  ((sid . "00101101") (name . "assoc") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Standard list operations derived in pure Lisp"))
  ((sid . "00101110") (name . "pair") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . no) (rationale . "Distinct binary constructor; retain distinct from list"))
  ((sid . "00101111") (name . "second") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . no) (rationale . "List ordinal accessor; keep distinct from structural cadr"))
  ((sid . "00110000") (name . "third") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: composite car/cdr accessor"))
  ((sid . "00110001") (name . "fourth") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: composite car/cdr accessor"))
  ((sid . "00110010") (name . "fifth") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: composite car/cdr accessor"))
  ((sid . "00110011") (name . "caar") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: (car (car x))"))
  ((sid . "00110100") (name . "cadr") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . no) (rationale . "McCarthy pair algebra projection; retain distinct from second"))
  ((sid . "00110101") (name . "cddr") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: composite cdr/car accessor"))
  ((sid . "00110110") (name . "cadddr") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: composite cdr/car accessor"))
  ((sid . "00110111") (name . "map") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Higher-order functional operators derived over lambda"))
  ((sid . "00111000") (name . "filter") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Higher-order functional operators derived over lambda"))
  ((sid . "00111001") (name . "reduce") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Higher-order functional operators derived over lambda"))
  ((sid . "00111010") (name . "string-append") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Fundamental string manipulation primitives"))
  ((sid . "00111011") (name . "string-length") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Fundamental string manipulation primitives"))
  ((sid . "00111100") (name . "string-empty?") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "String helper functions derived in Lisp"))
  ((sid . "00111101") (name . "string-prefix?") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "String helper functions derived in Lisp"))
  ((sid . "00111110") (name . "string-contains?") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "String helper functions derived in Lisp"))
  ((sid . "00111111") (name . "string-first") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "String helper functions derived in Lisp"))
  ((sid . "01000000") (name . "string-rest") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "String helper functions derived in Lisp"))
  ((sid . "01000001") (name . "string-slice") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Fundamental string manipulation primitives"))
  ((sid . "01000010") (name . "symbol->string") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Type coercion bridge primitives"))
  ((sid . "01000011") (name . "string->symbol") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Type coercion bridge primitives"))
  ((sid . "01000100") (name . "codepoint->string") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Type coercion bridge primitives"))
  ((sid . "01000101") (name . "string->codepoint") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Type coercion bridge primitives"))
  ((sid . "01000110") (name . "number->string") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Type coercion bridge primitives"))
  ((sid . "01000111") (name . "digit->string") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Derived lookup helper"))
  ((sid . "01001000") (name . "print") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Substrate transcript/console output hooks"))
  ((sid . "01001001") (name . "princ") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Substrate transcript/console output hooks"))
  ((sid . "01001010") (name . "read") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Lisp metaprogramming and serialization primitives"))
  ((sid . "01001011") (name . "read-all") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Looping wrapper around read"))
  ((sid . "01001100") (name . "write-to-string") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Lisp metaprogramming and serialization primitives"))
  ((sid . "01001101") (name . "eval") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Lisp metaprogramming and serialization primitives"))
  ((sid . "01001110") (name . "env") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Current environment introspection hook"))
  ((sid . "01001111") (name . "vector") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core random-access linear sequence primitives"))
  ((sid . "01010000") (name . "make-vector") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core random-access linear sequence primitives"))
  ((sid . "01010001") (name . "vector-length") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core random-access linear sequence primitives"))
  ((sid . "01010010") (name . "vector-ref") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core random-access linear sequence primitives"))
  ((sid . "01010011") (name . "vector-set!") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Mutable vector cell update"))
  ((sid . "01010100") (name . "i32-buffer") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collection conversion helpers"))
  ((sid . "01010101") (name . "f32-buffer") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collection conversion helpers"))
  ((sid . "01010110") (name . "numeric-buffer-type") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01010111") (name . "numeric-buffer-length") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01011000") (name . "numeric-buffer-ref") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01011001") (name . "numeric-buffer-map") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01011010") (name . "mono-ns") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01011011") (name . "unix-time-now") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01011100") (name . "ntp-query-raw") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01011101") (name . "timezone-declarations-raw") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01011110") (name . "utc-now") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01011111") (name . "utc-from-unix") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01100000") (name . "unix-time-observation->utc") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01100001") (name . "milliseconds-from-nanoseconds") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01100010") (name . "mono-ms") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01100011") (name . "timezone-name") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01100100") (name . "timezone-detect") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01100101") (name . "timezone-offset-seconds") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01100110") (name . "deadline-reached?") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01100111") (name . "deadline-reached-at?") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01101000") (name . "elapsed-ns") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01101001") (name . "deadline-from") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01101010") (name . "deadline-after-ns") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01101011") (name . "internet-time-sync") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01101100") (name . "map-empty") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01101101") (name . "map-get") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01101110") (name . "map-insert") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01101111") (name . "map-contains?") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01110000") (name . "map->list") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01110001") (name . "vec-empty") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01110010") (name . "vec-conj") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01110011") (name . "vec-count") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01110100") (name . "vec-nth") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01110101") (name . "vec->list") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01110110") (name . "vec-from-list") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01110111") (name . "is-fact?") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01111000") (name . "describe") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01111001") (name . "collect-facts-about") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01111010") (name . "contains-atom?") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01111011") (name . "forward-in") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01111100") (name . "reason-in") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01111101") (name . "check-conflict") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01111110") (name . "module-known?") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01111111") (name . "module-clauses-now") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "10000000") (name . "prove-goal") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "10000001") (name . "prove-goals") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "10000010") (name . "explain-proof") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "10000011") (name . "source-of") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10000100") (name . "provenance") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10000101") (name . "reason") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10000110") (name . "reason-explain") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10000111") (name . "unify") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10001000") (name . "logic-var") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10001001") (name . "var?") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10001010") (name . "apply-subst") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10001011") (name . "walk") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10001100") (name . "occurs-check") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10001101") (name . "claim?") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10001110") (name . "claim-statement") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10001111") (name . "claim-review") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10010000") (name . "evidence?") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10010001") (name . "evidence-method") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10010010") (name . "evidence-outcome") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10010011") (name . "observation?") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10010100") (name . "observation-statement") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10010101") (name . "intent?") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10010110") (name . "intent-goal") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10010111") (name . "supporting-evidence") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10011000") (name . "identity") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10011001") (name . "gensym") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10011010") (name . "and") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: macro over cond"))
  ((sid . "10011011") (name . "or") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: macro over cond"))
  ((sid . "10011100") (name . "let") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: macro over lambda"))
  ((sid . "10011101") (name . "let*") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: macro over lambda"))
  ((sid . "10011110") (name . "->") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10011111") (name . "->>") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10100000") (name . "json-parse") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10100001") (name . "sha256-hex") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10100010") (name . "process-run") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10100011") (name . "tcp-read") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10100100") (name . "tcp-write") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10100101") (name . "tcp-listen") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10100110") (name . "read-file") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10100111") (name . "write-file") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10101000") (name . "kernel") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10101001") (name . "callable") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10101010") (name . "request") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10101011") (name . "response") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10101100") (name . "source") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10101101") (name . "target") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10101110") (name . "payload") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10101111") (name . "invoke") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10110000") (name . "observe") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10110001") (name . "route") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10110010") (name . "relation") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10110011") (name . "bridge") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10110100") (name . "transport") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10110101") (name . "result") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10110110") (name . "status") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10110111") (name . "start") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10111000") (name . "stop") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10111001") (name . "restart") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10111010") (name . "snapshot") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10111011") (name . "measure") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10111100") (name . "producer") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10111101") (name . "lisp-kernel") (category . ordinary-data) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago kernel identifier; can be ordinary data symbol"))
  ((sid . "10111110") (name . "prolog-kernel") (category . ordinary-data) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago kernel identifier; can be ordinary data symbol"))
  ((sid . "10111111") (name . "clips-kernel") (category . ordinary-data) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago kernel identifier; can be ordinary data symbol"))
  ((sid . "11000000") (name . "datalog-kernel") (category . ordinary-data) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago kernel identifier; can be ordinary data symbol"))
  ((sid . "11000001") (name . "owns-callable") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago capability relation predicate"))
  ((sid . "11000010") (name . "can-call") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago capability relation predicate"))
  ((sid . "11000011") (name . "can-observe") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago capability relation predicate"))
  ((sid . "11000100") (name . "has-transport") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago capability relation predicate"))
)
