; primitive-budget-audit-734.lisp — 197 Experimental IDs Budget Audit (#734)
;
; Parent: #730, #726
; Hard budget constraint: <= 256 identities (00000000..11111111)
; Accounted baseline: 197 identities (0..196), leaving 59 unused slots.
;
(primitive-budget-audit/1
  ((sid . "00000000") (index . 0) (name . "empty-list") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Canon 0 ground object"))
  ((sid . "00000001") (index . 1) (name . "quote") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "McCarthy 7 constitutive primitive"))
  ((sid . "00000010") (index . 2) (name . "atom") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "McCarthy 7 constitutive primitive"))
  ((sid . "00000011") (index . 3) (name . "eq") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "McCarthy 7 constitutive primitive"))
  ((sid . "00000100") (index . 4) (name . "cons") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "McCarthy 7 constitutive primitive"))
  ((sid . "00000101") (index . 5) (name . "car") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "McCarthy 7 constitutive primitive"))
  ((sid . "00000110") (index . 6) (name . "cdr") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "McCarthy 7 constitutive primitive"))
  ((sid . "00000111") (index . 7) (name . "cond") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "McCarthy 7 constitutive primitive"))
  ((sid . "00001000") (index . 8) (name . "lambda") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core evaluator binding form"))
  ((sid . "00001001") (index . 9) (name . "define") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core evaluator binding form"))
  ((sid . "00001010") (index . 10) (name . "defmacro") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core evaluator binding form"))
  ((sid . "00001011") (index . 11) (name . "def") (category . surface-only) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Alias for define"))
  ((sid . "00001100") (index . 12) (name . "додати") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Exact arithmetic core operation"))
  ((sid . "00001101") (index . 13) (name . "відняти") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Exact arithmetic core operation"))
  ((sid . "00001110") (index . 14) (name . "помножити") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Exact arithmetic core operation"))
  ((sid . "00001111") (index . 15) (name . "поділити") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Exact arithmetic core operation"))
  ((sid . "00010000") (index . 16) (name . "abs") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Derivable via cond and unary minus"))
  ((sid . "00010001") (index . 17) (name . "min") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Derivable via comparison and cond"))
  ((sid . "00010010") (index . 18) (name . "max") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Derivable via comparison and cond"))
  ((sid . "00010011") (index . 19) (name . "mod") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Integer division / remainder primitive"))
  ((sid . "00010100") (index . 20) (name . "quotient") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Integer division / remainder primitive"))
  ((sid . "00010101") (index . 21) (name . "sqrt") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Substrate numeric calculation hook"))
  ((sid . "00010110") (index . 22) (name . "isqrt") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Integer square root algorithm"))
  ((sid . "00010111") (index . 23) (name . "min-list") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: derivable via reduce"))
  ((sid . "00011000") (index . 24) (name . "max-list") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: derivable via reduce"))
  ((sid . "00011001") (index . 25) (name . "largest-chunk") (category . compatibility-only) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Historical buffer calculation helper"))
  ((sid . "00011010") (index . 26) (name . "менше?") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core mathematical comparison order/equality"))
  ((sid . "00011011") (index . 27) (name . "більше?") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: derivable from < and ="))
  ((sid . "00011100") (index . 28) (name . "рівне?") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core mathematical comparison order/equality"))
  ((sid . "00011101") (index . 29) (name . "не-більше?") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: derivable from < and ="))
  ((sid . "00011110") (index . 30) (name . "не-менше?") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: derivable from < and ="))
  ((sid . "00011111") (index . 31) (name . "nondecreasing-from?") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Sequence property checker over pairwise comparison"))
  ((sid . "00100000") (index . 32) (name . "nonincreasing-from?") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Sequence property checker over pairwise comparison"))
  ((sid . "00100001") (index . 33) (name . "not") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: derivable via cond"))
  ((sid . "00100010") (index . 34) (name . "equal?") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: structural recursive equality over eq"))
  ((sid . "00100011") (index . 35) (name . "symbol?") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core structural predicate and string ordering"))
  ((sid . "00100100") (index . 36) (name . "string?") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core structural predicate and string ordering"))
  ((sid . "00100101") (index . 37) (name . "string<?") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core structural predicate and string ordering"))
  ((sid . "00100110") (index . 38) (name . "numeric-buffer?") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host buffer type inspection"))
  ((sid . "00100111") (index . 39) (name . "list") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: variadic lambda (lambda args args)"))
  ((sid . "00101000") (index . 40) (name . "length") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Standard list operations derived in pure Lisp"))
  ((sid . "00101001") (index . 41) (name . "append") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Standard list operations derived in pure Lisp"))
  ((sid . "00101010") (index . 42) (name . "reverse") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Standard list operations derived in pure Lisp"))
  ((sid . "00101011") (index . 43) (name . "nth") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Standard list operations derived in pure Lisp"))
  ((sid . "00101100") (index . 44) (name . "member?") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Standard list operations derived in pure Lisp"))
  ((sid . "00101101") (index . 45) (name . "assoc") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Standard list operations derived in pure Lisp"))
  ((sid . "00101110") (index . 46) (name . "pair") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . no) (rationale . "Distinct binary constructor; retain distinct from list"))
  ((sid . "00101111") (index . 47) (name . "second") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . no) (rationale . "List ordinal accessor; keep distinct from structural cadr"))
  ((sid . "00110000") (index . 48) (name . "third") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: composite car/cdr accessor"))
  ((sid . "00110001") (index . 49) (name . "fourth") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: composite car/cdr accessor"))
  ((sid . "00110010") (index . 50) (name . "fifth") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: composite car/cdr accessor"))
  ((sid . "00110011") (index . 51) (name . "caar") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: (car (car x))"))
  ((sid . "00110100") (index . 52) (name . "cadr") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . no) (rationale . "McCarthy pair algebra projection; retain distinct from second"))
  ((sid . "00110101") (index . 53) (name . "cddr") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: composite cdr/car accessor"))
  ((sid . "00110110") (index . 54) (name . "cadddr") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: composite cdr/car accessor"))
  ((sid . "00110111") (index . 55) (name . "map") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Higher-order functional operators derived over lambda"))
  ((sid . "00111000") (index . 56) (name . "filter") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Higher-order functional operators derived over lambda"))
  ((sid . "00111001") (index . 57) (name . "reduce") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Higher-order functional operators derived over lambda"))
  ((sid . "00111010") (index . 58) (name . "string-append") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Fundamental string manipulation primitives"))
  ((sid . "00111011") (index . 59) (name . "string-length") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Fundamental string manipulation primitives"))
  ((sid . "00111100") (index . 60) (name . "string-empty?") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "String helper functions derived in Lisp"))
  ((sid . "00111101") (index . 61) (name . "string-prefix?") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "String helper functions derived in Lisp"))
  ((sid . "00111110") (index . 62) (name . "string-contains?") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "String helper functions derived in Lisp"))
  ((sid . "00111111") (index . 63) (name . "string-first") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "String helper functions derived in Lisp"))
  ((sid . "01000000") (index . 64) (name . "string-rest") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "String helper functions derived in Lisp"))
  ((sid . "01000001") (index . 65) (name . "string-slice") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Fundamental string manipulation primitives"))
  ((sid . "01000010") (index . 66) (name . "symbol->string") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Type coercion bridge primitives"))
  ((sid . "01000011") (index . 67) (name . "string->symbol") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Type coercion bridge primitives"))
  ((sid . "01000100") (index . 68) (name . "codepoint->string") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Type coercion bridge primitives"))
  ((sid . "01000101") (index . 69) (name . "string->codepoint") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Type coercion bridge primitives"))
  ((sid . "01000110") (index . 70) (name . "number->string") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Type coercion bridge primitives"))
  ((sid . "01000111") (index . 71) (name . "digit->string") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Derived lookup helper"))
  ((sid . "01001000") (index . 72) (name . "print") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Substrate transcript/console output hooks"))
  ((sid . "01001001") (index . 73) (name . "princ") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Substrate transcript/console output hooks"))
  ((sid . "01001010") (index . 74) (name . "read") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Lisp metaprogramming and serialization primitives"))
  ((sid . "01001011") (index . 75) (name . "read-all") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Looping wrapper around read"))
  ((sid . "01001100") (index . 76) (name . "write-to-string") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Lisp metaprogramming and serialization primitives"))
  ((sid . "01001101") (index . 77) (name . "eval") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Lisp metaprogramming and serialization primitives"))
  ((sid . "01001110") (index . 78) (name . "env") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Current environment introspection hook"))
  ((sid . "01001111") (index . 79) (name . "vector") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core random-access linear sequence primitives"))
  ((sid . "01010000") (index . 80) (name . "make-vector") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core random-access linear sequence primitives"))
  ((sid . "01010001") (index . 81) (name . "vector-length") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core random-access linear sequence primitives"))
  ((sid . "01010010") (index . 82) (name . "vector-ref") (category . primitive-essential) (derivable? . no) (reclaim-candidate? . no) (rationale . "Core random-access linear sequence primitives"))
  ((sid . "01010011") (index . 83) (name . "vector-set!") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Mutable vector cell update"))
  ((sid . "01010100") (index . 84) (name . "i32-buffer") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collection conversion helpers"))
  ((sid . "01010101") (index . 85) (name . "f32-buffer") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collection conversion helpers"))
  ((sid . "01010110") (index . 86) (name . "numeric-buffer-type") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01010111") (index . 87) (name . "numeric-buffer-length") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01011000") (index . 88) (name . "numeric-buffer-ref") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01011001") (index . 89) (name . "numeric-buffer-map") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01011010") (index . 90) (name . "mono-ns") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01011011") (index . 91) (name . "unix-time-now") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01011100") (index . 92) (name . "ntp-query-raw") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01011101") (index . 93) (name . "timezone-declarations-raw") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01011110") (index . 94) (name . "utc-now") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01011111") (index . 95) (name . "utc-from-unix") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01100000") (index . 96) (name . "unix-time-observation->utc") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01100001") (index . 97) (name . "milliseconds-from-nanoseconds") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01100010") (index . 98) (name . "mono-ms") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01100011") (index . 99) (name . "timezone-name") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01100100") (index . 100) (name . "timezone-detect") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Collections/persistent data structure helpers"))
  ((sid . "01100101") (index . 101) (name . "timezone-offset-seconds") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01100110") (index . 102) (name . "deadline-reached?") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01100111") (index . 103) (name . "deadline-reached-at?") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01101000") (index . 104) (name . "elapsed-ns") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01101001") (index . 105) (name . "deadline-from") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01101010") (index . 106) (name . "deadline-after-ns") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01101011") (index . 107) (name . "internet-time-sync") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01101100") (index . 108) (name . "map-empty") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01101101") (index . 109) (name . "map-get") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01101110") (index . 110) (name . "map-insert") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01101111") (index . 111) (name . "map-contains?") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01110000") (index . 112) (name . "map->list") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01110001") (index . 113) (name . "vec-empty") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01110010") (index . 114) (name . "vec-conj") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01110011") (index . 115) (name . "vec-count") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01110100") (index . 116) (name . "vec-nth") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01110101") (index . 117) (name . "vec->list") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01110110") (index . 118) (name . "vec-from-list") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01110111") (index . 119) (name . "is-fact?") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01111000") (index . 120) (name . "describe") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01111001") (index . 121) (name . "collect-facts-about") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01111010") (index . 122) (name . "contains-atom?") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01111011") (index . 123) (name . "forward-in") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01111100") (index . 124) (name . "reason-in") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01111101") (index . 125) (name . "check-conflict") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01111110") (index . 126) (name . "module-known?") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "01111111") (index . 127) (name . "module-clauses-now") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "10000000") (index . 128) (name . "prove-goal") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "10000001") (index . 129) (name . "prove-goals") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "10000010") (index . 130) (name . "explain-proof") (category . ordinary-data) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Candidate for delegation to Prolog/Datalog islands"))
  ((sid . "10000011") (index . 131) (name . "source-of") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10000100") (index . 132) (name . "provenance") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10000101") (index . 133) (name . "reason") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10000110") (index . 134) (name . "reason-explain") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10000111") (index . 135) (name . "unify") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10001000") (index . 136) (name . "logic-var") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10001001") (index . 137) (name . "var?") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10001010") (index . 138) (name . "apply-subst") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10001011") (index . 139) (name . "walk") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10001100") (index . 140) (name . "occurs-check") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10001101") (index . 141) (name . "claim?") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10001110") (index . 142) (name . "claim-statement") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10001111") (index . 143) (name . "claim-review") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10010000") (index . 144) (name . "evidence?") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10010001") (index . 145) (name . "evidence-method") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10010010") (index . 146) (name . "evidence-outcome") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10010011") (index . 147) (name . "observation?") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10010100") (index . 148) (name . "observation-statement") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10010101") (index . 149) (name . "intent?") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10010110") (index . 150) (name . "intent-goal") (category . experimental-evidence) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Epistemic/evidence structures from experiments"))
  ((sid . "10010111") (index . 151) (name . "supporting-evidence") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10011000") (index . 152) (name . "identity") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10011001") (index . 153) (name . "gensym") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10011010") (index . 154) (name . "and") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: macro over cond"))
  ((sid . "10011011") (index . 155) (name . "or") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: macro over cond"))
  ((sid . "10011100") (index . 156) (name . "let") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: macro over lambda"))
  ((sid . "10011101") (index . 157) (name . "let*") (category . derived-operation) (derivable? . yes) (reclaim-candidate? . yes) (rationale . "Reclaim candidate: macro over lambda"))
  ((sid . "10011110") (index . 158) (name . "->") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10011111") (index . 159) (name . "->>") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10100000") (index . 160) (name . "json-parse") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10100001") (index . 161) (name . "sha256-hex") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10100010") (index . 162) (name . "process-run") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10100011") (index . 163) (name . "tcp-read") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10100100") (index . 164) (name . "tcp-write") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10100101") (index . 165) (name . "tcp-listen") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10100110") (index . 166) (name . "read-file") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10100111") (index . 167) (name . "write-file") (category . runtime-mechanism) (derivable? . no) (reclaim-candidate? . no) (rationale . "Host capability OS/IO hook"))
  ((sid . "10101000") (index . 168) (name . "kernel") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10101001") (index . 169) (name . "callable") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10101010") (index . 170) (name . "request") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10101011") (index . 171) (name . "response") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10101100") (index . 172) (name . "source") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10101101") (index . 173) (name . "target") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10101110") (index . 174) (name . "payload") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10101111") (index . 175) (name . "invoke") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10110000") (index . 176) (name . "observe") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10110001") (index . 177) (name . "route") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10110010") (index . 178) (name . "relation") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10110011") (index . 179) (name . "bridge") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10110100") (index . 180) (name . "transport") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10110101") (index . 181) (name . "result") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10110110") (index . 182) (name . "status") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10110111") (index . 183) (name . "start") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10111000") (index . 184) (name . "stop") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10111001") (index . 185) (name . "restart") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10111010") (index . 186) (name . "snapshot") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10111011") (index . 187) (name . "measure") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10111100") (index . 188) (name . "producer") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago shared coordination primitive"))
  ((sid . "10111101") (index . 189) (name . "lisp-kernel") (category . ordinary-data) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago kernel identifier; can be ordinary data symbol"))
  ((sid . "10111110") (index . 190) (name . "prolog-kernel") (category . ordinary-data) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago kernel identifier; can be ordinary data symbol"))
  ((sid . "10111111") (index . 191) (name . "clips-kernel") (category . ordinary-data) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago kernel identifier; can be ordinary data symbol"))
  ((sid . "11000000") (index . 192) (name . "datalog-kernel") (category . ordinary-data) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago kernel identifier; can be ordinary data symbol"))
  ((sid . "11000001") (index . 193) (name . "owns-callable") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago capability relation predicate"))
  ((sid . "11000010") (index . 194) (name . "can-call") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago capability relation predicate"))
  ((sid . "11000011") (index . 195) (name . "can-observe") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago capability relation predicate"))
  ((sid . "11000100") (index . 196) (name . "has-transport") (category . primitive-shared) (derivable? . no) (reclaim-candidate? . no) (rationale . "Archipelago capability relation predicate"))
)
