; semantic-ownership-audit-733.lisp — Lisp-owned semantic ownership audit (#733)
;
; Parent: #726
; Related: #730, #746, #749, COMMON-LISP-KERNEL-1
;
; CRITICAL DISTINCTION:
;   Does this item define WHAT THE LANGUAGE MEANS,
;   or only HOW AN IMPLEMENTATION EXECUTES IT?
;
; CLASSIFICATION TAXONOMY:
;   * semantic-authority      — Defines the inviolable meaning of the language (Canons, laws, SID registry).
;   * semantic-witness        — Pure Lisp data or runner that witnesses and verifies language laws.
;   * compatibility-reference — External standards or surface synonym references (ANSI Common Lisp, Ukrainian profiles).
;   * execution-mechanism     — Concrete substrate implementation (Rust/C runtime, allocation, evaluators, memory layouts).
;   * kernel-adapter          — Mechanical boundary / C-ABI bridge to the 4 autonomous islands (Prolog, Datalog, CLIPS, CL).
;   * historical-experiment   — Complex monolithic subsystem or in-Lisp engine candidate for demotion or routing to islands.
;   * unknown                 — Ambiguous item requiring focused experiment before moving or demoting.

(semantic-ownership-audit/1
  ; --------------------------------------------------------------------------
  ; SECTION 1: SEMANTIC AUTHORITIES (Defines WHAT the language means)
  ; --------------------------------------------------------------------------

  ((key . canon-laws)
   (path . "lib/canon.lisp")
   (category . semantic-authority)
   (question-answer . what-language-means)
   (semantic-role . constitutive-laws)
   (future-action . retain-in-core)
   (target-destination . "lib/canon.lisp")
   (rationale . "Defines Canon 0 empty list () and McCarthy 7 constitutive axioms (quote, atom, eq, cons, car, cdr, cond) as executable semantic laws in my-lisp."))

  ((key . semantic-registry-schema)
   (path . "lib/surface/semantic-registry.lisp")
   (category . semantic-authority)
   (question-answer . what-language-means)
   (semantic-role . semantic-identity-registry)
   (future-action . retain-in-core)
   (target-destination . "lib/surface/semantic-registry.lisp")
   (rationale . "Single authoritative 8-bit SID schema (00000000..10101000) mapping bitstrings to semantic identities across Ukrainian, English, Sanskrit, and keyboard-symbol surfaces."))

  ((key . answer-contract)
   (path . "contracts/answer-contract.lisp")
   (category . semantic-authority)
   (question-answer . what-language-means)
   (semantic-role . shared-predicate-control-boundary)
   (future-action . retain-minimal)
   (target-destination . "contracts/answer-contract.lisp")
   (rationale . "Minimal shared law only: structural empty, one-bit predicates, and two-part COND. Domain-specific mathematics/reasoning live in separate contracts."))

  ((key . island-compatibility-contract)
   (path . "contracts/island-compat-contract.lisp")
   (category . semantic-authority)
   (question-answer . what-language-means)
   (semantic-role . kernel-interaction-contract)
   (future-action . retain-in-core)
   (target-destination . "contracts/island-compat-contract.lisp")
   (rationale . "Defines language-facing kernel call/result protocol and cross-island data flow through pure S-expression data."))

  ((key . core-bootstrap-library)
   (path . "lib/core.lisp")
   (category . semantic-authority)
   (question-answer . what-language-means)
   (semantic-role . derived-language-semantics)
   (future-action . retain-in-core)
   (target-destination . "lib/core.lisp")
   (rationale . "Pure Lisp bootstrap definitions (list, not, and, or, let, map, filter, reduce) defining language semantics derived from primitives without host intrusion."))

  ((key . exact-q-binary-contract)
   (path . "contracts/exact-q-binary-contract.lisp")
   (category . semantic-authority)
   (question-answer . what-language-means)
   (semantic-role . mathematical-truth-domain)
   (future-action . retain-in-core)
   (target-destination . "contracts/exact-q-binary-contract.lisp")
   (rationale . "Defines 0/1 | 1/1 truth algebra for exact rational decisions, preventing collapse of structural/epistemic uncertainty into false."))

  ((key . structural-observation-contract)
   (path . "contracts/structural-observation-contract.lisp")
   (category . semantic-authority)
   (question-answer . what-language-means)
   (semantic-role . structural-query-laws)
   (future-action . retain-in-core)
   (target-destination . "contracts/structural-observation-contract.lisp")
   (rationale . "Defines observation taxonomy for atom, pair, symbol, and string representations."))

  ((key . core-macro-laws)
   (path . "lib/macro.lisp")
   (category . semantic-authority)
   (question-answer . what-language-means)
   (semantic-role . syntactic-transformation-laws)
   (future-action . retain-in-core)
   (target-destination . "lib/macro.lisp")
   (rationale . "Defines macroexpansion rules and definition mechanics in pure Lisp on top of primitive make-macro substrate."))

  ((key . result-status-taxonomy)
   (path . "lib/result-status.lisp")
   (category . semantic-authority)
   (question-answer . what-language-means)
   (semantic-role . result-status-ontology)
   (future-action . retain-in-core)
   (target-destination . "lib/result-status.lisp")
   (rationale . "Defines outcome vocabulary: ok, err, pass, fail, halt, pending."))

  ((key . evaluator-dispatch-contract)
   (path . "lib/surface/function-signatures.lisp")
   (category . semantic-authority)
   (question-answer . what-language-means)
   (semantic-role . evaluator-operation-classification)
   (future-action . retain-in-core)
   (target-destination . "lib/surface/function-signatures.lisp")
   (rationale . "Owns the language-level mapping from semantic identities to evaluator operation classes; host runtimes may project this data to mechanisms but must not recreate the mapping."))

  ; --------------------------------------------------------------------------
  ; SECTION 2: SEMANTIC WITNESSES (Proves in Lisp data that laws hold)
  ; --------------------------------------------------------------------------

  ((key . island-compat-witness)
   (path . "tests/fixtures/island-compat-witness.lisp")
   (category . semantic-witness)
   (question-answer . what-language-means)
   (semantic-role . kernel-contract-verifier)
   (future-action . retain-in-core)
   (target-destination . "tests/fixtures/island-compat-witness.lisp")
   (rationale . "Lisp-owned witness verifying #749 island call, 0/1/N count distinguishability, and data flow laws."))



  ((key . compiler-conformance-corpus)
   (path . "tests/fixtures/conformance.lisp")
   (category . semantic-witness)
   (question-answer . what-language-means)
   (semantic-role . execution-conformance-corpus)
   (future-action . retain-in-core)
   (target-destination . "tests/fixtures/conformance.lisp")
   (rationale . "Canonical test rows in pure Lisp data validating primitive evaluation, macros, and closures."))

  ((key . canon-laws-v2-witness)
   (path . "tests/fixtures/canon-laws-v2-witness.lisp")
   (category . semantic-witness)
   (question-answer . what-language-means)
   (semantic-role . canon-axioms-verifier)
   (future-action . retain-in-core)
   (target-destination . "tests/fixtures/canon-laws-v2-witness.lisp")
   (rationale . "Pure Lisp witness evaluating canon constitutive laws and returning structured pass/fail verdicts."))

  ((key . meta-circular-evaluator)
   (path . "lib/meta-eval.lisp")
   (category . semantic-witness)
   (question-answer . what-language-means)
   (semantic-role . self-hosting-evaluator-witness)
   (future-action . isolate-as-witness)
   (target-destination . "lib/meta-eval.lisp")
   (rationale . "Self-hosting evaluator in Lisp. Explicitly documented as a semantic witness of evaluation laws, not the production runtime."))

  ((key . peer-identity-witness)
   (path . "lib/surface/peer-identity-acceptance.lisp")
   (category . semantic-witness)
   (question-answer . what-language-means)
   (semantic-role . multilingual-surface-verifier)
   (future-action . retain-in-core)
   (target-destination . "lib/surface/peer-identity-acceptance.lisp")
   (rationale . "Witness verifying that Ukrainian, Sanskrit, and English surfaces evaluate to the exact same semantic identities."))

  ; --------------------------------------------------------------------------
  ; SECTION 3: EXECUTION MECHANISMS (HOW an implementation executes the language)
  ; --------------------------------------------------------------------------

  ((key . rust-canon-dispatch)
   (path . "crates/my-lisp/src/eval/canon.rs")
   (category . execution-mechanism)
   (question-answer . how-implementation-executes-it)
   (semantic-role . canonical-operation-execution)
   (future-action . project-from-language-authority)
   (target-destination . "crates/my-lisp/src/eval/canon.rs")
   (rationale . "Executes Canon mechanisms in Rust. It is a reference implementation projection and must not independently own SID-to-meaning authority."))


  ((key . rust-reader-parser)
   (path . "crates/my-lisp/src/parser.rs")
   (category . execution-mechanism)
   (question-answer . how-implementation-executes-it)
   (semantic-role . concrete-text-to-ast-parser)
   (future-action . retain-in-core)
   (target-destination . "crates/my-lisp/src/parser.rs")
   (rationale . "Concrete Rust recursive-descent parser, cursor tracking, and span allocations."))

  ((key . rust-evaluator-loop)
   (path . "crates/my-lisp/src/eval/mod.rs")
   (category . execution-mechanism)
   (question-answer . how-implementation-executes-it)
   (semantic-role . evaluation-trampoline-loop)
   (future-action . retain-in-core)
   (target-destination . "crates/my-lisp/src/eval/mod.rs")
   (rationale . "Rust evaluator dispatch loop, tail-call trampolining, and stack overflow guards."))

  ((key . rust-environment-frames)
   (path . "crates/my-lisp/src/environment.rs")
   (category . execution-mechanism)
   (question-answer . how-implementation-executes-it)
   (semantic-role . lexical-environment-storage)
   (future-action . retain-in-core)
   (target-destination . "crates/my-lisp/src/environment.rs")
   (rationale . "Concrete Rust Rc<RefCell<Frame>> hash maps, iterative worklist drop, and session transcripts."))

  ((key . rust-value-representation)
   (path . "crates/my-lisp/src/value.rs")
   (category . execution-mechanism)
   (question-answer . how-implementation-executes-it)
   (semantic-role . runtime-value-enum)
   (future-action . retain-in-core)
   (target-destination . "crates/my-lisp/src/value.rs")
   (rationale . "Concrete Rust enum Value definition, pointer layouts, Rational representation, and memory cleanup."))

  ((key . rust-bignum-arithmetic)
   (path . "crates/my-lisp/src/bignum.rs")
   (category . execution-mechanism)
   (question-answer . how-implementation-executes-it)
   (semantic-role . arbitrary-precision-integer-algorithms)
   (future-action . retain-in-core)
   (target-destination . "crates/my-lisp/src/bignum.rs")
   (rationale . "Hand-rolled BigInt arithmetic, Karatsuba multiplication, and limb operations in Rust."))

  ((key . rust-arithmetic-builtins)
   (path . "crates/my-lisp/src/eval/arithmetic.rs")
   (category . execution-mechanism)
   (question-answer . how-implementation-executes-it)
   (semantic-role . arithmetic-primitive-execution)
   (future-action . retain-in-core)
   (target-destination . "crates/my-lisp/src/eval/arithmetic.rs")
   (rationale . "Concrete Rust execution hooks for +, -, *, /, mod, sqrt, and bit operations."))

  ((key . rust-closures-machinery)
   (path . "crates/my-lisp/src/eval/closures.rs")
   (category . execution-mechanism)
   (question-answer . how-implementation-executes-it)
   (semantic-role . closure-binding-implementation)
   (future-action . retain-in-core)
   (target-destination . "crates/my-lisp/src/eval/closures.rs")
   (rationale . "Rust parameter matching, variadic rest packing, and lexical frame binding."))

  ((key . rust-special-forms-io)
   (path . "crates/my-lisp/src/eval/special_forms/io.rs")
   (category . execution-mechanism)
   (question-answer . how-implementation-executes-it)
   (semantic-role . os-filesystem-io-hooks)
   (future-action . retain-in-core)
   (target-destination . "crates/my-lisp/src/eval/special_forms/io.rs")
   (rationale . "Concrete host filesystem interaction hooks (read-file, write-file, load)."))

  ((key . rust-special-forms-json)
   (path . "crates/my-lisp/src/eval/special_forms/json.rs")
   (category . execution-mechanism)
   (question-answer . how-implementation-executes-it)
   (semantic-role . wire-format-json-decoder)
   (future-action . retain-in-core)
   (target-destination . "crates/my-lisp/src/eval/special_forms/json.rs")
   (rationale . "Rust wire-format JSON parser and unicode escape decoder."))

  ((key . rust-compiler-ir)
   (path . "crates/my-lisp/src/ir.rs")
   (category . execution-mechanism)
   (question-answer . how-implementation-executes-it)
   (semantic-role . intermediate-representation)
   (future-action . retain-in-core)
   (target-destination . "crates/my-lisp/src/ir.rs")
   (rationale . "Linear compiler IR instructions for native execution and analysis."))

  ((key . rust-memory-layout)
   (path . "crates/my-lisp/src/layout.rs")
   (category . execution-mechanism)
   (question-answer . how-implementation-executes-it)
   (semantic-role . memory-alignment-and-struct-packing)
   (future-action . retain-in-core)
   (target-destination . "crates/my-lisp/src/layout.rs")
   (rationale . "Physical memory offsets and alignment calculations for compiled values."))

  ((key . kernel-host-supervisor)
   (path . "crates/wsm-kernel-host/")
   (category . execution-mechanism)
   (question-answer . how-implementation-executes-it)
   (semantic-role . island-supervisor-and-router)
   (future-action . retain-in-core)
   (target-destination . "crates/wsm-kernel-host/")
   (rationale . "Mechanical orchestration substrate: thread pooling, request queues, latency timers, and opaque byte buffering."))

  ((key . precompiled-fasl-image)
   (path . "lib/core.lisp.fasl")
   (category . execution-mechanism)
   (question-answer . how-implementation-executes-it)
   (semantic-role . binary-bootstrap-snapshot)
   (future-action . retain-in-core)
   (target-destination . "lib/core.lisp.fasl")
   (rationale . "Pre-serialized binary memory snapshot of core.lisp for sub-millisecond host bootstrap."))

  ; --------------------------------------------------------------------------
  ; SECTION 4: KERNEL ADAPTERS (Bridges to the 4 autonomous islands)
  ; --------------------------------------------------------------------------

  ((key . kernel-c-abi-contract)
   (path . "crates/wsm-kernel-c-abi/")
   (category . kernel-adapter)
   (question-answer . how-implementation-executes-it)
   (semantic-role . foreign-c-abi-vtables)
   (future-action . retain-in-core)
   (target-destination . "crates/wsm-kernel-c-abi/")
   (rationale . "Defines mechanical C-ABI calling conventions, byte spans, and function pointers without imposing a shared semantic ontology."))

  ((key . prolog-kernel-adapter)
   (path . "crates/wsm-prolog-kernel/")
   (category . kernel-adapter)
   (question-answer . how-implementation-executes-it)
   (semantic-role . prolog-island-boundary)
   (future-action . retain-in-core)
   (target-destination . "crates/wsm-prolog-kernel/")
   (rationale . "C-ABI wrapper adapter for autonomous Prolog SLD resolution and backtracking engine."))

  ((key . datalog-kernel-adapter)
   (path . "crates/wsm-datalog-kernel/")
   (category . kernel-adapter)
   (question-answer . how-implementation-executes-it)
   (semantic-role . datalog-island-boundary)
   (future-action . retain-in-core)
   (target-destination . "crates/wsm-datalog-kernel/")
   (rationale . "C-ABI wrapper adapter for autonomous Datalog deductive closure and relational fixpoint engine."))

  ((key . clips-kernel-adapter)
   (path . "crates/wsm-clips-kernel/")
   (category . kernel-adapter)
   (question-answer . how-implementation-executes-it)
   (semantic-role . clips-island-boundary)
   (future-action . retain-in-core)
   (target-destination . "crates/wsm-clips-kernel/")
   (rationale . "C-ABI wrapper adapter for autonomous CLIPS 6.4.2 production rules and RETE working memory."))

  ((key . common-lisp-kernel-adapter)
   (path . "crates/wsm-common-lisp-kernel/")
   (category . kernel-adapter)
   (question-answer . how-implementation-executes-it)
   (semantic-role . common-lisp-island-boundary)
   (future-action . retain-in-core)
   (target-destination . "crates/wsm-common-lisp-kernel/")
   (rationale . "C-ABI wrapper adapter for autonomous ANSI Common Lisp execution island."))

  ; --------------------------------------------------------------------------
  ; SECTION 5: COMPATIBILITY REFERENCES (Standards & surface synonyms)
  ; --------------------------------------------------------------------------

  ((key . ansi-cl-compatibility)
   (path . "crates/wsm-common-lisp-kernel/tests/")
   (category . compatibility-reference)
   (question-answer . what-language-means)
   (semantic-role . external-standard-reference)
   (future-action . retain-in-core)
   (target-destination . "crates/wsm-common-lisp-kernel/tests/")
   (rationale . "Conformity baseline with ANSI Common Lisp standard without restricting my-lisp core semantics."))

  ((key . ukrainian-surface-reference)
   (path . "lib/surface/uk.lisp")
   (category . compatibility-reference)
   (question-answer . what-language-means)
   (semantic-role . language-surface-synonyms)
   (future-action . retain-in-core)
   (target-destination . "lib/surface/uk.lisp")
   (rationale . "Full Ukrainian surface spelling vocabulary and dialect profile."))

  ((key . sanskrit-surface-reference)
   (path . "lib/surface/sa.lisp")
   (category . compatibility-reference)
   (question-answer . what-language-means)
   (semantic-role . language-surface-synonyms)
   (future-action . retain-in-core)
   (target-destination . "lib/surface/sa.lisp")
   (rationale . "Sanskrit Paninian grammatical surface aliases."))

  ; --------------------------------------------------------------------------
  ; SECTION 6: HISTORICAL EXPERIMENTS & DEMOTION CANDIDATES
  ; --------------------------------------------------------------------------

  ((key . reason-backward-inference)
   (path . "lib/reason.lisp")
   (category . historical-experiment)
   (question-answer . how-implementation-executes-it)
   (semantic-role . in-lisp-backward-chaining-engine)
   (future-action . route-to-island)
   (target-destination . "wsm-prolog-kernel or optional package")
   (rationale . "Historical in-Lisp Advice Taker backward-chaining engine. Deductive resolution belongs to the autonomous Prolog island."))

  ((key . forward-rule-engine)
   (path . "lib/forward.lisp")
   (category . historical-experiment)
   (question-answer . how-implementation-executes-it)
   (semantic-role . in-lisp-forward-chaining-engine)
   (future-action . route-to-island)
   (target-destination . "wsm-clips-kernel or optional package")
   (rationale . "Historical in-Lisp CLIPS-style forward-chaining rule engine. Production rules belong to the autonomous CLIPS island."))

  ((key . clips-import-parser)
   (path . "lib/clips-import.lisp")
   (category . historical-experiment)
   (question-answer . how-implementation-executes-it)
   (semantic-role . clips-format-importer)
   (future-action . demote-to-package)
   (target-destination . "tooling/clips-import or wsm-clips-kernel")
   (rationale . "In-Lisp parser for CLIPS defrule constructs. Belongs to CLIPS island tooling rather than my-lisp core."))

  ((key . unify-pattern-matcher)
   (path . "lib/unify.lisp")
   (category . historical-experiment)
   (question-answer . how-implementation-executes-it)
   (semantic-role . in-lisp-unification-algorithm)
   (future-action . route-to-island)
   (target-destination . "wsm-prolog-kernel or optional package")
   (rationale . "In-Lisp Robinson unification with occurs-check. Unification and term substitution belong to autonomous logic islands."))

  ((key . knowledge-journal-system)
   (path . "lib/knowledge.lisp")
   (category . historical-experiment)
   (question-answer . how-implementation-executes-it)
   (semantic-role . in-lisp-knowledge-base)
   (future-action . demote-to-package)
   (target-destination . "packages/knowledge or datalog relations")
   (rationale . "In-Lisp append-only fact journal and module projection. Knowledge facts should be stored as relational facts in Datalog or isolated in an optional package."))

  ((key . immutable-world-system)
   (path . "lib/world.lisp")
   (category . historical-experiment)
   (question-answer . how-implementation-executes-it)
   (semantic-role . world-state-branching)
   (future-action . demote-to-package)
   (target-destination . "packages/world-simulation")
   (rationale . "In-Lisp immutable world branching over knowledge journals. Complex domain subsystem, demote to optional package."))

  ((key . yantra-coding-agent)
   (path . "lib/yantra.lisp")
   (category . historical-experiment)
   (question-answer . how-implementation-executes-it)
   (semantic-role . autonomous-coding-agent)
   (future-action . demote-to-package)
   (target-destination . "apps/yantra or standalone agent package")
   (rationale . "Full LLM coding agent with turn loops, JSON escaping, and curl subprocesses. Belongs in applications/tooling layer, not language core."))

  ((key . persistent-avl-map)
   (path . "lib/persistent-map.lisp")
   (category . historical-experiment)
   (question-answer . how-implementation-executes-it)
   (semantic-role . in-lisp-avl-tree-map)
   (future-action . demote-to-package)
   (target-destination . "packages/collections/persistent-map")
   (rationale . "In-Lisp AVL tree persistent map. Non-core collection; substrate or island structures can provide high-performance alternatives."))

  ((key . persistent-bitmapped-vector)
   (path . "lib/persistent-vector.lisp")
   (category . historical-experiment)
   (question-answer . how-implementation-executes-it)
   (semantic-role . in-lisp-vector-trie)
   (future-action . demote-to-package)
   (target-destination . "packages/collections/persistent-vector")
   (rationale . "In-Lisp 32-way branching vector trie. Non-core collection structure."))

  ((key . ground-graph-experiment)
   (path . "experiments/ground-graph.lisp")
   (category . historical-experiment)
   (question-answer . how-implementation-executes-it)
   (semantic-role . ternary-semantic-graph)
   (future-action . demote-to-package)
   (target-destination . "research/graph-indexing")
   (rationale . "Ternary semantic graph experiment (endpoint relation endpoint) for call-graph indexing. Demote to graph research package."))

  ; --------------------------------------------------------------------------
  ; SECTION 7: AMBIGUOUS ITEMS REQUIRING EXPERIMENT (unknown)
  ; --------------------------------------------------------------------------

  ((key . physical-units-si)
   (path . "lib/si.lisp")
   (category . unknown)
   (question-answer . what-language-means)
   (semantic-role . physical-dimension-typing)
   (future-action . experiment-needed)
   (target-destination . "experiment: test SI as core semantic type vs domain package")
   (rationale . "SI dimensions: experiment required to test whether dimension-checking is a core semantic typing law or a domain package."))

  ((key . physical-quantities)
   (path . "lib/quantity.lisp")
   (category . unknown)
   (question-answer . what-language-means)
   (semantic-role . exact-quantity-units)
   (future-action . experiment-needed)
   (target-destination . "experiment: test coupling of quantity with exact rational arithmetic")
   (rationale . "Exact quantities with units: requires experiment to determine coupling with exact rational arithmetic versus modular package."))

  ((key . calendar-calculations)
   (path . "lib/time.lisp")
   (category . unknown)
   (question-answer . what-language-means)
   (semantic-role . calendar-and-date-arithmetic)
   (future-action . experiment-needed)
   (target-destination . "experiment: benchmark pure Lisp calendar vs Common Lisp island date library")
   (rationale . "Calendar arithmetic in Lisp without clock: requires experiment to compare pure Lisp implementation against Common Lisp island standard utilities."))

  ((key . surface-translation-system)
   (path . "lib/translation.lisp")
   (category . unknown)
   (question-answer . what-language-means)
   (semantic-role . multi-surface-translation)
   (future-action . experiment-needed)
   (target-destination . "experiment: evaluate whether translation belongs to coordinator or linguistic island")
   (rationale . "Surface translation between Ukrainian, English, Sanskrit: requires experiment to determine whether cross-surface translation is coordinator logic or island utility."))

  ((key . content-addressed-storage)
   (path . "lib/content-store.lisp")
   (category . unknown)
   (question-answer . how-implementation-executes-it)
   (semantic-role . content-addressed-virtual-fs)
   (future-action . experiment-needed)
   (target-destination . "experiment: test CAS as host capability vs pure Lisp structural store")
   (rationale . "CAS content store: requires experiment to test whether immutable content addressing belongs in host adapter or pure Lisp virtual filesystem."))

  ((key . host-networking-process)
   (path . "lib/tcp.lisp")
   (category . unknown)
   (question-answer . how-implementation-executes-it)
   (semantic-role . network-socket-wrapper)
   (future-action . experiment-needed)
   (target-destination . "experiment: test capability-gated TCP wrapper against host sandboxing")
   (rationale . "TCP socket wrapper in Lisp: requires experiment to determine the exact boundary between coordination language and host security sandbox.")))
