; structural-query-inventory.lisp — Lisp-owned domain map for #218.
;
; Historical surface spelling and historical t/() return shape are evidence
; about the current implementation. They do not own the ontology of a question.
;
; In particular:
;   * a `?` suffix does not make a question mathematical-binary;
;   * deterministic does not mean mathematical-binary;
;   * only exact-Q decision questions delegate to #216's 0/1 | 1/1 algebra;
;   * outside that exact mathematical jurisdiction, "not established here"
;     must delegate rather than collapse to FALSE;
;   * structural/type/text questions stay under #218 until their own result
;     algebra is ratified;
;   * generic historical negation belongs to #217/#220 control/truth migration.
;
; This document is an inventory and ownership boundary, not the final result
; algebra for structural observations. Production predicate semantics are not
; changed by this slice.

(structural-query-inventory/1
  ((identity . "0002")
   (surface . atom?)
   (producer . rust-canon-value-truth)
   (current-result . classic-lisp-t-or-empty)
   (question-domain . value-shape)
   (mathematical-binary? . no)
   (owner . structural-observation-218)
   (consumer-class . legacy-cond-and-library-control)
   (compatibility-impact . high-bootstrap)
   (migration . explicit-structural-result-pending-218))

  ((identity . "0003")
   (surface . eq?)
   (producer . rust-canon-eq-value-truth)
   (current-result . classic-lisp-t-or-empty)
   (question-domain . atomic-identity)
   (mathematical-binary? . no)
   (owner . structural-observation-218)
   (consumer-class . legacy-cond-and-library-control)
   (compatibility-impact . high-bootstrap)
   (migration . explicit-identity-result-pending-218))

  ((identity . "1014")
   (surface . <)
   (producer . rust-comparison-value-truth)
   (current-result . classic-lisp-t-or-empty)
   (question-domain . numeric-order)
   (mathematical-binary? . yes-domain-bounded)
   (owner . exact-q-decision-216)
   (consumer-class . arithmetic-and-legacy-control)
   (compatibility-impact . high-public)
   (migration . exact-q-0/1-1/1-otherwise-delegate))

  ((identity . "1016")
   (surface . =)
   (producer . rust-comparison-value-truth)
   (current-result . classic-lisp-t-or-empty)
   (question-domain . numeric-equality)
   (mathematical-binary? . yes-domain-bounded)
   (owner . exact-q-decision-216)
   (consumer-class . arithmetic-and-legacy-control)
   (compatibility-impact . high-public)
   (migration . exact-q-0/1-1/1-otherwise-delegate))

  ((identity . "1015")
   (surface . >)
   (producer . rust-comparison-value-truth)
   (current-result . classic-lisp-t-or-empty)
   (question-domain . numeric-order)
   (mathematical-binary? . yes-domain-bounded)
   (owner . exact-q-decision-216)
   (consumer-class . arithmetic-and-legacy-control)
   (compatibility-impact . high-public)
   (migration . exact-q-0/1-1/1-otherwise-delegate))

  ((identity . "1026")
   (surface . numeric-buffer?)
   (producer . rust-builtin-value-truth-or-nil)
   (current-result . classic-lisp-t-or-empty)
   (question-domain . runtime-representation-kind)
   (mathematical-binary? . no)
   (owner . structural-observation-218)
   (consumer-class . type-guard-and-legacy-control)
   (compatibility-impact . medium-public)
   (migration . explicit-representation-result-pending-218))

  ((identity . "1025")
   (surface . string<?)
   (producer . rust-string-value-truth)
   (current-result . classic-lisp-t-or-empty)
   (question-domain . text-order)
   (mathematical-binary? . no)
   (owner . structural-observation-218)
   (consumer-class . text-guard-and-legacy-control)
   (compatibility-impact . medium-public)
   (migration . explicit-text-relation-result-pending-218))

  ((identity . "1024")
   (surface . string?)
   (producer . rust-string-type-value-truth)
   (current-result . classic-lisp-t-or-empty)
   (question-domain . runtime-value-kind)
   (mathematical-binary? . no)
   (owner . structural-observation-218)
   (consumer-class . type-guard-and-legacy-control)
   (compatibility-impact . medium-public)
   (migration . explicit-value-kind-result-pending-218))

  ((identity . "1021")
   (surface . not?)
   (producer . lisp-core-generic-truthiness-negation)
   (current-result . classic-lisp-t-or-empty)
   (question-domain . generic-control-negation)
   (mathematical-binary? . no)
   (owner . control-logic-217)
   (consumer-class . control-combinator)
   (compatibility-impact . high-bootstrap)
   (migration . retire-generic-truthiness-217-220))

  ((identity . "1022")
   (surface . equal?)
   (producer . lisp-core-atom-eq-recursion)
   (current-result . classic-lisp-t-or-empty)
   (question-domain . deep-structural-relation)
   (mathematical-binary? . no)
   (owner . structural-observation-218)
   (consumer-class . structural-guard-and-legacy-control)
   (compatibility-impact . high-library)
   (migration . explicit-structural-relation-result-pending-218))

  ((identity . "1032")
   (surface . member?)
   (producer . lisp-core-equal-recursion)
   (current-result . classic-lisp-t-or-empty)
   (question-domain . finite-list-membership)
   (mathematical-binary? . no)
   (owner . structural-observation-218)
   (consumer-class . list-guard-and-legacy-control)
   (compatibility-impact . high-library)
   (migration . explicit-membership-result-pending-218))

  ((identity . "1045")
   (surface . string-empty?)
   (producer . lisp-core-eq-derived)
   (current-result . classic-lisp-t-or-empty)
   (question-domain . text-emptiness)
   (mathematical-binary? . no)
   (owner . structural-observation-218)
   (consumer-class . text-guard-and-legacy-control)
   (compatibility-impact . medium-library)
   (migration . explicit-text-observation-result-pending-218))

  ((identity . "1046")
   (surface . string-prefix?)
   (producer . lisp-core-recursive-text-observation)
   (current-result . classic-lisp-t-or-empty)
   (question-domain . text-prefix-relation)
   (mathematical-binary? . no)
   (owner . structural-observation-218)
   (consumer-class . text-guard-and-legacy-control)
   (compatibility-impact . medium-library)
   (migration . explicit-text-relation-result-pending-218))

  ((identity . "1047")
   (surface . string-contains?)
   (producer . lisp-core-recursive-text-observation)
   (current-result . classic-lisp-t-or-empty)
   (question-domain . text-containment-relation)
   (mathematical-binary? . no)
   (owner . structural-observation-218)
   (consumer-class . text-guard-and-legacy-control)
   (compatibility-impact . medium-library)
   (migration . explicit-text-relation-result-pending-218))

  ((identity . "10101011")
   (surface . null?)
   (producer . lisp-core-atom-derived)
   (current-result . classic-lisp-t-or-empty)
   (question-domain . list-emptiness)
   (mathematical-binary? . no)
   (owner . structural-observation-218)
   (consumer-class . list-guard-and-legacy-control)
   (compatibility-impact . medium-library)
   (migration . explicit-list-observation-result-pending-218))

  ((identity . "1023")
   (surface . symbol?)
   (producer . lisp-core-atom-eq-derived)
   (current-result . classic-lisp-t-or-empty)
   (question-domain . runtime-value-kind)
   (mathematical-binary? . no)
   (owner . structural-observation-218)
   (consumer-class . type-guard-and-legacy-control)
   (compatibility-impact . high-library)
   (migration . explicit-value-kind-result-pending-218))

  ((identity . "1017")
   (surface . <=)
   (producer . lisp-core-derived-comparison)
   (current-result . classic-lisp-t-or-empty)
   (question-domain . numeric-order)
   (mathematical-binary? . yes-domain-bounded)
   (owner . exact-q-decision-216)
   (consumer-class . arithmetic-and-legacy-control)
   (compatibility-impact . high-public)
   (migration . exact-q-0/1-1/1-otherwise-delegate))

  ((identity . "1018")
   (surface . >=)
   (producer . lisp-core-derived-comparison)
   (current-result . classic-lisp-t-or-empty)
   (question-domain . numeric-order)
   (mathematical-binary? . yes-domain-bounded)
   (owner . exact-q-decision-216)
   (consumer-class . arithmetic-and-legacy-control)
   (compatibility-impact . high-public)
   (migration . exact-q-0/1-1/1-otherwise-delegate)))
