(u8-boundary-audit/1
  (boundary
    (name semantic-ref)
    (current-representation opaque-host-u8)
    (classification semantic-binary-identity-projection)
    (language-u8-domain no)
    (authority lib/surface/semantic-registry.lisp)
    (action retain)
    (reason "u8 is only the mechanical projection of a Lisp-owned Binary semantic identity"))
  (boundary
    (name utf8-byte-list)
    (current-representation exact-integer-list-0-255)
    (classification language-byte-data)
    (language-u8-domain no)
    (authority lib/utf8.lisp)
    (action retain-compatibility-boundary)
    (reason "UTF-8 algorithms own byte meaning in Lisp; existing public list representation remains exact integers until a deliberate migration proves compatibility"))
  (boundary
    (name file-raw-bytes)
    (current-representation exact-integer-list-0-255)
    (classification raw-host-mechanism)
    (language-u8-domain no)
    (authority crates/my-lisp-host)
    (action retain)
    (reason "read-file-bytes/write-file-bytes transport raw bytes; lib/fs.lisp owns text interpretation"))
  (boundary
    (name tcp-process-raw-bytes)
    (current-representation exact-integer-list-0-255)
    (classification raw-host-mechanism)
    (language-u8-domain no)
    (authority crates/my-lisp-host)
    (action retain)
    (reason "raw socket/process capabilities transport observations; Lisp owns UTF-8 interpretation and public policy"))
  (boundary
    (name machine-encoder-bytes)
    (current-representation exact-integer-list-0-255)
    (classification machine-mechanism)
    (language-u8-domain no)
    (authority lib/machine)
    (action retain)
    (reason "encoded instruction bytes are machine artifacts, not semantic-ID or general Lisp-u8 identity"))
  (boundary
    (name kernel-c-abi-semantic-id)
    (current-representation opaque-c-u8)
    (classification opaque-semantic-id-transport)
    (language-u8-domain no)
    (authority lib/surface/semantic-registry.lisp)
    (action retain)
    (reason "the ABI byte carries provenance only; it does not define semantic identity or Lisp u8 algebra"))
  (boundary
    (name lisp-u8)
    (current-representation binary-width-8)
    (classification language-value)
    (language-u8-domain yes)
    (authority lib/u8.lisp)
    (action admit)
    (reason "width-8 Binary is the single Lisp-owned u8 value domain; no second U8 storage type")))
