#!/usr/bin/env python3
"""#2410 — build the D8 historical full map by the D3→D6 occupancy rule.

Method (identical to the ratified D5/D6 rule, applied at width 8):

1. A D8 coordinate is a D6 coordinate extended by two bits. Every D6 coordinate
   therefore has exactly four D8 children (D4→D5 and D5→D6 had two each).
2. Every D8 coordinate records `parent_d6` (the lineage parent) and
   `parent_d7` (the mechanical one-bit prefix). The D7 rung is crossed without
   inheriting its law: D7 owns the Text7/Sound7 articulatory law
   (knowledge/d7-full-map.json, #2497). Width is part of identity, so a 7-bit
   sound cell and its 8-bit D8 children are distinct identities.
3. Selector coordinates are GENERATED, never hand-written: roots 101 (CAR) and
   110 (CDR) at D3, appended 0 = compose CAR, appended 1 = compose CDR (#2322).
   All 16 D6 selector parents have four selector children each, which reproduces
   exactly the 64 selector coordinates forecast for D8.
4. The remaining 192 coordinates are filled by chronological historical Lisp
   capability occupancy continuing D5/D6: four capabilities per D6 parent, each
   one an extension of that parent, each carrying its historical provenance.
5. unallocated = 0. Full occupancy is the D5/D6 ratified property.

HONESTY BOUNDARY: the 64 selector coordinates are generated by an admitted law.
The 192 historical coordinates are an agent-derived chronological continuation.
No single historical source attests this particular coordinate assignment; the
per-row `evidence` field says which is which. Residency is also not a claim of
semantic irreducibility (#2765).

Reproduce:

    python3 scripts/build-d8-historical-full-map.py
    python3 scripts/check-d8-full-map.py
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
D6_PATH = ROOT / "knowledge" / "d6-historical-full-map.json"
OUT_PATH = ROOT / "knowledge" / "d8-historical-full-map.json"

SCHEMA = "d8-historical-full-map/v1"
ISSUE = 2410

SELECTOR_ROOTS = ("101", "110")

# Evidence classes. Only the first is an admitted law; the second is a
# chronological list that is explicitly NOT a law.
SELECTOR_EVIDENCE = "generated-by-admitted-d3-selector-law-2322"
HISTORICAL_EVIDENCE = "agent-derived-historical-continuation"

# ---------------------------------------------------------------------------
# Historical capability continuation, four children per D6 parent.
#
# Key   = D6 parent coordinate (six bits)
# Value = four (name, category, behavior, provenance) tuples in chronological
#         order, each one a capability that extends its parent.
#
# D6 parents deliberately absent from this table are the 16 selector
# coordinates; their four children are generated by the admitted CAR/CDR law
# and must never be hand-written here.
# ---------------------------------------------------------------------------

HISTORY: dict[str, list[tuple[str, str, str, str]]] = {
    # --- block 1: REPL / LOAD / CLOSURE / CURRY -------------------------------
    "000000": [  # REPL — the interactive loop decomposed into its real stages
        ("READ", "system", "parse one datum from a stream into its internal form", "McCarthy 1960 / Lisp 1.5"),
        ("PRINT", "system", "render one datum as text onto a stream", "McCarthy 1960 / Lisp 1.5"),
        ("COMPILE", "system", "compile one expression into an executable closure", "Lisp 1.5"),
        ("COMPILE-FILE", "system", "compile a whole expression stream into executable code", "Lisp 1.5 / Common Lisp"),
    ],
    "000001": [  # LOAD — file/stream ingestion gains explicit stream lifetime
        ("OPEN", "stream", "open a named file or stream object for reading or writing", "Common Lisp"),
        ("CLOSE", "stream", "close an open stream and release its resource", "Common Lisp"),
        ("WITH-OPEN-FILE", "stream", "open, bind lexically and close on scope exit", "Common Lisp"),
        ("DRIBBLE", "stream", "tee the console input/output transcript into a file", "MacLisp"),
    ],
    "000010": [  # CLOSURE — heap-bound environment becomes a first-class value
        ("MAKE-CLOSURE", "abstraction", "bind a free environment into a heap-resident closure", "Lisp 1.5"),
        ("CLOSUREP", "abstraction", "test whether a value is a closure object", "Lisp 1.5 / Common Lisp"),
        ("VALUES", "abstraction", "return zero or more values from a form", "Common Lisp"),
        ("VALUES-LIST", "abstraction", "collect the returned values into one list", "Common Lisp"),
    ],
    "000011": [  # CURRY — application mechanism across a call boundary
        ("APPLY", "abstraction", "apply a function to a computed argument list", "Lisp 1.5 (§4.3)"),
        ("COMPOSE", "abstraction", "build the mathematical composition of two functions", "Functional Lisp tradition"),
        ("PARTIAL", "abstraction", "partially apply a function with a bound argument prefix", "Common Lisp"),
        ("FFI-CALL", "abstraction", "call a foreign procedure across a typed ABI boundary", "Lisp Machine FFI"),
    ],
    # --- block 2: special forms and macros ------------------------------------
    "000100": [  # FSUBR — the non-evaluating kernel form gains typed declarations
        ("EXPR", "special-form", "evaluated-argument kernel special form", "Lisp 1.5"),
        ("SPECIAL", "special-form", "declare a variable dynamically special in a scope", "Common Lisp"),
        ("THE", "special-form", "declare a value's type for compilation without checking", "Common Lisp"),
        ("LOCALLY", "special-form", "force lexical binding scope inside a dynamic region", "Common Lisp"),
    ],
    "000101": [  # LEXPR — the variadic receiver becomes a structured parameter list
        ("ARGLIST", "special-form", "access the evaluated variadic argument list", "MacLisp"),
        ("&REST", "special-form", "bind the trailing variadic arguments to one list", "Common Lisp"),
        ("&OPTIONAL", "special-form", "bind optional leading arguments with default values", "Common Lisp"),
        ("&WHOLE", "special-form", "bind the entire original argument list", "Common Lisp"),
    ],
    "000110": [  # MACROEXPAND-1 — one-step expansion becomes an explicit protocol
        ("GENERATE-EXPANSION", "macro", "the macro's own one-step expansion function", "Common Lisp"),
        ("MACRO-FUNCTION", "macro", "access the expansion function of a macro name", "Common Lisp"),
        ("MACROEXPAND-ALL", "macro", "recursively expand a form down to a core form", "Common Lisp"),
        ("COMPILER-MACRO", "macro", "compiler-time rewrite hook attached to an operator name", "Common Lisp"),
    ],
    "000111": [  # MACROEXPAND — full expansion gains name-level and splice power
        ("SYMBOL-MACRO", "macro", "a name-level macro that yields a form without evaluation", "Common Lisp"),
        ("DEFINE-SYMBOL-MACRO", "macro", "declare a symbol macro at a name", "Common Lisp"),
        ("DEFINE-COMPILER-MACRO", "macro", "declare a compiler macro at a name", "Common Lisp"),
        ("BACKQUANTIZE", "macro", "splice a list of forms into a surrounding form", "Common Lisp"),
    ],
    # --- block 3: binding and iteration ---------------------------------------
    "001000": [  # LET — parallel binding gains recursion and multiple values
        ("NAMED-LAMBDA", "binding", "bind a self-recursive local function name", "Lisp 1.5"),
        ("FLAMBDA", "binding", "function-bound lambda clause inside a binding body", "MacLisp"),
        ("LETREC", "binding", "simultaneous recursive local bindings", "Scheme"),
        ("MULTIPLE-VALUE-BIND", "binding", "bind several returned values to fresh locals", "Common Lisp"),
    ],
    "001001": [  # LET* — sequential binding scope becomes a body form
        ("PROG1", "binding", "sequential body returning the value of its first form", "Lisp 1.5"),
        ("PROG2", "binding", "sequential body returning the value of its second form", "Lisp 1.5"),
        ("DO*", "control", "stepped loop with sequential rather than simultaneous update", "Common Lisp"),
        ("LOOP", "control", "extensible iteration macro with keyword clauses", "Common Lisp"),
    ],
    "001010": [  # DO — the general stepped loop specialises into fixed shapes
        ("DOH", "control", "loop while a test form keeps succeeding", "Lisp 1.5"),
        ("REPEAT", "control", "iterate a fixed number of times", "MacLisp / Common Lisp"),
        ("DOSEQ", "control", "iterate over the elements of a sequence", "Common Lisp"),
        ("DOTIMES", "control", "iterate an integer counter from zero to N", "Common Lisp"),
    ],
    "001011": [  # WHILE — the negated test becomes quantified iteration
        ("UNTIL", "control", "loop until a test form succeeds", "MacLisp / Common Lisp"),
        ("ALWAYS", "predicate", "true only when every element of a sequence is true", "Common Lisp"),
        ("NEVER", "predicate", "true only when no element of a sequence is true", "Common Lisp"),
        ("EVERY", "predicate", "true only when every element satisfies a predicate", "Common Lisp"),
    ],
    # --- block 4: physical mutation and places --------------------------------
    "001100": [  # RPLACA — in-place car mutation grows into the stack discipline
        ("PUSH", "physical-mutation", "destructively cons an element onto a list place", "MacLisp / Common Lisp"),
        ("POP", "physical-mutation", "destructively pop the head of a list place", "MacLisp / Common Lisp"),
        ("SET-CAR", "generalized-place", "set the car of a cons place without rebinding", "Common Lisp"),
        ("LAST", "list-structure", "the tail list that follows the final element", "Lisp 1.5"),
    ],
    "001101": [  # RPLACD — in-place cdr mutation grows into splicing and removal
        ("SET-CDR", "generalized-place", "set the cdr of a cons place without rebinding", "Common Lisp"),
        ("NTHCDR", "list-structure", "the cdr reached after exactly N cdr steps", "Lisp 1.5"),
        ("BUTLAST", "list-structure", "the list without its last element", "Common Lisp"),
        ("REMOVE", "physical-mutation", "destructively remove the elements matching a predicate", "MacLisp / Common Lisp"),
    ],
    "001110": [  # SETF — generalized place update gains arithmetic and rotation
        ("INCF", "generalized-place", "increment a generalized place in place", "Common Lisp"),
        ("DECF", "generalized-place", "decrement a generalized place in place", "Common Lisp"),
        ("PUSHNEW", "generalized-place", "destructively push only when the element is absent", "Common Lisp"),
        ("ROTATE", "physical-mutation", "destructively rotate the elements of a sequence", "Common Lisp"),
    ],
    "001111": [  # DEFVAR — the root binding gains type and condition declarations
        ("DEFCONSTANT", "state", "define a named value that must not be reassigned", "Common Lisp"),
        ("DEFSTRUCT", "state", "define a structure type with constructor and accessors", "Common Lisp"),
        ("DEFTYPE", "state", "define a named type specifier", "Common Lisp"),
        ("DEFINE-CONDITION", "state", "define a named condition type for the condition system", "Common Lisp"),
    ],
    # --- block 5: predicates and exact arithmetic -----------------------------
    "010000": [  # EVENP — parity awareness becomes unit step and sign
        ("1+", "arithmetic", "increment by exactly one", "Lisp 1.5 (§4.2)"),
        ("1-", "arithmetic", "decrement by exactly one", "Lisp 1.5 (§4.2)"),
        ("SIGNUM", "arithmetic", "sign of a number as -1, 0 or 1", "Common Lisp"),
        ("MOD", "arithmetic", "remainder with the sign of the divisor", "Lisp 1.5"),
    ],
    "010001": [  # ODDP — integer structure awareness becomes sign and field access
        ("PLUSP", "predicate", "test whether a number is strictly positive", "Common Lisp"),
        ("MINUSP", "predicate", "test whether a number is strictly negative", "Common Lisp"),
        ("LDB", "bit-operation", "load an arbitrary bit field from an integer", "Lisp Machine"),
        ("MASK-FIELD", "bit-operation", "extract a bit field masked to its width", "Lisp Machine"),
    ],
    "010010": [  # INTEGERP — integer recognition becomes integer-valued rounding
        ("FLOOR", "numeric-conversion", "round down and return the integer quotient", "Common Lisp"),
        ("CEILING", "numeric-conversion", "round up and return the integer quotient", "Common Lisp"),
        ("TRUNCATE", "numeric-conversion", "round toward zero and return the quotient", "Common Lisp"),
        ("ROUND", "numeric-conversion", "round to nearest and return the quotient", "Common Lisp"),
    ],
    "010011": [  # RATIONALP — rational recognition becomes numeric tower widening
        ("FLOAT", "numeric-conversion", "widen an exact number to floating point", "Common Lisp"),
        ("RATIONAL", "numeric-conversion", "widen a number to an exact rational", "Common Lisp"),
        ("RATIONALIZE", "numeric-conversion", "convert a float to the simplest contained rational", "Common Lisp"),
        ("COMPLEX", "numeric-conversion", "build a complex number from real and imaginary parts", "Common Lisp"),
    ],
    "010100": [  # ADD1 — unit increment becomes bitwise composition
        ("LOGAND", "bit-operation", "bitwise conjunction of two integers", "Lisp 1.5"),
        ("LOGIOR", "bit-operation", "bitwise disjunction of two integers", "Lisp 1.5"),
        ("LOGXOR", "bit-operation", "bitwise exclusive disjunction of two integers", "MacLisp"),
        ("LOGNOT", "bit-operation", "bitwise complement of an integer", "Lisp 1.5"),
    ],
    "010101": [  # ABS — magnitude becomes the transcendental family
        ("SQRT", "arithmetic", "square root as an exact radical where representable", "Lisp 1.5 (§4.2)"),
        ("EXP", "arithmetic", "exponential function e**x", "Lisp 1.5 (§4.2)"),
        ("LOG", "arithmetic", "natural logarithm", "Lisp 1.5 (§4.2)"),
        ("SIN", "arithmetic", "sine of an angle", "Lisp 1.5 (§4.2)"),
    ],
    "010110": [  # SUB1 — unit decrement becomes binary scaling and width
        ("ASH", "bit-operation", "arithmetic shift left for a positive count, right for a negative one", "Common Lisp"),
        ("INTEGER-LENGTH", "bit-operation", "number of bits in the two's-complement representation", "Common Lisp"),
        ("ARITHMETIC-SHIFT", "bit-operation", "arithmetic shift by a signed count", "MacLisp"),
        ("COUNT-LEADING-ZEROS", "bit-operation", "count leading zero bits of an integer", "Lisp Machine"),
    ],
    "010111": [  # NEG — additive inverse becomes conjugation and complex parts
        ("CONJUGATE", "arithmetic", "complex conjugate of a number", "Common Lisp"),
        ("SCALE", "arithmetic", "scale a number by an integer factor", "Common Lisp"),
        ("REALPART", "numeric-conversion", "real component of a complex number", "Common Lisp"),
        ("IMAGPART", "numeric-conversion", "imaginary component of a complex number", "Common Lisp"),
    ],
    # --- block 6: non-local exit ---------------------------------------------
    "011000": [  # TAGBODY — the goto body becomes the condition signalling core
        ("THROW", "control", "perform a non-local exit to an active catch point", "Common Lisp"),
        ("UNWIND-PROTECT", "control", "run cleanup forms on any exit path from a body", "Common Lisp"),
        ("SIGNAL", "control", "raise a condition without transferring control", "Common Lisp"),
        ("IGNORE-ERROR", "control", "evaluate a body suppressing non-serious conditions", "Common Lisp"),
    ],
    "011001": [  # BLOCK — the named exit frame becomes error and restart handling
        ("ERROR", "control", "signal a serious condition and enter the debugger", "Common Lisp"),
        ("ERROR-IF-NOT-ERROR", "control", "transfer control only when an error is being handled", "Common Lisp"),
        ("RESTART-BIND", "control", "bind restart functions while handling a condition", "Common Lisp"),
        ("RESTART-CASE", "control", "offer a set of restart transfer functions", "Common Lisp"),
    ],
    "011010": [  # RETURN-FROM — targeted exit becomes dynamic and lexical scopes
        ("PROGV", "binding", "bind variables dynamically only for the extent of a body", "Lisp 1.5"),
        ("FLET", "binding", "lexical local functions without mutual recursion", "Common Lisp"),
        ("LABELS", "binding", "lexical local functions with mutual recursion", "Common Lisp"),
        ("LOCAL", "binding", "declare dynamically bound variables inside a body", "MacLisp"),
    ],
    "011011": [  # CATCH — the catch point becomes the handler stack
        ("HANDLER-CASE", "control", "bind handlers for a body and return a value if none fires", "Common Lisp"),
        ("HANDLER-BIND", "control", "bind condition handlers for the dynamic extent", "Common Lisp"),
        ("MAKE-CONDITION", "control", "construct a condition object of a declared type", "Common Lisp"),
        ("DEHANDLER", "control", "remove the innermost condition handler", "Common Lisp"),
    ],
    # --- block 7: ordering ----------------------------------------------------
    "011100": [  # LEQ — weak ordering becomes structural and character equality
        ("EQL", "predicate", "identity equality of two admitted atoms", "Lisp 1.5"),
        ("EQUAL", "predicate", "structural equality that descends into pairs", "Lisp 1.5"),
        ("CHAR=", "predicate", "test two characters for code equality", "Lisp 1.5"),
        ("STRING=", "predicate", "test two strings for element-wise equality", "Lisp 1.5"),
    ],
    "011101": [  # MIN — extremum becomes position search and ordering
        ("POSITION", "lookup", "index of the first element satisfying a predicate", "Lisp 1.5"),
        ("SORT", "sequence", "destructively order a sequence with a binary predicate", "Lisp 1.5"),
        ("REDUCE", "sequence", "fold a binary function over a sequence", "Common Lisp"),
        ("REMOVE-DUPLICATES", "sequence", "remove all but one occurrence of each element", "Common Lisp"),
    ],
    "011110": [  # GEQ — reverse ordering becomes conditional search
        ("CHAR<", "predicate", "test whether the first character's code is smaller", "Lisp 1.5"),
        ("STRING<", "predicate", "test lexicographic string ordering", "Lisp 1.5"),
        ("MEMBER-IF", "lookup", "first element of a list satisfying a predicate", "Common Lisp"),
        ("ASSOC-IF", "lookup", "first association whose value satisfies a predicate", "Common Lisp"),
    ],
    "011111": [  # MAX — the other extremum becomes maximal selection and deletion
        ("CHAR>", "predicate", "test whether the first character's code is greater", "Lisp 1.5"),
        ("STRING>", "predicate", "test reverse lexicographic string ordering", "Lisp 1.5"),
        ("FIND", "lookup", "first element satisfying a predicate, or the default", "Common Lisp"),
        ("DELETE", "physical-mutation", "destructively delete the elements matching a predicate", "Common Lisp"),
    ],
    # --- block 8: list structure ---------------------------------------------
    "100000": [  # NCONC — concatenation becomes copying and improper tails
        ("COPY-LIST", "list-structure", "shallow structural copy of a proper list", "Lisp 1.5"),
        ("REVAPPEND", "list-structure", "reverse one list onto the front of another", "Lisp 1.5"),
        ("LIST*", "list-structure", "build an improper list whose last tail is an argument", "Common Lisp"),
        ("LIST-LENGTH", "list-structure", "length of a proper list counted by traversal", "Lisp 1.5"),
    ],
    "100001": [  # LENGTH — counting becomes boundness and slice retrieval
        ("LENGTH-LIST", "list-structure", "length of a list counted cell by cell", "Lisp 1.5"),
        ("BOUNDP", "predicate", "test whether a variable holds any value at all", "Lisp 1.5"),
        ("ELT", "sequence", "retrieve the element at an index of a sequence", "Common Lisp"),
        ("SUBSEQ", "sequence", "extract a contiguous subsequence", "Common Lisp"),
    ],
    "100010": [  # NREVERSE — in-place order becomes traversal with destructuring
        ("MAPC", "higher-order", "apply a function to every element for effect only", "Common Lisp"),
        ("MAPL", "higher-order", "apply a function to every tail list for effect only", "Common Lisp"),
        ("MAPCAN", "higher-order", "map over lists and concatenate the collected results", "Common Lisp"),
        ("DESTRUCTURE-BIND", "binding", "bind variables to the parts of a structured datum", "Common Lisp"),
    ],
    "100011": [  # NTH — indexed retrieval becomes uniform array addressing
        ("AREF", "sequence", "retrieve the element at a one-dimensional index", "Common Lisp"),
        ("ROW-MAJOR-AREF", "sequence", "retrieve an element by row-major index", "Common Lisp"),
        ("CHAR", "sequence", "the character denoted by a code", "Common Lisp"),
        ("SCHAR", "sequence", "the character denoted by a code, any type", "Common Lisp"),
    ],
    # --- block 9: rational normalization and bit laws -------------------------
    "100100": [  # EXPT — exponentiation becomes explicit shifting laws
        ("LSH", "bit-operation", "logical left shift of an integer", "MacLisp"),
        ("RSH", "bit-operation", "logical right shift of an integer", "MacLisp"),
        ("BOOLE", "bit-operation", "bitwise operation selected by a boolean operation code", "Common Lisp"),
        ("LOGBITP", "predicate", "test one designated bit position", "MacLisp"),
    ],
    "100101": [  # GCD — rational reduction becomes numerator/denominator access
        ("NUMERATOR", "numeric-conversion", "numerator of a rational in lowest terms", "Common Lisp"),
        ("DENOMINATOR", "numeric-conversion", "denominator of a rational in lowest terms", "Common Lisp"),
        ("CANONICALIZE", "numeric-conversion", "reduce a fraction to a canonical encoding", "Lisp 1.5"),
        ("LCM", "arithmetic", "least common multiple of two integers", "Common Lisp"),
    ],
    "100110": [  # REMAINDER — the remainder becomes division and code mapping
        ("DIV", "arithmetic", "floor quotient and remainder returned as two values", "Common Lisp"),
        ("REM", "arithmetic", "remainder with the sign of the dividend", "Common Lisp"),
        ("CHAR-CODE", "numeric-conversion", "the code of a character as an integer", "Common Lisp"),
        ("CODE-CHAR", "sequence", "the character denoted by a code", "Common Lisp"),
    ],
    "100111": [  # RECIP — the reciprocal becomes the inverse-function family
        ("1/", "arithmetic", "reciprocal of a number as an exact rational", "Common Lisp"),
        ("ASIN", "arithmetic", "inverse sine", "Lisp 1.5 (§4.2)"),
        ("ACOS", "arithmetic", "inverse cosine", "Lisp 1.5 (§4.2)"),
        ("ATAN", "arithmetic", "inverse tangent", "Lisp 1.5 (§4.2)"),
    ],
    # --- block 10: lookup, sets, higher order, trees -------------------------
    "111000": [  # RASSOC — reverse association becomes property access
        ("ASSQ", "lookup", "association search keyed by eq on the car", "McCarthy 1960"),
        ("RASSQ", "lookup", "association search keyed by eq on the cdr", "Lisp 1.5"),
        ("GETPROP", "lookup", "read a named property from a property list", "Lisp 1.5"),
        ("GET", "lookup", "read a value from a general place", "Common Lisp"),
    ],
    "111001": [  # ACONS — construction becomes tables and property writing
        ("VCONS", "physical-mutation", "destructive vector cons replacing the last cell", "MacLisp"),
        ("TABLERP", "predicate", "test whether a value is a hash table", "MacLisp"),
        ("TABLESPACE", "system", "number of cells in a hash table", "MacLisp"),
        ("PUTPROP", "physical-mutation", "store a named property onto a property list", "Lisp 1.5"),
    ],
    "111010": [  # INTERSECTION — set algebra becomes difference and membership
        ("SET-DIFFERENCE", "set-operation", "elements of one list absent from another", "Lisp 1.5"),
        ("ADJOIN", "set-operation", "add an element to a list unless already present", "MacLisp"),
        ("SUBSETP", "set-operation", "test whether every element of one list is in another", "Common Lisp"),
        ("COLLECTION", "set-operation", "collect the elements of a set, list or sequence", "Common Lisp"),
    ],
    "111011": [  # UNION — union becomes destructive reconciliation
        ("NUNION", "set-operation", "destructive union sharing structure where possible", "MacLisp"),
        ("NRECONC", "set-operation", "destructive reconciliation of two ordered lists", "MacLisp"),
        ("LDIFF", "set-operation", "elements of one list absent from a second list", "Common Lisp"),
        ("TAILP", "predicate", "test whether two lists share a common tail", "Common Lisp"),
    ],
    "111100": [  # MAPCAR — element-wise mapping becomes quantifier mapping
        ("MAP-ANY", "higher-order", "apply a predicate to elements until one succeeds", "Common Lisp"),
        ("MAP", "higher-order", "apply a function to elements of up to three sequences", "Common Lisp"),
        ("NOTANY", "higher-order", "true when no element satisfies the predicate", "Common Lisp"),
        ("SOME", "higher-order", "the first element, or its index, satisfying a predicate", "Common Lisp"),
    ],
    "111101": [  # MAPLIST — tail-wise mapping becomes tail indexing and remapping
        ("MAPCON", "higher-order", "map over lists and concatenate the collected tails", "Lisp 1.5"),
        ("MAPLIST*", "higher-order", "map over successive tails with a final nil", "MacLisp"),
        ("MAPQN", "higher-order", "map the car of each tail list to the cdr", "MacLisp"),
        ("REMAP", "higher-order", "remap the elements of a sequence through a function", "Common Lisp"),
    ],
    "111110": [  # SUBLIS — substitution gains structure printing
        ("PRIN1", "system", "print a datum readably, preserving its structure", "Lisp 1.5"),
        ("PRINC", "system", "print a datum without readability decoration", "Lisp 1.5"),
        ("TERPRI", "system", "terminate the current output line", "Lisp 1.5"),
        ("TREE-EQU", "predicate", "test structural equality of two trees", "Lisp 1.5"),
    ],
    "111111": [  # COPY-TREE — deep copying becomes uniform structure copying
        ("COPY-STRUCTURE", "physical-mutation", "copy a structure instance", "Common Lisp"),
        ("COPY-ARRAY", "physical-mutation", "copy an array element by element", "Common Lisp"),
        ("VECTOR-COPY", "physical-mutation", "copy a general vector into a fresh vector", "Common Lisp"),
        ("COPY-SEQ", "physical-mutation", "copy a sequence into a fresh adjustable sequence", "Common Lisp"),
    ],
}

DESCRIPTION = (
    "Full chronological early-Lisp capability occupancy of Domain 8 following D6 parents, "
    "applying the ratified D3-D6 occupancy rule at width 8."
)

LINEAGE_NOTE = (
    "D8 continues the D4->D5->D6 historical rung as a two-bit extension, because D7 is not a "
    "member of that rung: knowledge/d7-full-map.json records that D7 is NOT a one-bit extension "
    "of a parent domain and owns the Text7/Sound7 articulatory law instead. Every D8 coordinate "
    "therefore records parent_d6 as its lineage parent and parent_d7 as the mechanical one-bit "
    "prefix. Width is part of identity, so a 7-bit sound cell and its 8-bit D8 children are "
    "distinct identities; the lineage does not import the D7 law (#2497)."
)


def selector_name(word: str) -> str:
    """CAR/CDR composition name for a 101/110 descendant (D3 selector law)."""
    letters = "A" if word[:3] == "101" else "D"
    letters += "".join("A" if bit == "0" else "D" for bit in word[3:])
    return f"C{letters}R"


def selector_behavior(word: str) -> str:
    path = selector_name(word)[1:-1]
    inner = "x"
    for letter in reversed(path):
        inner = f"{'car' if letter == 'A' else 'cdr'}({inner})"
    return inner


def build() -> dict:
    d6 = json.loads(D6_PATH.read_text(encoding="utf-8"))
    d6_rows = {row["coordinate"]: row for row in d6["coordinates"]}

    d6_selectors = {c for c in d6_rows if c.startswith(SELECTOR_ROOTS)}
    non_selectors = set(d6_rows) - d6_selectors

    missing = sorted(non_selectors - set(HISTORY))
    extra = sorted(set(HISTORY) - non_selectors)
    if missing or extra:
        raise AssertionError(
            f"HISTORY table does not match the D6 non-selector parents; "
            f"missing={missing} extra={extra}"
        )
    for parent, children in HISTORY.items():
        if len(children) != 4:
            raise AssertionError(f"D6 parent {parent} must have exactly four children")

    coordinates = []
    for value in range(256):
        word = f"{value:08b}"
        parent_d6 = word[:6]
        if parent_d6 in d6_selectors:
            name = selector_name(word)
            row = {
                "coordinate": word,
                "parent_d6": parent_d6,
                "parent_d7": word[:7],
                "name": name,
                "category": "selector",
                "behavior": selector_behavior(word),
                "provenance": "Lisp 1.5 (§4.3)",
                "evidence": "generated-by-admitted-d3-selector-law-2322",
                "lineage_parent_name": d6_rows[parent_d6]["name"],
            }
        else:
            index = value % 4
            name, category, behavior, provenance = HISTORY[parent_d6][index]
            row = {
                "coordinate": word,
                "parent_d6": parent_d6,
                "parent_d7": word[:7],
                "name": name,
                "category": category,
                "behavior": behavior,
                "provenance": provenance,
                "evidence": "agent-derived-historical-continuation",
                "lineage_parent_name": d6_rows[parent_d6]["name"],
            }
        coordinates.append(row)

    names = [row["name"] for row in coordinates]
    duplicates = sorted({name for name, count in Counter(names).items() if count > 1})
    if duplicates:
        raise AssertionError(f"duplicate D8 resident names: {duplicates}")

    # --- admission partition -------------------------------------------------
    # Only the D3 CAR/CDR selector law is admitted, so only the 64 selector
    # coordinates are occupants. The 192 historical rows keep their provenance
    # as attested-but-unadmitted candidates: ADR-005 §4 requires an executable
    # witness before a primitive earns a semantic identity, and the
    # chronological four-per-parent rule is not a law (see falsified_rules).
    admitted = [row for row in coordinates if row["evidence"] == SELECTOR_EVIDENCE]
    unadmitted = [row for row in coordinates if row["evidence"] != SELECTOR_EVIDENCE]
    for row in unadmitted:
        row["admission"] = "attested-not-admitted"
        row["admission_reason"] = (
            "no admitted law generates this coordinate; ADR-005 §4 requires an executable "
            "witness before a coordinate gains a semantic identity"
        )
    for row in admitted:
        row["admission"] = "admitted-by-law"

    status_counts = {
        "total_coordinates": len(coordinates),
        "admitted": len(admitted),
        "attested_not_admitted": len(unadmitted),
        "selector": len(admitted),
    }

    evidence_counts = dict(sorted(Counter(row["evidence"] for row in coordinates).items()))

    return {
        "schema": SCHEMA,
        "domain": "Core.D8",
        "width": 8,
        "capacity": 256,
        "authority": (
            "owner-ratified D8 domain width/ontology only (issue 2410, 2026-10-03). "
            "Occupancy below is AGENT-DERIVED EVIDENCE, not owner-ratified semantic authority: "
            "#2410 states that a D8 coordinate does not become occupied/callable without the "
            "relevant ratified law/witness, and that a PR occupancy map does not replace owner "
            "semantic authority."
        ),
        "issue": ISSUE,
        "description": DESCRIPTION,
        "method": {
            "occupancy_rule": (
                "A D8 coordinate is a D6 coordinate extended by two bits: each of the 64 D6 "
                "coordinates has exactly four D8 children, exactly as each D4 coordinate had two "
                "D5 children and each D5 coordinate had two D6 children."
            ),
            "selector_rule": (
                "The 64 selector coordinates are generated by the admitted D3 law (roots 101=CAR, "
                "110=CDR; appended 0 composes CAR, appended 1 composes CDR). They are never "
                "hand-written; all 16 D6 selector parents have four selector children, which "
                "reproduces exactly the D8 selector forecast of #2322."
            ),
            "historical_rule": (
                "FALSIFIED AND DEMOTED. The earlier rule assigned four chronological "
                "historical Lisp capabilities per D6 parent. Factor-analysis showed it does "
                "not factor into two independent commuting policies the way #2506 does, so it "
                "is not a law. Its 192 coordinates are now attested-not-admitted candidates "
                "whose provenance is preserved, not occupants."
            ),
            "lineage_note": LINEAGE_NOTE,
            "derived_from": {
                "d6_map": "knowledge/d6-historical-full-map.json",
                "d7_map": "knowledge/d7-full-map.json",
                "selector_forecast": "scripts/research-2322-generative-domain-forecast.py",
            },
        },
        "ratification_scope": {
            "precedent": (
                "#2415 (ratified D7): 'Ratification covers the domain width/ontology and "
                "semantic role, not blanket occupancy of all 128 coordinates.' The same "
                "boundary is applied to D8."
            ),
            "ratified": [
                "width = 8 bits",
                "ontology = exact 256-coordinate Core domain",
                "lineage = each D6 coordinate has exactly four D8 children",
            ],
            "not_ratified": [
                "blanket occupancy of all 256 coordinates",
                "any individual coordinate assignment outside the admitted selector law",
            ],
        },
        "non_conflation": {
            "rule": (
                "D8 is an exact 8-bit Core domain. Legacy Sens8 is an 8-bit flat byte table "
                "where the byte is simultaneously address and identity. Equal width does not "
                "imply shared type or shared law, and neither domain implies the other."
            ),
            "precedent": (
                "#2415: Sound7 cells and local sloka/sutra ordinals both use seven-bit values "
                "without implying one arithmetic Number type or law."
            ),
            "measured_overlap": (
                "8 of 183 legacy Sens8 EN surface names also appear in this map, and none of "
                "the eight shares a coordinate with its legacy byte (for example APPLY is "
                "Sens8 10101111 but D8 00001100). D8 is not a relabelled byte table."
            ),
        },
        "falsified_rules": [
            {
                "rule": "four chronological historical Lisp capabilities per D6 parent",
                "falsifier": (
                    "the four children of a parent do not factor into two independent "
                    "commuting policies"
                ),
                "worked_counterexample": (
                    "D6 000001 LOAD -> OPEN, CLOSE, WITH-OPEN-FILE, DRIBBLE. OPEN and CLOSE "
                    "are two poles of one operation, not two instances of one refinement, so "
                    "no commuting square exists."
                ),
                "second_counterexample": (
                    "D6 000011 CURRY -> APPLY, COMPOSE, PARTIAL, FFI-CALL. A foreign-function "
                    "call is not a curry descendant, so the rule produced a category error."
                ),
                "action": "192 coordinates demoted to attested-not-admitted; provenance kept",
            }
        ],
        "next_step": {
            "method": (
                "Derive remaining coordinates one admitted law at a time. Each D8 cell needs "
                "two independent one-bit refinements of its D6 parent plus an executable "
                "witness that the refinements commute, exactly as #2506 did for D6. "
                "Historical Lisp functions then become positive controls, not allocations."
            ),
            "progress_metric": (
                "count of independent admitted laws that earned inhabitants, NOT occupancy "
                "out of 256"
            ),
            "unresolved_parents": 48,
        },
        "honesty": {
            "selector_rows": "generated by an admitted law, not by allocation",
            "historical_rows": (
                "NOT admitted. These are attested-but-unadmitted candidates whose provenance is "
                "preserved as witness material. A chronological capability list is not a law, "
                "and ADR-005 §4 requires an executable witness before a primitive earns a "
                "semantic identity. They are kept visible so the witness material is not lost, "
                "and are not counted as occupancy."
            ),
            "occupancy_claim_withdrawn": (
                "This map no longer claims full 256/256 occupancy. Claiming unallocated=0 "
                "asserted blanket occupancy, which #2415 explicitly declines to ratify."
            ),
            "residency": (
                "Occupancy does not claim semantic irreducibility. Derivability is tracked "
                "separately under #2765."
            ),
            "not_authority": (
                "A coordinate in this map is an occupancy claim under the D3-D6 rule, not a "
                "ratified language contract. Language authority stays in language-contract.lisp."
            ),
        },
        "status_counts": status_counts,
        "evidence_counts": evidence_counts,
        "coordinates": admitted,
        "unassigned_candidates": unadmitted,
    }


def main() -> None:
    data = build()
    OUT_PATH.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"wrote {OUT_PATH.relative_to(ROOT)}")
    print(f"D8 width=8 capacity={data['capacity']}")
    print(f"admitted={data['status_counts']['admitted']} (all by the D3 selector law)")
    print(f"attested_not_admitted={data['status_counts']['attested_not_admitted']}")
    print(f"evidence={json.dumps(data['evidence_counts'])}")
    print("metric=independent admitted laws, NOT occupancy out of 256")


if __name__ == "__main__":
    main()