#!/usr/bin/env python3
"""#2958 — generate canonical D3-D6 owner-coordinate projection.

Authority inputs:
- D3/D4: knowledge/exact-width-admitted-corpus.json (widths 3/4 only)
- D5: knowledge/d5-historical-full-map.json (OD-005)
- D6: knowledge/d6-historical-full-map.json (OD-006)

The generated Rust intentionally excludes human labels, surfaces and legacy
backend bytes. Those are projections/compatibility metadata, not occupancy
authority.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORPUS = ROOT / "knowledge" / "exact-width-admitted-corpus.json"
D5 = ROOT / "knowledge" / "d5-historical-full-map.json"
D6 = ROOT / "knowledge" / "d6-historical-full-map.json"
OUT = ROOT / "crates" / "sens" / "src" / "domain_owner_generated.rs"


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def owner_rows():
    corpus = load_json(CORPUS)
    d5 = load_json(D5)
    d6 = load_json(D6)
    rows = []

    for row in corpus["rows"]:
        width = row["width"]
        word = row["word"]
        status = row["status"]
        if width == 3 and word != "000" and status == "admitted":
            rows.append((3, word, 0))
        elif width == 4 and status in {"admitted", "generated"}:
            rows.append((4, word, 0))

    if d5["width"] != 5 or d5["capacity"] != 32 or len(d5["coordinates"]) != 32:
        raise SystemExit("OD-005 shape mismatch")
    if d6["width"] != 6 or d6["capacity"] != 64 or len(d6["coordinates"]) != 64:
        raise SystemExit("OD-006 shape mismatch")

    rows.extend((5, row["coordinate"], 1) for row in d5["coordinates"])
    rows.extend((6, row["coordinate"], 2) for row in d6["coordinates"])
    rows.sort(key=lambda row: (row[0], int(row[1], 2)))

    if len(rows) != 117:
        raise SystemExit(f"expected 117 owner coordinates, got {len(rows)}")
    if len({(width, word) for width, word, _ in rows}) != len(rows):
        raise SystemExit("duplicate exact-domain coordinate")

    counts = {width: sum(1 for row in rows if row[0] == width) for width in (3, 4, 5, 6)}
    if counts != {3: 7, 4: 14, 5: 32, 6: 64}:
        raise SystemExit(f"owner count mismatch: {counts}")

    for control in [(4, "1100"), (5, "01010"), (6, "001111")]:
        if not any((width, word) == control for width, word, _ in rows):
            raise SystemExit(f"missing positive control D{control[0]}:{control[1]}")

    return rows


def render(rows):
    body = "\n".join(
        f"    DomainOwnerCoordinate {{ width: {width}, bits: 0b{word}, source: {source} }},"
        for width, word, source in rows
    )
    return f"""// @generated by scripts/generate-domain-owner-registry.py; DO NOT EDIT.
//
// Canonical owner occupancy only. Human labels, surfaces and historical
// backend bytes are deliberately excluded from this artifact.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct DomainOwnerCoordinate {{
    pub(crate) width: u8,
    pub(crate) bits: u8,
    pub(crate) source: u8,
}}

pub(crate) const DOMAIN_OWNER_COORDINATES: &[DomainOwnerCoordinate] = &[
{body}
];

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn generated_projection_has_owner_counts_and_controls() {{
        assert_eq!(DOMAIN_OWNER_COORDINATES.len(), 117);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 3).count(), 7);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 4).count(), 14);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 5).count(), 32);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 6).count(), 64);

        for (width, bits) in [(4, 0b1100), (5, 0b01010), (6, 0b001111)] {{
            assert!(DOMAIN_OWNER_COORDINATES
                .iter()
                .any(|row| row.width == width && row.bits == bits));
        }}
    }}

    #[test]
    fn generated_projection_has_unique_domain_coordinates() {{
        let mut seen = std::collections::HashSet::new();
        for row in DOMAIN_OWNER_COORDINATES {{
            assert!(seen.insert((row.width, row.bits)));
        }}
    }}
}}
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    expected = render(owner_rows())
    if args.check:
        actual = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if actual != expected:
            raise SystemExit("domain owner generated projection is stale")
        print("domain owner generated projection: PASS")
        return 0

    OUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
