#!/usr/bin/env python3
"""#487/#2372: derive compact coverage inputs from Lisp admission + pinned #175 evidence.

Transport/projection only. This tool does not decide semantics or full-form coverage.
It fails closed on any admission head that cannot map to pinned evidence.
"""
from __future__ import annotations
import argparse, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / "lib/machine/xed/generated/machine-evidence.lisp"
ADMISSION = ROOT / "lib/machine/admission/x86-64.lisp"
INDEX = ROOT / "lib/machine/encoding/admitted-iclass-index.lisp"
PROJECTION = ROOT / "lib/machine/encoding/admission-iclass-projection.lisp"

SET_ALIAS = {
    "setc":"SETB","setnc":"SETNB","setae":"SETNB","sete":"SETZ","setne":"SETNZ",
    "setna":"SETBE","seta":"SETNBE","setpe":"SETP","setpo":"SETNP","setnge":"SETL",
    "setge":"SETNL","setng":"SETLE","setg":"SETNLE",
}
CMOV_ALIAS = {
    "cmovc":"CMOVB","cmovnc":"CMOVNB","cmovae":"CMOVNB","cmove":"CMOVZ",
    "cmovne":"CMOVNZ","cmovna":"CMOVBE","cmova":"CMOVNBE","cmovpe":"CMOVP",
    "cmovpo":"CMOVNP","cmovnge":"CMOVL","cmovge":"CMOVNL","cmovng":"CMOVLE",
    "cmovg":"CMOVNLE",
}
SPECIAL = {
    "ret":("X86-BASE","RET_NEAR"),
    "call-rel32":("X86-BASE","CALL_NEAR"), "call-r64":("X86-BASE","CALL_NEAR"),
    "movsd-xmm-xmm":("SSE2","MOVSD_XMM"),
    "movq-xmm-r64":("SSE2","MOVQ"), "movq-r64-xmm":("SSE2","MOVQ"),
    "rep-stosq":("X86-64","REP_STOSQ"), "rep-stosb":("X86-BASE","REP_STOSB"),
    "rep-movsq":("X86-64","REP_MOVSQ"), "rep-movsb":("X86-BASE","REP_MOVSB"),
}

def balanced_blocks(text: str, name: str) -> list[str]:
    out=[]; needle="("+name; pos=0
    while True:
        start=text.find(needle,pos)
        if start < 0: return out
        after=text[start+len(needle):start+len(needle)+1]
        if after and not (after.isspace() or after==")"):
            pos=start+len(needle); continue
        depth=0; string=False; escape=False; comment=False
        for i in range(start,len(text)):
            ch=text[i]
            if comment:
                if ch=="\n": comment=False
                continue
            if string:
                if escape: escape=False
                elif ch=="\\": escape=True
                elif ch=='"': string=False
                continue
            if ch==";": comment=True; continue
            if ch=='"': string=True; continue
            if ch=="(": depth+=1
            elif ch==")":
                depth-=1
                if depth==0:
                    out.append(text[start:i+1]); pos=i+1; break
        else:
            raise ValueError(f"unterminated ({name} block")

def quoted(block: str, key: str) -> str:
    m=re.search(r"\("+re.escape(key)+r'\s+"((?:\\.|[^"\\])*)"\)',block)
    if not m: raise ValueError(f"missing {key}")
    raw=m.group(1)
    return re.sub(r"\\(.)",r"\1",raw)

def evidence_rows(text: str) -> list[tuple[str,str]]:
    rows=[]
    for b in balanced_blocks(text,"form"):
        em=re.search(r"\(extension\s+([^\s()]+)\)",b)
        if em: rows.append((em.group(1),quoted(b,"iclass")))
    return rows

def admission_heads(text: str) -> list[str]:
    start=text.find("(00001001 x86-admitted-instruction-patterns")
    if start < 0: raise ValueError("x86-admitted-instruction-patterns missing")
    block=balanced_blocks(text[start:],"00001001")[0]
    heads=[]
    for line in block.splitlines():
        m=(re.match(r"^\s{4}\(\(([A-Za-z0-9?+*/<>=!._:-]+)",line)
           or re.match(r"^\s{5}\(([A-Za-z0-9?+*/<>=!._:-]+)",line))
        if m and m.group(1) not in heads: heads.append(m.group(1))
    return heads

def derive(evidence: list[tuple[str,str]], heads: list[str]):
    by_iclass={}
    for ext,iclass in evidence: by_iclass.setdefault(iclass,[]).append(ext)
    pairs={}
    orphans=[]
    for head in heads:
        if head in SPECIAL:
            pair=SPECIAL[head]
        else:
            prefix=head.split("-",1)[0]
            iclass=SET_ALIAS.get(prefix,CMOV_ALIAS.get(prefix,prefix.upper()))
            exts=by_iclass.get(iclass,[])
            pair=(exts[0],iclass) if len(exts)==1 else None
        if pair is None:
            orphans.append(head); continue
        if pair not in evidence:
            raise ValueError(f"mapped admission {head} -> {pair} absent from pinned evidence")
        pairs.setdefault(pair,[]).append(head)
    if orphans:
        raise ValueError("unmapped admission heads: "+", ".join(orphans))
    return pairs

def render_index(evidence):
    rows=sorted(evidence,key=lambda p:(p[1],p[0]))
    lines=[
      "; GENERATED by scripts/generate-encoder-coverage-input.py -- do not hand-edit.",
      "; Compact #175 evidence projection: no status, opcode, semantic ID, or policy.","",
      "(x86-admitted-iclass-index/2",f"  (pair-count #b{len(rows):b})",
    ]
    lines += [f'  (00101110 {ext} "{iclass}")' for ext,iclass in rows]
    return "\n".join(lines+[" )".replace(" ","",1),""])

def render_projection(heads,pairs):
    lines=[
      "; GENERATED by scripts/generate-encoder-coverage-input.py -- do not hand-edit.",
      "; Derived mechanically from Lisp admission + pinned #175 evidence.",
      "; A partial pair means at least one structured admitted form maps to the ICLASS;",
      "; it does NOT claim every XED operand/addressing form is implemented.","",
      "(x86-admission-iclass-projection/1",
      f"  (admission-head-count #b{len(heads):b})",
      f"  (partial-pair-count #b{len(pairs):b})",
      "  (orphan-count #b0)",
    ]
    for (ext,iclass),hs in sorted(pairs.items(),key=lambda kv:(kv[0][1],kv[0][0])):
        lines.append(f'  (partial {ext} "{iclass}" (heads {" ".join(hs)}))')
    return "\n".join(lines+[")",""])

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--check",action="store_true")
    ns=ap.parse_args()
    evidence=evidence_rows(EVIDENCE.read_text())
    heads=admission_heads(ADMISSION.read_text())
    pairs=derive(evidence,heads)
    outputs={INDEX:render_index(evidence),PROJECTION:render_projection(heads,pairs)}
    if ns.check:
        bad=[str(p.relative_to(ROOT)) for p,want in outputs.items() if not p.exists() or p.read_text()!=want]
        if bad:
            print("stale coverage input projection: "+", ".join(bad),file=sys.stderr); return 1
        print(f"coverage-input --check: {len(evidence)} evidence pairs, {len(heads)} admission heads, {len(pairs)} partial pairs")
        return 0
    for p,data in outputs.items():
        p.parent.mkdir(parents=True,exist_ok=True);p.write_text(data)
        print(f"wrote {p.relative_to(ROOT)}")
    return 0

if __name__=="__main__":
    raise SystemExit(main())
