#!/usr/bin/env python3
"""Generate the current human-surface projection table.

Semantic authority stays in exact DomainIdentity/domain laws.  This generator
only turns the machine-readable surface spelling table into a Rust projection.

Usage:
  python3 scripts/generate_current_domain_surfaces.py
  python3 scripts/generate_current_domain_surfaces.py --check
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "lib" / "surface" / "current-domain-surfaces.tsv"
OUTPUT = ROOT / "crates" / "sens" / "src" / "human_surface_generated.rs"


def rust_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def read_rows() -> list[dict[str, str]]:
    with SOURCE.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        rows = [dict(row) for row in reader]

    required = {"domain", "bits", "en", "uk", "sa", "status"}
    if not rows:
        raise ValueError("surface table is empty")
    if set(rows[0]) != required:
        raise ValueError(f"surface table columns must be {sorted(required)}")

    seen_identity: set[tuple[int, str]] = set()
    seen_spelling: dict[str, tuple[int, str]] = {}

    for row in rows:
        domain = row["domain"]
        if not domain.startswith("D") or not domain[1:].isdigit():
            raise ValueError(f"invalid domain: {domain!r}")
        width = int(domain[1:])
        if not 1 <= width <= 8:
            raise ValueError(f"current Core surface width out of range: {domain}")
        bits = row["bits"]
        if len(bits) != width or any(ch not in "01" for ch in bits):
            raise ValueError(f"{domain} requires exactly {width} bits: {bits!r}")
        if row["status"] != "stable":
            raise ValueError(f"only stable current-native rows may be generated: {row!r}")

        identity = (width, bits)
        if identity in seen_identity:
            raise ValueError(f"duplicate exact domain identity: D{width}:{bits}")
        seen_identity.add(identity)

        for language in ("en", "uk", "sa"):
            spelling = row[language]
            if not spelling:
                raise ValueError(f"empty {language} spelling for D{width}:{bits}")
            prior = seen_spelling.get(spelling)
            if prior is not None and prior != identity:
                raise ValueError(
                    f"surface collision {spelling!r}: D{prior[0]}:{prior[1]} vs D{width}:{bits}"
                )
            seen_spelling[spelling] = identity

    return rows


def generated_text(rows: list[dict[str, str]]) -> str:
    lines = [
        "// @generated by scripts/generate_current_domain_surfaces.py",
        "// Source: lib/surface/current-domain-surfaces.tsv",
        "// Do not edit by hand.",
        "",
        "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
        "pub(crate) struct CurrentHumanSurfaceRow {",
        "    pub(crate) width: u8,",
        "    pub(crate) bits: u8,",
        "    pub(crate) en: &'static str,",
        "    pub(crate) uk: &'static str,",
        "    pub(crate) sa: &'static str,",
        "}",
        "",
        "pub(crate) const CURRENT_HUMAN_SURFACES: &[CurrentHumanSurfaceRow] = &[",
    ]
    for row in rows:
        width = int(row["domain"][1:])
        bits = row["bits"]
        lines.extend(
            [
                "    CurrentHumanSurfaceRow {",
                f"        width: {width},",
                f"        bits: 0b{bits},",
                f"        en: {rust_string(row['en'])},",
                f"        uk: {rust_string(row['uk'])},",
                f"        sa: {rust_string(row['sa'])},",
                "    },",
            ]
        )
    lines.extend(["];", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    text = generated_text(read_rows())
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            raise SystemExit(
                "human surface projection is stale; run "
                "python3 scripts/generate_current_domain_surfaces.py"
            )
        print("current domain surface projection: fresh")
        return 0

    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
