#!/usr/bin/env python3
"""#2958 / #3029 — generate full D1-D8 exact-domain occupancy projection.

Authority:
- #3020: every canonical SENS identity is exact binary object + exact domain.
- #3029: every D1-D8 coordinate is owner-ratified occupied.

This generator projects occupancy identity only. It does NOT invent role,
law, derivability, callability, surface spelling, or runtime mechanism.
Those facts remain separate downstream evidence.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OCCUPANCY = ROOT / "knowledge" / "d1-d8-full-occupancy.json"
OUT = ROOT / "crates" / "sens" / "src" / "domain_owner_generated.rs"

EXPECTED_WIDTHS = tuple(range(1, 9))
EXPECTED_TOTAL = sum(1 << width for width in EXPECTED_WIDTHS)


def load_authority():
    data = json.loads(OCCUPANCY.read_text(encoding="utf-8"))
    if data.get("authority") != "#3029":
        raise SystemExit("full-occupancy authority must be #3029")
    if data.get("status") != "owner-ratified":
        raise SystemExit("D1-D8 occupancy projection is not owner-ratified")
    domains = data.get("domains", [])
    widths = tuple(row["width"] for row in domains)
    if widths != EXPECTED_WIDTHS:
        raise SystemExit(f"D1-D8 width set mismatch: {widths}")
    for row in domains:
        expected = 1 << row["width"]
        if row["capacity"] != expected or row["occupied"] != expected:
            raise SystemExit(f"D{row['width']} is not fully occupied: {row}")
    if data.get("total_capacity") != EXPECTED_TOTAL or data.get("total_occupied") != EXPECTED_TOTAL:
        raise SystemExit("D1-D8 total occupancy must be 510/510")
    return domains


def owner_rows(domains):
    rows = []
    for row in domains:
        width = row["width"]
        for bits in range(row["occupied"]):
            rows.append((width, bits))
    if len(rows) != EXPECTED_TOTAL:
        raise SystemExit(f"full D1-D8 occupancy must contain {EXPECTED_TOTAL} identities")
    if len(set(rows)) != len(rows):
        raise SystemExit("duplicate exact-domain coordinate")
    return rows


def render(rows):
    body = "\n".join(
        f"    DomainOwnerCoordinate {{ width: {width}, bits: 0b{bits:0{width}b} }},"
        for width, bits in rows
    )
    return f"""// @generated by scripts/generate-domain-owner-registry.py; DO NOT EDIT.
//
// Full owner-ratified D1-D8 occupancy projection from #3029.
// Every row is canonical exact-domain binary identity: (width, exact bits).
// This file projects OCCUPANCY ONLY. It does not assert role, law, derivability,
// callability, human surface, legacy byte, or runtime mechanism.
// Absence/presence in executable mechanism tables is a separate question.

#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
pub(crate) struct DomainOwnerCoordinate {{
    pub(crate) width: u8,
    pub(crate) bits: u8,
}}

pub(crate) const DOMAIN_WIDTHS_IN_SCOPE: &[u8] = &[1, 2, 3, 4, 5, 6, 7, 8];

pub(crate) const DOMAIN_OWNER_COORDINATES: &[DomainOwnerCoordinate] = &[
{body}
];

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn all_d1_d8_coordinates_are_owner_ratified_residents() {{
        let expected = [(1, 2usize), (2, 4), (3, 8), (4, 16), (5, 32), (6, 64), (7, 128), (8, 256)];
        assert_eq!(DOMAIN_WIDTHS_IN_SCOPE, &[1, 2, 3, 4, 5, 6, 7, 8]);
        for (width, occupied) in expected {{
            assert_eq!(
                DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == width).count(),
                occupied,
                "D{{width}} occupancy drifted from #3029"
            );
        }}
        assert_eq!(DOMAIN_OWNER_COORDINATES.len(), 510);
    }}

    #[test]
    fn projection_contains_structural_sound_and_full_d8_identity_space() {{
        for (width, bits) in [
            (1, 0b0),
            (2, 0b00),
            (3, 0b000),
            (4, 0b0101),
            (4, 0b1001),
            (7, 0b0000000),
            (7, 0b1111111),
            (8, 0b00000000),
            (8, 0b11111111),
        ] {{
            assert!(DOMAIN_OWNER_COORDINATES
                .iter()
                .any(|row| row.width == width && row.bits == bits));
        }}
    }}

    #[test]
    fn equal_payloads_in_different_domains_remain_distinct_coordinates() {{
        for width in 1u8..8 {{
            assert!(DOMAIN_OWNER_COORDINATES.iter().any(|row| row.width == width && row.bits == 1));
            assert!(DOMAIN_OWNER_COORDINATES.iter().any(|row| row.width == width + 1 && row.bits == 1));
            assert_ne!(
                DomainOwnerCoordinate {{ width, bits: 1 }},
                DomainOwnerCoordinate {{ width: width + 1, bits: 1 }}
            );
        }}
    }}

    #[test]
    fn full_occupancy_does_not_encode_callability_or_role() {{
        let fields_are_only_identity = |row: &DomainOwnerCoordinate| (row.width, row.bits);
        assert_eq!(fields_are_only_identity(&DOMAIN_OWNER_COORDINATES[0]), (1, 0));
    }}
}}
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    expected = render(owner_rows(load_authority()))
    if args.check:
        actual = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if actual != expected:
            raise SystemExit("D1-D8 owner occupancy projection is stale")
        print("D1-D8 full owner occupancy projection: PASS (510/510)")
        return 0

    OUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
