#!/usr/bin/env python3
"""#2958 — generate canonical D3-D8 owner-residency projection.

Authority inputs:
- D3/D4: knowledge/exact-width-admitted-corpus.json
- D5: knowledge/d5-historical-full-map.json (OD-005)
- D6: knowledge/d6-historical-full-map.json (OD-006)
- D7 existence/non-callability boundary: language-contract.lisp
- D8 selector residency: language-contract.lisp root+suffix law

Important: domain existence is not occupancy. D7 intentionally contributes
zero owner-residency rows here. knowledge/d7-full-map.json is research-only and
MUST NOT mint residency. D8 contributes only selector-law descendants; width 8
does not imply full occupancy or callability.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORPUS = ROOT / "knowledge" / "exact-width-admitted-corpus.json"
D5 = ROOT / "knowledge" / "d5-historical-full-map.json"
D6 = ROOT / "knowledge" / "d6-historical-full-map.json"
CONTRACT = ROOT / "language-contract.lisp"
OUT = ROOT / "crates" / "sens" / "src" / "domain_owner_generated.rs"

DOMAIN_WIDTHS_IN_SCOPE = (3, 4, 5, 6, 7, 8)


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def assert_contract_guards(contract: str) -> None:
    if "(d7-sound-local-ordinal" not in contract or "Occupancy remains law/witness-specific." not in contract:
        raise SystemExit("D7 owner contract guard missing")
    if "(d8-exact-core-domain" not in contract or "admitted selector descendants may execute from the selector root+suffix law" not in contract:
        raise SystemExit("D8 selector contract guard missing")


def owner_rows():
    corpus = load_json(CORPUS)
    d5 = load_json(D5)
    d6 = load_json(D6)
    contract = CONTRACT.read_text(encoding="utf-8")
    assert_contract_guards(contract)
    rows = []

    for row in corpus["rows"]:
        width = row["width"]
        word = row["word"]
        status = row["status"]
        if width == 3 and word != "000" and status == "admitted":
            rows.append((3, word, 0))
        elif width == 4 and status in {"admitted", "generated"}:
            rows.append((4, word, 0))

    if d5["width"] != 5 or d5["capacity"] != 32 or len(d5["coordinates"]) != 32:
        raise SystemExit("OD-005 shape mismatch")
    if d6["width"] != 6 or d6["capacity"] != 64 or len(d6["coordinates"]) != 64:
        raise SystemExit("OD-006 shape mismatch")

    rows.extend((5, row["coordinate"], 1) for row in d5["coordinates"])
    rows.extend((6, row["coordinate"], 2) for row in d6["coordinates"])

    # D7: zero rows by design. Its owner-ratified witness explicitly makes no
    # occupancy claim over the 128 mechanically valid coordinates.

    # D8: only the selector family certified by the root+suffix law.
    for root in ("101", "110"):
        for suffix in range(32):
            rows.append((8, root + format(suffix, "05b"), 3))

    rows.sort(key=lambda row: (row[0], int(row[1], 2)))

    expected_counts = {3: 7, 4: 14, 5: 32, 6: 64, 7: 0, 8: 64}
    counts = {width: sum(1 for row in rows if row[0] == width) for width in DOMAIN_WIDTHS_IN_SCOPE}
    if counts != expected_counts:
        raise SystemExit(f"owner count mismatch: {counts}")
    if len({(width, word) for width, word, _ in rows}) != len(rows):
        raise SystemExit("duplicate exact-domain coordinate")

    for control in [
        (4, "1100"),
        (5, "01010"),
        (6, "001111"),
        (8, "10100000"),
        (8, "11011111"),
    ]:
        if not any((width, word) == control for width, word, _ in rows):
            raise SystemExit(f"missing positive control D{control[0]}:{control[1]}")

    if any(width == 7 for width, _, _ in rows):
        raise SystemExit("D7 residency must not be invented by width")
    if any(width == 8 and not (word.startswith("101") or word.startswith("110")) for width, word, _ in rows):
        raise SystemExit("D8 non-selector residency must not be invented")

    return rows


def render(rows):
    body = "\n".join(
        f"    DomainOwnerCoordinate {{ width: {width}, bits: 0b{word}, source: {['DomainOwnerSource::ExactWidthCorpus','DomainOwnerSource::Od005','DomainOwnerSource::Od006','DomainOwnerSource::SelectorLaw'][source]} }},"
        for width, word, source in rows
    )
    return f"""// @generated by scripts/generate-domain-owner-registry.py; DO NOT EDIT.
//
// Canonical owner residency projection for D3-D8.
// Domain existence and resident coordinates are deliberately separate facts.
// D7 is in scope but currently contributes zero residency rows because the
// owner contract keeps D7 occupancy law/witness-specific and the ratification
// witness makes no 128-coordinate occupancy claim.
// D8 contributes only selector descendants certified by the root+suffix law.
// Human labels, surfaces and historical backend bytes are excluded.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum DomainOwnerSource {{
    ExactWidthCorpus,
    Od005,
    Od006,
    SelectorLaw,
}}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct DomainOwnerCoordinate {{
    pub(crate) width: u8,
    pub(crate) bits: u8,
    pub(crate) source: DomainOwnerSource,
}}

pub(crate) const DOMAIN_WIDTHS_IN_SCOPE: &[u8] = &[3, 4, 5, 6, 7, 8];

pub(crate) const DOMAIN_OWNER_COORDINATES: &[DomainOwnerCoordinate] = &[
{body}
];

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn generated_projection_separates_domain_existence_from_residency() {{
        assert_eq!(DOMAIN_WIDTHS_IN_SCOPE, &[3, 4, 5, 6, 7, 8]);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 3).count(), 7);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 4).count(), 14);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 5).count(), 32);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 6).count(), 64);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 7).count(), 0);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 8).count(), 64);

        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.source == DomainOwnerSource::ExactWidthCorpus).count(), 21);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.source == DomainOwnerSource::Od005).count(), 32);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.source == DomainOwnerSource::Od006).count(), 64);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.source == DomainOwnerSource::SelectorLaw).count(), 64);
    }}

    #[test]
    fn generated_projection_has_controls_without_width_based_invention() {{
        for (width, bits) in [
            (4, 0b1100),
            (5, 0b01010),
            (6, 0b001111),
            (8, 0b10100000),
            (8, 0b11011111),
        ] {{
            assert!(DOMAIN_OWNER_COORDINATES
                .iter()
                .any(|row| row.width == width && row.bits == bits));
        }}
        assert!(!DOMAIN_OWNER_COORDINATES.iter().any(|row| row.width == 7));
        assert!(!DOMAIN_OWNER_COORDINATES
            .iter()
            .any(|row| row.width == 8 && row.bits < 0b10100000));
    }}

    #[test]
    fn generated_projection_has_unique_domain_coordinates() {{
        let mut seen = std::collections::HashSet::new();
        for row in DOMAIN_OWNER_COORDINATES {{
            assert!(seen.insert((row.width, row.bits)));
        }}
    }}
}}
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    expected = render(owner_rows())
    if args.check:
        actual = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if actual != expected:
            raise SystemExit("domain owner generated projection is stale")
        print("domain owner generated projection: PASS")
        return 0

    OUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
