#!/usr/bin/env python3
"""#2250/#2253/#2254: first arithmetic function-algebra placement witness.

Research only. This script does not allocate or renumber production SENS identities.

It checks two candidate mathematical structures over a bounded exact-rational corpus:
1. one group-family schema shared by ADD/NEG/SUB and MUL/RECIP/DIV;
2. the Klein-four action generated by argument swap (S) and PredicateBit
   negation (N) over LT, producing LT/GT/GE/LE.

Binary coordinates reported here are candidate research coordinates, not
language authority.
"""

from __future__ import annotations

from fractions import Fraction
from itertools import product


def corpus(limit: int = 4) -> tuple[Fraction, ...]:
    return tuple(sorted({
        Fraction(n, d)
        for n in range(-limit, limit + 1)
        for d in range(1, limit + 1)
    }))


Q = corpus()


def verify_group_family() -> dict[str, int]:
    additive_cases = 0
    multiplicative_inverse_cases = 0
    multiplicative_quotient_cases = 0

    for a, b in product(Q, repeat=2):
        assert a - b == a + (-b)
        additive_cases += 1

        if a != 0:
            assert a * (1 / a) == 1
            multiplicative_inverse_cases += 1

        if b != 0:
            assert a / b == a * (1 / b)
            multiplicative_quotient_cases += 1

    for thunk in (
        lambda: Fraction(1, 0),
        lambda: Fraction(1) / Fraction(0),
    ):
        try:
            thunk()
        except ZeroDivisionError:
            pass
        else:
            raise AssertionError("zero reciprocal/division must be rejected")

    return {
        "additive_quotient_cases": additive_cases,
        "multiplicative_inverse_cases": multiplicative_inverse_cases,
        "multiplicative_quotient_cases": multiplicative_quotient_cases,
        "zero_inverse_rejected": 1,
        "zero_division_rejected": 1,
    }


# Action coordinate bits:
#   bit 0 = swap arguments
#   bit 1 = negate PredicateBit result
I, S, N, NS = 0b00, 0b01, 0b10, 0b11


def transformed_lt(action: int, a: Fraction, b: Fraction) -> bool:
    if action & S:
        a, b = b, a
    answer = a < b
    if action & N:
        answer = not answer
    return answer


def compose_actions(first: int, second: int, a: Fraction, b: Fraction) -> bool:
    """Apply first then second as transformations of the LT predicate."""
    swap = bool(first & S) ^ bool(second & S)
    negate = bool(first & N) ^ bool(second & N)
    if swap:
        a, b = b, a
    answer = a < b
    if negate:
        answer = not answer
    return answer


def verify_order_klein4() -> dict[str, int]:
    relation_cases = 0
    composition_cases = 0

    for a, b in product(Q, repeat=2):
        assert transformed_lt(I, a, b) == (a < b)
        assert transformed_lt(S, a, b) == (a > b)
        assert transformed_lt(N, a, b) == (a >= b)
        assert transformed_lt(NS, a, b) == (a <= b)
        relation_cases += 4

        for first, second in product((I, S, N, NS), repeat=2):
            assert compose_actions(first, second, a, b) == transformed_lt(
                first ^ second, a, b
            )
            composition_cases += 1

    return {
        "relation_cases": relation_cases,
        "action_composition_cases": composition_cases,
    }


def group_family_candidate() -> tuple[tuple[str, str, int], ...]:
    return (
        ("additive-root", "0", 1),
        ("additive-inverse", "00", 2),
        ("additive-quotient", "01", 2),
        ("multiplicative-root", "1", 1),
        ("multiplicative-inverse", "10", 2),
        ("multiplicative-quotient", "11", 2),
    )


def main() -> None:
    group = verify_group_family()
    order = verify_order_klein4()
    placement = group_family_candidate()

    print(f"Q-CORPUS-SIZE={len(Q)}")
    for key, value in group.items():
        print(f"{key.upper().replace('_', '-')}={value}")
    for key, value in order.items():
        print(f"{key.upper().replace('_', '-')}={value}")

    print("GROUP-FAMILY-CANDIDATE:")
    for role, code, width in placement:
        print(f"  {code}\twidth={width}\t{role}")

    total_bits = sum(width for _, _, width in placement)
    flat3_bits = 6 * 3
    print(f"GROUP-FAMILY-TOTAL-IDENTITY-BITS={total_bits}")
    print(f"FLAT-3BIT-SIX-OPS-BITS={flat3_bits}")
    print(f"IDENTITY-BIT-DELTA={total_bits-flat3_bits}")
    print("NOTE=framing/domain-tag/proof-metadata costs excluded")

    print("ORDER-KLEIN4-CANDIDATE:")
    print("  00 LT")
    print("  01 GT   ; swap")
    print("  10 GE   ; predicate-negation")
    print("  11 LE   ; swap+predicate-negation")
    print("ORDER-ACTION-LAW=compose-actions-via-xor")
    print("STATUS=PASS-BOUNDED-EXACT-Q-WITNESS")
    print("AUTHORITY=RESEARCH-ONLY-NO-PRODUCTION-ALLOCATION")


if __name__ == "__main__":
    main()
