; D6 human surface projection.
; Projection only: semantic authority remains exact D6 bits + owner-ratified D6 law.
; Authority: #3393 / knowledge/d1-d7-foundation.json / knowledge/d6-ratified.json.
; Historical flat-byte coordinates are not valid keys here.
;
; Row format:
; (row D6 "BITS" ROLE "EN" UK SA UK_STATUS SA_STATUS)
;
; UK/SA may be () when no current human peer has been selected.
; Candidate fills are lexical projections only; they do not ratify new semantics.
; Empty marker is projection metadata only; it is not a semantic object.

(domain-surfaces-d6
  (schema domain-surfaces-d6/1)
  (status projection-only)
  (identity-law "surface -> exact (D6,bits) -> D6 law")
  (languages en uk sa)

  (row D6 "000000" function "length" "довжина" "pramāṇa" donor-or-selected donor-or-selected)
  (row D6 "000001" function "length-onto" "довжина-до" "pramāṇa-saṅkalana" candidate candidate)
  (row D6 "000010" function "min-list" "найменше-у-списку" "śreṇī-alpatara" donor-or-selected candidate)
  (row D6 "000011" function "max-list" "найбільше-у-списку" "śreṇī-brhattara" donor-or-selected candidate)
  (row D6 "000100" function "nth" "елемент-списку-за-індексом" "kramāṅka" donor-or-selected donor-or-selected)
  (row D6 "000101" function "maplist" "відобразити-залишки" "śeṣa-āvartana" donor-or-selected candidate)
  (row D6 "000110" function "macroexpand-1" "розгорнути-макрос-1" "vistāra-rūpa-prasāra-eka" candidate candidate)
  (row D6 "000111" function "macroexpand" "розгорнути-макрос" "vistāra-rūpa-prasāra" candidate candidate)
  (row D6 "001000" form "let" "нехай" "sthānika-bandha" donor-or-selected candidate)
  (row D6 "001001" form "let*" "нехай*" "krama-sthānika-bandha" donor-or-selected candidate)
  (row D6 "001010" function "sublis" "підставити-пари" "yugma-ādeśa" donor-or-selected candidate)
  (row D6 "001011" function "compose" "скласти-функції" "phalana-saṃyojana" candidate candidate)
  (row D6 "001100" function "rassoc" "знайти-за-значенням" "mūlya-saṃbandha-anveṣaṇa" candidate candidate)
  (row D6 "001101" function "acons" "додати-асоціацію" "saṃbandha-niveśana" candidate candidate)
  (row D6 "001110" function "add1" "додати-1" "eka-yoga" candidate candidate)
  (row D6 "001111" function "sub1" "відняти-1" "eka-viyoga" candidate candidate)
  (row D6 "010000" predicate "evenp?" "парне?" "sama-saṅkhyā" candidate candidate)
  (row D6 "010001" predicate "oddp?" "непарне?" "viṣama-saṅkhyā" candidate candidate)
  (row D6 "010010" function "neg" "змінити-знак" "cihna-viparyaya" candidate candidate)
  (row D6 "010011" function "abs" "модуль" "rūpa" donor-or-selected donor-or-selected)
  (row D6 "010100" function "remainder" "остача" "avasiṣṭa" donor-or-selected donor-or-selected)
  (row D6 "010101" function "gcd" "найбільший-спільний-дільник" "mahattama-samāpavartaka" candidate candidate)
  (row D6 "010110" function "recip" "обернене" "vyutkrama" candidate candidate)
  (row D6 "010111" function "expt" "піднести-до-степеня" "ghāta" candidate candidate)
  (row D6 "011000" selector "cdaaar" "решта-від-першого-від-першого-від-першого" "śeṣa-ādi-ādi-ādi" generated generated)
  (row D6 "011001" selector "cdaadr" "решта-від-першого-від-першого-від-решти" "śeṣa-ādi-ādi-śeṣa" generated generated)
  (row D6 "011010" selector "cdadar" "решта-від-першого-від-решти-від-першого" "śeṣa-ādi-śeṣa-ādi" generated generated)
  (row D6 "011011" selector "cdaddr" "решта-від-першого-від-решти-від-решти" "śeṣa-ādi-śeṣa-śeṣa" generated generated)
  (row D6 "011100" selector "cddaar" "решта-від-решти-від-першого-від-першого" "śeṣa-śeṣa-ādi-ādi" generated generated)
  (row D6 "011101" selector "cddadr" "решта-від-решти-від-першого-від-решти" "śeṣa-śeṣa-ādi-śeṣa" generated generated)
  (row D6 "011110" selector "cdddar" "решта-від-решти-від-решти-від-першого" "śeṣa-śeṣa-śeṣa-ādi" generated generated)
  (row D6 "011111" selector "cddddr" "решта-від-решти-від-решти-від-решти" "śeṣa-śeṣa-śeṣa-śeṣa" generated generated)
  (row D6 "100000" selector "caaaar" "перше-від-першого-від-першого-від-першого" "ādi-ādi-ādi-ādi" generated generated)
  (row D6 "100001" selector "caaadr" "перше-від-першого-від-першого-від-решти" "ādi-ādi-ādi-śeṣa" generated generated)
  (row D6 "100010" selector "caadar" "перше-від-першого-від-решти-від-першого" "ādi-ādi-śeṣa-ādi" generated generated)
  (row D6 "100011" selector "caaddr" "перше-від-першого-від-решти-від-решти" "ādi-ādi-śeṣa-śeṣa" generated generated)
  (row D6 "100100" selector "cadaar" "перше-від-решти-від-першого-від-першого" "ādi-śeṣa-ādi-ādi" generated generated)
  (row D6 "100101" selector "cadadr" "перше-від-решти-від-першого-від-решти" "ādi-śeṣa-ādi-śeṣa" generated generated)
  (row D6 "100110" selector "caddar" "перше-від-решти-від-решти-від-першого" "ādi-śeṣa-śeṣa-ādi" generated generated)
  (row D6 "100111" selector "cadddr" "перше-від-решти-від-решти-від-решти" "ādi-śeṣa-śeṣa-śeṣa" generated generated)
  (row D6 "101000" function "map" "відобразити" "āvartana" donor-or-selected donor-or-selected)
  (row D6 "101001" function "filter" "відсіяти" "kalpana" donor-or-selected donor-or-selected)
  (row D6 "101010" function "map-onto" "відобразити-до" "āvartana-saṅkalana" candidate candidate)
  (row D6 "101011" function "filter-onto" "відсіяти-до" "kalpana-saṅkalana" candidate candidate)
  (row D6 "101100" function "curry" "частково-застосувати" "pūrva-bandha" candidate candidate)
  (row D6 "101101" function "flip" "поміняти-аргументи" "krama-viparyaya" candidate candidate)
  (row D6 "101110" function "reduce" "згорнути" "saṅgraha" donor-or-selected donor-or-selected)
  (row D6 "101111" function "scan" "накопичувати" "krama-saṅgraha" candidate candidate)
  (row D6 "110000" function "take" "взяти" "grahaṇa" candidate candidate)
  (row D6 "110001" function "drop" "відкинути" "tyāga" candidate candidate)
  (row D6 "110010" form "do" "робити" "kriyā-punarāvṛtti" candidate candidate)
  (row D6 "110011" form "while" "поки" "yāvat-punarāvṛtti" candidate candidate)
  (row D6 "110100" predicate "leq?" "не-більше?" "na-adhika" donor-or-selected donor-or-selected)
  (row D6 "110101" function "min" "найменше" "alpatara" donor-or-selected donor-or-selected)
  (row D6 "110110" predicate "geq?" "не-менше?" "na-hīna" donor-or-selected donor-or-selected)
  (row D6 "110111" function "max" "найбільше" "brhattara" donor-or-selected donor-or-selected)
  (row D6 "111000" function "zip" "спарувати-послідовності" "yugma-saṃyojana" candidate candidate)
  (row D6 "111001" function "unzip" "розпарувати-пари" "yugma-vibhajana" candidate candidate)
  (row D6 "111010" function "intersection" "перетин" "mithaścheda" candidate candidate)
  (row D6 "111011" function "union" "об'єднання" "samūha-saṃyoga" candidate candidate)
  (row D6 "111100" predicate "any?" "будь-яке?" "kaścit" candidate candidate)
  (row D6 "111101" predicate "all?" "усі?" "sarva" candidate candidate)
  (row D6 "111110" predicate "integerp?" "ціле?" "pūrṇāṅka" candidate candidate)
  (row D6 "111111" predicate "rationalp?" "раціональне?" "parimeya-saṅkhyā" candidate candidate)
)
