; Метадані функцій таблиці за кодом СЕНС: вид, механізм особливої форми,
; арність, сигнатура й опис для інструментів (LSP, довідка REPL).
; Назви тут не повторюються — їх дає lib/surface/semantic-registry.lisp.
; Rust отримує це лише як згенеровану проєкцію
; (scripts/generate-rust-function-signatures.lisp) — без власної копії.
;
; (КОД (kind builtin|syntax|macro) [(form lambda|define)] (arity N|(at-least N)|(between A B))
;      (surfaces stable|admitted) (sig "...") (doc "..."))
(
  (00000001 (kind syntax) (arity 1) (surfaces stable) (sig "(quote value)") (doc "Return value unevaluated"))
  (00000010 (kind builtin) (arity 1) (surfaces stable) (sig "(atom? value)") (doc "Test whether value is not a pair"))
  (00000011 (kind builtin) (arity 2) (surfaces stable) (sig "(eq? left right)") (doc "Test structural or identity equality"))
  (00000100 (kind builtin) (arity 2) (surfaces stable) (sig "(cons head tail)") (doc "Create a pair"))
  (00000101 (kind builtin) (arity 1) (surfaces stable) (sig "(car pair)") (doc "Return the first element of a pair"))
  (00000110 (kind builtin) (arity 1) (surfaces stable) (sig "(cdr pair)") (doc "Return the tail of a pair"))
  (00000111 (kind syntax) (arity (at-least 0)) (surfaces stable) (sig "(cond (test result) ...)") (doc "Evaluate the first matching clause"))
  (00001000 (kind syntax) (form lambda) (arity (at-least 2)) (surfaces stable) (sig "(lambda (params) body ...)") (doc "Create an anonymous function"))
  (00001001 (kind syntax) (form define) (arity 2) (surfaces stable) (sig "(define name value)") (doc "Bind name in the current scope"))
  (00001010 (kind macro) (arity (at-least 3)) (surfaces admitted) (sig "(defmacro name (params) body ...)") (doc "Bind a language-owned macro"))
  (00001011 (kind syntax) (form define) (arity 2) (surfaces admitted) (sig "(def name value)") (doc "Compatibility-only binding form"))
  (00001100 (kind builtin) (arity (at-least 0)) (surfaces stable) (sig "(+ number ...)") (doc "Sum all arguments"))
  (00001101 (kind builtin) (arity (at-least 1)) (surfaces stable) (sig "(- number ...)") (doc "Subtract or negate"))
  (00001110 (kind builtin) (arity (at-least 0)) (surfaces stable) (sig "(* number ...)") (doc "Multiply all arguments"))
  (00001111 (kind builtin) (arity (at-least 1)) (surfaces stable) (sig "(/ number ...)") (doc "Perform exact rational division"))
  (00011010 (kind builtin) (arity (at-least 1)) (surfaces stable) (sig "(< number ...)") (doc "Less-than chain comparison"))
  (00011011 (kind builtin) (arity (at-least 1)) (surfaces stable) (sig "(> number ...)") (doc "Greater-than chain comparison"))
  (00011100 (kind builtin) (arity (at-least 1)) (surfaces stable) (sig "(= number ...)") (doc "Numeric equality"))
  (00100100 (kind builtin) (arity 1) (surfaces stable) (sig "(string? value)") (doc "Return t if value is a string"))
  (00100101 (kind builtin) (arity 2) (surfaces stable) (sig "(string<? left right)") (doc "Compare strings lexicographically"))
  (00100110 (kind builtin) (arity 1) (surfaces stable) (sig "(numeric-buffer? value)") (doc "Test for a numeric buffer"))
  (00111010 (kind builtin) (arity 2) (surfaces stable) (sig "(string-append left right)") (doc "Concatenate two strings"))
  (00111111 (kind builtin) (arity 1) (surfaces stable) (sig "(string-first string)") (doc "Return the first character as a string"))
  (01000000 (kind builtin) (arity 1) (surfaces stable) (sig "(string-rest string)") (doc "Return the string without its first character"))
  (01000001 (kind builtin) (arity 3) (surfaces stable) (sig "(string-slice string start end)") (doc "Return a UTF-8-safe substring"))
  (01000010 (kind builtin) (arity 1) (surfaces stable) (sig "(symbol->string symbol)") (doc "Return the string form of a symbol"))
  (01000011 (kind builtin) (arity 1) (surfaces stable) (sig "(string->symbol string)") (doc "Create a symbol from a string"))
  (01000100 (kind builtin) (arity 1) (surfaces stable) (sig "(codepoint->string scalar)") (doc "Materialize one Unicode scalar as a string"))
  (01000101 (kind builtin) (arity 1) (surfaces stable) (sig "(string->codepoint string)") (doc "Return the Unicode scalar value of one-character string"))
  (01001000 (kind builtin) (arity 1) (surfaces stable) (sig "(print value)") (doc "Output value followed by newline"))
  (01001001 (kind builtin) (arity 1) (surfaces stable) (sig "(princ value)") (doc "Output value without reader quoting"))
  (01001010 (kind builtin) (arity (between 0 1)) (surfaces stable) (sig "(read [source])") (doc "Read one s-expression from a string or stdin"))
  (01001011 (kind builtin) (arity 1) (surfaces stable) (sig "(read-all source)") (doc "Read all expressions from a string"))
  (01001100 (kind builtin) (arity 1) (surfaces stable) (sig "(write-to-string value)") (doc "Return a readable string representation"))
  (01001101 (kind builtin) (arity 1) (surfaces stable) (sig "(eval expression)") (doc "Evaluate an expression represented as data"))
  (01001110 (kind builtin) (arity 0) (surfaces stable) (sig "(env)") (doc "Return visible bindings as an alist"))
  (01001111 (kind builtin) (arity (at-least 0)) (surfaces stable) (sig "(vector value ...)") (doc "Create a vector containing the arguments"))
  (01010000 (kind builtin) (arity 1) (surfaces stable) (sig "(make-vector length)") (doc "Create a vector of nil slots"))
  (01010001 (kind builtin) (arity 1) (surfaces stable) (sig "(vector-length vector)") (doc "Return the element count"))
  (01010010 (kind builtin) (arity 2) (surfaces stable) (sig "(vector-ref vector index)") (doc "Return an element by index"))
  (01010011 (kind builtin) (arity 3) (surfaces stable) (sig "(vector-set! vector index value)") (doc "Mutate a vector slot"))
  (01010100 (kind builtin) (arity (at-least 0)) (surfaces stable) (sig "(i32-buffer number ...)") (doc "Create a signed 32-bit numeric buffer"))
  (01010101 (kind builtin) (arity (at-least 0)) (surfaces stable) (sig "(f32-buffer number ...)") (doc "Create a binary32 numeric buffer"))
  (01010110 (kind builtin) (arity 1) (surfaces stable) (sig "(numeric-buffer-type buffer)") (doc "Return i32 or f32"))
  (01010111 (kind builtin) (arity 1) (surfaces stable) (sig "(numeric-buffer-length buffer)") (doc "Return the element count"))
  (01011000 (kind builtin) (arity 2) (surfaces stable) (sig "(numeric-buffer-ref buffer index)") (doc "Return an element by index"))
  (01011001 (kind builtin) (arity 2) (surfaces stable) (sig "(numeric-buffer-map function buffer)") (doc "Map a function over a numeric buffer"))
  (01011010 (kind builtin) (arity 0) (surfaces stable) (sig "(mono-ns)") (doc "Return a monotonic nanosecond counter as an exact integer"))
  (01011011 (kind builtin) (arity 0) (surfaces stable) (sig "(unix-time-now)") (doc "Observe the host wall clock as raw Unix seconds and nanoseconds"))
  (01011100 (kind builtin) (arity 2) (surfaces stable) (sig "(ntp-query-raw host timeout-ms)") (doc "Perform one bounded NTP query and return raw protocol fields"))
  (01011101 (kind builtin) (arity 0) (surfaces stable) (sig "(timezone-declarations-raw)") (doc "Observe raw TZ and /etc/timezone declaration candidates"))
  (10100000 (kind builtin) (arity 1) (surfaces stable) (sig "(json-parse string)") (doc "Parse JSON into sens values"))
  (10100001 (kind builtin) (arity 1) (surfaces stable) (sig "(sha256-hex string)") (doc "Return the SHA-256 hex digest"))
)
