; Єдина машинна authority мовних поверхонь — compact byte-SID schema.
; Значення первинне. Мови рівноправні.
;
; Перший елемент кожного рядка — string із рівно 8 біт opaque semantic ID (SID).
; SID — машинна identity, НЕ Lisp surface spelling і НЕ арифметичне значення.
; Bare numeric tokens у програмі завжди лишаються exact numbers; semantic routing:
; surface -> registry bitstring -> u8 SID.
;
; 00000000 — Canon 0, порожній список (), primordial ground object.
; Далі всі identities йдуть щільно та послідовно без дірок у semantic/group order.
; Кожна identity має однакові namespace-поля: en / uk / ukr / sa / sym.
; Значення — або surface spelling, або () якщо surface для цього namespace відсутня.
; Статусів stable / candidate / compatibility-only / missing у схемі немає.
; Surface spelling, що конфліктує з reader syntax (зокрема апостроф), серіалізується string-ом.
; Порядок surface-форм усередині identity не має семантичного значення.
; Старий decimal-ID простір 0001/0104/1000... superseded цією sr/2 authority.
;
(sr/2
  ("00000000" ())
  ("00000001" (en quote) (uk як-є) (ukr як-є) (sa svarūpa) (sym "'"))
  ("00000010" (en atom) (uk атом?) (ukr атом?) (sa aṇu) (sym .?))
  ("00000011" (en eq) (uk тотожне?) (ukr тотожне?) (sa abheda) (sym =?))
  ("00000100" (en cons) (uk сполучити) (ukr сполучити) (sa saṃyuj) (sym :))
  ("00000101" (en car) (uk перше) (ukr перше) (sa ādi) (sym :п))
  ("00000110" (en cdr) (uk решта) (ukr решта) (sa śeṣa) (sym :р))
  ("00000111" (en cond) (uk за-умовою) (ukr за-умовою) (sa anukrama) (sym ?:))
  ("00001000" (en lambda) (uk функція) (ukr функція) (sa ()) (sym ()))
  ("00001001" (en define) (uk визначити) (ukr визначити) (sa ()) (sym ()))
  ("00001010" (en defmacro) (uk визначити-макрос) (ukr визначити-макрос) (sa ()) (sym ()))
  ("00001011" (en def) (uk ()) (ukr ()) (sa ()) (sym ()))
  ("00001100" (en ()) (uk додати) (ukr додати) (sa yoga) (sym +))
  ("00001101" (en ()) (uk відняти) (ukr відняти) (sa viyoga) (sym -))
  ("00001110" (en ()) (uk помножити) (ukr помножити) (sa guṇana) (sym *))
  ("00001111" (en ()) (uk поділити) (ukr поділити) (sa haraṇa) (sym /))
  ("00010000" (en abs) (uk модуль) (ukr модуль) (sa rūpa) (sym ()))
  ("00010001" (en min) (uk найменше) (ukr найменше) (sa alpatara) (sym ()))
  ("00010010" (en max) (uk найбільше) (ukr найбільше) (sa brhattara) (sym ()))
  ("00010011" (en mod) (uk остача) (ukr остача) (sa avasiṣṭa) (sym ()))
  ("00010100" (en quotient) (uk частка) (ukr частка) (sa bhāga) (sym ()))
  ("00010101" (en sqrt) (uk корінь) (ukr корінь) (sa mūla) (sym ()))
  ("00010110" (en isqrt) (uk цілий-корінь) (ukr цілий-корінь) (sa sakalamūla) (sym ()))
  ("00010111" (en min-list) (uk найменше-у-списку) (ukr найменше-у-списку) (sa ()) (sym ()))
  ("00011000" (en max-list) (uk найбільше-у-списку) (ukr найбільше-у-списку) (sa ()) (sym ()))
  ("00011001" (en largest-chunk) (uk ()) (ukr найбільший-фрагмент) (sa ()) (sym ()))
  ("00011010" (en ()) (uk менше?) (ukr менше?) (sa hīna?) (sym <))
  ("00011011" (en ()) (uk більше?) (ukr більше?) (sa adhika?) (sym >))
  ("00011100" (en ()) (uk рівне?) (ukr рівне?) (sa sama?) (sym =))
  ("00011101" (en ()) (uk не-більше?) (ukr не-більше?) (sa na-adhika?) (sym <=))
  ("00011110" (en ()) (uk не-менше?) (ukr не-менше?) (sa na-hīna?) (sym >=))
  ("00011111" (en nondecreasing-from?) (uk ()) (ukr неспадне-починаючи-з?) (sa ()) (sym ()))
  ("00100000" (en nonincreasing-from?) (uk ()) (ukr незростаюче-починаючи-з?) (sa ()) (sym ()))
  ("00100001" (en not) (uk хибне?) (ukr хибне?) (sa na) (sym ()))
  ("00100010" (en equal?) (uk однакові?) (ukr однакові?) (sa tulya?) (sym ()))
  ("00100011" (en symbol?) (uk символ?) (ukr символ?) (sa nāman?) (sym ()))
  ("00100100" (en string?) (uk текст?) (ukr текст?) (sa śabda?) (sym ()))
  ("00100101" (en string<?) (uk текст-передує?) (ukr текст-передує?) (sa śabda-hīna?) (sym ()))
  ("00100110" (en numeric-buffer?) (uk числовий-буфер?) (ukr числовий-буфер?) (sa ()) (sym ()))
  ("00100111" (en list) (uk список) (ukr список) (sa śreṇī) (sym ()))
  ("00101000" (en length) (uk довжина) (ukr довжина) (sa pramāṇa) (sym ()))
  ("00101001" (en append) (uk приєднати) (ukr приєднати) (sa saṅkalana) (sym ()))
  ("00101010" (en reverse) (uk зворот) (ukr зворот) (sa viloma) (sym ()))
  ("00101011" (en nth) (uk елемент-списку-за-індексом) (ukr елемент-списку-за-індексом) (sa kramāṅka) (sym ()))
  ("00101100" (en member?) (uk значення-у-списку?) (ukr значення-у-списку?) (sa sambaddha?) (sym ()))
  ("00101101" (en assoc) (uk знайти-за-ключем) (ukr знайти-за-ключем) (sa saṃbandha) (sym ()))
  ("00101110" (en pair) (uk пара) (ukr пара) (sa dvandva) (sym ()))
  ("00101111" (en second) (uk друге) (ukr друге) (sa dvitīya) (sym ()))
  ("00110000" (en third) (uk третє) (ukr третє) (sa tṛtīya) (sym ()))
  ("00110001" (en fourth) (uk четверте) (ukr четверте) (sa caturtha) (sym ()))
  ("00110010" (en fifth) (uk п'яте) (ukr п'яте) (sa pañcama) (sym ()))
  ("00110011" (en caar) (uk ()) (ukr перше-від-першого) (sa ()) (sym ()))
  ("00110100" (en cadr) (uk ()) (ukr перше-від-решти) (sa ()) (sym ()))
  ("00110101" (en cddr) (uk ()) (ukr решта-від-решти) (sa ()) (sym ()))
  ("00110110" (en cadddr) (uk ()) (ukr перше-після-трьох-решт) (sa ()) (sym ()))
  ("00110111" (en map) (uk відобразити) (ukr відобразити) (sa āvartana) (sym ()))
  ("00111000" (en filter) (uk відсіяти) (ukr відсіяти) (sa kalpana) (sym ()))
  ("00111001" (en reduce) (uk згорнути) (ukr згорнути) (sa saṅgraha) (sym ()))
  ("00111010" (en string-append) (uk зчепити) (ukr зчепити) (sa śabdasaṃyoga) (sym ()))
  ("00111011" (en string-length) (uk довжина-тексту) (ukr довжина-тексту) (sa śabdapramāṇa) (sym ()))
  ("00111100" (en string-empty?) (uk текст-порожній?) (ukr порожній-текст?) (sa śūnya?) (sym ()))
  ("00111101" (en string-prefix?) (uk префікс-тексту?) (ukr текст-починається-з?) (sa pūrva?) (sym ()))
  ("00111110" (en string-contains?) (uk фрагмент-у-тексті?) (ukr фрагмент-у-тексті?) (sa śabdasambaddha?) (sym ()))
  ("00111111" (en string-first) (uk перший-символ-тексту) (ukr перший-символ-тексту) (sa prathamavarṇa) (sym ()))
  ("01000000" (en string-rest) (uk решта-символів-тексту) (ukr решта-символів-тексту) (sa śeṣavarṇa) (sym ()))
  ("01000001" (en string-slice) (uk відрізати) (ukr відрізати) (sa cheda) (sym ()))
  ("01000010" (en symbol->string) (uk символ-у-текст) (ukr символ-у-текст) (sa nāman-śabda) (sym ()))
  ("01000011" (en string->symbol) (uk текст-у-символ) (ukr текст-у-символ) (sa śabda-nāman) (sym ()))
  ("01000100" (en codepoint->string) (uk кодова-точка-у-текст) (ukr кодова-точка-у-текст) (sa varṇa-śabda) (sym ()))
  ("01000101" (en string->codepoint) (uk текст-у-кодову-точку) (ukr текст-у-кодову-точку) (sa śabda-varṇa) (sym ()))
  ("01000110" (en number->string) (uk число-у-текст) (ukr число-у-текст) (sa saṅkhyā-śabda) (sym ()))
  ("01000111" (en digit->string) (uk ()) (ukr цифра-у-текст) (sa ()) (sym ()))
  ("01001000" (en print) (uk друкувати) (ukr друкувати) (sa mudraṇa) (sym ()))
  ("01001001" (en princ) (uk показати) (ukr показати) (sa darśana) (sym ()))
  ("01001010" (en read) (uk прочитати) (ukr прочитати) (sa pāṭhana) (sym ()))
  ("01001011" (en read-all) (uk прочитати-усе) (ukr прочитати-усе) (sa pāṭhana-sarva) (sym ()))
  ("01001100" (en write-to-string) (uk значення-у-текст) (ukr значення-у-текст) (sa likhana) (sym ()))
  ("01001101" (en eval) (uk обчислити) (ukr обчислити) (sa vicāraṇa) (sym ()))
  ("01001110" (en env) (uk середовище) (ukr середовище) (sa āśraya) (sym ()))
  ("01001111" (en vector) (uk вектор) (ukr вектор) (sa samūha) (sym ()))
  ("01010000" (en make-vector) (uk створити-вектор) (ukr створити-вектор) (sa samūha-nirmāṇa) (sym ()))
  ("01010001" (en vector-length) (uk довжина-вектора) (ukr довжина-вектора) (sa samūha-pramāṇa) (sym ()))
  ("01010010" (en vector-ref) (uk елемент-вектора) (ukr елемент-вектора) (sa samūha-āvartana) (sym ()))
  ("01010011" (en vector-set!) (uk встановити-елемент-вектора!) (ukr встановити-елемент-вектора!) (sa ()) (sym ()))
  ("01010100" (en i32-buffer) (uk ()) (ukr буфер-32-бітних-цілих-зі-знаком) (sa ()) (sym ()))
  ("01010101" (en f32-buffer) (uk ()) (ukr буфер-32-бітних-чисел-з-плавною-комою) (sa ()) (sym ()))
  ("01010110" (en numeric-buffer-type) (uk ()) (ukr тип-числового-буфера) (sa ()) (sym ()))
  ("01010111" (en numeric-buffer-length) (uk ()) (ukr довжина-числового-буфера) (sa ()) (sym ()))
  ("01011000" (en numeric-buffer-ref) (uk ()) (ukr елемент-числового-буфера) (sa ()) (sym ()))
  ("01011001" (en numeric-buffer-map) (uk ()) (ukr відобразити-числовий-буфер) (sa ()) (sym ()))
  ("01011010" (en mono-ns) (uk монотонний-нс) (ukr монотонний-час-у-наносекундах) (sa kāla-mono) (sym ()))
  ("01011011" (en unix-time-now) (uk поточний-юнікс-час) (ukr поточний-юнікс-час) (sa kāla-unix) (sym ()))
  ("01011100" (en ntp-query-raw) (uk ()) (ukr сирий-запит-мережевого-часу) (sa ()) (sym ()))
  ("01011101" (en timezone-declarations-raw) (uk ()) (ukr сирі-декларації-часових-поясів) (sa ()) (sym ()))
  ("01011110" (en utc-now) (uk поточний-всч) (ukr поточний-всесвітній-координований-час) (sa kāla-adya) (sym ()))
  ("01011111" (en utc-from-unix) (uk всч-із-юнікс) (ukr всесвітній-координований-час-із-часу-юнікс) (sa ()) (sym ()))
  ("01100000" (en unix-time-observation->utc) (uk юнікс-спостереження-у-всч) (ukr спостереження-часу-юнікс-у-всесвітній-координований-час) (sa ()) (sym ()))
  ("01100001" (en milliseconds-from-nanoseconds) (uk мілісекунди-із-наносекунд) (ukr мілісекунди-із-наносекунд) (sa kāla-millisecondāni) (sym ()))
  ("01100010" (en mono-ms) (uk монотонний-мс) (ukr монотонний-час-у-мілісекундах) (sa kāla-mono-ms) (sym ()))
  ("01100011" (en timezone-name) (uk назва-часового-поясу) (ukr назва-часового-поясу) (sa deśa-kāla-nāma) (sym ()))
  ("01100100" (en timezone-detect) (uk визначити-часовий-пояс) (ukr визначити-часовий-пояс) (sa deśa-kāla-jñāna) (sym ()))
  ("01100101" (en timezone-offset-seconds) (uk зміщення-часового-поясу-в-секундах) (ukr зміщення-часового-поясу-в-секундах) (sa deśa-kāla-śeṣa) (sym ()))
  ("01100110" (en deadline-reached?) (uk дедлайн-досягнуто?) (ukr граничний-час-досягнуто?) (sa avadhi-gatā?) (sym ()))
  ("01100111" (en deadline-reached-at?) (uk дедлайн-досягнуто-на-момент?) (ukr граничний-час-досягнуто-на-момент?) (sa avadhi-gatā-kadā?) (sym ()))
  ("01101000" (en elapsed-ns) (uk минуло-нс) (ukr минуло-наносекунд) (sa atīta-ns) (sym ()))
  ("01101001" (en deadline-from) (uk дедлайн-від) (ukr граничний-час-від) (sa avadhi-nirmāṇa) (sym ()))
  ("01101010" (en deadline-after-ns) (uk дедлайн-через-нс) (ukr граничний-час-через-наносекунди) (sa avadhi-anantara-ns) (sym ()))
  ("01101011" (en internet-time-sync) (uk запитати-інтернет-час) (ukr синхронізувати-час-через-інтернет) (sa ()) (sym ()))
  ("01101100" (en map-empty) (uk порожня-карта) (ukr порожня-карта) (sa kośa-śūnya) (sym ()))
  ("01101101" (en map-get) (uk отримати-з-карти) (ukr отримати-з-карти) (sa kośa-grahaṇa) (sym ()))
  ("01101110" (en map-insert) (uk вставити-в-карту) (ukr вставити-в-карту) (sa kośa-niveśana) (sym ()))
  ("01101111" (en map-contains?) (uk ключ-у-карті?) (ukr ключ-у-карті?) (sa kośa-sambaddha?) (sym ()))
  ("01110000" (en map->list) (uk карта-у-список) (ukr карта-у-список) (sa kośa-śreṇī) (sym ()))
  ("01110001" (en vec-empty) (uk порожній-вектор) (ukr порожній-вектор) (sa samūha-śūnya) (sym ()))
  ("01110010" (en vec-conj) (uk додати-до-вектора) (ukr додати-до-вектора) (sa samūha-yukti) (sym ()))
  ("01110011" (en vec-count) (uk розмір-вектора) (ukr розмір-вектора) (sa samūha-gaṇana) (sym ()))
  ("01110100" (en vec-nth) (uk елемент-вектора-за-індексом) (ukr елемент-вектора-за-індексом) (sa samūha-kramāṅka) (sym ()))
  ("01110101" (en vec->list) (uk вектор-у-список) (ukr вектор-у-список) (sa samūha-śreṇī) (sym ()))
  ("01110110" (en vec-from-list) (uk вектор-із-списку) (ukr вектор-із-списку) (sa śreṇī-samūha) (sym ()))
  ("01110111" (en is-fact?) (uk факт?) (ukr факт?) (sa jñāna-satya?) (sym ()))
  ("01111000" (en describe) (uk описати) (ukr описати) (sa varṇana) (sym ()))
  ("01111001" (en collect-facts-about) (uk зібрати-факти-про) (ukr зібрати-факти-про) (sa jñāna-saṅgraha) (sym ()))
  ("01111010" (en contains-atom?) (uk атом-у-списку?) (ukr атом-у-списку?) (sa aṇu-sambaddha?) (sym ()))
  ("01111011" (en forward-in) (uk пряме-виведення) (ukr пряме-виведення) (sa abhimukha-anumāna) (sym ()))
  ("01111100" (en reason-in) (uk логічний-висновок) (ukr логічний-висновок) (sa anumāna) (sym ()))
  ("01111101" (en check-conflict) (uk конфлікт?) (ukr є-конфлікт?) (sa virodha-parīkṣā) (sym ()))
  ("01111110" (en module-known?) (uk модуль-відомий?) (ukr модуль-відомий?) (sa ()) (sym ()))
  ("01111111" (en module-clauses-now) (uk поточні-клаузи-модуля) (ukr поточні-клаузи-модуля) (sa ()) (sym ()))
  ("10000000" (en prove-goal) (uk довести-мету) (ukr довести-мету) (sa siddhi-sādhana) (sym ()))
  ("10000001" (en prove-goals) (uk довести-мети) (ukr довести-мети) (sa siddhi-sādhana-sarva) (sym ()))
  ("10000010" (en explain-proof) (uk пояснити-доведення) (ukr пояснити-доведення) (sa siddhi-vyākhyā) (sym ()))
  ("10000011" (en source-of) (uk джерело-доведення) (ukr джерело-доведення) (sa siddhi-mūla) (sym ()))
  ("10000100" (en provenance) (uk походження) (ukr походження) (sa utpatti) (sym ()))
  ("10000101" (en reason) (uk міркування) (ukr міркування) (sa tarka) (sym ()))
  ("10000110" (en reason-explain) (uk пояснити-міркування) (ukr пояснити-міркування) (sa tarka-vyākhyā) (sym ()))
  ("10000111" (en unify) (uk уніфікувати) (ukr уніфікувати) (sa ekīkaraṇa) (sym ()))
  ("10001000" (en logic-var) (uk логічна-змінна) (ukr логічна-змінна) (sa tarka-cihna) (sym ()))
  ("10001001" (en var?) (uk змінна?) (ukr змінна?) (sa cihna?) (sym ()))
  ("10001010" (en apply-subst) (uk підставити) (ukr підставити) (sa pratyāroha) (sym ()))
  ("10001011" (en walk) (uk розіменувати) (ukr розіменувати) (sa vicāraṇa-gamana) (sym ()))
  ("10001100" (en occurs-check) (uk змінна-зустрічається?) (ukr змінна-зустрічається?) (sa parivṛtti-parīkṣā) (sym ()))
  ("10001101" (en claim?) (uk твердження?) (ukr твердження?) (sa pratyaya?) (sym ()))
  ("10001110" (en claim-statement) (uk зміст-твердження) (ukr зміст-твердження) (sa pratyaya-vākya) (sym ()))
  ("10001111" (en claim-review) (uk стан-розгляду-твердження) (ukr стан-розгляду-твердження) (sa pratyaya-parīkṣā) (sym ()))
  ("10010000" (en evidence?) (uk доказ?) (ukr доказ?) (sa pramāṇa?) (sym ()))
  ("10010001" (en evidence-method) (uk метод-доказу) (ukr метод-доказу) (sa pramāṇa-vidhi) (sym ()))
  ("10010010" (en evidence-outcome) (uk результат-доказу) (ukr результат-доказу) (sa pramāṇa-phala) (sym ()))
  ("10010011" (en observation?) (uk спостереження?) (ukr спостереження?) (sa pratyakṣa?) (sym ()))
  ("10010100" (en observation-statement) (uk зміст-спостереження) (ukr зміст-спостереження) (sa pratyakṣa-vākya) (sym ()))
  ("10010101" (en intent?) (uk намір?) (ukr намір?) (sa saṅkalpa?) (sym ()))
  ("10010110" (en intent-goal) (uk мета-наміру) (ukr мета-наміру) (sa saṅkalpa-lakṣya) (sym ()))
  ("10010111" (en supporting-evidence) (uk підтримувальний-доказ) (ukr підтримувальний-доказ) (sa sahāya-pramāṇa) (sym ()))
  ("10011000" (en identity) (uk без-змін) (ukr повернути-без-змін) (sa svabhāva) (sym ()))
  ("10011001" (en gensym) (uk генерувати-символ) (ukr створити-унікальний-символ) (sa nāman-nirmāṇa) (sym ()))
  ("10011010" (en and) (uk та) (ukr та) (sa ()) (sym ()))
  ("10011011" (en or) (uk або) (ukr або) (sa ()) (sym ()))
  ("10011100" (en let) (uk нехай) (ukr нехай) (sa ()) (sym ()))
  ("10011101" (en let*) (uk нехай*) (ukr нехай-послідовно) (sa ()) (sym ()))
  ("10011110" (en ()) (uk ()) (ukr ланцюжок-першого-аргументу) (sa ()) (sym ->))
  ("10011111" (en ()) (uk ()) (ukr ланцюжок-останнього-аргументу) (sa ()) (sym ->>))
  ("10100000" (en json-parse) (uk ()) (ukr розібрати-текст-формату-джейсон) (sa ()) (sym ()))
  ("10100001" (en sha256-hex) (uk ()) (ukr обчислити-хеш-ша-256-тексту-у-шістнадцятковому-записі) (sa ()) (sym ()))
  ("10100010" (en process-run) (uk запустити-процес) (ukr запустити-процес) (sa ()) (sym ()))
  ("10100011" (en tcp-read) (uk прочитати-текст-з-з'єднання-протоколу-керування-передаванням) (ukr прочитати-текст-з-з'єднання-протоколу-керування-передаванням) (sa ()) (sym ()))
  ("10100100" (en tcp-write) (uk записати-текст-у-з'єднання-протоколу-керування-передаванням) (ukr записати-текст-у-з'єднання-протоколу-керування-передаванням) (sa ()) (sym ()))
  ("10100101" (en tcp-listen) (uk слухати-порт-протоколу-керування-передаванням) (ukr слухати-порт-протоколу-керування-передаванням) (sa ()) (sym ()))
  ("10100110" (en read-file) (uk прочитати-файл) (ukr прочитати-файл) (sa ()) (sym ()))
  ("10100111" (en write-file) (uk записати-файл) (ukr записати-файл) (sa ()) (sym ()))
)
