// @generated by scripts/generate-domain-owner-registry.py; DO NOT EDIT.
//
// Canonical owner occupancy only. Human labels, surfaces and historical
// backend bytes are deliberately excluded from this artifact.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct DomainOwnerCoordinate {
    pub(crate) width: u8,
    pub(crate) bits: u8,
    pub(crate) source: u8,
}

pub(crate) const DOMAIN_OWNER_COORDINATES: &[DomainOwnerCoordinate] = &[
    DomainOwnerCoordinate { width: 3, bits: 0b001, source: 0 },
    DomainOwnerCoordinate { width: 3, bits: 0b010, source: 0 },
    DomainOwnerCoordinate { width: 3, bits: 0b011, source: 0 },
    DomainOwnerCoordinate { width: 3, bits: 0b100, source: 0 },
    DomainOwnerCoordinate { width: 3, bits: 0b101, source: 0 },
    DomainOwnerCoordinate { width: 3, bits: 0b110, source: 0 },
    DomainOwnerCoordinate { width: 3, bits: 0b111, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b0000, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b0001, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b0010, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b0011, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b0100, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b0110, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b0111, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b1000, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b1010, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b1011, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b1100, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b1101, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b1110, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b1111, source: 0 },
    DomainOwnerCoordinate { width: 5, bits: 0b00000, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b00001, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b00010, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b00011, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b00100, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b00101, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b00110, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b00111, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b01000, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b01001, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b01010, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b01011, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b01100, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b01101, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b01110, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b01111, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b10000, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b10001, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b10010, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b10011, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b10100, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b10101, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b10110, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b10111, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b11000, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b11001, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b11010, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b11011, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b11100, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b11101, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b11110, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b11111, source: 1 },
    DomainOwnerCoordinate { width: 6, bits: 0b000000, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b000001, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b000010, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b000011, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b000100, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b000101, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b000110, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b000111, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b001000, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b001001, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b001010, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b001011, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b001100, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b001101, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b001110, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b001111, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b010000, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b010001, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b010010, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b010011, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b010100, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b010101, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b010110, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b010111, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b011000, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b011001, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b011010, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b011011, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b011100, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b011101, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b011110, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b011111, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b100000, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b100001, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b100010, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b100011, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b100100, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b100101, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b100110, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b100111, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b101000, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b101001, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b101010, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b101011, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b101100, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b101101, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b101110, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b101111, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b110000, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b110001, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b110010, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b110011, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b110100, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b110101, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b110110, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b110111, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b111000, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b111001, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b111010, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b111011, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b111100, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b111101, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b111110, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b111111, source: 2 },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_projection_has_owner_counts_and_controls() {
        assert_eq!(DOMAIN_OWNER_COORDINATES.len(), 117);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 3).count(), 7);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 4).count(), 14);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 5).count(), 32);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 6).count(), 64);

        for (width, bits) in [(4, 0b1100), (5, 0b01010), (6, 0b001111)] {
            assert!(DOMAIN_OWNER_COORDINATES
                .iter()
                .any(|row| row.width == width && row.bits == bits));
        }
    }

    #[test]
    fn generated_projection_has_unique_domain_coordinates() {
        let mut seen = std::collections::HashSet::new();
        for row in DOMAIN_OWNER_COORDINATES {
            assert!(seen.insert((row.width, row.bits)));
        }
    }
}
