// GENERATED — DO NOT EDIT BY HAND.
// Occupancy authority:
//   D3/D4: knowledge/exact-width-admitted-corpus.json
//   D5:    knowledge/d5-historical-full-map.json (OD-005)
//   D6:    knowledge/d6-historical-full-map.json (OD-006)
// Compatibility projection:
//   knowledge/domain-legacy-compat-projection.json
// Generator: scripts/generate-domain-owner-registry.py
//
// Legacy surfaces/backend bytes never create residency.

pub(crate) const DOMAIN_OWNER_ROWS: &[DomainOwnerRow] = &[
    DomainOwnerRow { width: 3, bits: 0b001, name: "QUOTE", authority: "exact-width-admitted-corpus", legacy_mechanism: Some(0b00000001), surfaces: &["quote", "як-є", "як-є", "svarūpa", "'"] },
    DomainOwnerRow { width: 3, bits: 0b010, name: "ATOM", authority: "exact-width-admitted-corpus", legacy_mechanism: Some(0b00000010), surfaces: &["atom?", "атом?", "атом?", "aṇu", ".?"] },
    DomainOwnerRow { width: 3, bits: 0b011, name: "COND", authority: "exact-width-admitted-corpus", legacy_mechanism: Some(0b00000111), surfaces: &["cond", "за-умовою", "за-умовою", "anukrama", "?:"] },
    DomainOwnerRow { width: 3, bits: 0b100, name: "CONS", authority: "exact-width-admitted-corpus", legacy_mechanism: Some(0b00000100), surfaces: &["cons", "сполучити", "сполучити", "saṃyuj"] },
    DomainOwnerRow { width: 3, bits: 0b101, name: "CAR", authority: "exact-width-admitted-corpus", legacy_mechanism: Some(0b00000101), surfaces: &["car", "перше", "перше", "ādi", ":п"] },
    DomainOwnerRow { width: 3, bits: 0b110, name: "CDR", authority: "exact-width-admitted-corpus", legacy_mechanism: Some(0b00000110), surfaces: &["cdr", "решта", "решта", "śeṣa", ":р"] },
    DomainOwnerRow { width: 3, bits: 0b111, name: "EQ", authority: "exact-width-admitted-corpus", legacy_mechanism: Some(0b00000011), surfaces: &["eq?", "тотожне?", "тотожне?", "abheda", "=?"] },
    DomainOwnerRow { width: 4, bits: 0b0000, name: "APPLY", authority: "exact-width-admitted-corpus", legacy_mechanism: Some(0b10101111), surfaces: &["apply", "застосувати", "застосувати"] },
    DomainOwnerRow { width: 4, bits: 0b0001, name: "EVAL", authority: "exact-width-admitted-corpus", legacy_mechanism: Some(0b01001101), surfaces: &["eval", "обчислити", "обчислити", "vicāraṇa"] },
    DomainOwnerRow { width: 4, bits: 0b0010, name: "LAMBDA", authority: "exact-width-admitted-corpus", legacy_mechanism: Some(0b00001000), surfaces: &["lambda", "функція", "функція"] },
    DomainOwnerRow { width: 4, bits: 0b0011, name: "DEFINE", authority: "exact-width-admitted-corpus", legacy_mechanism: Some(0b00001001), surfaces: &["define", "визначити", "визначити"] },
    DomainOwnerRow { width: 4, bits: 0b0100, name: "NOT", authority: "exact-width-admitted-corpus", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 4, bits: 0b0110, name: "EVCON", authority: "exact-width-admitted-corpus", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 4, bits: 0b0111, name: "EVLIS", authority: "exact-width-admitted-corpus", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 4, bits: 0b1000, name: "LIST", authority: "exact-width-admitted-corpus", legacy_mechanism: Some(0b00100111), surfaces: &["list", "список", "список", "śreṇī"] },
    DomainOwnerRow { width: 4, bits: 0b1010, name: "CAAR", authority: "exact-width-admitted-corpus", legacy_mechanism: Some(0b00110011), surfaces: &["caar", "перше-від-першого"] },
    DomainOwnerRow { width: 4, bits: 0b1011, name: "CADR", authority: "exact-width-admitted-corpus", legacy_mechanism: Some(0b00110100), surfaces: &["cadr", "перше-від-решти"] },
    DomainOwnerRow { width: 4, bits: 0b1100, name: "CDAR", authority: "exact-width-admitted-corpus", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 4, bits: 0b1101, name: "CDDR", authority: "exact-width-admitted-corpus", legacy_mechanism: Some(0b00110101), surfaces: &["cddr", "решта-від-решти"] },
    DomainOwnerRow { width: 4, bits: 0b1110, name: "LOOKUP", authority: "exact-width-admitted-corpus", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 4, bits: 0b1111, name: "BIND", authority: "exact-width-admitted-corpus", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b00000, name: "EVALQUOTE", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b00001, name: "FUNCTION", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b00010, name: "FEXPR", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b00011, name: "MACRO", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b00100, name: "LABEL", authority: "OD-005", legacy_mechanism: Some(0b10101010), surfaces: &["label", "мітка", "мітка"] },
    DomainOwnerRow { width: 5, bits: 0b00101, name: "PROG", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b00110, name: "SET", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b00111, name: "SETQ", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b01000, name: "ZEROP", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b01001, name: "NUMBERP", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b01010, name: "PLUS", authority: "OD-005", legacy_mechanism: Some(0b00001100), surfaces: &["plus", "додати", "додати", "yoga", "+"] },
    DomainOwnerRow { width: 5, bits: 0b01011, name: "DIFFERENCE", authority: "OD-005", legacy_mechanism: Some(0b00001101), surfaces: &["difference", "відняти", "відняти", "viyoga", "-"] },
    DomainOwnerRow { width: 5, bits: 0b01100, name: "GO", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b01101, name: "RETURN", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b01110, name: "LESSP", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b01111, name: "GREATERP", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b10000, name: "APPEND", authority: "OD-005", legacy_mechanism: Some(0b00101001), surfaces: &["append", "приєднати", "приєднати", "saṅkalana"] },
    DomainOwnerRow { width: 5, bits: 0b10001, name: "REVERSE", authority: "OD-005", legacy_mechanism: Some(0b00101010), surfaces: &["reverse", "зворот", "зворот", "viloma"] },
    DomainOwnerRow { width: 5, bits: 0b10010, name: "TIMES", authority: "OD-005", legacy_mechanism: Some(0b00001110), surfaces: &["times", "помножити", "помножити", "guṇana", "*"] },
    DomainOwnerRow { width: 5, bits: 0b10011, name: "QUOTIENT", authority: "OD-005", legacy_mechanism: Some(0b00010100), surfaces: &["quotient", "частка", "частка", "bhāga"] },
    DomainOwnerRow { width: 5, bits: 0b10100, name: "CAAAR", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b10101, name: "CAADR", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b10110, name: "CADAR", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b10111, name: "CADDR", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b11000, name: "CDAAR", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b11001, name: "CDADR", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b11010, name: "CDDAR", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b11011, name: "CDDDR", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b11100, name: "ASSOC", authority: "OD-005", legacy_mechanism: Some(0b00101101), surfaces: &["assoc", "знайти-за-ключем", "знайти-за-ключем", "saṃbandha"] },
    DomainOwnerRow { width: 5, bits: 0b11101, name: "MEMBER", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b11110, name: "PAIRLIS", authority: "OD-005", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 5, bits: 0b11111, name: "SUBST", authority: "OD-005", legacy_mechanism: Some(0b10101100), surfaces: &["subst", "замінити", "замінити"] },
    DomainOwnerRow { width: 6, bits: 0b000000, name: "REPL", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b000001, name: "LOAD", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b000010, name: "CLOSURE", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b000011, name: "CURRY", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b000100, name: "FSUBR", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b000101, name: "LEXPR", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b000110, name: "MACROEXPAND-1", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b000111, name: "MACROEXPAND", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b001000, name: "LET", authority: "OD-006", legacy_mechanism: Some(0b10011100), surfaces: &["let", "нехай", "нехай"] },
    DomainOwnerRow { width: 6, bits: 0b001001, name: "LET*", authority: "OD-006", legacy_mechanism: Some(0b10011101), surfaces: &["let*", "нехай*", "нехай-послідовно"] },
    DomainOwnerRow { width: 6, bits: 0b001010, name: "DO", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b001011, name: "WHILE", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b001100, name: "RPLACA", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b001101, name: "RPLACD", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b001110, name: "SETF", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b001111, name: "DEFVAR", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b010000, name: "EVENP", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b010001, name: "ODDP", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b010010, name: "INTEGERP", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b010011, name: "RATIONALP", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b010100, name: "ADD1", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b010101, name: "ABS", authority: "OD-006", legacy_mechanism: Some(0b00010000), surfaces: &["abs", "модуль", "модуль", "rūpa"] },
    DomainOwnerRow { width: 6, bits: 0b010110, name: "SUB1", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b010111, name: "NEG", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b011000, name: "TAGBODY", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b011001, name: "BLOCK", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b011010, name: "RETURN-FROM", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b011011, name: "CATCH", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b011100, name: "LEQ", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b011101, name: "MIN", authority: "OD-006", legacy_mechanism: Some(0b00010001), surfaces: &["min", "найменше", "найменше", "alpatara"] },
    DomainOwnerRow { width: 6, bits: 0b011110, name: "GEQ", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b011111, name: "MAX", authority: "OD-006", legacy_mechanism: Some(0b00010010), surfaces: &["max", "найбільше", "найбільше", "brhattara"] },
    DomainOwnerRow { width: 6, bits: 0b100000, name: "NCONC", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b100001, name: "LENGTH", authority: "OD-006", legacy_mechanism: Some(0b00101000), surfaces: &["length", "довжина", "довжина", "pramāṇa"] },
    DomainOwnerRow { width: 6, bits: 0b100010, name: "NREVERSE", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b100011, name: "NTH", authority: "OD-006", legacy_mechanism: Some(0b00101011), surfaces: &["nth", "елемент-списку-за-індексом", "елемент-списку-за-індексом", "kramāṅka"] },
    DomainOwnerRow { width: 6, bits: 0b100100, name: "EXPT", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b100101, name: "GCD", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b100110, name: "REMAINDER", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b100111, name: "RECIP", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b101000, name: "CAAAAR", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b101001, name: "CAAADR", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b101010, name: "CAADAR", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b101011, name: "CAADDR", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b101100, name: "CADAAR", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b101101, name: "CADADR", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b101110, name: "CADDAR", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b101111, name: "CADDDR", authority: "OD-006", legacy_mechanism: Some(0b00110110), surfaces: &["cadddr", "перше-після-трьох-решт"] },
    DomainOwnerRow { width: 6, bits: 0b110000, name: "CDAAAR", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b110001, name: "CDAADR", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b110010, name: "CDADAR", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b110011, name: "CDADDR", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b110100, name: "CDDAAR", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b110101, name: "CDDADR", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b110110, name: "CDDDAR", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b110111, name: "CDDDDR", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b111000, name: "RASSOC", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b111001, name: "ACONS", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b111010, name: "INTERSECTION", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b111011, name: "UNION", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b111100, name: "MAPCAR", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
    DomainOwnerRow { width: 6, bits: 0b111101, name: "MAPLIST", authority: "OD-006", legacy_mechanism: Some(0b10101110), surfaces: &["maplist", "відобразити-залишки", "відобразити-залишки"] },
    DomainOwnerRow { width: 6, bits: 0b111110, name: "SUBLIS", authority: "OD-006", legacy_mechanism: Some(0b10101101), surfaces: &["sublis", "підставити-пари", "підставити-пари"] },
    DomainOwnerRow { width: 6, bits: 0b111111, name: "COPY-TREE", authority: "OD-006", legacy_mechanism: None, surfaces: &[] },
];
