// @generated by scripts/generate-domain-owner-registry.py; DO NOT EDIT.
//
// Executable/Core-owner residency projection for D3-D8.
// This is NOT the complete semantic-residency ontology. D1/D2, D3:000
// structural empty, D7 Sound7/Text7 cells, and other admitted non-executable
// objects remain canonical binary identities under #3020 outside this slice.
// Domain existence and this projection's resident coordinates are separate facts.
// D7 is in scope but currently contributes zero residency rows because the
// owner contract keeps D7 occupancy law/witness-specific and the ratification
// witness makes no 128-coordinate occupancy claim.
// D8 contributes only selector descendants certified by the root+suffix law.
// Human labels, surfaces and historical backend bytes are excluded.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum DomainOwnerSource {
    ExactWidthCorpus,
    Od005,
    Od006,
    SelectorLaw,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct DomainOwnerCoordinate {
    pub(crate) width: u8,
    pub(crate) bits: u8,
    pub(crate) source: DomainOwnerSource,
}

pub(crate) const DOMAIN_WIDTHS_IN_SCOPE: &[u8] = &[3, 4, 5, 6, 7, 8];

pub(crate) const DOMAIN_OWNER_COORDINATES: &[DomainOwnerCoordinate] = &[
    DomainOwnerCoordinate { width: 3, bits: 0b001, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 3, bits: 0b010, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 3, bits: 0b011, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 3, bits: 0b100, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 3, bits: 0b101, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 3, bits: 0b110, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 3, bits: 0b111, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 4, bits: 0b0000, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 4, bits: 0b0001, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 4, bits: 0b0010, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 4, bits: 0b0011, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 4, bits: 0b0100, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 4, bits: 0b0110, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 4, bits: 0b0111, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 4, bits: 0b1000, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 4, bits: 0b1010, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 4, bits: 0b1011, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 4, bits: 0b1100, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 4, bits: 0b1101, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 4, bits: 0b1110, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 4, bits: 0b1111, source: DomainOwnerSource::ExactWidthCorpus },
    DomainOwnerCoordinate { width: 5, bits: 0b00000, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b00001, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b00010, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b00011, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b00100, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b00101, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b00110, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b00111, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b01000, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b01001, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b01010, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b01011, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b01100, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b01101, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b01110, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b01111, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b10000, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b10001, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b10010, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b10011, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b10100, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b10101, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b10110, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b10111, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b11000, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b11001, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b11010, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b11011, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b11100, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b11101, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b11110, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 5, bits: 0b11111, source: DomainOwnerSource::Od005 },
    DomainOwnerCoordinate { width: 6, bits: 0b000000, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b000001, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b000010, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b000011, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b000100, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b000101, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b000110, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b000111, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b001000, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b001001, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b001010, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b001011, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b001100, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b001101, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b001110, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b001111, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b010000, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b010001, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b010010, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b010011, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b010100, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b010101, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b010110, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b010111, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b011000, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b011001, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b011010, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b011011, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b011100, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b011101, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b011110, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b011111, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b100000, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b100001, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b100010, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b100011, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b100100, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b100101, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b100110, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b100111, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b101000, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b101001, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b101010, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b101011, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b101100, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b101101, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b101110, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b101111, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b110000, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b110001, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b110010, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b110011, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b110100, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b110101, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b110110, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b110111, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b111000, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b111001, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b111010, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b111011, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b111100, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b111101, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b111110, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 6, bits: 0b111111, source: DomainOwnerSource::Od006 },
    DomainOwnerCoordinate { width: 8, bits: 0b10100000, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10100001, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10100010, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10100011, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10100100, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10100101, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10100110, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10100111, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10101000, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10101001, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10101010, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10101011, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10101100, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10101101, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10101110, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10101111, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10110000, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10110001, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10110010, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10110011, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10110100, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10110101, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10110110, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10110111, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10111000, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10111001, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10111010, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10111011, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10111100, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10111101, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10111110, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b10111111, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11000000, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11000001, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11000010, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11000011, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11000100, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11000101, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11000110, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11000111, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11001000, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11001001, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11001010, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11001011, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11001100, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11001101, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11001110, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11001111, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11010000, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11010001, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11010010, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11010011, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11010100, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11010101, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11010110, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11010111, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11011000, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11011001, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11011010, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11011011, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11011100, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11011101, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11011110, source: DomainOwnerSource::SelectorLaw },
    DomainOwnerCoordinate { width: 8, bits: 0b11011111, source: DomainOwnerSource::SelectorLaw },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_projection_separates_domain_existence_from_residency() {
        assert_eq!(DOMAIN_WIDTHS_IN_SCOPE, &[3, 4, 5, 6, 7, 8]);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 3).count(), 7);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 4).count(), 14);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 5).count(), 32);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 6).count(), 64);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 7).count(), 0);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 8).count(), 64);

        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.source == DomainOwnerSource::ExactWidthCorpus).count(), 21);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.source == DomainOwnerSource::Od005).count(), 32);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.source == DomainOwnerSource::Od006).count(), 64);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.source == DomainOwnerSource::SelectorLaw).count(), 64);
    }

    #[test]
    fn generated_projection_has_controls_without_width_based_invention() {
        for (width, bits) in [
            (4, 0b1100),
            (5, 0b01010),
            (6, 0b001111),
            (8, 0b10100000),
            (8, 0b11011111),
        ] {
            assert!(DOMAIN_OWNER_COORDINATES
                .iter()
                .any(|row| row.width == width && row.bits == bits));
        }
        assert!(!DOMAIN_OWNER_COORDINATES.iter().any(|row| row.width == 7));
        assert!(!DOMAIN_OWNER_COORDINATES
            .iter()
            .any(|row| row.width == 8 && row.bits < 0b10100000));
    }

    #[test]
    fn generated_projection_has_unique_domain_coordinates() {
        let mut seen = std::collections::HashSet::new();
        for row in DOMAIN_OWNER_COORDINATES {
            assert!(seen.insert((row.width, row.bits)));
        }
    }
}
