// GENERATED — DO NOT EDIT BY HAND.
// Authority: Contract 11 D3/D4 + D5/D6 owner maps.
// Surface aliases may be donated by lib/surface/semantic-registry.lisp,
// but legacy byte positions never determine domain identity.
// Generator: scripts/generate-domain-surface-registry.py

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) struct DomainSurfaceRow {
    pub(super) width: u8,
    pub(super) bits: u8,
    pub(super) role: &'static str,
    // Compatibility implementation coordinate only; never identity.
    pub(super) legacy_backend_byte: Option<u8>,
    pub(super) surfaces: &'static [&'static str],
}

pub(super) const DOMAIN_SURFACE_ROWS: &[DomainSurfaceRow] = &[
    DomainSurfaceRow { width: 3, bits: 0b001, role: "QUOTE", legacy_backend_byte: Some(0b00000001), surfaces: &["quote", "quote", "як-є", "як-є", "svarūpa", "'"] },
    DomainSurfaceRow { width: 3, bits: 0b010, role: "ATOM", legacy_backend_byte: Some(0b00000010), surfaces: &["atom", "atom?", "атом?", "атом?", "aṇu", ".?"] },
    DomainSurfaceRow { width: 3, bits: 0b011, role: "COND", legacy_backend_byte: Some(0b00000111), surfaces: &["cond", "cond", "за-умовою", "за-умовою", "anukrama", "?:"] },
    DomainSurfaceRow { width: 3, bits: 0b100, role: "CONS", legacy_backend_byte: Some(0b00000100), surfaces: &["cons", "cons", "сполучити", "сполучити", "saṃyuj"] },
    DomainSurfaceRow { width: 3, bits: 0b101, role: "CAR", legacy_backend_byte: Some(0b00000101), surfaces: &["car", "car", "перше", "перше", "ādi", ":п"] },
    DomainSurfaceRow { width: 3, bits: 0b110, role: "CDR", legacy_backend_byte: Some(0b00000110), surfaces: &["cdr", "cdr", "решта", "решта", "śeṣa", ":р"] },
    DomainSurfaceRow { width: 3, bits: 0b111, role: "EQ", legacy_backend_byte: Some(0b00000011), surfaces: &["eq", "eq?", "тотожне?", "тотожне?", "abheda", "=?"] },
    DomainSurfaceRow { width: 4, bits: 0b0000, role: "APPLY", legacy_backend_byte: Some(0b10101111), surfaces: &["apply", "apply", "застосувати", "застосувати"] },
    DomainSurfaceRow { width: 4, bits: 0b0001, role: "EVAL", legacy_backend_byte: Some(0b01001101), surfaces: &["eval", "eval", "обчислити", "обчислити", "vicāraṇa"] },
    DomainSurfaceRow { width: 4, bits: 0b0010, role: "LAMBDA", legacy_backend_byte: Some(0b00001000), surfaces: &["lambda", "lambda", "функція", "функція"] },
    DomainSurfaceRow { width: 4, bits: 0b0011, role: "DEFINE", legacy_backend_byte: Some(0b00001001), surfaces: &["define", "define", "визначити", "визначити"] },
    DomainSurfaceRow { width: 4, bits: 0b0100, role: "NOT", legacy_backend_byte: Some(0b00100001), surfaces: &["not", "not?", "хибне?", "хибне?", "na"] },
    DomainSurfaceRow { width: 4, bits: 0b0110, role: "EVCON", legacy_backend_byte: None, surfaces: &["evcon"] },
    DomainSurfaceRow { width: 4, bits: 0b0111, role: "EVLIS", legacy_backend_byte: None, surfaces: &["evlis"] },
    DomainSurfaceRow { width: 4, bits: 0b1000, role: "LIST", legacy_backend_byte: Some(0b00100111), surfaces: &["list", "list", "список", "список", "śreṇī"] },
    DomainSurfaceRow { width: 4, bits: 0b1010, role: "CAAR", legacy_backend_byte: Some(0b00110011), surfaces: &["caar", "caar", "перше-від-першого"] },
    DomainSurfaceRow { width: 4, bits: 0b1011, role: "CADR", legacy_backend_byte: Some(0b00110100), surfaces: &["cadr", "cadr", "перше-від-решти"] },
    DomainSurfaceRow { width: 4, bits: 0b1100, role: "CDAR", legacy_backend_byte: None, surfaces: &["cdar"] },
    DomainSurfaceRow { width: 4, bits: 0b1101, role: "CDDR", legacy_backend_byte: Some(0b00110101), surfaces: &["cddr", "cddr", "решта-від-решти"] },
    DomainSurfaceRow { width: 4, bits: 0b1110, role: "LOOKUP", legacy_backend_byte: None, surfaces: &["lookup"] },
    DomainSurfaceRow { width: 4, bits: 0b1111, role: "BIND", legacy_backend_byte: None, surfaces: &["bind"] },
    DomainSurfaceRow { width: 5, bits: 0b00000, role: "EVALQUOTE", legacy_backend_byte: None, surfaces: &["evalquote"] },
    DomainSurfaceRow { width: 5, bits: 0b00001, role: "FUNCTION", legacy_backend_byte: None, surfaces: &["function"] },
    DomainSurfaceRow { width: 5, bits: 0b00010, role: "FEXPR", legacy_backend_byte: None, surfaces: &["fexpr"] },
    DomainSurfaceRow { width: 5, bits: 0b00011, role: "MACRO", legacy_backend_byte: None, surfaces: &["macro"] },
    DomainSurfaceRow { width: 5, bits: 0b00100, role: "LABEL", legacy_backend_byte: Some(0b10101010), surfaces: &["label", "label", "мітка", "мітка"] },
    DomainSurfaceRow { width: 5, bits: 0b00101, role: "PROG", legacy_backend_byte: None, surfaces: &["prog"] },
    DomainSurfaceRow { width: 5, bits: 0b00110, role: "SET", legacy_backend_byte: None, surfaces: &["set"] },
    DomainSurfaceRow { width: 5, bits: 0b00111, role: "SETQ", legacy_backend_byte: None, surfaces: &["setq"] },
    DomainSurfaceRow { width: 5, bits: 0b01000, role: "ZEROP", legacy_backend_byte: None, surfaces: &["zerop"] },
    DomainSurfaceRow { width: 5, bits: 0b01001, role: "NUMBERP", legacy_backend_byte: None, surfaces: &["numberp"] },
    DomainSurfaceRow { width: 5, bits: 0b01010, role: "PLUS", legacy_backend_byte: Some(0b00001100), surfaces: &["plus", "plus", "додати", "додати", "yoga", "+"] },
    DomainSurfaceRow { width: 5, bits: 0b01011, role: "DIFFERENCE", legacy_backend_byte: Some(0b00001101), surfaces: &["difference", "difference", "відняти", "відняти", "viyoga", "-"] },
    DomainSurfaceRow { width: 5, bits: 0b01100, role: "GO", legacy_backend_byte: None, surfaces: &["go"] },
    DomainSurfaceRow { width: 5, bits: 0b01101, role: "RETURN", legacy_backend_byte: None, surfaces: &["return"] },
    DomainSurfaceRow { width: 5, bits: 0b01110, role: "LESSP", legacy_backend_byte: Some(0b00011010), surfaces: &["lessp", "lessp?", "менше?", "менше?", "hīna?", "<"] },
    DomainSurfaceRow { width: 5, bits: 0b01111, role: "GREATERP", legacy_backend_byte: Some(0b00011011), surfaces: &["greaterp", "greaterp?", "більше?", "більше?", "adhika?", ">"] },
    DomainSurfaceRow { width: 5, bits: 0b10000, role: "APPEND", legacy_backend_byte: Some(0b00101001), surfaces: &["append", "append", "приєднати", "приєднати", "saṅkalana"] },
    DomainSurfaceRow { width: 5, bits: 0b10001, role: "REVERSE", legacy_backend_byte: Some(0b00101010), surfaces: &["reverse", "reverse", "зворот", "зворот", "viloma"] },
    DomainSurfaceRow { width: 5, bits: 0b10010, role: "TIMES", legacy_backend_byte: Some(0b00001110), surfaces: &["times", "times", "помножити", "помножити", "guṇana", "*"] },
    DomainSurfaceRow { width: 5, bits: 0b10011, role: "QUOTIENT", legacy_backend_byte: Some(0b00001111), surfaces: &["divide", "divide", "поділити", "поділити", "haraṇa", "/"] },
    DomainSurfaceRow { width: 5, bits: 0b10100, role: "CAAAR", legacy_backend_byte: None, surfaces: &["caaar"] },
    DomainSurfaceRow { width: 5, bits: 0b10101, role: "CAADR", legacy_backend_byte: None, surfaces: &["caadr"] },
    DomainSurfaceRow { width: 5, bits: 0b10110, role: "CADAR", legacy_backend_byte: None, surfaces: &["cadar"] },
    DomainSurfaceRow { width: 5, bits: 0b10111, role: "CADDR", legacy_backend_byte: None, surfaces: &["caddr"] },
    DomainSurfaceRow { width: 5, bits: 0b11000, role: "CDAAR", legacy_backend_byte: None, surfaces: &["cdaar"] },
    DomainSurfaceRow { width: 5, bits: 0b11001, role: "CDADR", legacy_backend_byte: None, surfaces: &["cdadr"] },
    DomainSurfaceRow { width: 5, bits: 0b11010, role: "CDDAR", legacy_backend_byte: None, surfaces: &["cddar"] },
    DomainSurfaceRow { width: 5, bits: 0b11011, role: "CDDDR", legacy_backend_byte: None, surfaces: &["cdddr"] },
    DomainSurfaceRow { width: 5, bits: 0b11100, role: "ASSOC", legacy_backend_byte: Some(0b00101101), surfaces: &["assoc", "assoc", "знайти-за-ключем", "знайти-за-ключем", "saṃbandha"] },
    DomainSurfaceRow { width: 5, bits: 0b11101, role: "MEMBER", legacy_backend_byte: Some(0b00101100), surfaces: &["member", "member?", "значення-у-списку?", "значення-у-списку?", "sambaddha?"] },
    DomainSurfaceRow { width: 5, bits: 0b11110, role: "PAIRLIS", legacy_backend_byte: None, surfaces: &["pairlis"] },
    DomainSurfaceRow { width: 5, bits: 0b11111, role: "SUBST", legacy_backend_byte: Some(0b10101100), surfaces: &["subst", "subst", "замінити", "замінити"] },
    DomainSurfaceRow { width: 6, bits: 0b000000, role: "REPL", legacy_backend_byte: None, surfaces: &["repl"] },
    DomainSurfaceRow { width: 6, bits: 0b000001, role: "LOAD", legacy_backend_byte: None, surfaces: &["load"] },
    DomainSurfaceRow { width: 6, bits: 0b000010, role: "CLOSURE", legacy_backend_byte: None, surfaces: &["closure"] },
    DomainSurfaceRow { width: 6, bits: 0b000011, role: "CURRY", legacy_backend_byte: None, surfaces: &["curry"] },
    DomainSurfaceRow { width: 6, bits: 0b000100, role: "FSUBR", legacy_backend_byte: None, surfaces: &["fsubr"] },
    DomainSurfaceRow { width: 6, bits: 0b000101, role: "LEXPR", legacy_backend_byte: None, surfaces: &["lexpr"] },
    DomainSurfaceRow { width: 6, bits: 0b000110, role: "MACROEXPAND-1", legacy_backend_byte: None, surfaces: &["macroexpand-1"] },
    DomainSurfaceRow { width: 6, bits: 0b000111, role: "MACROEXPAND", legacy_backend_byte: None, surfaces: &["macroexpand"] },
    DomainSurfaceRow { width: 6, bits: 0b001000, role: "LET", legacy_backend_byte: Some(0b10011100), surfaces: &["let", "let", "нехай", "нехай"] },
    DomainSurfaceRow { width: 6, bits: 0b001001, role: "LET*", legacy_backend_byte: Some(0b10011101), surfaces: &["let*", "let*", "нехай*", "нехай-послідовно"] },
    DomainSurfaceRow { width: 6, bits: 0b001010, role: "DO", legacy_backend_byte: None, surfaces: &["do"] },
    DomainSurfaceRow { width: 6, bits: 0b001011, role: "WHILE", legacy_backend_byte: None, surfaces: &["while"] },
    DomainSurfaceRow { width: 6, bits: 0b001100, role: "RPLACA", legacy_backend_byte: None, surfaces: &["rplaca"] },
    DomainSurfaceRow { width: 6, bits: 0b001101, role: "RPLACD", legacy_backend_byte: None, surfaces: &["rplacd"] },
    DomainSurfaceRow { width: 6, bits: 0b001110, role: "SETF", legacy_backend_byte: None, surfaces: &["setf"] },
    DomainSurfaceRow { width: 6, bits: 0b001111, role: "DEFVAR", legacy_backend_byte: None, surfaces: &["defvar"] },
    DomainSurfaceRow { width: 6, bits: 0b010000, role: "EVENP", legacy_backend_byte: None, surfaces: &["evenp"] },
    DomainSurfaceRow { width: 6, bits: 0b010001, role: "ODDP", legacy_backend_byte: None, surfaces: &["oddp"] },
    DomainSurfaceRow { width: 6, bits: 0b010010, role: "INTEGERP", legacy_backend_byte: None, surfaces: &["integerp"] },
    DomainSurfaceRow { width: 6, bits: 0b010011, role: "RATIONALP", legacy_backend_byte: None, surfaces: &["rationalp"] },
    DomainSurfaceRow { width: 6, bits: 0b010100, role: "ADD1", legacy_backend_byte: None, surfaces: &["add1"] },
    DomainSurfaceRow { width: 6, bits: 0b010101, role: "ABS", legacy_backend_byte: Some(0b00010000), surfaces: &["abs", "abs", "модуль", "модуль", "rūpa"] },
    DomainSurfaceRow { width: 6, bits: 0b010110, role: "SUB1", legacy_backend_byte: None, surfaces: &["sub1"] },
    DomainSurfaceRow { width: 6, bits: 0b010111, role: "NEG", legacy_backend_byte: None, surfaces: &["neg"] },
    DomainSurfaceRow { width: 6, bits: 0b011000, role: "TAGBODY", legacy_backend_byte: None, surfaces: &["tagbody"] },
    DomainSurfaceRow { width: 6, bits: 0b011001, role: "BLOCK", legacy_backend_byte: None, surfaces: &["block"] },
    DomainSurfaceRow { width: 6, bits: 0b011010, role: "RETURN-FROM", legacy_backend_byte: None, surfaces: &["return-from"] },
    DomainSurfaceRow { width: 6, bits: 0b011011, role: "CATCH", legacy_backend_byte: None, surfaces: &["catch"] },
    DomainSurfaceRow { width: 6, bits: 0b011100, role: "LEQ", legacy_backend_byte: Some(0b00011101), surfaces: &["leq", "not-greaterp?", "не-більше?", "не-більше?", "na-adhika?", "<="] },
    DomainSurfaceRow { width: 6, bits: 0b011101, role: "MIN", legacy_backend_byte: Some(0b00010001), surfaces: &["min", "min", "найменше", "найменше", "alpatara"] },
    DomainSurfaceRow { width: 6, bits: 0b011110, role: "GEQ", legacy_backend_byte: Some(0b00011110), surfaces: &["geq", "not-lessp?", "не-менше?", "не-менше?", "na-hīna?", ">="] },
    DomainSurfaceRow { width: 6, bits: 0b011111, role: "MAX", legacy_backend_byte: Some(0b00010010), surfaces: &["max", "max", "найбільше", "найбільше", "brhattara"] },
    DomainSurfaceRow { width: 6, bits: 0b100000, role: "NCONC", legacy_backend_byte: None, surfaces: &["nconc"] },
    DomainSurfaceRow { width: 6, bits: 0b100001, role: "LENGTH", legacy_backend_byte: Some(0b00101000), surfaces: &["length", "length", "довжина", "довжина", "pramāṇa"] },
    DomainSurfaceRow { width: 6, bits: 0b100010, role: "NREVERSE", legacy_backend_byte: None, surfaces: &["nreverse"] },
    DomainSurfaceRow { width: 6, bits: 0b100011, role: "NTH", legacy_backend_byte: Some(0b00101011), surfaces: &["nth", "nth", "елемент-списку-за-індексом", "елемент-списку-за-індексом", "kramāṅka"] },
    DomainSurfaceRow { width: 6, bits: 0b100100, role: "EXPT", legacy_backend_byte: None, surfaces: &["expt"] },
    DomainSurfaceRow { width: 6, bits: 0b100101, role: "GCD", legacy_backend_byte: None, surfaces: &["gcd"] },
    DomainSurfaceRow { width: 6, bits: 0b100110, role: "REMAINDER", legacy_backend_byte: None, surfaces: &["remainder"] },
    DomainSurfaceRow { width: 6, bits: 0b100111, role: "RECIP", legacy_backend_byte: None, surfaces: &["recip"] },
    DomainSurfaceRow { width: 6, bits: 0b101000, role: "CAAAAR", legacy_backend_byte: None, surfaces: &["caaaar"] },
    DomainSurfaceRow { width: 6, bits: 0b101001, role: "CAAADR", legacy_backend_byte: None, surfaces: &["caaadr"] },
    DomainSurfaceRow { width: 6, bits: 0b101010, role: "CAADAR", legacy_backend_byte: None, surfaces: &["caadar"] },
    DomainSurfaceRow { width: 6, bits: 0b101011, role: "CAADDR", legacy_backend_byte: None, surfaces: &["caaddr"] },
    DomainSurfaceRow { width: 6, bits: 0b101100, role: "CADAAR", legacy_backend_byte: None, surfaces: &["cadaar"] },
    DomainSurfaceRow { width: 6, bits: 0b101101, role: "CADADR", legacy_backend_byte: None, surfaces: &["cadadr"] },
    DomainSurfaceRow { width: 6, bits: 0b101110, role: "CADDAR", legacy_backend_byte: None, surfaces: &["caddar"] },
    DomainSurfaceRow { width: 6, bits: 0b101111, role: "CADDDR", legacy_backend_byte: Some(0b00110110), surfaces: &["cadddr", "cadddr", "перше-після-трьох-решт"] },
    DomainSurfaceRow { width: 6, bits: 0b110000, role: "CDAAAR", legacy_backend_byte: None, surfaces: &["cdaaar"] },
    DomainSurfaceRow { width: 6, bits: 0b110001, role: "CDAADR", legacy_backend_byte: None, surfaces: &["cdaadr"] },
    DomainSurfaceRow { width: 6, bits: 0b110010, role: "CDADAR", legacy_backend_byte: None, surfaces: &["cdadar"] },
    DomainSurfaceRow { width: 6, bits: 0b110011, role: "CDADDR", legacy_backend_byte: None, surfaces: &["cdaddr"] },
    DomainSurfaceRow { width: 6, bits: 0b110100, role: "CDDAAR", legacy_backend_byte: None, surfaces: &["cddaar"] },
    DomainSurfaceRow { width: 6, bits: 0b110101, role: "CDDADR", legacy_backend_byte: None, surfaces: &["cddadr"] },
    DomainSurfaceRow { width: 6, bits: 0b110110, role: "CDDDAR", legacy_backend_byte: None, surfaces: &["cdddar"] },
    DomainSurfaceRow { width: 6, bits: 0b110111, role: "CDDDDR", legacy_backend_byte: None, surfaces: &["cddddr"] },
    DomainSurfaceRow { width: 6, bits: 0b111000, role: "RASSOC", legacy_backend_byte: None, surfaces: &["rassoc"] },
    DomainSurfaceRow { width: 6, bits: 0b111001, role: "ACONS", legacy_backend_byte: None, surfaces: &["acons"] },
    DomainSurfaceRow { width: 6, bits: 0b111010, role: "INTERSECTION", legacy_backend_byte: None, surfaces: &["intersection"] },
    DomainSurfaceRow { width: 6, bits: 0b111011, role: "UNION", legacy_backend_byte: None, surfaces: &["union"] },
    DomainSurfaceRow { width: 6, bits: 0b111100, role: "MAPCAR", legacy_backend_byte: None, surfaces: &["mapcar"] },
    DomainSurfaceRow { width: 6, bits: 0b111101, role: "MAPLIST", legacy_backend_byte: Some(0b10101110), surfaces: &["maplist", "maplist", "відобразити-залишки", "відобразити-залишки"] },
    DomainSurfaceRow { width: 6, bits: 0b111110, role: "SUBLIS", legacy_backend_byte: Some(0b10101101), surfaces: &["sublis", "sublis", "підставити-пари", "підставити-пари"] },
    DomainSurfaceRow { width: 6, bits: 0b111111, role: "COPY-TREE", legacy_backend_byte: None, surfaces: &["copy-tree"] },
];
