// GENERATED — DO NOT EDIT BY HAND.
// Authority: Contract 11 D3/D4 + D5/D6 owner maps.
// Surface aliases may be donated by lib/surface/semantic-registry.lisp,
// but legacy byte positions never determine domain identity.
// Generator: scripts/generate-domain-surface-registry.py

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) struct DomainSurfaceRow {
    pub(super) width: u8,
    pub(super) bits: u8,
    pub(super) role: &'static str,
    pub(super) surfaces: &'static [&'static str],
}

pub(super) const DOMAIN_SURFACE_ROWS: &[DomainSurfaceRow] = &[
    DomainSurfaceRow { width: 3, bits: 0b001, role: "QUOTE", surfaces: &["quote", "quote", "як-є", "як-є", "svarūpa", "'"] },
    DomainSurfaceRow { width: 3, bits: 0b010, role: "ATOM", surfaces: &["atom", "atom?", "атом?", "атом?", "aṇu", ".?"] },
    DomainSurfaceRow { width: 3, bits: 0b011, role: "COND", surfaces: &["cond", "cond", "за-умовою", "за-умовою", "anukrama", "?:"] },
    DomainSurfaceRow { width: 3, bits: 0b100, role: "CONS", surfaces: &["cons", "cons", "сполучити", "сполучити", "saṃyuj"] },
    DomainSurfaceRow { width: 3, bits: 0b101, role: "CAR", surfaces: &["car", "car", "перше", "перше", "ādi", ":п"] },
    DomainSurfaceRow { width: 3, bits: 0b110, role: "CDR", surfaces: &["cdr", "cdr", "решта", "решта", "śeṣa", ":р"] },
    DomainSurfaceRow { width: 3, bits: 0b111, role: "EQ", surfaces: &["eq", "eq?", "тотожне?", "тотожне?", "abheda", "=?"] },
    DomainSurfaceRow { width: 4, bits: 0b0000, role: "APPLY", surfaces: &["apply", "apply", "застосувати", "застосувати"] },
    DomainSurfaceRow { width: 4, bits: 0b0001, role: "EVAL", surfaces: &["eval", "eval", "обчислити", "обчислити", "vicāraṇa"] },
    DomainSurfaceRow { width: 4, bits: 0b0010, role: "LAMBDA", surfaces: &["lambda", "lambda", "функція", "функція"] },
    DomainSurfaceRow { width: 4, bits: 0b0011, role: "DEFINE", surfaces: &["define", "define", "визначити", "визначити"] },
    DomainSurfaceRow { width: 4, bits: 0b0100, role: "NOT", surfaces: &["not", "not?", "хибне?", "хибне?", "na"] },
    DomainSurfaceRow { width: 4, bits: 0b0110, role: "EVCON", surfaces: &["evcon"] },
    DomainSurfaceRow { width: 4, bits: 0b0111, role: "EVLIS", surfaces: &["evlis"] },
    DomainSurfaceRow { width: 4, bits: 0b1000, role: "LIST", surfaces: &["list", "list", "список", "список", "śreṇī"] },
    DomainSurfaceRow { width: 4, bits: 0b1010, role: "CAAR", surfaces: &["caar", "caar", "перше-від-першого"] },
    DomainSurfaceRow { width: 4, bits: 0b1011, role: "CADR", surfaces: &["cadr", "cadr", "перше-від-решти"] },
    DomainSurfaceRow { width: 4, bits: 0b1100, role: "CDAR", surfaces: &["cdar"] },
    DomainSurfaceRow { width: 4, bits: 0b1101, role: "CDDR", surfaces: &["cddr", "cddr", "решта-від-решти"] },
    DomainSurfaceRow { width: 4, bits: 0b1110, role: "LOOKUP", surfaces: &["lookup"] },
    DomainSurfaceRow { width: 4, bits: 0b1111, role: "BIND", surfaces: &["bind"] },
    DomainSurfaceRow { width: 5, bits: 0b00000, role: "EVALQUOTE", surfaces: &["evalquote"] },
    DomainSurfaceRow { width: 5, bits: 0b00001, role: "FUNCTION", surfaces: &["function"] },
    DomainSurfaceRow { width: 5, bits: 0b00010, role: "FEXPR", surfaces: &["fexpr"] },
    DomainSurfaceRow { width: 5, bits: 0b00011, role: "MACRO", surfaces: &["macro"] },
    DomainSurfaceRow { width: 5, bits: 0b00100, role: "LABEL", surfaces: &["label", "label", "мітка", "мітка"] },
    DomainSurfaceRow { width: 5, bits: 0b00101, role: "PROG", surfaces: &["prog"] },
    DomainSurfaceRow { width: 5, bits: 0b00110, role: "SET", surfaces: &["set"] },
    DomainSurfaceRow { width: 5, bits: 0b00111, role: "SETQ", surfaces: &["setq"] },
    DomainSurfaceRow { width: 5, bits: 0b01000, role: "ZEROP", surfaces: &["zerop"] },
    DomainSurfaceRow { width: 5, bits: 0b01001, role: "NUMBERP", surfaces: &["numberp"] },
    DomainSurfaceRow { width: 5, bits: 0b01010, role: "PLUS", surfaces: &["plus", "plus", "додати", "додати", "yoga", "+"] },
    DomainSurfaceRow { width: 5, bits: 0b01011, role: "DIFFERENCE", surfaces: &["difference", "difference", "відняти", "відняти", "viyoga", "-"] },
    DomainSurfaceRow { width: 5, bits: 0b01100, role: "GO", surfaces: &["go"] },
    DomainSurfaceRow { width: 5, bits: 0b01101, role: "RETURN", surfaces: &["return"] },
    DomainSurfaceRow { width: 5, bits: 0b01110, role: "LESSP", surfaces: &["lessp", "lessp?", "менше?", "менше?", "hīna?", "<"] },
    DomainSurfaceRow { width: 5, bits: 0b01111, role: "GREATERP", surfaces: &["greaterp", "greaterp?", "більше?", "більше?", "adhika?", ">"] },
    DomainSurfaceRow { width: 5, bits: 0b10000, role: "APPEND", surfaces: &["append", "append", "приєднати", "приєднати", "saṅkalana"] },
    DomainSurfaceRow { width: 5, bits: 0b10001, role: "REVERSE", surfaces: &["reverse", "reverse", "зворот", "зворот", "viloma"] },
    DomainSurfaceRow { width: 5, bits: 0b10010, role: "TIMES", surfaces: &["times", "times", "помножити", "помножити", "guṇana", "*"] },
    DomainSurfaceRow { width: 5, bits: 0b10011, role: "QUOTIENT", surfaces: &["quotient", "quotient", "частка", "частка", "bhāga", "divide", "поділити", "поділити", "haraṇa", "/"] },
    DomainSurfaceRow { width: 5, bits: 0b10100, role: "CAAAR", surfaces: &["caaar"] },
    DomainSurfaceRow { width: 5, bits: 0b10101, role: "CAADR", surfaces: &["caadr"] },
    DomainSurfaceRow { width: 5, bits: 0b10110, role: "CADAR", surfaces: &["cadar"] },
    DomainSurfaceRow { width: 5, bits: 0b10111, role: "CADDR", surfaces: &["caddr"] },
    DomainSurfaceRow { width: 5, bits: 0b11000, role: "CDAAR", surfaces: &["cdaar"] },
    DomainSurfaceRow { width: 5, bits: 0b11001, role: "CDADR", surfaces: &["cdadr"] },
    DomainSurfaceRow { width: 5, bits: 0b11010, role: "CDDAR", surfaces: &["cddar"] },
    DomainSurfaceRow { width: 5, bits: 0b11011, role: "CDDDR", surfaces: &["cdddr"] },
    DomainSurfaceRow { width: 5, bits: 0b11100, role: "ASSOC", surfaces: &["assoc", "assoc", "знайти-за-ключем", "знайти-за-ключем", "saṃbandha"] },
    DomainSurfaceRow { width: 5, bits: 0b11101, role: "MEMBER", surfaces: &["member", "member?", "значення-у-списку?", "значення-у-списку?", "sambaddha?"] },
    DomainSurfaceRow { width: 5, bits: 0b11110, role: "PAIRLIS", surfaces: &["pairlis"] },
    DomainSurfaceRow { width: 5, bits: 0b11111, role: "SUBST", surfaces: &["subst", "subst", "замінити", "замінити"] },
    DomainSurfaceRow { width: 6, bits: 0b000000, role: "REPL", surfaces: &["repl"] },
    DomainSurfaceRow { width: 6, bits: 0b000001, role: "LOAD", surfaces: &["load"] },
    DomainSurfaceRow { width: 6, bits: 0b000010, role: "CLOSURE", surfaces: &["closure"] },
    DomainSurfaceRow { width: 6, bits: 0b000011, role: "CURRY", surfaces: &["curry"] },
    DomainSurfaceRow { width: 6, bits: 0b000100, role: "FSUBR", surfaces: &["fsubr"] },
    DomainSurfaceRow { width: 6, bits: 0b000101, role: "LEXPR", surfaces: &["lexpr"] },
    DomainSurfaceRow { width: 6, bits: 0b000110, role: "MACROEXPAND-1", surfaces: &["macroexpand-1"] },
    DomainSurfaceRow { width: 6, bits: 0b000111, role: "MACROEXPAND", surfaces: &["macroexpand"] },
    DomainSurfaceRow { width: 6, bits: 0b001000, role: "LET", surfaces: &["let", "let", "нехай", "нехай"] },
    DomainSurfaceRow { width: 6, bits: 0b001001, role: "LET*", surfaces: &["let*", "let*", "нехай*", "нехай-послідовно"] },
    DomainSurfaceRow { width: 6, bits: 0b001010, role: "DO", surfaces: &["do"] },
    DomainSurfaceRow { width: 6, bits: 0b001011, role: "WHILE", surfaces: &["while"] },
    DomainSurfaceRow { width: 6, bits: 0b001100, role: "RPLACA", surfaces: &["rplaca"] },
    DomainSurfaceRow { width: 6, bits: 0b001101, role: "RPLACD", surfaces: &["rplacd"] },
    DomainSurfaceRow { width: 6, bits: 0b001110, role: "SETF", surfaces: &["setf"] },
    DomainSurfaceRow { width: 6, bits: 0b001111, role: "DEFVAR", surfaces: &["defvar"] },
    DomainSurfaceRow { width: 6, bits: 0b010000, role: "EVENP", surfaces: &["evenp"] },
    DomainSurfaceRow { width: 6, bits: 0b010001, role: "ODDP", surfaces: &["oddp"] },
    DomainSurfaceRow { width: 6, bits: 0b010010, role: "INTEGERP", surfaces: &["integerp"] },
    DomainSurfaceRow { width: 6, bits: 0b010011, role: "RATIONALP", surfaces: &["rationalp"] },
    DomainSurfaceRow { width: 6, bits: 0b010100, role: "ADD1", surfaces: &["add1"] },
    DomainSurfaceRow { width: 6, bits: 0b010101, role: "ABS", surfaces: &["abs", "abs", "модуль", "модуль", "rūpa"] },
    DomainSurfaceRow { width: 6, bits: 0b010110, role: "SUB1", surfaces: &["sub1"] },
    DomainSurfaceRow { width: 6, bits: 0b010111, role: "NEG", surfaces: &["neg"] },
    DomainSurfaceRow { width: 6, bits: 0b011000, role: "TAGBODY", surfaces: &["tagbody"] },
    DomainSurfaceRow { width: 6, bits: 0b011001, role: "BLOCK", surfaces: &["block"] },
    DomainSurfaceRow { width: 6, bits: 0b011010, role: "RETURN-FROM", surfaces: &["return-from"] },
    DomainSurfaceRow { width: 6, bits: 0b011011, role: "CATCH", surfaces: &["catch"] },
    DomainSurfaceRow { width: 6, bits: 0b011100, role: "LEQ", surfaces: &["leq", "not-greaterp?", "не-більше?", "не-більше?", "na-adhika?", "<="] },
    DomainSurfaceRow { width: 6, bits: 0b011101, role: "MIN", surfaces: &["min", "min", "найменше", "найменше", "alpatara"] },
    DomainSurfaceRow { width: 6, bits: 0b011110, role: "GEQ", surfaces: &["geq", "not-lessp?", "не-менше?", "не-менше?", "na-hīna?", ">="] },
    DomainSurfaceRow { width: 6, bits: 0b011111, role: "MAX", surfaces: &["max", "max", "найбільше", "найбільше", "brhattara"] },
    DomainSurfaceRow { width: 6, bits: 0b100000, role: "NCONC", surfaces: &["nconc"] },
    DomainSurfaceRow { width: 6, bits: 0b100001, role: "LENGTH", surfaces: &["length", "length", "довжина", "довжина", "pramāṇa"] },
    DomainSurfaceRow { width: 6, bits: 0b100010, role: "NREVERSE", surfaces: &["nreverse"] },
    DomainSurfaceRow { width: 6, bits: 0b100011, role: "NTH", surfaces: &["nth", "nth", "елемент-списку-за-індексом", "елемент-списку-за-індексом", "kramāṅka"] },
    DomainSurfaceRow { width: 6, bits: 0b100100, role: "EXPT", surfaces: &["expt"] },
    DomainSurfaceRow { width: 6, bits: 0b100101, role: "GCD", surfaces: &["gcd"] },
    DomainSurfaceRow { width: 6, bits: 0b100110, role: "REMAINDER", surfaces: &["remainder"] },
    DomainSurfaceRow { width: 6, bits: 0b100111, role: "RECIP", surfaces: &["recip"] },
    DomainSurfaceRow { width: 6, bits: 0b101000, role: "CAAAAR", surfaces: &["caaaar"] },
    DomainSurfaceRow { width: 6, bits: 0b101001, role: "CAAADR", surfaces: &["caaadr"] },
    DomainSurfaceRow { width: 6, bits: 0b101010, role: "CAADAR", surfaces: &["caadar"] },
    DomainSurfaceRow { width: 6, bits: 0b101011, role: "CAADDR", surfaces: &["caaddr"] },
    DomainSurfaceRow { width: 6, bits: 0b101100, role: "CADAAR", surfaces: &["cadaar"] },
    DomainSurfaceRow { width: 6, bits: 0b101101, role: "CADADR", surfaces: &["cadadr"] },
    DomainSurfaceRow { width: 6, bits: 0b101110, role: "CADDAR", surfaces: &["caddar"] },
    DomainSurfaceRow { width: 6, bits: 0b101111, role: "CADDDR", surfaces: &["cadddr", "cadddr", "перше-після-трьох-решт"] },
    DomainSurfaceRow { width: 6, bits: 0b110000, role: "CDAAAR", surfaces: &["cdaaar"] },
    DomainSurfaceRow { width: 6, bits: 0b110001, role: "CDAADR", surfaces: &["cdaadr"] },
    DomainSurfaceRow { width: 6, bits: 0b110010, role: "CDADAR", surfaces: &["cdadar"] },
    DomainSurfaceRow { width: 6, bits: 0b110011, role: "CDADDR", surfaces: &["cdaddr"] },
    DomainSurfaceRow { width: 6, bits: 0b110100, role: "CDDAAR", surfaces: &["cddaar"] },
    DomainSurfaceRow { width: 6, bits: 0b110101, role: "CDDADR", surfaces: &["cddadr"] },
    DomainSurfaceRow { width: 6, bits: 0b110110, role: "CDDDAR", surfaces: &["cdddar"] },
    DomainSurfaceRow { width: 6, bits: 0b110111, role: "CDDDDR", surfaces: &["cddddr"] },
    DomainSurfaceRow { width: 6, bits: 0b111000, role: "RASSOC", surfaces: &["rassoc"] },
    DomainSurfaceRow { width: 6, bits: 0b111001, role: "ACONS", surfaces: &["acons"] },
    DomainSurfaceRow { width: 6, bits: 0b111010, role: "INTERSECTION", surfaces: &["intersection"] },
    DomainSurfaceRow { width: 6, bits: 0b111011, role: "UNION", surfaces: &["union"] },
    DomainSurfaceRow { width: 6, bits: 0b111100, role: "MAPCAR", surfaces: &["mapcar"] },
    DomainSurfaceRow { width: 6, bits: 0b111101, role: "MAPLIST", surfaces: &["maplist", "maplist", "відобразити-залишки", "відобразити-залишки"] },
    DomainSurfaceRow { width: 6, bits: 0b111110, role: "SUBLIS", surfaces: &["sublis", "sublis", "підставити-пари", "підставити-пари"] },
    DomainSurfaceRow { width: 6, bits: 0b111111, role: "COPY-TREE", surfaces: &["copy-tree"] },
];
