// GENERATED — DO NOT EDIT BY HAND.
// Authority: lib/surface/domain-surfaces-d1-d4.lisp + domain-surfaces-d5.lisp
// Checked by: scripts/check-domain-surfaces-d1-d4.py

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) struct DomainSurfaceName {
    pub(super) namespace: &'static str,
    pub(super) name: &'static str,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) struct DomainSurfaceRow {
    pub(super) width: u8,
    pub(super) bits: u8,
    pub(super) source_routable: bool,
    pub(super) surfaces: &'static [DomainSurfaceName],
}

pub(super) const DOMAIN_SURFACE_ROWS: &[DomainSurfaceRow] = &[
    DomainSurfaceRow { width: 1, bits: 0b0, source_routable: false, surfaces: &[DomainSurfaceName { namespace: "uk", name: "ні" }, DomainSurfaceName { namespace: "sa", name: "na" }] },
    DomainSurfaceRow { width: 1, bits: 0b1, source_routable: false, surfaces: &[DomainSurfaceName { namespace: "uk", name: "так" }, DomainSurfaceName { namespace: "sa", name: "ām" }] },
    DomainSurfaceRow { width: 2, bits: 0b00, source_routable: false, surfaces: &[DomainSurfaceName { namespace: "uk", name: "пропуск" }, DomainSurfaceName { namespace: "sa", name: "antarāla" }] },
    DomainSurfaceRow { width: 2, bits: 0b01, source_routable: false, surfaces: &[DomainSurfaceName { namespace: "uk", name: "закрити" }, DomainSurfaceName { namespace: "sa", name: "samāpana" }] },
    DomainSurfaceRow { width: 2, bits: 0b10, source_routable: false, surfaces: &[DomainSurfaceName { namespace: "uk", name: "відкрити" }, DomainSurfaceName { namespace: "sa", name: "udghāṭana" }] },
    DomainSurfaceRow { width: 2, bits: 0b11, source_routable: false, surfaces: &[DomainSurfaceName { namespace: "uk", name: "крапка" }, DomainSurfaceName { namespace: "sa", name: "bindu" }] },
    DomainSurfaceRow { width: 3, bits: 0b000, source_routable: false, surfaces: &[DomainSurfaceName { namespace: "uk", name: "порожнє" }, DomainSurfaceName { namespace: "sa", name: "śūnya" }] },
    DomainSurfaceRow { width: 3, bits: 0b001, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "як-є" }, DomainSurfaceName { namespace: "sa", name: "svarūpa" }] },
    DomainSurfaceRow { width: 3, bits: 0b010, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "атом?" }, DomainSurfaceName { namespace: "sa", name: "aṇu?" }] },
    DomainSurfaceRow { width: 3, bits: 0b011, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "решта" }, DomainSurfaceName { namespace: "sa", name: "śeṣa" }] },
    DomainSurfaceRow { width: 3, bits: 0b100, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "перше" }, DomainSurfaceName { namespace: "sa", name: "ādi" }] },
    DomainSurfaceRow { width: 3, bits: 0b101, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "тотожне?" }, DomainSurfaceName { namespace: "sa", name: "abheda?" }] },
    DomainSurfaceRow { width: 3, bits: 0b110, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "за-умовою" }, DomainSurfaceName { namespace: "sa", name: "krama" }] },
    DomainSurfaceRow { width: 3, bits: 0b111, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "сполучити" }, DomainSurfaceName { namespace: "sa", name: "saṃyuj" }] },
    DomainSurfaceRow { width: 4, bits: 0b0000, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "застосувати" }, DomainSurfaceName { namespace: "sa", name: "prayoga" }] },
    DomainSurfaceRow { width: 4, bits: 0b0001, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "обчислити" }, DomainSurfaceName { namespace: "sa", name: "vicāraṇa" }] },
    DomainSurfaceRow { width: 4, bits: 0b0010, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "функція" }, DomainSurfaceName { namespace: "sa", name: "phalana" }] },
    DomainSurfaceRow { width: 4, bits: 0b0011, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "визначити" }, DomainSurfaceName { namespace: "sa", name: "nirvacana" }] },
    DomainSurfaceRow { width: 4, bits: 0b0100, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "не" }, DomainSurfaceName { namespace: "sa", name: "niṣedha" }] },
    DomainSurfaceRow { width: 4, bits: 0b0101, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "порожнє?" }, DomainSurfaceName { namespace: "sa", name: "śūnya?" }] },
    DomainSurfaceRow { width: 4, bits: 0b0110, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "решта-від-першого" }, DomainSurfaceName { namespace: "sa", name: "śeṣa-ādi" }] },
    DomainSurfaceRow { width: 4, bits: 0b0111, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "решта-від-решти" }, DomainSurfaceName { namespace: "sa", name: "śeṣa-śeṣa" }] },
    DomainSurfaceRow { width: 4, bits: 0b1000, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "перше-від-першого" }, DomainSurfaceName { namespace: "sa", name: "ādi-ādi" }] },
    DomainSurfaceRow { width: 4, bits: 0b1001, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "перше-від-решти" }, DomainSurfaceName { namespace: "sa", name: "ādi-śeṣa" }] },
    DomainSurfaceRow { width: 4, bits: 0b1010, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "знайти" }, DomainSurfaceName { namespace: "sa", name: "anveṣaṇa" }] },
    DomainSurfaceRow { width: 4, bits: 0b1011, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "зв'язати" }, DomainSurfaceName { namespace: "sa", name: "bandha" }] },
    DomainSurfaceRow { width: 4, bits: 0b1100, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "обчислити-умови" }, DomainSurfaceName { namespace: "sa", name: "krama-vicāraṇa" }] },
    DomainSurfaceRow { width: 4, bits: 0b1101, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "обчислити-список" }, DomainSurfaceName { namespace: "sa", name: "śreṇī-vicāraṇa" }] },
    DomainSurfaceRow { width: 4, bits: 0b1110, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "список" }, DomainSurfaceName { namespace: "sa", name: "śreṇī" }] },
    DomainSurfaceRow { width: 4, bits: 0b1111, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "приєднати" }, DomainSurfaceName { namespace: "sa", name: "saṅkalana" }] },
    DomainSurfaceRow { width: 5, bits: 0b00000, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "обчислити-як-є" }, DomainSurfaceName { namespace: "sa", name: "svarūpa-vicāraṇa" }] },
    DomainSurfaceRow { width: 5, bits: 0b00001, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "функція-значення" }, DomainSurfaceName { namespace: "sa", name: "phalana-rūpa" }] },
    DomainSurfaceRow { width: 5, bits: 0b00010, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "необчислений-вираз" }, DomainSurfaceName { namespace: "sa", name: "avicārita-rūpa" }] },
    DomainSurfaceRow { width: 5, bits: 0b00011, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "макрос" }, DomainSurfaceName { namespace: "sa", name: "vistāra-rūpa" }] },
    DomainSurfaceRow { width: 5, bits: 0b00100, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "мітка" }, DomainSurfaceName { namespace: "sa", name: "cihna" }] },
    DomainSurfaceRow { width: 5, bits: 0b00101, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "програма" }, DomainSurfaceName { namespace: "sa", name: "kāryakrama" }] },
    DomainSurfaceRow { width: 5, bits: 0b00110, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "встановити" }, DomainSurfaceName { namespace: "sa", name: "sthāpana" }] },
    DomainSurfaceRow { width: 5, bits: 0b00111, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "встановити-ім'я" }, DomainSurfaceName { namespace: "sa", name: "nāma-sthāpana" }] },
    DomainSurfaceRow { width: 5, bits: 0b01000, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "нуль?" }, DomainSurfaceName { namespace: "sa", name: "saṅkhyā-śūnya?" }] },
    DomainSurfaceRow { width: 5, bits: 0b01001, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "число?" }, DomainSurfaceName { namespace: "sa", name: "saṅkhyā?" }] },
    DomainSurfaceRow { width: 5, bits: 0b01010, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "додати" }, DomainSurfaceName { namespace: "sa", name: "yoga" }] },
    DomainSurfaceRow { width: 5, bits: 0b01011, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "відняти" }, DomainSurfaceName { namespace: "sa", name: "viyoga" }] },
    DomainSurfaceRow { width: 5, bits: 0b01100, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "решта-від-першого-від-першого" }, DomainSurfaceName { namespace: "sa", name: "śeṣa-ādi-ādi" }] },
    DomainSurfaceRow { width: 5, bits: 0b01101, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "решта-від-першого-від-решти" }, DomainSurfaceName { namespace: "sa", name: "śeṣa-ādi-śeṣa" }] },
    DomainSurfaceRow { width: 5, bits: 0b01110, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "решта-від-решти-від-першого" }, DomainSurfaceName { namespace: "sa", name: "śeṣa-śeṣa-ādi" }] },
    DomainSurfaceRow { width: 5, bits: 0b01111, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "решта-від-решти-від-решти" }, DomainSurfaceName { namespace: "sa", name: "śeṣa-śeṣa-śeṣa" }] },
    DomainSurfaceRow { width: 5, bits: 0b10000, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "перше-від-першого-від-першого" }, DomainSurfaceName { namespace: "sa", name: "ādi-ādi-ādi" }] },
    DomainSurfaceRow { width: 5, bits: 0b10001, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "перше-від-першого-від-решти" }, DomainSurfaceName { namespace: "sa", name: "ādi-ādi-śeṣa" }] },
    DomainSurfaceRow { width: 5, bits: 0b10010, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "перше-від-решти-від-першого" }, DomainSurfaceName { namespace: "sa", name: "ādi-śeṣa-ādi" }] },
    DomainSurfaceRow { width: 5, bits: 0b10011, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "перше-від-решти-від-решти" }, DomainSurfaceName { namespace: "sa", name: "ādi-śeṣa-śeṣa" }] },
    DomainSurfaceRow { width: 5, bits: 0b10100, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "зворот" }, DomainSurfaceName { namespace: "sa", name: "viloma" }] },
    DomainSurfaceRow { width: 5, bits: 0b10101, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "зворот-до" }, DomainSurfaceName { namespace: "sa", name: "viloma-saṅkalana" }] },
    DomainSurfaceRow { width: 5, bits: 0b10110, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "помножити" }, DomainSurfaceName { namespace: "sa", name: "guṇana" }] },
    DomainSurfaceRow { width: 5, bits: 0b10111, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "частка" }, DomainSurfaceName { namespace: "sa", name: "bhāga" }] },
    DomainSurfaceRow { width: 5, bits: 0b11000, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "перейти" }, DomainSurfaceName { namespace: "sa", name: "gamana" }] },
    DomainSurfaceRow { width: 5, bits: 0b11001, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "повернути" }, DomainSurfaceName { namespace: "sa", name: "nivartana" }] },
    DomainSurfaceRow { width: 5, bits: 0b11010, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "менше?" }, DomainSurfaceName { namespace: "sa", name: "hīna?" }] },
    DomainSurfaceRow { width: 5, bits: 0b11011, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "більше?" }, DomainSurfaceName { namespace: "sa", name: "adhika?" }] },
    DomainSurfaceRow { width: 5, bits: 0b11100, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "знайти-за-ключем" }, DomainSurfaceName { namespace: "sa", name: "saṃbandha" }] },
    DomainSurfaceRow { width: 5, bits: 0b11101, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "значення-у-списку?" }, DomainSurfaceName { namespace: "sa", name: "sambaddha?" }] },
    DomainSurfaceRow { width: 5, bits: 0b11110, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "спарувати" }, DomainSurfaceName { namespace: "sa", name: "yugma-bandha" }] },
    DomainSurfaceRow { width: 5, bits: 0b11111, source_routable: true, surfaces: &[DomainSurfaceName { namespace: "uk", name: "замінити" }, DomainSurfaceName { namespace: "sa", name: "ādeśa" }] },
];
