// @generated by scripts/generate-domain-owner-registry.py; DO NOT EDIT.
//
// Canonical owner occupancy only. Human labels, surfaces and historical
// backend bytes are deliberately excluded from this artifact.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct DomainOwnerCoordinate {
    pub(crate) width: u8,
    pub(crate) bits: u8,
    pub(crate) source: u8,
}

pub(crate) const DOMAIN_OWNER_COORDINATES: &[DomainOwnerCoordinate] = &[
    DomainOwnerCoordinate { width: 3, bits: 0b001, source: 0 },
    DomainOwnerCoordinate { width: 3, bits: 0b010, source: 0 },
    DomainOwnerCoordinate { width: 3, bits: 0b011, source: 0 },
    DomainOwnerCoordinate { width: 3, bits: 0b100, source: 0 },
    DomainOwnerCoordinate { width: 3, bits: 0b101, source: 0 },
    DomainOwnerCoordinate { width: 3, bits: 0b110, source: 0 },
    DomainOwnerCoordinate { width: 3, bits: 0b111, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b0000, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b0001, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b0010, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b0011, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b0100, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b0110, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b0111, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b1000, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b1010, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b1011, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b1100, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b1101, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b1110, source: 0 },
    DomainOwnerCoordinate { width: 4, bits: 0b1111, source: 0 },
    DomainOwnerCoordinate { width: 5, bits: 0b00000, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b00001, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b00010, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b00011, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b00100, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b00101, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b00110, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b00111, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b01000, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b01001, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b01010, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b01011, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b01100, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b01101, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b01110, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b01111, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b10000, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b10001, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b10010, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b10011, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b10100, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b10101, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b10110, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b10111, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b11000, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b11001, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b11010, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b11011, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b11100, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b11101, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b11110, source: 1 },
    DomainOwnerCoordinate { width: 5, bits: 0b11111, source: 1 },
    DomainOwnerCoordinate { width: 6, bits: 0b000000, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b000001, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b000010, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b000011, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b000100, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b000101, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b000110, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b000111, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b001000, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b001001, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b001010, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b001011, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b001100, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b001101, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b001110, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b001111, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b010000, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b010001, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b010010, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b010011, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b010100, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b010101, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b010110, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b010111, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b011000, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b011001, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b011010, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b011011, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b011100, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b011101, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b011110, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b011111, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b100000, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b100001, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b100010, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b100011, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b100100, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b100101, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b100110, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b100111, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b101000, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b101001, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b101010, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b101011, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b101100, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b101101, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b101110, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b101111, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b110000, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b110001, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b110010, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b110011, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b110100, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b110101, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b110110, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b110111, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b111000, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b111001, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b111010, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b111011, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b111100, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b111101, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b111110, source: 2 },
    DomainOwnerCoordinate { width: 6, bits: 0b111111, source: 2 },
    DomainOwnerCoordinate { width: 7, bits: 0b0000000, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0000001, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0000010, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0000011, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0000100, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0000101, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0000110, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0000111, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0001000, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0001001, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0001010, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0001011, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0001100, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0001101, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0001110, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0001111, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0010000, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0010001, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0010010, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0010011, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0010100, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0010101, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0010110, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0010111, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0011000, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0011001, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0011010, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0011011, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0011100, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0011101, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0011110, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0011111, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0100000, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0100010, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0100011, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0100100, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0100101, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0100110, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0100111, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0101000, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0101001, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0101011, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0101100, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0101101, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0101110, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0101111, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0110000, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0110001, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0110010, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0110011, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0110100, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0110101, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0110110, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0110111, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0111000, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0111001, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0111010, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0111011, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0111100, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0111101, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0111110, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b0111111, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1000000, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1000001, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1000010, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1000011, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1000100, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1000101, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1000110, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1000111, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1001000, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1001001, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1001010, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1001011, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1001100, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1001101, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1001110, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1001111, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1010000, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1010001, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1010010, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1010011, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1010100, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1010101, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1010110, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1010111, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1011000, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1011001, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1011010, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1011011, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1011100, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1011101, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1011110, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1011111, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1100000, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1100001, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1100010, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1100011, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1100100, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1100101, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1100110, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1100111, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1101000, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1101001, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1101010, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1101011, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1101100, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1101101, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1101110, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1101111, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1110000, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1110001, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1110010, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1110011, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1110100, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1110101, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1110110, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1110111, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1111000, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1111001, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1111010, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1111011, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1111100, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1111101, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1111110, source: 3 },
    DomainOwnerCoordinate { width: 7, bits: 0b1111111, source: 3 },
];

/// Widths whose *entire* coordinate set is covered by separately owner-ratified
/// complete maps. Generated from D8 #3960 / D9 #4008 after exhaustive checks.
/// A full-width residency certificate is never a callable mechanism.
pub(crate) const DOMAIN_OWNER_FULL_WIDTHS: &[u8] = &[8, 9];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_projection_has_owner_counts_and_controls() {
        assert_eq!(DOMAIN_OWNER_COORDINATES.len(), 243);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 3).count(), 7);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 4).count(), 14);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 5).count(), 32);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 6).count(), 64);
        assert_eq!(DOMAIN_OWNER_COORDINATES.iter().filter(|row| row.width == 7).count(), 126);

        for (width, bits) in [(4, 0b1100), (5, 0b01010), (6, 0b001111)] {
            assert!(DOMAIN_OWNER_COORDINATES
                .iter()
                .any(|row| row.width == width && row.bits == bits));
        }
    }

    #[test]
    fn generated_d7_occupancy_excludes_two_pinned_reservations() {
        for word in 0..128u8 {
            let admitted = DOMAIN_OWNER_COORDINATES
                .iter()
                .any(|row| row.width == 7 && row.bits == word);
            assert_eq!(admitted, word != 0b0100001 && word != 0b0101010);
        }
    }

    #[test]
    fn generated_dense_owner_widths_are_source_certified_not_function_tables() {
        assert_eq!(DOMAIN_OWNER_FULL_WIDTHS, &[8, 9]);
        assert!(!DOMAIN_OWNER_FULL_WIDTHS.contains(&10));
    }

    #[test]
    fn generated_projection_has_unique_domain_coordinates() {
        let mut seen = std::collections::HashSet::new();
        for row in DOMAIN_OWNER_COORDINATES {
            assert!(seen.insert((row.width, row.bits)));
        }
    }
}
