// GENERATED — DO NOT EDIT BY HAND.
// Authority: lib/surface/function-signatures.lisp
// Generator: scripts/generate-rust-function-signatures.lisp

use crate::language_items::{Arity, LanguageItemKind};

#[derive(Clone, Copy, Debug)]
pub(crate) struct FunctionSignature {
    pub(crate) semantic_id: u8,
    pub(crate) kind: LanguageItemKind,
    pub(crate) arity: Arity,
    pub(crate) admitted_surfaces: bool,
    pub(crate) signature: &'static str,
    pub(crate) documentation: &'static str,
}

pub(crate) const FUNCTION_SIGNATURES: &[FunctionSignature] = &[
    FunctionSignature { semantic_id: 0b00000001, kind: LanguageItemKind::SyntaxForm, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(quote value)", documentation: "Return value unevaluated" },
    FunctionSignature { semantic_id: 0b00000010, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(atom? value)", documentation: "Test whether value is not a pair" },
    FunctionSignature { semantic_id: 0b00000011, kind: LanguageItemKind::Builtin, arity: Arity::Exact(2), admitted_surfaces: false, signature: "(eq? left right)", documentation: "Test structural or identity equality" },
    FunctionSignature { semantic_id: 0b00000100, kind: LanguageItemKind::Builtin, arity: Arity::Exact(2), admitted_surfaces: false, signature: "(cons head tail)", documentation: "Create a pair" },
    FunctionSignature { semantic_id: 0b00000101, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(car pair)", documentation: "Return the first element of a pair" },
    FunctionSignature { semantic_id: 0b00000110, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(cdr pair)", documentation: "Return the tail of a pair" },
    FunctionSignature { semantic_id: 0b00000111, kind: LanguageItemKind::SyntaxForm, arity: Arity::AtLeast(0), admitted_surfaces: false, signature: "(cond (test result) ...)", documentation: "Evaluate the first matching clause" },
    FunctionSignature { semantic_id: 0b00001000, kind: LanguageItemKind::SyntaxForm, arity: Arity::AtLeast(2), admitted_surfaces: false, signature: "(lambda (params) body ...)", documentation: "Create an anonymous function" },
    FunctionSignature { semantic_id: 0b00001001, kind: LanguageItemKind::SyntaxForm, arity: Arity::Exact(2), admitted_surfaces: false, signature: "(define name value)", documentation: "Bind name in the current scope" },
    FunctionSignature { semantic_id: 0b00001010, kind: LanguageItemKind::Macro, arity: Arity::AtLeast(3), admitted_surfaces: true, signature: "(defmacro name (params) body ...)", documentation: "Bind a language-owned macro" },
    FunctionSignature { semantic_id: 0b00001011, kind: LanguageItemKind::SyntaxForm, arity: Arity::Exact(2), admitted_surfaces: true, signature: "(def name value)", documentation: "Compatibility-only binding form" },
    FunctionSignature { semantic_id: 0b00001100, kind: LanguageItemKind::Builtin, arity: Arity::AtLeast(0), admitted_surfaces: false, signature: "(+ number ...)", documentation: "Sum all arguments" },
    FunctionSignature { semantic_id: 0b00001101, kind: LanguageItemKind::Builtin, arity: Arity::AtLeast(1), admitted_surfaces: false, signature: "(- number ...)", documentation: "Subtract or negate" },
    FunctionSignature { semantic_id: 0b00001110, kind: LanguageItemKind::Builtin, arity: Arity::AtLeast(0), admitted_surfaces: false, signature: "(* number ...)", documentation: "Multiply all arguments" },
    FunctionSignature { semantic_id: 0b00001111, kind: LanguageItemKind::Builtin, arity: Arity::AtLeast(1), admitted_surfaces: false, signature: "(/ number ...)", documentation: "Perform exact rational division" },
    FunctionSignature { semantic_id: 0b00011010, kind: LanguageItemKind::Builtin, arity: Arity::AtLeast(1), admitted_surfaces: false, signature: "(< number ...)", documentation: "Less-than chain comparison" },
    FunctionSignature { semantic_id: 0b00011011, kind: LanguageItemKind::Builtin, arity: Arity::AtLeast(1), admitted_surfaces: false, signature: "(> number ...)", documentation: "Greater-than chain comparison" },
    FunctionSignature { semantic_id: 0b00011100, kind: LanguageItemKind::Builtin, arity: Arity::AtLeast(1), admitted_surfaces: false, signature: "(= number ...)", documentation: "Numeric equality" },
    FunctionSignature { semantic_id: 0b00100100, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(string? value)", documentation: "Return t if value is a string" },
    FunctionSignature { semantic_id: 0b00100101, kind: LanguageItemKind::Builtin, arity: Arity::Exact(2), admitted_surfaces: false, signature: "(string<? left right)", documentation: "Compare strings lexicographically" },
    FunctionSignature { semantic_id: 0b00100110, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(numeric-buffer? value)", documentation: "Test for a numeric buffer" },
    FunctionSignature { semantic_id: 0b00111010, kind: LanguageItemKind::Builtin, arity: Arity::Exact(2), admitted_surfaces: false, signature: "(string-append left right)", documentation: "Concatenate two strings" },
    FunctionSignature { semantic_id: 0b00111011, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(string-length string)", documentation: "Return the number of characters" },
    FunctionSignature { semantic_id: 0b00111100, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(string-empty? string)", documentation: "Test whether the string is empty" },
    FunctionSignature { semantic_id: 0b00111101, kind: LanguageItemKind::Builtin, arity: Arity::Exact(2), admitted_surfaces: false, signature: "(string-prefix? prefix string)", documentation: "Test whether string starts with prefix" },
    FunctionSignature { semantic_id: 0b00111110, kind: LanguageItemKind::Builtin, arity: Arity::Exact(2), admitted_surfaces: false, signature: "(string-contains? needle string)", documentation: "Test whether needle occurs in string" },
    FunctionSignature { semantic_id: 0b00111111, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(string-first string)", documentation: "Return the first character as a string" },
    FunctionSignature { semantic_id: 0b01000000, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(string-rest string)", documentation: "Return the string without its first character" },
    FunctionSignature { semantic_id: 0b01000001, kind: LanguageItemKind::Builtin, arity: Arity::Exact(3), admitted_surfaces: false, signature: "(string-slice string start end)", documentation: "Return a UTF-8-safe substring" },
    FunctionSignature { semantic_id: 0b01000010, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(symbol->string symbol)", documentation: "Return the string form of a symbol" },
    FunctionSignature { semantic_id: 0b01000011, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(string->symbol string)", documentation: "Create a symbol from a string" },
    FunctionSignature { semantic_id: 0b01000100, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(codepoint->string scalar)", documentation: "Materialize one Unicode scalar as a string" },
    FunctionSignature { semantic_id: 0b01000101, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(string->codepoint string)", documentation: "Return the Unicode scalar value of one-character string" },
    FunctionSignature { semantic_id: 0b01001000, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(print value)", documentation: "Output value followed by newline" },
    FunctionSignature { semantic_id: 0b01001001, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(princ value)", documentation: "Output value without reader quoting" },
    FunctionSignature { semantic_id: 0b01001010, kind: LanguageItemKind::Builtin, arity: Arity::Between { min: 0, max: 1 }, admitted_surfaces: false, signature: "(read [source])", documentation: "Read one s-expression from a string or stdin" },
    FunctionSignature { semantic_id: 0b01001011, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(read-all source)", documentation: "Read all expressions from a string" },
    FunctionSignature { semantic_id: 0b01001100, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(write-to-string value)", documentation: "Return a readable string representation" },
    FunctionSignature { semantic_id: 0b01001101, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(eval expression)", documentation: "Evaluate an expression represented as data" },
    FunctionSignature { semantic_id: 0b01001110, kind: LanguageItemKind::Builtin, arity: Arity::Exact(0), admitted_surfaces: false, signature: "(env)", documentation: "Return visible bindings as an alist" },
    FunctionSignature { semantic_id: 0b01001111, kind: LanguageItemKind::Builtin, arity: Arity::AtLeast(0), admitted_surfaces: false, signature: "(vector value ...)", documentation: "Create a vector containing the arguments" },
    FunctionSignature { semantic_id: 0b01010000, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(make-vector length)", documentation: "Create a vector of nil slots" },
    FunctionSignature { semantic_id: 0b01010001, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(vector-length vector)", documentation: "Return the element count" },
    FunctionSignature { semantic_id: 0b01010010, kind: LanguageItemKind::Builtin, arity: Arity::Exact(2), admitted_surfaces: false, signature: "(vector-ref vector index)", documentation: "Return an element by index" },
    FunctionSignature { semantic_id: 0b01010011, kind: LanguageItemKind::Builtin, arity: Arity::Exact(3), admitted_surfaces: false, signature: "(vector-set! vector index value)", documentation: "Mutate a vector slot" },
    FunctionSignature { semantic_id: 0b01010100, kind: LanguageItemKind::Builtin, arity: Arity::AtLeast(0), admitted_surfaces: false, signature: "(i32-buffer number ...)", documentation: "Create a signed 32-bit numeric buffer" },
    FunctionSignature { semantic_id: 0b01010101, kind: LanguageItemKind::Builtin, arity: Arity::AtLeast(0), admitted_surfaces: false, signature: "(f32-buffer number ...)", documentation: "Create a binary32 numeric buffer" },
    FunctionSignature { semantic_id: 0b01010110, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(numeric-buffer-type buffer)", documentation: "Return i32 or f32" },
    FunctionSignature { semantic_id: 0b01010111, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(numeric-buffer-length buffer)", documentation: "Return the element count" },
    FunctionSignature { semantic_id: 0b01011000, kind: LanguageItemKind::Builtin, arity: Arity::Exact(2), admitted_surfaces: false, signature: "(numeric-buffer-ref buffer index)", documentation: "Return an element by index" },
    FunctionSignature { semantic_id: 0b01011001, kind: LanguageItemKind::Builtin, arity: Arity::Exact(2), admitted_surfaces: false, signature: "(numeric-buffer-map function buffer)", documentation: "Map a function over a numeric buffer" },
    FunctionSignature { semantic_id: 0b01011010, kind: LanguageItemKind::Builtin, arity: Arity::Exact(0), admitted_surfaces: false, signature: "(mono-ns)", documentation: "Return a monotonic nanosecond counter as an exact integer" },
    FunctionSignature { semantic_id: 0b01011011, kind: LanguageItemKind::Builtin, arity: Arity::Exact(0), admitted_surfaces: false, signature: "(unix-time-now)", documentation: "Observe the host wall clock as raw Unix seconds and nanoseconds" },
    FunctionSignature { semantic_id: 0b01011100, kind: LanguageItemKind::Builtin, arity: Arity::Exact(2), admitted_surfaces: false, signature: "(ntp-query-raw host timeout-ms)", documentation: "Perform one bounded NTP query and return raw protocol fields" },
    FunctionSignature { semantic_id: 0b01011101, kind: LanguageItemKind::Builtin, arity: Arity::Exact(0), admitted_surfaces: false, signature: "(timezone-declarations-raw)", documentation: "Observe raw TZ and /etc/timezone declaration candidates" },
    FunctionSignature { semantic_id: 0b10100000, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(json-parse string)", documentation: "Parse JSON into sens values" },
    FunctionSignature { semantic_id: 0b10100001, kind: LanguageItemKind::Builtin, arity: Arity::Exact(1), admitted_surfaces: false, signature: "(sha256-hex string)", documentation: "Return the SHA-256 hex digest" },
];
