// @generated by scripts/generate_current_domain_surfaces.py
// Source: lib/surface/current-domain-surfaces.tsv
// Do not edit by hand.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct CurrentHumanSurfaceRow {
    pub(crate) width: u8,
    pub(crate) bits: u8,
    pub(crate) en: &'static str,
    pub(crate) uk: &'static str,
    pub(crate) sa: &'static str,
}

pub(crate) const CURRENT_HUMAN_SURFACES: &[CurrentHumanSurfaceRow] = &[
    CurrentHumanSurfaceRow {
        width: 3,
        bits: 0b001,
        en: "quote",
        uk: "як-є",
        sa: "svarūpa",
    },
    CurrentHumanSurfaceRow {
        width: 3,
        bits: 0b010,
        en: "atom",
        uk: "атом?",
        sa: "aṇu",
    },
    CurrentHumanSurfaceRow {
        width: 3,
        bits: 0b011,
        en: "cond",
        uk: "за-умовою",
        sa: "anukrama",
    },
    CurrentHumanSurfaceRow {
        width: 3,
        bits: 0b100,
        en: "cons",
        uk: "сполучити",
        sa: "saṃyuj",
    },
    CurrentHumanSurfaceRow {
        width: 3,
        bits: 0b101,
        en: "car",
        uk: "перше",
        sa: "ādi",
    },
    CurrentHumanSurfaceRow {
        width: 3,
        bits: 0b110,
        en: "cdr",
        uk: "решта",
        sa: "śeṣa",
    },
    CurrentHumanSurfaceRow {
        width: 3,
        bits: 0b111,
        en: "eq",
        uk: "тотожне?",
        sa: "abheda",
    },
];
