// GENERATED — DO NOT EDIT BY HAND.
// Authority: pinned juv4uk/shiva-sutras UPC-7 projection.
// Generator: scripts/generate-text7-projection.py
pub(crate) const UPC7_SOURCE_REVISION: &str = "062b268557fe1fbe610dbaf036b3c782bbfd6070";
pub(crate) const UPC7_TABLE_SHA256: &str =
    "dbceb2733247801e2434aad27427138bacd35b7755faa0223f3cbf91240ccca6";
pub(crate) const UPC7_LAYOUT_SHA256: &str =
    "f225761de0209d92cc7a034d008bc25f4802105a2aae9a6402b834fbe33aa0a3";

pub(crate) const UK_ENCODE: &[(&str, Option<&[u8]>)] = &[
    ("ДЖ", Some(&[0x3f])),
    ("ДЗ", Some(&[0x3e])),
    ("Дж", Some(&[0x3f])),
    ("Дз", Some(&[0x3e])),
    ("дж", Some(&[0x3f])),
    ("дз", Some(&[0x3e])),
    ("\t", Some(&[0x62])),
    ("\n", Some(&[0x61])),
    (" ", Some(&[0x60])),
    ("!", Some(&[0x78])),
    ("\"", Some(&[0x65])),
    ("#", Some(&[0x7e])),
    ("&", Some(&[0x6d])),
    ("'", Some(&[0x79])),
    ("(", Some(&[0x63])),
    (")", Some(&[0x64])),
    ("*", Some(&[0x72])),
    ("+", Some(&[0x70])),
    (",", Some(&[0x7b])),
    ("-", Some(&[0x71])),
    (".", Some(&[0x7a])),
    ("/", Some(&[0x73])),
    (":", Some(&[0x7c])),
    (";", Some(&[0x7d])),
    ("<", Some(&[0x75])),
    ("=", Some(&[0x74])),
    (">", Some(&[0x76])),
    ("?", Some(&[0x77])),
    ("@", Some(&[0x7f])),
    ("\\", Some(&[0x66])),
    ("_", Some(&[0x67])),
    ("`", Some(&[0x6f])),
    ("|", Some(&[0x6e])),
    ("Є", Some(&[0x26, 0x5d])),
    ("І", Some(&[0x44])),
    ("Ї", Some(&[0x26, 0x44])),
    ("А", Some(&[0x5c])),
    ("Б", Some(&[0x16])),
    ("В", Some(&[0x32])),
    ("Г", Some(&[0x35])),
    ("Д", Some(&[0x11])),
    ("Е", Some(&[0x5d])),
    ("Ж", Some(&[0x25])),
    ("З", Some(&[0x2d])),
    ("И", Some(&[0x5f])),
    ("Й", Some(&[0x26])),
    ("К", Some(&[0x00])),
    ("Л", Some(&[0x2f])),
    ("М", Some(&[0x18])),
    ("Н", Some(&[0x13])),
    ("О", Some(&[0x5e])),
    ("П", Some(&[0x14])),
    ("Р", Some(&[0x2e])),
    ("С", Some(&[0x2c])),
    ("Т", Some(&[0x0f])),
    ("У", Some(&[0x48])),
    ("Ф", Some(&[0x30])),
    ("Х", Some(&[0x20])),
    ("Ц", Some(&[0x3c])),
    ("Ч", Some(&[0x3d])),
    ("Ш", Some(&[0x24])),
    ("Щ", Some(&[0x24, 0x3d])),
    ("Ь", Some(&[0x27])),
    ("Ю", Some(&[0x26, 0x48])),
    ("Я", Some(&[0x26, 0x5c])),
    ("а", Some(&[0x5c])),
    ("б", Some(&[0x16])),
    ("в", Some(&[0x32])),
    ("г", Some(&[0x35])),
    ("д", Some(&[0x11])),
    ("е", Some(&[0x5d])),
    ("ж", Some(&[0x25])),
    ("з", Some(&[0x2d])),
    ("и", Some(&[0x5f])),
    ("й", Some(&[0x26])),
    ("к", Some(&[0x00])),
    ("л", Some(&[0x2f])),
    ("м", Some(&[0x18])),
    ("н", Some(&[0x13])),
    ("о", Some(&[0x5e])),
    ("п", Some(&[0x14])),
    ("р", Some(&[0x2e])),
    ("с", Some(&[0x2c])),
    ("т", Some(&[0x0f])),
    ("у", Some(&[0x48])),
    ("ф", Some(&[0x30])),
    ("х", Some(&[0x20])),
    ("ц", Some(&[0x3c])),
    ("ч", Some(&[0x3d])),
    ("ш", Some(&[0x24])),
    ("щ", Some(&[0x24, 0x3d])),
    ("ь", Some(&[0x27])),
    ("ю", Some(&[0x26, 0x48])),
    ("я", Some(&[0x26, 0x5c])),
    ("є", Some(&[0x26, 0x5d])),
    ("і", Some(&[0x44])),
    ("ї", Some(&[0x26, 0x44])),
    ("Ґ", Some(&[0x02])),
    ("ґ", Some(&[0x02])),
];

pub(crate) const UK_RENDER: &[Option<&str>; 128] = &[
    Some("к"),
    None,
    Some("ґ"),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("т"),
    None,
    Some("д"),
    None,
    Some("н"),
    Some("п"),
    None,
    Some("б"),
    None,
    Some("м"),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("х"),
    None,
    None,
    None,
    Some("ш"),
    Some("ж"),
    Some("й"),
    Some("ь"),
    None,
    None,
    None,
    None,
    Some("с"),
    Some("з"),
    Some("р"),
    Some("л"),
    Some("ф"),
    None,
    Some("в"),
    None,
    None,
    Some("г"),
    None,
    None,
    None,
    None,
    None,
    None,
    Some("ц"),
    Some("ч"),
    Some("дз"),
    Some("дж"),
    None,
    None,
    None,
    None,
    Some("і"),
    None,
    None,
    None,
    Some("у"),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("а"),
    Some("е"),
    Some("о"),
    Some("и"),
    Some(" "),
    Some("\n"),
    Some("\t"),
    Some("("),
    Some(")"),
    Some("\""),
    Some("\\"),
    Some("_"),
    None,
    None,
    None,
    None,
    None,
    Some("&"),
    Some("|"),
    Some("`"),
    Some("+"),
    Some("-"),
    Some("*"),
    Some("/"),
    Some("="),
    Some("<"),
    Some(">"),
    Some("?"),
    Some("!"),
    Some("'"),
    Some("."),
    Some(","),
    Some(":"),
    Some(";"),
    Some("#"),
    Some("@"),
];

pub(crate) const SA_SLP1_ENCODE: &[(&str, Option<&[u8]>)] = &[
    ("..", Some(&[0x6c])),
    ("\t", Some(&[0x62])),
    ("\n", Some(&[0x61])),
    (" ", Some(&[0x60])),
    ("!", Some(&[0x78])),
    ("\"", Some(&[0x65])),
    ("#", Some(&[0x7e])),
    ("&", Some(&[0x6d])),
    ("'", Some(&[0x6a])),
    ("(", Some(&[0x63])),
    (")", Some(&[0x64])),
    ("*", Some(&[0x72])),
    ("+", Some(&[0x70])),
    (",", Some(&[0x7b])),
    ("-", Some(&[0x71])),
    (".", Some(&[0x6b])),
    ("/", Some(&[0x73])),
    (":", Some(&[0x7c])),
    (";", Some(&[0x7d])),
    ("<", Some(&[0x75])),
    ("=", Some(&[0x74])),
    (">", Some(&[0x76])),
    ("?", Some(&[0x77])),
    ("@", Some(&[0x7f])),
    ("A", Some(&[0x41])),
    ("B", Some(&[0x17])),
    ("C", Some(&[0x06])),
    ("D", Some(&[0x12])),
    ("E", Some(&[0x55])),
    ("F", Some(&[0x4d])),
    ("G", Some(&[0x03])),
    ("H", Some(&[0x69])),
    ("I", Some(&[0x45])),
    ("J", Some(&[0x08])),
    ("K", Some(&[0x01])),
    ("M", Some(&[0x68])),
    ("N", Some(&[0x04])),
    ("O", Some(&[0x59])),
    ("P", Some(&[0x15])),
    ("Q", Some(&[0x0d])),
    ("R", Some(&[0x0e])),
    ("S", Some(&[0x24])),
    ("T", Some(&[0x10])),
    ("U", Some(&[0x49])),
    ("W", Some(&[0x0b])),
    ("X", Some(&[0x51])),
    ("Y", Some(&[0x09])),
    ("\\", Some(&[0x66])),
    ("_", Some(&[0x67])),
    ("`", Some(&[0x6f])),
    ("a", Some(&[0x40])),
    ("b", Some(&[0x16])),
    ("c", Some(&[0x05])),
    ("d", Some(&[0x11])),
    ("e", Some(&[0x54])),
    ("f", Some(&[0x4c])),
    ("g", Some(&[0x02])),
    ("h", Some(&[0x34])),
    ("i", Some(&[0x44])),
    ("j", Some(&[0x07])),
    ("k", Some(&[0x00])),
    ("l", Some(&[0x2f])),
    ("m", Some(&[0x18])),
    ("n", Some(&[0x13])),
    ("o", Some(&[0x58])),
    ("p", Some(&[0x14])),
    ("q", Some(&[0x0c])),
    ("r", Some(&[0x2e])),
    ("s", Some(&[0x2c])),
    ("t", Some(&[0x0f])),
    ("u", Some(&[0x48])),
    ("v", Some(&[0x32])),
    ("w", Some(&[0x0a])),
    ("x", Some(&[0x50])),
    ("y", Some(&[0x26])),
    ("z", Some(&[0x28])),
    ("|", Some(&[0x6e])),
];

pub(crate) const SA_SLP1_RENDER: &[Option<&str>; 128] = &[
    Some("k"),
    Some("K"),
    Some("g"),
    Some("G"),
    Some("N"),
    Some("c"),
    Some("C"),
    Some("j"),
    Some("J"),
    Some("Y"),
    Some("w"),
    Some("W"),
    Some("q"),
    Some("Q"),
    Some("R"),
    Some("t"),
    Some("T"),
    Some("d"),
    Some("D"),
    Some("n"),
    Some("p"),
    Some("P"),
    Some("b"),
    Some("B"),
    Some("m"),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("S"),
    None,
    Some("y"),
    None,
    Some("z"),
    None,
    None,
    None,
    Some("s"),
    None,
    Some("r"),
    Some("l"),
    None,
    None,
    Some("v"),
    None,
    Some("h"),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("a"),
    Some("A"),
    None,
    None,
    Some("i"),
    Some("I"),
    None,
    None,
    Some("u"),
    Some("U"),
    None,
    None,
    Some("f"),
    Some("F"),
    None,
    None,
    Some("x"),
    Some("X"),
    None,
    None,
    Some("e"),
    Some("E"),
    None,
    None,
    Some("o"),
    Some("O"),
    None,
    None,
    None,
    None,
    None,
    None,
    Some(" "),
    Some("\n"),
    Some("\t"),
    Some("("),
    Some(")"),
    Some("\""),
    Some("\\"),
    Some("_"),
    Some("M"),
    Some("H"),
    Some("'"),
    Some("."),
    Some(".."),
    Some("&"),
    Some("|"),
    Some("`"),
    Some("+"),
    Some("-"),
    Some("*"),
    Some("/"),
    Some("="),
    Some("<"),
    Some(">"),
    Some("?"),
    Some("!"),
    None,
    None,
    Some(","),
    Some(":"),
    Some(";"),
    Some("#"),
    Some("@"),
];

pub(crate) const SA_IAST_ENCODE: &[(&str, Option<&[u8]>)] = &[
    ("ai", Some(&[0x55])),
    ("au", Some(&[0x59])),
    ("bh", Some(&[0x17])),
    ("ch", Some(&[0x06])),
    ("dh", Some(&[0x12])),
    ("gh", Some(&[0x03])),
    ("jh", Some(&[0x08])),
    ("kh", Some(&[0x01])),
    ("ph", Some(&[0x15])),
    ("th", Some(&[0x10])),
    ("ḍh", Some(&[0x0d])),
    ("ṭh", Some(&[0x0b])),
    ("\t", Some(&[0x62])),
    ("\n", Some(&[0x61])),
    (" ", Some(&[0x60])),
    ("!", Some(&[0x78])),
    ("\"", Some(&[0x65])),
    ("#", Some(&[0x7e])),
    ("&", Some(&[0x6d])),
    ("'", Some(&[0x79])),
    ("(", Some(&[0x63])),
    (")", Some(&[0x64])),
    ("*", Some(&[0x72])),
    ("+", Some(&[0x70])),
    (",", Some(&[0x7b])),
    ("-", Some(&[0x71])),
    (".", Some(&[0x7a])),
    ("/", Some(&[0x73])),
    (":", Some(&[0x7c])),
    (";", Some(&[0x7d])),
    ("<", Some(&[0x75])),
    ("=", Some(&[0x74])),
    (">", Some(&[0x76])),
    ("?", Some(&[0x77])),
    ("@", Some(&[0x7f])),
    ("\\", Some(&[0x66])),
    ("_", Some(&[0x67])),
    ("`", Some(&[0x6f])),
    ("a", Some(&[0x40])),
    ("b", Some(&[0x16])),
    ("c", Some(&[0x05])),
    ("d", Some(&[0x11])),
    ("e", Some(&[0x54])),
    ("g", Some(&[0x02])),
    ("h", Some(&[0x34])),
    ("i", Some(&[0x44])),
    ("j", Some(&[0x07])),
    ("k", Some(&[0x00])),
    ("l", Some(&[0x2f])),
    ("m", Some(&[0x18])),
    ("n", Some(&[0x13])),
    ("o", Some(&[0x58])),
    ("p", Some(&[0x14])),
    ("r", Some(&[0x2e])),
    ("s", Some(&[0x2c])),
    ("t", Some(&[0x0f])),
    ("u", Some(&[0x48])),
    ("v", Some(&[0x32])),
    ("y", Some(&[0x26])),
    ("|", Some(&[0x6e])),
    ("ñ", Some(&[0x09])),
    ("ā", Some(&[0x41])),
    ("ī", Some(&[0x45])),
    ("ś", Some(&[0x24])),
    ("ū", Some(&[0x49])),
    ("।", Some(&[0x6b])),
    ("॥", Some(&[0x6c])),
    ("ḍ", Some(&[0x0c])),
    ("ḥ", Some(&[0x69])),
    ("ḷ", Some(&[0x50])),
    ("ḹ", Some(&[0x51])),
    ("ṃ", Some(&[0x68])),
    ("ṅ", Some(&[0x04])),
    ("ṇ", Some(&[0x0e])),
    ("ṛ", Some(&[0x4c])),
    ("ṝ", Some(&[0x4d])),
    ("ṣ", Some(&[0x28])),
    ("ṭ", Some(&[0x0a])),
    ("’", Some(&[0x6a])),
];

pub(crate) const SA_IAST_RENDER: &[Option<&str>; 128] = &[
    Some("k"),
    Some("kh"),
    Some("g"),
    Some("gh"),
    Some("ṅ"),
    Some("c"),
    Some("ch"),
    Some("j"),
    Some("jh"),
    Some("ñ"),
    Some("ṭ"),
    Some("ṭh"),
    Some("ḍ"),
    Some("ḍh"),
    Some("ṇ"),
    Some("t"),
    Some("th"),
    Some("d"),
    Some("dh"),
    Some("n"),
    Some("p"),
    Some("ph"),
    Some("b"),
    Some("bh"),
    Some("m"),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("ś"),
    None,
    Some("y"),
    None,
    Some("ṣ"),
    None,
    None,
    None,
    Some("s"),
    None,
    Some("r"),
    Some("l"),
    None,
    None,
    Some("v"),
    None,
    Some("h"),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("a"),
    Some("ā"),
    None,
    None,
    Some("i"),
    Some("ī"),
    None,
    None,
    Some("u"),
    Some("ū"),
    None,
    None,
    Some("ṛ"),
    Some("ṝ"),
    None,
    None,
    Some("ḷ"),
    Some("ḹ"),
    None,
    None,
    Some("e"),
    Some("ai"),
    None,
    None,
    Some("o"),
    Some("au"),
    None,
    None,
    None,
    None,
    None,
    None,
    Some(" "),
    Some("\n"),
    Some("\t"),
    Some("("),
    Some(")"),
    Some("\""),
    Some("\\"),
    Some("_"),
    Some("ṃ"),
    Some("ḥ"),
    Some("’"),
    Some("।"),
    Some("॥"),
    Some("&"),
    Some("|"),
    Some("`"),
    Some("+"),
    Some("-"),
    Some("*"),
    Some("/"),
    Some("="),
    Some("<"),
    Some(">"),
    Some("?"),
    Some("!"),
    Some("'"),
    Some("."),
    Some(","),
    Some(":"),
    Some(";"),
    Some("#"),
    Some("@"),
];

pub(crate) const SA_DEVA_ENCODE: &[(&str, Option<&[u8]>)] = &[
    ("\t", Some(&[0x62])),
    ("\n", Some(&[0x61])),
    (" ", Some(&[0x60])),
    ("!", Some(&[0x78])),
    ("\"", Some(&[0x65])),
    ("#", Some(&[0x7e])),
    ("&", Some(&[0x6d])),
    ("'", Some(&[0x79])),
    ("(", Some(&[0x63])),
    (")", Some(&[0x64])),
    ("*", Some(&[0x72])),
    ("+", Some(&[0x70])),
    (",", Some(&[0x7b])),
    ("-", Some(&[0x71])),
    (".", Some(&[0x7a])),
    ("/", Some(&[0x73])),
    (":", Some(&[0x7c])),
    (";", Some(&[0x7d])),
    ("<", Some(&[0x75])),
    ("=", Some(&[0x74])),
    (">", Some(&[0x76])),
    ("?", Some(&[0x77])),
    ("@", Some(&[0x7f])),
    ("\\", Some(&[0x66])),
    ("_", Some(&[0x67])),
    ("`", Some(&[0x6f])),
    ("|", Some(&[0x6e])),
    ("ं", Some(&[0x68])),
    ("ः", Some(&[0x69])),
    ("अ", Some(&[0x40])),
    ("आ", Some(&[0x41])),
    ("इ", Some(&[0x44])),
    ("ई", Some(&[0x45])),
    ("उ", Some(&[0x48])),
    ("ऊ", Some(&[0x49])),
    ("ऋ", Some(&[0x4c])),
    ("ऌ", Some(&[0x50])),
    ("ए", Some(&[0x54])),
    ("ऐ", Some(&[0x55])),
    ("ओ", Some(&[0x58])),
    ("औ", Some(&[0x59])),
    ("क", Some(&[0x00])),
    ("ख", Some(&[0x01])),
    ("ग", Some(&[0x02])),
    ("घ", Some(&[0x03])),
    ("ङ", Some(&[0x04])),
    ("च", Some(&[0x05])),
    ("छ", Some(&[0x06])),
    ("ज", Some(&[0x07])),
    ("झ", Some(&[0x08])),
    ("ञ", Some(&[0x09])),
    ("ट", Some(&[0x0a])),
    ("ठ", Some(&[0x0b])),
    ("ड", Some(&[0x0c])),
    ("ढ", Some(&[0x0d])),
    ("ण", Some(&[0x0e])),
    ("त", Some(&[0x0f])),
    ("थ", Some(&[0x10])),
    ("द", Some(&[0x11])),
    ("ध", Some(&[0x12])),
    ("न", Some(&[0x13])),
    ("प", Some(&[0x14])),
    ("फ", Some(&[0x15])),
    ("ब", Some(&[0x16])),
    ("भ", Some(&[0x17])),
    ("म", Some(&[0x18])),
    ("य", Some(&[0x26])),
    ("र", Some(&[0x2e])),
    ("ल", Some(&[0x2f])),
    ("व", Some(&[0x32])),
    ("श", Some(&[0x24])),
    ("ष", Some(&[0x28])),
    ("स", Some(&[0x2c])),
    ("ह", Some(&[0x34])),
    ("ऽ", Some(&[0x6a])),
    ("ॠ", Some(&[0x4d])),
    ("ॡ", Some(&[0x51])),
    ("।", Some(&[0x6b])),
    ("॥", Some(&[0x6c])),
];

pub(crate) const SA_DEVA_RENDER: &[Option<&str>; 128] = &[
    Some("क"),
    Some("ख"),
    Some("ग"),
    Some("घ"),
    Some("ङ"),
    Some("च"),
    Some("छ"),
    Some("ज"),
    Some("झ"),
    Some("ञ"),
    Some("ट"),
    Some("ठ"),
    Some("ड"),
    Some("ढ"),
    Some("ण"),
    Some("त"),
    Some("थ"),
    Some("द"),
    Some("ध"),
    Some("न"),
    Some("प"),
    Some("फ"),
    Some("ब"),
    Some("भ"),
    Some("म"),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("श"),
    None,
    Some("य"),
    None,
    Some("ष"),
    None,
    None,
    None,
    Some("स"),
    None,
    Some("र"),
    Some("ल"),
    None,
    None,
    Some("व"),
    None,
    Some("ह"),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("अ"),
    Some("आ"),
    None,
    None,
    Some("इ"),
    Some("ई"),
    None,
    None,
    Some("उ"),
    Some("ऊ"),
    None,
    None,
    Some("ऋ"),
    Some("ॠ"),
    None,
    None,
    Some("ऌ"),
    Some("ॡ"),
    None,
    None,
    Some("ए"),
    Some("ऐ"),
    None,
    None,
    Some("ओ"),
    Some("औ"),
    None,
    None,
    None,
    None,
    None,
    None,
    Some(" "),
    Some("\n"),
    Some("\t"),
    Some("("),
    Some(")"),
    Some("\""),
    Some("\\"),
    Some("_"),
    Some("ं"),
    Some("ः"),
    Some("ऽ"),
    Some("।"),
    Some("॥"),
    Some("&"),
    Some("|"),
    Some("`"),
    Some("+"),
    Some("-"),
    Some("*"),
    Some("/"),
    Some("="),
    Some("<"),
    Some(">"),
    Some("?"),
    Some("!"),
    Some("'"),
    Some("."),
    Some(","),
    Some(":"),
    Some(";"),
    Some("#"),
    Some("@"),
];
